### PR TITLE
Add `TODO` annotations with links to JIRA tickets

### PR DESCRIPTION
**Pull request by sschneid**
### High-level description

Add `TODO` annotations with links to JIRA tickets

### Corresponding DC/OS tickets

  - [DCOS_OSS-3460](https://jira.mesosphere.com/browse/DCOS_OSS-3460) release/test_release.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3461](https://jira.mesosphere.com/browse/DCOS_OSS-3461) gen/tests/test_gen.py has muted Windows tests requiring investigation	
  - [DCOS_OSS-3462](https://jira.mesosphere.com/browse/DCOS_OSS-3462) gen/tests/test_config.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3463](https://jira.mesosphere.com/browse/DCOS_OSS-3463) gen/tests/test_adminrouter_tls_conf.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3464](https://jira.mesosphere.com/browse/DCOS_OSS-3464) pkgpanda/test_repository.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3465](https://jira.mesosphere.com/browse/DCOS_OSS-3465) pkgpanda/test_setup.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3466](https://jira.mesosphere.com/browse/DCOS_OSS-3466) pkgpanda/test_active_list.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3467](https://jira.mesosphere.com/browse/DCOS_OSS-3467) pkgpanda/test_fetch.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3468](https://jira.mesosphere.com/browse/DCOS_OSS-3468) pkgpanda/test_http.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3469](https://jira.mesosphere.com/browse/DCOS_OSS-3469) pkgpanda/test_check.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3470](https://jira.mesosphere.com/browse/DCOS_OSS-3470) pkgpanda/build/tests/build_integration_test.py has muted Windows tests requiring investigation	
  - [DCOS_OSS-3471](https://jira.mesosphere.com/browse/DCOS_OSS-3471) pkgpanda/test_install.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3472](https://jira.mesosphere.com/browse/DCOS_OSS-3472) packages/dcos-history/extra/test_history_service.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3473](https://jira.mesosphere.com/browse/DCOS_OSS-3473) dcos_installer/test_backend.py has muted Windows tests requiring investigation
  - [DCOS_OSS-3474](https://jira.mesosphere.com/browse/DCOS_OSS-3474) dcos_installer/test_async_server.py has muted Windows tests requiring investigation

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot override-status  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot label [Ready For Review |Request For Comment |Holding |Work In Progress |Ship It] 
@mesosphere-mergebot merge-it  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mesosphere-mergebot-dev** [comment]
:wave: This PR has been inactive for 3 days. Please review the status checks to see what needs to be done to move it forward or change the label to Work in Progress. Thank you!

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-19790

**Pull request merged**
