### PR TITLE
[2.2][BACKPORT] 7694 from  master: Add a Marathon integration test using NFS CSI volume.

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
This is a backport of the following PR:

https://github.com/dcos/dcos/pull/7694

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [D2IQ-ID](https://jira.d2iq.com/browse/D2IQ-ID) JIRA title / short description.

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by qianzhangxa** [comment]
@mesosphere-mergebot test teamcity/dcos/test/test-e2e/group1

**Review by pierrebeitz — APPROVED** [review]

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ship It

**Comment by qianzhangxa** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
