### PR TITLE
Update cosmos version to 0.4.1

### PR DESCRIPTION
**Pull request by larioj**
## High Level Description

Add metrics and documentation.

## Related Issues

  - [DCOS-17822](https://jira.mesosphere.com/browse/DCOS-17822) Release cosmos
  - [DCOS-17823](https://jira.mesosphere.com/browse/DCOS-17823) Release cosmos enterprise

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Change Log](https://github.com/dcos/cosmos/compare/v0.4.0...v0.4.1)
  - [x] Test Results: [link to CI job test results for component](https://teamcity.mesosphere.io/viewLog.html?buildId=741738&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_PublishRelease)
  - [x] Code Coverage (if available): [link to code coverage report](https://teamcity.mesosphere.io/viewLog.html?buildId=741566&buildTypeId=DcosIo_Cosmos_Scoverag&tab=report_project211_Scoverage)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by larioj** [comment]
@jsancio @cruhland

**Comment by larioj** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by larioj** [comment]
@mesosphere-mergebot bump-ee

**Comment by cdaw** [comment]
@takirala @jsancio @cruhland ping, please review.  Needed for final train today.

**Pull request merged**
