### PR TITLE
Update DC/OS UI to 1.9

### PR DESCRIPTION
**Pull request by orlandohohmeier**
---
ℹ️   _This branch depends on features that will be introduced with #971 and #1024 thus not all of the features will work until the respective branches got merged. For further details please see the integration section._

---

Update DC/OS to include the latest DC/OS UI 1.9 release. The new DC/OS UI has a brand new look and feel, provides new tools to debug services, and features a much-improved flow for creating services.

## Highlights

service-create
_Much-improved flow for creating services._

new-look
_New look and feel._

sevice-debug
_New tools to debug services._

## Integration

This DC/OS UI version uses a set of new endpoints and packages that will land with #1045 and #1024 therefore not all of the features will work.   Nevertheless, it's ok to integrate the DC/OS UI packages first, as it was build in a way that the UI shouldn't break if those dependencies aren't there.

The following issue might occur without the respective updates:

* The new log view will display inform the user that the endpoint isn't working, but it is still possible to get the logs via the file browser.
* The service debug view should already work with the current version of Marathon.
* Marathon might respond with validation errors as the API (spec) in Marathon 1.4.0-snap29 had some incompatibilities.

### CODE REVIEW

**Comment by cmaloney** [comment]
Replaces #1041, #1037

**Comment by rcorral** [comment]
I've added a commit which adds additional metadata for the UI tracking plugin. This will allow us to better segment application errors from the UI.

**Comment by orlandohohmeier** [comment]
We're seeing some validation errors,  preventing users from creating services, due to issues in  the Marathon API spec. Please hold merge until the following issues have been addressed and the dependencies have been updated. 

* https://github.com/mesosphere/marathon/issues/4817
* https://github.com/mesosphere/marathon/issues/4811
* https://github.com/mesosphere/marathon/issues/4821

I went ahead and provided fixes for all of them and the Marathon Team assured they will land them soon.

**Comment by orlandohohmeier** [comment]
The Marathon team has release a new version which includes fixes for the named issues. I've updated the references and we should be good to integrate DC/OS UI 1.9 🚢

**Comment by rcorral** [comment]
Let's :shipit:

**Comment by rcorral** [comment]
Unit tests for referenced commit:
https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-ui-pulls/5876/

Here's a link to the epic tracking the integration tests for the UI: https://mesosphere.atlassian.net/browse/DCOS-10832

**Comment by lingmann** [comment]
Thanks @rcorral . From the unit test summary:

> Test Suites: 219 passed, 219 total
> Tests:       2636 passed, 2636 total
> Snapshots:   0 total
> Time:        126.215s
> Ran all test suites.

In the future free to link directly to the console log output of the test. That will make it a bit easier for us to scan through the test results.

**Pull request merged**
