### PR TITLE
SetTruncateBit: true in mesos-dns

### PR DESCRIPTION
**Pull request by lloesche**
## High Level Description

Set the truncate bit in mesos-dns so that tools like dig and libraries will retry in tcp mode when the answer was truncated.

This was the default behaviour previously and is what most people will expect from an RFC conform DNS server. Without it service discovery via Mesos-DNS is broken and e.g. monitoring Software like Prometheus won't find all the nodes in the cluster.

Also makes the option configurable via the Installer so that customers can choose to turn it off.

The breaking change was originally introduced via [DCOS-7855](https://jira.mesosphere.com/browse/DCOS-7855) to solve a customer's issue who's running containers with non-compliant libc.

## Related Issues

  - [DCOS-15771](https://jira.mesosphere.com/browse/DCOS-15771) mesos-dns doesn't return all SRV records of running tasks.
  - [DCOS-16588](https://jira.mesosphere.com/browse/DCOS-16588) release notes: mesos-dns default changing.

### CODE REVIEW

**Comment by lloesche** [comment]
@mesosphere-mergebot bump-ee

**Comment by lloesche** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by gpaul** [comment]
Let's discuss this on the jira before we merge this.

**Comment by lloesche** [comment]
@mesosphere-mergebot label Request For Comment

**Comment by lloesche** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
