### PR TITLE
Train 117

### PR DESCRIPTION
**Pull request by lingmann**
Train merge:
#1106 Fix azure flaky tests
#1114 Pinning the version for webtest-aiohttp
#1123 Don't expose the --uninstall flag since it is not supported or documented and not functional
#1112 Add parameters to test_upgrade_vpc.py to all overrides
#1118 Add zkEnv.sh to /bin

### CODE REVIEW

**Comment by lingmann** [comment]
@adam-mesos I'm not sure if that is really a sustainable approach here to always have an enterprise bump for each train without automatic tooling... last time I tried a bump of enterprise we had other issues that blocked merging basic fixes in open (such as all code-quality builds are currently failing.) @spahl thoughts?

**Comment by adam-mesos** [comment]
> last time I tried a bump of enterprise we had other issues
That's exactly the problem I'm trying to avoid. I can't (easily) test any of my OSS changes (e.g. Mesos bump) in EE with the current state of things, and piling more commits on top of dcos/dcos will only make the eventual upstream bump even nastier.
If every OSS train checked the upstream bump health, we could avoid all these broken windows.
And I'm 100% in favor of automated tooling for upstream bumps. I'd prioritize that ASAP, personally.
As it stands now, it seems like upstream bump is healthy for ~1 week, then broken for ~1 month, then fixed for 1 week, etc. This drastically slows down development of our core $$ product.

**Comment by lingmann** [comment]
Summarizing RL discussion had earlier today with @spahl @adam-mesos: we are going to always bump downstream with open trains, even though it is going to slow us down in short term. Train conductors will own making sure this happens. We also agreed to merge this train without the downstream bump, since we are going to prioritize getting downstream building again today.

**Comment by lingmann** [comment]
Since I created this train I will make sure all of the issues with downstream are triaged / prioritized / merged today as well.

**Pull request merged**
