### PR TITLE
[1.13]  Update excludes list for Windows

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description
Backport of #6021 

Update excludes list for Windows, so that it can build. Also, adds some additional logging to `pkgpanda` which makes packages causing failures more obvious.

As it was for the `master` branch, the build passes the dependency problem but still fails due to subsequent errors: see https://teamcity.mesosphere.io/viewLog.html?buildId=2152092&tab=buildResultsDiv&buildTypeId=DcOs_Windows_Build_BuildDcOs

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5429](https://jira.mesosphere.com/browse/https://jira.mesosphere.com/browse/DCOS_OSS-5429) Fix Windows build packages
  - [DCOS-45547](https://jira.mesosphere.com/browse/DCOS-45547) teamcity/dcos/build/dcos/windows: 'package python is supposed to have variant windows'

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
Build fails earlier if reverted.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required fixing failed build

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @jgehrcke @mhrabovcin

**Comment by jgehrcke** [comment]
> @mesosphere-mergebot changelog-not-required fixing failed build

I think most importantly there is no reference; no release yet compared to which we could, from the user's point of view, document any changes.

**Pull request merged**
