### PR TITLE
bump metronome to v0.2.0

### PR DESCRIPTION
**Pull request by jdef**
- Upgrades metronome to 0.2.0

# Issues

# Checklist

 - [ ] Included a test which will fail if code is reverted but test is not
 - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

If this is a component/package update, include

 - [x] Change Log from last: https://github.com/dcos/metronome/releases/tag/v0.2.0
 - [ ] Test Results: n/a
 - [ ] Code Coverage: n/a

### CODE REVIEW

**Comment by cmaloney** [comment]
comment with "ready for review" when this is ready and the PR template is filled in.

**Comment by jdef** [comment]
ready for review

**Comment by spahl** [comment]
Please create a ticket to track creating these missing unit tests and link it here so that we don't rely on the few integration tests in this repo.

**Comment by orsenthil** [comment]
@jdef  - How do make sure that https://github.com/dcos/metronome/pull/96  does not break anything?  AFAIC, this is the functional change and rest were documentation changes included with this buildinfo.json change.

**Comment by jdef** [comment]
Looks like there's system (shakedown) tests for metronome. I don't see any
tests that use constraints though.

**Comment by spahl** [comment]
Shakedown tests should be linked here. It's better than nothing.

**Comment by kensipe** [comment]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/metronome-job-si-matrix/

**Comment by kensipe** [comment]
shakedown tests run nightly...  looking at history it commonly has partial failure in the test matrix... however all those failures are caused by ccm cluster creation failures or the like.  still waiting on dcos-launcher

**Comment by spahl** [comment]
Thanks. That give us pointers to what to improve.

**Comment by jdef** [comment]
https://mesosphere.atlassian.net/browse/DCOS-12216

**Pull request merged**
