### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Aug-14-11-01

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3210 - Bump ui to 1.11+v1.17.0

### CODE REVIEW

**Comment by mhrabovcin** [comment]
Can we please add https://github.com/dcos/dcos/pull/3248 to this train? Thanks!

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by cprovencher** [comment]
@mhrabovcin better to put it on the next one. This one is all green so we should just merge it and avoid potential delays.

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
