### PR TITLE
Fix CentOS 7 AMI journald directory permissions and rebuild AMIs

### PR DESCRIPTION
**Pull request by branden**
## High Level Description

This PR fixes CentOS 7 AMI journald log permissions, and fixes the upgrade test to successfully install stable on CentOS 7.3.

## Related Issues

  - [DCOS_OSS-711](https://jira.mesosphere.com/browse/DCOS_OSS-711) Logging API integration tests fail on CentOS 7.3

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by branden** [comment]
Upgrade test successfully installs 1.8.8, and fails for the expected reasons. :tada:

**Comment by branden** [comment]
Ready for review @lingmann @orsenthil.

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
All tests succeeded on the last enterprise bump. So I don't anticipate we'll have any issues, since the only change from @lloesche's original PR is @branden's fix to `test_util/test_upgrade_vpc.py`.

**Pull request merged**
