### PR TITLE
Admin Router: DRY up the AR code related to leader proxing

### PR DESCRIPTION
**Pull request by vespian**
## High-level description

This PR DRYies the AR code so that adding proxing to the dcos-storage leader instance does not require more copy-pasting and is simpler.

**This PR introduces a small change in the behaviour of AR:**
_In order to unify code paths for dcos-history-service and marathon wrt. leader proxying. it was necessary to change the response for Marathon Leader proxying, in a case when Leader has not been elected - from `404` to `503` This change shouldn't break anything and fits better the error condition AR is experiencing._

EDIT: Even if DSS is implemented via Marathon, this change should still land as it simplifies/streamlines the code and can be re-used by other services willing to do leader-proxing in the future.

## Corresponding DC/OS tickets (obligatory)

This PR is one of the PRs that will address

  - https://jira.mesosphere.com/browse/DCOS-19562 DSS/AR: AR routes DSS requests to the leading DSS instance

## Related PRs:
DC/OS EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1921

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@mesosphere-mergebot label Ready for review

**Comment by vespian** [comment]
@mhrabovcin @jgehrcke Please have a look (modulo CI).

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@mhrabovcin @jgehrcke Ping?

**Comment by jgehrcke** [comment]
Thanks for the reviews everyone! Now let's comment on the failed CI checks and get this in :)

Thanks, Pawel!

**Comment by vespian** [comment]
Rerunning Azure tests as per https://jira.mesosphere.com/browse/DCOS_OSS-1877

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker https://jira.mesosphere.com/browse/DCOS-19542

**Comment by vespian** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Pull request merged**
