### PR TITLE
Train 164

### PR DESCRIPTION
**Pull request by BenWhitehead**
* #1502 
* #1511 
* #1552 
* #1557 
* #1562

### CODE REVIEW

**Comment by mellenburg** [comment]
The CLI test failed because a setting was turned on AFTER the last train was merged which in turn exercised code that was tragically non-conflicting and in the same merge. https://github.com/dcos/dcos/pull/1568 was opened to fix this and that test setting can be reenabled with it's merge. In the meanwhile, I simply turned off the setting to unblock testing

**Comment by mellenburg** [comment]
@BenWhitehead sorry, I made a terrible mistake and accidentally left a patch in https://github.com/dcos/dcos/pull/1552 that changed the SSL back to being something that I could actually use dcos-launch with. That commit has been removed and this train needs to be rebuilt to not mess with open ssl. My bad!

**Comment by orsenthil** [comment]
@mesosphere-mergebot ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
