### PR TITLE
Bumped Mesos package to 1.4.x head 60b8d41.

### PR DESCRIPTION
**Pull request by Gilbert88**
## High Level Description

This PR bumps the Mesos package to the latest HEAD of the 1.4.x branch, to bring in the recent backported bugfix.

## Related Issues

  - [MESOS-7926](https://issues.apache.org/jira/browse/MESOS-7926) Abnormal termination of default executor can cause MesosContainerizer::destroy to fail.
  - [MESOS-7934](https://issues.apache.org/jira/browse/MESOS-7934) OOM due to LibeventSSLSocket send incorrectly returning 0 after shutdown.
  - [MESOS-7861](https://issues.apache.org/jira/browse/MESOS-7861) Include check output in the DefaultExecutor log.

Edit(JP):
  - https://jira.mesosphere.com/browse/DCOS-18346

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: This PR relies on the Mesos test suite
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Mesos diff](https://github.com/mesosphere/mesos/compare/87f86acca1194fe8dcd2e249a081f150276cd750...c968b18baffd52c4f89f3968f73926fa5256fba8)
  - [x] Test Results: [CI results](https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/Mesos_CI-build/1726/)
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by qianzhangxa** [comment]
In the branch `dcos-mesos-1.4.x-60b8d41`, I see there is a commit [Added MESOS-7934 to the 1.4.0 CHANGELOG.](https://github.com/mesosphere/mesos/commit/60b8d41bc2ebb8316f9af9d0f45407b90d87a3d6), but I do not see a similar one for `MESOS-7926`, should we add one for that? @jieyu

**Comment by vinodkone** [comment]
LGTM

**Comment by Gilbert88** [comment]
@qianzhangxa , it is a documentation change that we can backport to Mesos later. Should not be a blocker for DC/OS 1.10 GA.

**Comment by jgehrcke** [comment]
@Gilbert88 please also include (a) DC/OS JIRA ticket(s) which motivates this change from a DC/OS point of view in the PR description!

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
