### PR TITLE
Added placeholder for running bootstrap.py on windows by winpanda

### PR DESCRIPTION
**Pull request by vadymzagorodko**
## High-level description

Added placeholder for running bootstrap.py on windows by winpanda. Fixed version of cryptography package (set 32 bit package for DCOS open too) 

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5696](https://jira.mesosphere.com/browse/DCOS_OSS-5696) Adjust configuration files for Bootstrap package.

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by vadymzagorodko** [comment]
@mesosphere-mergebot changelog-not-required reason

**Comment by vadymzagorodko** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by vadymzagorodko** [comment]
I see... So, my suggestion is to leave it now as is and create JIRA to change it ni GA. It would be better to setup bootstrap as an independent package and add the parameters to run it on demand with the services that should be served by bootstrap. But now it's important to provide Adminrouter with prerequisites during setup.

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Pull request merged**
