### PR TITLE
Print out the variant string rather than uninterpreted variant

### PR DESCRIPTION
**Pull request by cmaloney**
None -> empty variant

https://dcosjira.atlassian.net/browse/DCOS-210

### CODE REVIEW

**Comment by malnick** [comment]
This still gives incomplete information (in this case an empty string instead of None). 

Can we update the pkgpanda utility to do something like this https://github.com/malnick/dcos/blob/019ec51f543f1dcee7ab85342a2e50260e64fb39/ext/dcos-installer/dcos_installer/cli_dispatcher.py#L108 so we get the variant we expect (in the case of None, it's assumed to be Open)?

**Comment by cmaloney** [comment]
"open" and "enterprise" are not DC/OS variants that we build or use anywhere. That bit of CLI code is actually inconsistent with everything else in the codebase. The pkgpanda `variant` which is where the term comes from is whatever the prefix of the file is. so `treeinfo.json` -> "", "ee.treeinfo.json" -> `ee`, `foo.buildinfo.json` -> `foo`.

We could invent another term which is defined to be something like that, but variant isn't that.

**Comment by cmaloney** [comment]
For reference: https://github.com/dcos/dcos/blob/master/pkgpanda/util.py#L15. All those `variant_` translate variants between their different forms.

**Comment by spahl** [comment]
:ship:

**Pull request merged**
