### PR TITLE
Change dcos-log text test to expect 10 entries

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

Currently, the test was expecting 10 lines when dcos-log returns 10 entries. Test failed when multiline entry appeared. This change checks if the retrned text contains 10 entries by checking if it contains 10 timestamps that are added by dcos-log.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4416](https://jira.mesosphere.com/browse/DCOS_OSS-4416) dcos-log returns more lines than requested limit

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
@mesosphere-mergebot sync

**Comment by gpaul** [comment]
@mesosphere-mergebot sync

**Comment by gpaul** [comment]
@mesosphere-mergebot sync

**Comment by jgehrcke** [comment]
@mesosphere-mergebot sync

**Comment by jgehrcke** [comment]
@mesosphere-mergebot sync

**Comment by jgehrcke** [comment]
@mesosphere-mergebot sync

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label ship it

**Comment by jgehrcke** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@jgehrcke - Let's merge this / leave with the ship-it. I will track what is happening with status tranfers. Mergebot sees the correct state (as shown by sync), but the Github statues do not see it.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status mergebot/enterprise/review/approved/min_2 DCOS-45635

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
I merged the pull request as I think, *github* is having issues with posting to status, that is why both transfer, and direct post did not succeed. If we notice of this behavior, we will track to find a workaround /solution.

**Comment by jgehrcke** [comment]
Thank you @orsenthil!!

**Pull request merged**
