### PR TITLE
full Windows pkgpanda, minus the packages

### PR DESCRIPTION
**Pull request by paulcallen**
## High-level description

Port pkgpanda to Windows. Note that this change does not include the packages necessary to deploy Windows agents, in fact most packages have been disabled because they no longer build in the latest windows docker container necessary to make the build function. If these packages were there this change would successfully build and deploy Windows agents via a Windows bootstrap node, and also upgrade from one version to another.

Types of changes included in this pull request are:
* port scripts to Windows PowerShell
* Work around symlink differences between windows and Linux
* use 7-zip on windows for compression and packaging

Windows CI jobs need to be updated to support these changes doe to a change in Windows base operating system version requirement, and the need for python 3.6.5 and 7zip.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-1899](https://jira.mesosphere.com/browse/DCOS_OSS-1899) Port pkgpanda to Windows.

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by paulcallen** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by paulcallen** [comment]
I believe this test failure is not as a result of my change, although not completely sure: teamcity/dcos/test/azure/arm 

The Windows build is expected as it requires CI changes and an RS4 Windows server core build and a couple of required apps

**Comment by branden** [comment]
Thanks @paulcallen, scoping this down was a big help. This is still a large PR, so I'm continuing to look for opportunities to split it up further, but that's a lot easier now that it's roughly half its former size. I have a few ideas for PRs that can be extracted from these changes, listed below.

1. **Improve Windows build scripts**
   * The changes in https://github.com/dcos/dcos/pull/3300/commits/e049aaf6f29b2186adc3f55f702aa664deaf436d don't appear to be directly related to any other changes in this PR, so let's split that commit out into its own PR.
   * Related commits:
      * https://github.com/dcos/dcos/pull/3300/commits/e049aaf6f29b2186adc3f55f702aa664deaf436d
1. **Use different package build commands on Windows and Linux so tests on Windows can use a generic Windows dockerfile**
   * The motivation for using different package build commands on Windows and Linux appears to be this line from the commit message for https://github.com/dcos/dcos/pull/3300/commits/fad8d1cfd1431ab567d7568bad83a22e7cf5cd9a:

      > Move some docker entrypoint commands back to the builder code itself so tests on Windows can use a generic Windows docker file and not the actual builder docker file which does not work on CI machines without first doing a build

      It also looks like this change is related to some of the Dockerfile changes at https://github.com/dcos/dcos/pull/3300/commits/65e77583df6cd97a3f476742616f327ae759516d and https://github.com/dcos/dcos/pull/3300/commits/afa9767b4223d1b1439a78cb8b4803091fe1e4f5. I think it makes sense to group these changes together in their own separate pull request. The goal quoted above sounds well defined, it's separable from the overall goal of building and deploying DC/OS on Windows, and CI can prove that Windows package builds succeed before and after the change. This PR would include only the edits to Pkgpanda Dockerfiles and related changes to `docker run` commands in `/pkgpanda/build/__init__.py` necessary to support using a generic Windows dockerfile, and should add a test that protects the use case it enables. The ticket for this PR should explain that use case in detail.
   * Related commits:
      * https://github.com/dcos/dcos/pull/3300/commits/afa9767b4223d1b1439a78cb8b4803091fe1e4f5
      * https://github.com/dcos/dcos/commit/65e77583df6cd97a3f476742616f327ae759516d
      * https://github.com/dcos/dcos/commit/fad8d1cfd1431ab567d7568bad83a22e7cf5cd9a
1. **Add support for advanced installation on Windows**
    * Let's have a PR focused just on getting the advanced install method ([doc](https://docs.mesosphere.com/1.11/installing/production/deploying-dcos/installation/)) working for deploying DC/OS to Windows agents (and enabling related unit tests), since that's a hefty enough goal on its own. This would include most of the pkgpanda and gen changes. The PR should come with an integration test that uses the advanced install method to deploy DC/OS to Windows. (Note that this doesn't require working packages -- a useful test would be to deploy DC/OS, confirm that the deploy successfully finished, and then tear down the cluster without trying to use it.)
   * Related commits:
      * https://github.com/dcos/dcos/pull/3300/commits/3a9fb378481f67620b2a189891a92ea57d571133
      * https://github.com/dcos/dcos/pull/3300/commits/f941c41f5a620710c0851f3a60224ff642ef5ea4
      * https://github.com/dcos/dcos/pull/3300/commits/2f9202b4c895422b07b14389b8b069dbca50a985
      * https://github.com/dcos/dcos/pull/3300/commits/3de6411f5094af5598b2f7f6f3eddaa2790cb0a4
      * https://github.com/dcos/dcos/pull/3300/commits/09f7ee19e9cd2830c703bf31c5abb7d88335dc6a
      * https://github.com/dcos/dcos/pull/3300/commits/cc98b5dafc8821dbb29d402e6298cf27bbaf8fb6
      * https://github.com/dcos/dcos/pull/3300/commits/fad8d1cfd1431ab567d7568bad83a22e7cf5cd9a
      * https://github.com/dcos/dcos/pull/3300/commits/e3cece29c3fda6dabbfb5d6b3b3d21b9aed16266
      * https://github.com/dcos/dcos/pull/3300/commits/957016775249d85d4575f709b5b41ee31714a47a
1. **Add support for upgrade on Windows**
   * This PR would contain the changes to the upgrade script that get it to work on Windows, and an integration test that verifies upgrading DC/OS nodes on Windows works.
   * Depends on PR 3 for some pkgpanda and gen changes.
   * Related commits:
      * https://github.com/dcos/dcos/pull/3300/commits/3a9fb378481f67620b2a189891a92ea57d571133
      * https://github.com/dcos/dcos/pull/3300/commits/9872a7346415bc2a3d0a7b3c453978ac8b58a2d2
1. **Add support for Azure ARM installation on Windows**
   * This PR would contain only the changes necessary to deploy DC/OS to Windows using Azure ARM, along with an integration test that verifies it works.
   * Depends on PR 3 for some pkgpanda and gen changes.
   * Related commits:
      * https://github.com/dcos/dcos/pull/3300/commits/cc98b5dafc8821dbb29d402e6298cf27bbaf8fb6
      * https://github.com/dcos/dcos/commit/09f7ee19e9cd2830c703bf31c5abb7d88335dc6a

(There are a few commits that are related to more than one of the above suggested PRs: https://github.com/dcos/dcos/commit/fad8d1cfd1431ab567d7568bad83a22e7cf5cd9a, https://github.com/dcos/dcos/commit/3a9fb378481f67620b2a189891a92ea57d571133, https://github.com/dcos/dcos/commit/09f7ee19e9cd2830c703bf31c5abb7d88335dc6a, and https://github.com/dcos/dcos/commit/cc98b5dafc8821dbb29d402e6298cf27bbaf8fb6. Those commits are doing multiple things that aren't necessarily related, and would benefit from being broken up.)

I think PRs 1-3 could be submitted and merged independently of each other. PRs 4 and 5 would depend on the gen and pkgpanda updates in PR 3, but otherwise be independent of each other. PRs 1-2 only need a build of DC/OS on Windows to verify that they're working. The remaining PRs could be adequately tested by integration tests that verify deploying (or upgrading) DC/OS on Windows as appropriate, without testing the running cluster itself. We could then start adding integration tests that run against a live cluster with later PRs that add packages that are intended to run on Windows.

Please let me know what your thoughts are about the above approach. Thanks!

**Comment by paulcallen** [comment]
This pull request did not solve the underlying issues so closing to stop confusion.

**Pull request closed without merging**
