### PR TITLE
1.12 train

### PR DESCRIPTION
**Pull request by AliakseiKhomchanka**
Updating fixVersion data for Mergebot
#3750

[1.12] Fix TLS handshake
#3716

### CODE REVIEW

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot label ready for review

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
