### PR TITLE
bump marathon 1.6.654

### PR DESCRIPTION
**Pull request by kensipe**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-43816](https://jira.mesosphere.com/browse/DCOS-43816) Marathon latest 1.6 bump for 1.11.7.

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS-42753](https://jira.mesosphere.com/browse/DCOS-42753) Bump Akka library to fix memory leak issue.
  - [MARATHON-8453](https://jira.mesosphere.com/browse/MARATHON-8453) TaskOverdueActor now respects `--kill_retry_timeout`.
  - [MARATHON-8452](https://jira.mesosphere.com/browse/MARATHON-8452) Only log zero-value offers for scalar resources.
  - [MARATHON-8461](https://jira.mesosphere.com/browse/MARATHON-8461) Write correct version in Zkid (based on scala timestamp changes)
  - [MARATHON-8413](https://jira.mesosphere.com/browse/MARATHON-8413) Fix versioning for Apps and Pods based on timestamp changes.
  - [MARATHON-8420](https://jira.mesosphere.com/browse/MARATHON-8420) Marathon behavior has changed to fail if service is torn down in mesos but the frameworkid is in zk.
  - [MARATHON-7941](https://jira.mesosphere.com/browse/MARATHON-7941) Default for unreachable strategy on PUT /apps.
  - [MARATHON-8323](https://jira.mesosphere.com/browse/MARATHON-8323) Increase http proxy max-open-connections default.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/mesosphere/marathon/compare/f56ad6ec8...3fa693b32)
  - [x] Test Results: [test](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-team-releases/job/marathon-community-release-1.6/56/)
  - [x] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
@mesosphere-mergebot Label Ready for Review

**Comment by jgehrcke** [comment]
I know that this is a little annoying to do after already having approvals. But can we please update https://github.com/dcos/dcos/blob/1.11/CHANGES.md as part of this?

**Comment by kensipe** [comment]
on it @jgehrcke

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static DCOS-43864

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
`teamcity/dcos/test/dcos-docker/static` - never got triggered to a TeamCity / CI issue. This will be tested in the train since the problem is resolved.

**Pull request merged**
