### PR TITLE
Train 157

### PR DESCRIPTION
**Pull request by jgehrcke**
This train includes the following pull requests:

#1448 [DCOS_OSS-444] Introduce toggle for TLS 1.0 support in Admin Router
#1462 Add onprem support for dcos-launch
#1466 dcos-builder: update base image to golang 1.8.1
#1472 bump 3dt sha
#1484 [DCOS_OSS-1003] Admin Router auth module: require a literal 'false' for disabling the module
#1490 openssl: add no-rc4 no-ssl2(3) enable-ec_nistp_64_gcc_128 build opts

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
This train is currently getting blocked on a strict mode flake out for the test_networking suite that is refactored in #1413 

As it stands currently, this test is flaking out on master in a fairly similar manner albeit for perhaps different reasons. That test is muted and so such failure go unnoticed. With this refactored test, each of those flakes is fully exposed.

For some reason, this only seems to occur in strict mode....

There are two choices:
- #1413 will happen to pass consistently enough that we do merge it in this PR and then get a patch out ASAP
- Kick #1413 from this train and stabilize the test now

To address this flake out, our initial move will be to force each test to use a unique VIP port as it is a unlikely use-case to repeatedly re-use the same vip for many unique applications in succession. See:
https://jira.mesosphere.com/browse/DCOS_OSS-1027

**Comment by orsenthil** [comment]
I vote for this:

> Kick #1413 from this train and stabilize the test now

I think, given the effort spent on #1413, it could just be taken a little further, investigated and then stabilized before bringing that in.

**Comment by jgehrcke** [comment]
> Kick #1413 from this train and stabilize the test now

Ok. I did `$ git rebase -i upstream/master --preserve-merges` and dropped #1413 via:
```
d 6f49e43 Consolidate test server app definition generation
d 19e00f2 Serialize test_networking.py::test_vip
d dee9c72 Convert marathon app parameters to constants
d d265dd6 Mark test_networking.py::test_vip as slow
d b98139a Cleanup
d b20cc6d Merge #1413
pick c3a8faf Merge #1448
pick 341c83e Add onprem support for dcos-launch
pick 0ff4f23 Fix rebase errors
pick 6aa1624 Disable onprem config prevalidation by default
pick 2f99140 Merge #1462
pick 5003b58 update golang to 1.8.1 in builder image
pick 8291584 Merge #1466
pick 57d9c89 bump 3dt sha
pick 587cd04 Merge #1472
pick 04f4a3f auth module: require a literal 'false' for disabling the module
pick 9c7167f Merge #1484
pick 181706a openssl: add no-rc4 no-ssl2(3) enable-ec_nistp_64_gcc_128 build opts
pick 2f0f42e Merge #1490
```
Followed by a force-push.

**Comment by orsenthil** [comment]
The `test_upgrade_vpc.marathon_app_tasks_survive_upgrade` 	is actually a stable test .

The failure is due to `upgrade-viplisten` - That might be related to actual inclusion and exclusion the pr  #1413.  

I'll re-trigger the upgrade test to see if I can reproduce the problem consistently. 
 
```
test_upgrade_vpc.marathon_app_tasks_survive_upgrade 	
First failure:	pull/1495	#2179 	Changes (14) 	27 Apr 17 12:57
 expected: {'/upgrade-healthcheck-c9c4c3acf01443a4a8ec18fe931ac2a7': ['upgrade-healthcheck-c9c4c3acf01443a4a8ec18fe931ac2a7.021d35a0-2b86-11e7-8346-96f99c7e8755'], '/upgrade-viplisten-175c4c83d73f4013936ae46fbd188e39': ['upgrade-viplisten-175c4c83d73f4013936ae46fbd188e39.e9089dbe-2b85-11e7-8346-96f99c7e8755'], '/upgrade-viptalk-516750901d234dfb89d54ec3fe2df519': ['upgrade-viptalk-516750901d234dfb89d54ec3fe2df519.f58bbdbf-2b85-11e7-8346-96f99c7e8755'], '/upgrade-dns-c9c4c3acf01443a4a8ec18fe931ac2a7': ['upgrade-dns-c9c4c3acf01443a4a8ec18fe931ac2a7.1af73581-2b86-11e7-8346-96f99c7e8755']}
actual:   {'/upgrade-healthcheck-c9c4c3acf01443a4a8ec18fe931ac2a7': ['upgrade-healthcheck-c9c4c3acf01443a4a8ec18fe931ac2a7.021d35a0-2b86-11e7-8346-96f99c7e8755'], '/upgrade-viplisten-175c4c83d73f4013936ae46fbd188e39': ['upgrade-viplisten-175c4c83d73f4013936ae46fbd188e39.3210fc90-2b88-11e7-a129-f6054732b51f'], '/upgrade-viptalk-516750901d234dfb89d54ec3fe2df519': ['upgrade-viptalk-516750901d234dfb89d54ec3fe2df519.f58bbdbf-2b85-11e7-8346-96f99c7e8755'], '/upgrade-dns-c9c4c3acf01443a4a8ec18fe931ac2a7': ['upgrade-dns-c9c4c3acf01443a4a8ec18fe931ac2a7.1af73581-2b86-11e7-8346-96f99c7e8755']}
```

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
