### PR TITLE
Test against Python 3.6

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Test DC/OS against Python 3.6

## Corresponding DC/OS tickets (required)

  - [D2IQ-63690](https://jira.d2iq.com/browse/D2IQ-63690) Test Against Python 3.6

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot test

**Comment by orsenthil** [comment]
@mesosphere-mergebot test all

**Comment by orsenthil** [comment]
@mesosphere-mergebot test all

**Comment by orsenthil** [comment]
@mesosphere-mergebot test  teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Comment by cgawron1** [comment]
@mesosphere-mergebot test teamcity/dcos/build/tox

**Pull request closed without merging**
