### PR TITLE
Support custom managers in cosmos

### PR DESCRIPTION
**Pull request by kvish**
## High-level description

What features does this change enable? What bugs does this change fix?

This change support custom managers in cosmos for k8s team. See [DCOS-39579](https://jira.mesosphere.com/browse/DCOS-39579)

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - PR addresses all tickets under [DCOS-39579](https://jira.mesosphere.com/browse/DCOS-39579): Route package/install, package/uninstall, service/update, service/describe requests to custom managers when needed

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: managerId field is NOT user facing, this is a work around to enable custom management for k8s only. This feature will be hidden for regular users. [more](https://docs.google.com/document/d/1hJTZImY5JBeIBkQVgPUjVu0TwMb6bkzu71q4SbDDIfo/edit#)
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/cosmos/compare/2ebeaf3af34a26da89ca1c0abfe67c3c7572117e...451f7ccd255f67456c35b352c83467db0c2e4838)
  - [x] Test Results: [link to CI job test results for component] [here](https://teamcity.mesosphere.io/viewLog.html?buildId=1183848&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_PublishSnapshot)
  - [x] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by kvish** [comment]
@mesosphere-mergebot bump-ee

**Comment by kvish** [comment]
@mesosphere-mergebot label ready for review

**Comment by kvish** [comment]
@mesosphere-mergebot bump-ee

**Comment by kvish** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
This is the EE PR: https://github.com/mesosphere/dcos-enterprise/pull/3327  (

**Pull request merged**
