### PR TITLE
Add fetch_cluster_logs.bash

### PR DESCRIPTION
**Pull request by cprovencher**

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot teamcity/dcos/test/dcos-docker/static override-status https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by pcrews** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/dcos-docker/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by gauripowale** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/dcos-docker/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
