### PR TITLE
Train 207

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

* chore(dcos-ui): update package to v1.10.0-rc.6 #1854

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@spahl  / @lingmann  - please review.

**Comment by orsenthil** [comment]
We needed a train because the the EE side has multiple Prs.

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
