### PR TITLE
[1.11] Add more information to diagnostics bundle

### PR DESCRIPTION
**Pull request by janisz**
## High-level description
  
Backport #3211
    
This PR adds folowing information to diagnostics bundle
    * [`/quota`](http://mesos.apache.org/documentation/latest/endpoints/master/quota/)
    * [`/containers`](http://mesos.apache.org/documentation/latest/endpoints/slave/containers/)
    * [`/proc/[cmdline|cpuinfo|meminfo]`](http://man7.org/linux/man-pages/man5/proc.5.html) – additional hardware infro
    * [`ps aux www`](http://man7.org/linux/man-pages/man1/ps.1.html) – lists all proceses with wide information about them
    
## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-3958](https://jira.mesosphere.com/browse/DCOS_OSS-3958): Add information to diagnostics bundle

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@philipnrmn Can you take a look?

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot override-status mergebot/review/approved/min_2 DCOS-35423

**Comment by gpaul** [comment]
@janisz I don't know what happened here. This is bad as the bump PR got merged but this one didn't which leads to inconsistent state.

@cprovencher @orsenthil PTAL - something weird happened here

**Comment by orsenthil** [comment]
@gpaul  - Thanks for the alert. This was missed in the train review and we should have caught it. The problem was due to a mergebot bug (https://jira.mesosphere.com/browse/DCOS-40713) and I will resolve it.

I will also fix the situation with this PR and the EE part without the open is merged and this should be resolved immediately.

**Comment by orsenthil** [comment]
Merging this and updating the EE reference manually as the EE PR associated with this change got merged in the previous train (as noted in the comment: https://github.com/dcos/dcos/pull/3273#issuecomment-418316409)

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
The original EE PR was already merged (by mistake) and the manual merge of the current PR, and merge of this https://github.com/mesosphere/dcos-enterprise/pull/3364 will fix our references for 1.11 branch.

**Comment by orsenthil** [comment]
EE PR is merged too and the problem (/confusion) is resolved now. Thank you!

**Pull request merged**
