### PR TITLE
dcos version =  1.10-beta2

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

Set the DCOS version to 1.10-beta2

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
Are 19/20 of the enterprise smoke tests failing related to the version bump?  Or is that a separate issue https://teamcity.mesosphere.io/viewLog.html?buildId=720565&buildTypeId=ClosedSource_MesosphereEnterpriseDcOs_IntegrationTests_DcOsCommonsSmokeTest&guest=1 🤔

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
The test failures in this pull request should be followed up upon. I have updated https://jira.mesosphere.com/browse/DCOS_OSS-1463 for now.

**Pull request merged**
