### PR TITLE
Bump to latest Marathon snapshot

### PR DESCRIPTION
**Pull request by timcharper**
## High-level description

Bump Marathon to 1.9 latest, with the primary feature being multi-role support. See the related tickets for new features introduced in this bump.

## Corresponding DC/OS tickets (required)

  - [DCOS-56722](https://jira.mesosphere.com/browse/DCOS-56722) Include Marathon 1.9 snapshot it DC/OS latest

## Related tickets (optional)

* [MARATHON-8642](https://jira.mesosphere.com/browse/MARATHON-8642), [MARATHON-8666](https://jira.mesosphere.com/browse/MARATHON-8666) - Task role metadata
* [MARATHON-8650](https://jira.mesosphere.com/browse/MARATHON-8650) - Default group role behavior
* [MARATHON-8651](https://jira.mesosphere.com/browse/MARATHON-8651) - Patch group enforce role
* [MARATHON-8662](https://jira.mesosphere.com/browse/MARATHON-8662) - Support reservations for multirole
* [MARATHON-8653](https://jira.mesosphere.com/browse/MARATHON-8653) - Add deprecated feature flag to opt out of acceptedResourceRoles validation

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [d56fe7703...77eb26534](https://github.com/mesosphere/marathon/compare/d56fe7703...77eb26534)
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/1336/

### CODE REVIEW

**Comment by timcharper** [comment]
@mesosphere-mergebot bump-ee

**Comment by timcharper** [comment]
@mesosphere-mergebot Ready for review

**Comment by timcharper** [comment]
@mesosphere-mergebot label Ready for review

**Comment by timcharper** [comment]
@mesosphere-mergebot override-status readme

**Comment by timcharper** [comment]
@mesosphere-mergebot override-status changes

**Comment by timcharper** [comment]
failure in group1 is flaky: https://jira.mesosphere.com/browse/DCOS-55827

**Comment by timcharper** [comment]
@mesosphere-mergebot override-status pr-status-check https://jira.mesosphere.com/browse/DCOS-55827

**Comment by vinodkone** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/test-e2e/group1 https://jira.mesosphere.com/browse/DCOS-55827

**Pull request merged**
