### PR TITLE
Add owners from the Mesos pool of committers.

### PR DESCRIPTION
**Pull request by rukletsov**
## High-level description

This patch adds owners from the pool of Apache Mesos committers. Three people are in three different timezones and hence cover Apache Mesos ownership pretty well. 

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - none.

## Related tickets (optional)

Other tickets related to this change:

  - none

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by karya0** [comment]
@jgehrcke : Can you manually apply the Ship-it label to this one? This doesn't have any code changes so not sure if we still need EE bump.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple DCOS_OSS-2115

**Comment by orsenthil** [comment]
Hey @rukletsov  / @karya0  / @greggomann - 

Thank you! I wanted to share that this brings an additional responsibility too. You will be in CC: whenever mergebot is used to override the flaky tests. It is awareness so that you could assist others when they are struck. 

You could also apply the `ship-it` when deemed necessary and `merge-it` for the Trains that have met all the merge criteria encoded in the status-checks.

Thank you!

**Comment by greggomann** [comment]
SGTM, thank you @orsenthil

**Comment by orsenthil** [comment]
@rukletsov  - It doesn't make sense for these kinds of PRs, but we still do  `@mesosphere-mergebot bump-ee` on every PR, by issuing a command so that the EE side is tested against the PR against the master. And if this PR lands in dcos/dcos master, the EE pointer will be updated to the HEAD of dcos/dcos.

Also, as a process, we do a `bump-ee` and add the additional changes to the `bump-ee`. This will statisfy the status checks like these (`mergebot/enterprise/build-status/aggregate`, `mergebot/enterprise/review/approved/min_2`, `mergebot/enterprise/has_ship-it `) encoded in this PR.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by mesosphere-mergebot2** [comment]
Your pull request's branch is not based on the most recent version of `master`. Please rebase your changes against this repo's `master` branch.

**Comment by orsenthil** [comment]
This has been waiting for 6-days and EE PR is separated raised here - https://github.com/mesosphere/dcos-enterprise/pull/2678 

I am going ahead with applying the ship-it label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by karya0** [comment]
Thanks @orsenthil!

**Pull request merged**
