### PR TITLE
[1.9.1] Bump dcos-metrics for 1.9.1

### PR DESCRIPTION
**Pull request by philipnrmn**
## High Level Description

This change brings dcos-metrics up to date, resolving the last known issues affecting the ability of the package to work with external metrics storage providers. 

Specifically, it improves error handling and avoids transmitting very long labels. 

### Changelog:
- [Handle errors gracefully](https://github.com/dcos/dcos-metrics/pull/96/commits/7b84b5e01d3d1cdcb3a11c0c31390a27a40b3b70)
- [Drop long labels in mesos agent](https://github.com/dcos/dcos-metrics/pull/96/commits/cca85f336eee440c2468d4b4c9d1c3b246654188)

### Test results
https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/374/

### Code coverage report
https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/374/cobertura/

## Related Issues

  - [DCOS-15224](https://jira.mesosphere.com/browse/DCOS-15224) Improve error handling to dcos-metrics DataDog plugin
  - [DCOS-15939](https://jira.mesosphere.com/browse/DCOS-15939) Long labels can cause errors in datadog plugin for dcos-metrics

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-metrics/compare/a01acda5647c3108cff62851bc694d26d1a503d5...cca85f336eee440c2468d4b4c9d1c3b246654188)
  - [x] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/374/)
  - [x] Code Coverage (if available): [link to code coverage report](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/374/cobertura/)

### CODE REVIEW

**Comment by philipnrmn** [comment]
@collinvandyck @klueska would you kindly review this PR?

**Comment by philipnrmn** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by philipnrmn** [comment]
@mesosphere-mergebot bump-ee

**Comment by philipnrmn** [comment]
@collinvandyck oof, you're right. I misunderstood the use of the `ref_origin` field (which in retrospect is pretty obvious). Do you think it would be better to delete and remake the tag, or use a branch?

**Comment by collinvandyck** [comment]
I think tags are supposed to be somewhat immutable.  So deleting and moving the tag each time we want to backpatch the 1.9 series seems unfortunate.  Maybe we should just go with the branch for now and delete the tag?

**Comment by philipnrmn** [comment]
Yeah, updating the tag felt wrong. I'll go with your suggestion, thanks again for catching the error.

**Comment by philipnrmn** [comment]
Squashed and pushed.

**Comment by philipnrmn** [comment]
@branden mind giving this a ship-it label?

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
