### PR TITLE
[1.13] Update urllib to fix build problem

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

Pin the version of `requests` and `urllib` to allow CI to pass. Get ZooKeeper from our own repo

## Corresponding DC/OS tickets (required)

  - [D2IQ-ID](https://jira.d2iq.com/browse/D2IQ-ID) JIRA title / short description.

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot test all

**Comment by jongiddy** [comment]
@mesosphere-mergebot test all

**Comment by jongiddy** [comment]
@mesosphere-mergebot test all

**Comment by jongiddy** [comment]
@mesosphere-mergebot test all

**Comment by orsenthil** [comment]
Thanks, @jongiddy.  If all integration tests succeed this could unblock  DC/OS builds.

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @orsenthil

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required infra changes only

**Review by orsenthil — APPROVED** [review]
LGTM

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
