### PR TITLE
e2e: add external calico tests

### PR DESCRIPTION
**Pull request by jkoelker**
## High-level description

Add tests for accessing calico from outside the cluster.

## Corresponding DC/OS tickets (required)

  - [D2IQ-61011](https://jira.d2iq.com/browse/D2IQ-61011) DC/OS integration tests for accessing calicoctl from outside of the cluster

### CODE REVIEW

**Comment by jkoelker** [comment]
@mesosphere-mergebot changelog-not-required part of calico effort

**Comment by DominikDary** [comment]
@wavesoft can this be merged?

**Comment by DominikDary** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
