### PR TITLE
Upgrade Marathon to 1.4.3

### PR DESCRIPTION
**Pull request by timcharper**
https://github.com/mesosphere/marathon/releases/tag/v1.4.3

## High Level Description

Bugfix release

## Changes from 1.4.2 to 1.4.3
Bugfix release

### Fixed issues

- [MARATHON-7267](https://jira.mesosphere.com/browse/MARATHON-7267) Enforce validation for pod container names
- [DCOS-14890] Fix default scheme for HTTP health checks in pods
- [DCOS-14303] Fix issue in which Marathon would fail to launch if hostname is not resolvable (but still specified from the command line)

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by timcharper** [comment]
@mesosphere-mergebot bump-ee

**Comment by timcharper** [comment]
CC @kensipe ^^ :D

**Comment by aquamatthias** [comment]
retest this please

**Comment by adam-mesos** [comment]
Since you are bumping a component (Marathon), please fill out the component checklist, especially the Changelog link and the Marathon CI test results.

**Comment by jdef** [comment]
why is this in the 1.10 milestone? had a hard time finding this

**Comment by adam-mesos** [comment]
Because this PR is against `dcos:master`, which is 1.10.
If you wanted this bump in 1.9.1, then we need a PR against that branch.

**Pull request merged**
