### PR TITLE
bump ui version to 2.36.5

### PR DESCRIPTION
**Pull request by mperrotti**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
DCOS-43779
DCOS-40871
DCOS-46676
DCOS-43897
DCOS-44017
DCOS_OSS-4245
DCOS-44456
DCOS-43383
DCOS-42974
DCOS-44138
DCOS-43375
DCOS-41415
DCOS-43373
DCOS-43340
DCOS-41578
DCOS-43461
DCOS-43349
DCOS-43087
DCOS_OSS-4270
DCOS_OSS-4273
DCOS_OSS-2358
DCOS-43041
DCOS-43050
DCOS-43055
DCOS-40640

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by mperrotti** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by natmegs** [comment]
Should we take out the sample obligatory corresponding ticket? Not sure if it matters

**Comment by mperrotti** [comment]
@natmegs - I corrected the description per your feedback

**Comment by nLight** [comment]
@mperrotti as I can't edit a PR on dcos, would you please change the jira numbers to be links? Like it was suggested in the PR template:
`  - [DCOS-](https://jira.mesosphere.com/browse/DCOS-)` 

I'm afraid the @mesosphere-mergebot won't pick them up unless they are links.

Thanks!

**Comment by orsenthil** [comment]
@nLight - It will pick up any regex of form `"jira_regex": "((?:DCOS|DCOS_OSS|COPS|MARATHON)-\\d+)"`  https://github.com/dcos/dcos/blob/master/mergebot-config.json to update the fix version.

**Comment by nLight** [comment]
Oh, good to know! Though I'd still stick to the template

**Pull request merged**
