### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Aug-08-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3222 - [1.11] Bump Mesos to nightly 1.5.x 3ce0e64
* #3225 - [1.11] packages/java: Update Java to 8u181 version

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot Ready For Review

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
