### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Nov-13-22-46

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3645 - Bump dcos-log
* #3704 - [1.11] Bump dcos-net
* #3720 - [1.11] Added Mesos patch to include health checks in master API outputs.
* #3753 - Update dcos-test-utils

### CODE REVIEW

**Comment by pcrews** [comment]
@mesosphere-mergebot label ready for review

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by jdef** [comment]
@mesosphere-mergebot label Ship It

**Comment by orsenthil** [comment]
@mesosphere-mergebot label Ship It

**Comment by orsenthil** [comment]
@mesosphere-mergebot  merge-it

**Pull request merged**
