### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-May-18-02-08

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2878 - Bump 1.10 to 1.10.7
* #2869 - Updated Mesos patches to extra/patches directory.

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot override-status  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot label [Ready For Review |Holding |Request For Comment |Ship It |Work In Progress] 
@mesosphere-mergebot bump-ee  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
The build failure needs investigation - https://teamcity.mesosphere.io/viewLog.html?buildId=1068249&buildTypeId=DcOs_Open_Build_BuildDcOs&tab=buildLog&_focus=5771#_state=5771 - (Noticed this late. I could do this on May 19, PST).

**Comment by orlandohohmeier** [comment]
@orsenthil can we please move the UI bump forward and drop the Mesos changes for now?

**Comment by orlandohohmeier** [comment]
@orsenthil alright, thanks for the update.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/tox-windows https://jira.mesosphere.com/browse/DCOS_OSS-3530

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
