### PR TITLE
Windows: Add full Pkgpanda support

### PR DESCRIPTION
**Pull request by paulcallen**
## High-level description

This pull request does the full Windows port of the Pkgpanda component.

We will be able to build and setup the entire DC/OS product fully using Pkgpanda. In addition to this, the code has been added to do a DC/OS upgrade on Windows as well, since support for the Windows bootstrap node is added.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-1899](https://jira.mesosphere.com/browse/DCOS_OSS-1899) Port pkgpanda to Windows.

## Checklist for all PRs

  - [x] porting bash scripts to powershell
  - [x] create Windows versions of docker files to build packages in
  - [x] port all relevant unit tests to Windows (112 pass, 58 skip)
  - [x] configure all packages needed for windows
  - [x] updates to support system service units on Windows
  - [x] use 7-zip for all archives on Windows
  - [x] work around python issues on Windows such as symbolic links and file system issues
  - [x] externally updated dcos-engine to do a full deployment in Azure with this change (successfully!)
  - [x] CI jobs are up and working within Microsoft for building / running tox tests and the end-to-end tests too

### CODE REVIEW

**Comment by orsenthil** [comment]
Hi @paulcallen  - The `teamcity/dcos/build/dcos` and `teamcity/dcos/build/tox` and other status checks need to succeed for this PR. Please set this to `ready for review` once it the default DC/OS tox and build succeeds.

**Comment by paulcallen** [comment]
@orsenthil I am working on the build and tox issues :) Thanks.

**Comment by paulcallen** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by paulcallen** [comment]
@orsenthil is there anything I can do here to help troubleshoot these failures?

**Comment by orsenthil** [comment]
Hi @paulcallen  - I see that you have access to the TC account. You could login to see the errors. It looks like all the integration tests have failed. These are timing out in post-start checks and most definitely related to changes being introduced and being incompatible with the build/test of DC/OS

```
[08:34:50]	[2018-08-03 15:34:50,724|dcos_test_utils.dcos_api|INFO]: dcos-pkgpanda-api.service service health: 1
[08:34:52]	[2018-08-03 15:34:52,727|dcos_test_utils.helpers|DEBUG]: Request method GET: http://172.16.0.5/system/health/v1/units?cache=0. Arguments: {}
[08:34:52]	[2018-08-03 15:34:52,728|urllib3.connectionpool|DEBUG]: Starting new HTTP connection (1): 172.16.0.5
[08:34:52]	[2018-08-03 15:34:52,779|urllib3.connectionpool|DEBUG]: http://172.16.0.5:80 "GET /system/health/v1/units?cache=0 HTTP/1.1" 200 None
Show more...
```

I can help you further to reproduce this error locally, if you prefer.

**Comment by paulcallen** [comment]
@orsenthil the two sets of tests failing now do not look related to my changes to the best of my knowledge

**Comment by orsenthil** [comment]
@paulcallen  - Yes, you are right, those are not related to your changes. We can move forward with reviewing this PR. Thank you!

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by ionutbalutoiu** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by ionutbalutoiu** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by paulcallen** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by paulcallen** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by ionutbalutoiu** [comment]
Just updated the pull request and fixed the `Windows Apache Web Server package` since the old download URL for the package was expired.

**Comment by ionutbalutoiu** [comment]
Hello everyone,

Just added the commit https://github.com/dcos/dcos/pull/3192/commits/c6919a06ea5f123529c0955a0d06abd16f991b66. This removes the `dcos-metrics` service from Windows and adds the `dcos-telegraf` since it works out of the box on Windows as well.

Regards,
Ionut

**Pull request closed without merging**
