### PR TITLE
[DCOS_OSS-1470] Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger

### PR DESCRIPTION
**Pull request by rdeliallisi**
## High Level Description

What features does this change enable? What bugs does this change fix? High-Level description of how things changed.

## Related Issues

  - [DCOS_OSS-1470](https://jira.dcos.io/browse/DCOS_OSS-1470) Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger.

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jgehrcke** [comment]
@rdeliallisi please update the PR description template :)

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by rdeliallisi** [comment]
@adamtheturtle There is already log output on the PR for 1.10 (https://github.com/dcos/dcos/pull/1784). As for testing we might include one. We could trigger and exception by connecting to one of the zookeeper ports, 2181 for instance, and send an invalid command. Then the journal has to be parsed  to check for ZK exceptions. There is one problem with this tough, the exception contains no specific information about the client that caused it. The fact that ZK "usually" does not throw any exceptions during normal cluster running to just look for any exception, but this is extremely hakcy. Since this feature is not of critical importance to the cluster I decided not to write any tests.
@vespian The change does not affect Exhibitor logging, it changes only ZK logging configuration. It is however true that Exhibitor can clog journald, but I haven't come across any ticket referring to this issue.

**Comment by jgehrcke** [comment]
> The only thing that I am worried about is that if/when Exhibitor starts to fail in a continous manner(e.g. every 5s), the amount of logs that is going to be produced can clog journald.

"can", yes. :) Will? We don't know. Let's cross that bridge when... :-)

**Comment by jgehrcke** [comment]
Technically, we are fine with the `mergebot/enterprise/build-status/aggregate` failure (as of the ADS1 outage). Approving.

**Comment by adamtheturtle** [comment]
> Since this feature is not of critical importance to the cluster I decided not to write any tests.

@rdeliallisi We apparently care that this is was working properly. For me, this is reason enough to add a test. We don't only test "critical" functionality.

**Comment by jgehrcke** [comment]
No other pull request is currently labeled with the 1.9.3 milestone and the `ship-it` label. Proceeding with the integration.

**Comment by jgehrcke** [comment]
> We apparently care that this is was working properly. For me, this is reason enough to add a test. We don't only test "critical" functionality.

@rdeliallisi please work together with @adamtheturtle to find a pragmatic testing method. Then please create a JIRA ticket that describes that idea.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
> @vespian The change does not affect Exhibitor logging, it changes only ZK logging configuration. It is however true that Exhibitor can clog journald, but I haven't come across any ticket referring to this issue.

Uhh... I am sorry, I just quickly checked the PR title and assumed that this is an Exhibitor logging change :(

**Pull request merged**
