### PR TITLE
Bump Marathon to 1.8.232.

### PR DESCRIPTION
**Pull request by jeschkies**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS-62078](https://jira.mesosphere.com/browse/DCOS-62078) Marathon launches too many tasks.
 - [DCOS_OSS-5679](https://jira.mesosphere.com/browse/DCOS_OSS-5679) Problem with tasks multiplication during application upgrade.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [x] Test Results: [Marathon Build](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/releases%252F1.8/24/)
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jeschkies** [comment]
@mesosphere-mergebot sync

**Comment by jeschkies** [comment]
@mesosphere-mergebot changelog-not-required

**Comment by jongiddy** [comment]
@jeschkies Should we have a changelog that the Marathon version has changed?

**Comment by jeschkies** [comment]
> Should we have a changelog that the Marathon version has changed?

@jongiddy, that's a good question. I thought that the JIRA references in the PR message are enough. I'll add a changelog entry anyways.

**Comment by cgawron1** [comment]
@mesosphere-mergebot sync

**Pull request merged**
