### PR TITLE
Adding xvdb

### PR DESCRIPTION
**Pull request by amitaekbote**
## High Level Description
Add second volume to the cloudformation template instances

## Related Issues

https://jira.mesosphere.com/browse/DCOS_OSS-1702 

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by amitaekbote** [comment]
@mesosphere-mergebot label ready for review

**Comment by amitaekbote** [comment]
@lingmann can you approve this pr? I am not sure what the cost for an additional volume is on aws

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
80GB of gp2 EBS space in us-west-2 will add roughly $0.01/hour to running costs for each node in the cluster, so I think the cost aspect of this change is relatively insignificant to overall cluster costs. And I believe this will ensure proper disk usage isolation between / and /var/lib correct @amitaekbote ? If so, 👍  :)

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@orsenthil why did you remove the ship it label on this? I rebased because jeremy asked me to

**Comment by orsenthil** [comment]
@amitaekbote  - it is for investigating this: https://jira.mesosphere.com/browse/DCOS-19149 
I don't know how the mergebot added the ship-it label when there were red/ pending status checks.

**Comment by amitaekbote** [comment]
there werent pending red checks, its because I rebased after ship it label cause jeremy asked me to

**Comment by orsenthil** [comment]
@amitaekbote - this should be good to go now.

Two questions:

1. Was the previous ship-it added manually using the ship-it label command?

2. On the code itself, I think, this will prevent the errors like:

> Sep 27 16:39:10 ip-10-0-4-128.us-west-2.compute.internal bash[1270]: The file /dev/xvdb does not exist and no size was specified. 

But as Jeremy requested in his comment, will it " ensure proper disk usage isolation between / and /var/lib" ? While reviewing, I could not figure this out from docs/jira/discussion here.

**Comment by lingmann** [comment]
@amitaekbote did you see this [failure msg](https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=814606&_focus=4629) on `teamcity/dcos/test/docker`? It looks to me like `test_log_text` is getting different output than the test expects now that we have this xvdb device attached. cc: @mnaboka @klueska

**Comment by lingmann** [comment]
@orsenthil my concerns are addressed. I believe Amita and I chatted about this IRL. LGTM / ship-it!

**Pull request merged**
