### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Jun-27-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2977 - [1.11] Update checks timeout
* #3001 - [1.11] Increase timeout for package download

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Ship It |Holding |Work In Progress |Ready For Review |Request For Comment] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by adamtheturtle** [comment]
I manually added a Ship It as per https://jira.mesosphere.com/browse/DCOS-38650.

**Comment by adamtheturtle** [comment]
@mesosphere-mergebot label Ship It

**Comment by orsenthil** [comment]
@mesosphere-mergebot label Ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
