### PR TITLE
Bump Metronome to 0.6.63

### PR DESCRIPTION
**Pull request by pierrebeitz**
* [D2IQ-71940](https://jira.d2iq.com/browse/D2IQ-71940)

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot changelog-not-required jobs-with-deps already mentioned

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot sync

**Review by DominikDary — APPROVED** [review]

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot test all

**Comment by orsenthil** [comment]
Applying ship-it since the CI test was successful and only the status was not reported back.

**Pull request merged**
