### PR TITLE
Update python-requests from 2.6 to 2.7

### PR DESCRIPTION
**Pull request by mellenburg**

### CODE REVIEW

**Comment by malnick** [comment]
@spahl Can you run this into the merge queue?

**Comment by spahl** [comment]
:ship:

**Comment by cmaloney** [comment]
Why not upgrade to the actual latest, 2.10.0?

**Comment by mellenburg** [comment]
@cmaloney No reason, just wanted to get the minimum upgrade through to unblock. Heres a PR for lastest: https://github.com/dcos/dcos/pull/75

**Pull request merged**
