### PR TITLE
DCOS 1.9 - Train 254

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

* openssl: Disable TLS compression [1.9] #2079
* (1.9) Remove sensitive config values from diagnostics bundles and build output #2087

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
Upgrade from 1.8 to 1.9  timeout is captured here: https://jira.mesosphere.com/browse/DCOS-19208
`teamcity/dcos/test/upgrade-from-previous-major ` is override.

**Comment by orsenthil** [comment]
`teamcity/dcos/test/upgrade` - re-triggered the test because the test setup did not return after executing one test successfully. This should not block the PR.

**Comment by orsenthil** [comment]
`teamcity/dcos/test/upgrade` runs till timeout. Captured here: https://jira.mesosphere.com/browse/DCOS-19530 Probably due to use-checks, but we cannot expect the user to set the parameter and run every time.  

* Both Engineer's time and Infrastructure resources are wasted by that test / setting in 1.9 branch.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
