### PR TITLE
Pass origin info to custom managers in cosmos 

### PR DESCRIPTION
**Pull request by kvish**
## High-level description

pass client origin info to mke custom manager. This allows mke to deproxy/reproxy resource urls. 

What features does this change enable? What bugs does this change fix?
These cosmos changes support passing on information to multi kubernetes engine, to allow a single point of control for k8s on dcos
## Corresponding DC/OS tickets (obligatory)
[DCOS-41149](https://jira.mesosphere.com/browse/DCOS-41149) - SOAK Test for k8 Cosmos changes

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: cosmos custom managers is build to support k8s and is not customer facing
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [here](https://github.com/dcos/cosmos/compare/cb14dbaa1cd1c41d0406fd168ae3a12aabe43a64...44225ce4d84951d54b1d554b87f48db954ad2598)
  - [x] Test Results: [link to CI job test results for component](https://teamcity.mesosphere.io/viewLog.html?buildId=1193615&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_FullClusterIntegrationTests)
  - [x] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by kvish** [comment]
@mesosphere-mergebot bump-ee

**Comment by kvish** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by kvish** [comment]
@mesosphere-mergebot label Work In Progress

**Comment by kvish** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by MatApple** [comment]
@kvish can you please shepherd this one in so it makes it into soak112? Also, this might need to be cherry picked to the 1.12 beta release branch. cc/ @orsenthil

**Comment by orsenthil** [comment]
@MatApple  - Noted.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm  https://jira.mesosphere.com/browse/DCOS_OSS-4045

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS_OSS-4045

**Comment by orsenthil** [comment]
Hi @kvish  / @takirala  / @MatApple  - Please share as **why** this is critical for -beta1. This has already missed the cut-off date, and I unable to make a decision with the information given in the PR.

**Comment by orsenthil** [comment]
> These cosmos changes support passing on information to multi kubernetes engine, to allow a single point of control for k8s on dcos


Does this mean without this, "multi-kubernetes" engine is un-usable?

**Comment by kvish** [comment]
@mesosphere-mergebot bump-ee

**Comment by kvish** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
