### PR TITLE
Marathon 1.6.549 Bump on 1.11

### PR DESCRIPTION
**Pull request by kensipe**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-41716](https://jira.mesosphere.com/browse/DCOS-41716) Bump Marathon for 1.11.6.

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS-37999](https://jira.mesosphere.com/browse/DCOS-37999) Loosen constraint validation during migration.
  - [MARATHON-8095](https://jira.mesosphere.com/browse/MARATHON-8095) PATCH call not proxied correctly to active node.
  - [MARATHON-8381](https://jira.mesosphere.com/browse/MARATHON-8381) Use Different Exit Code for Marathon Suicide.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/mesosphere/marathon/compare/6b23a51d9...aabf74302)
  - [x] Test Results: [CI](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/releases%252F1.6/20/console)
  - [x] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
@mesosphere-mergebot Label Ready for Review

**Comment by jgehrcke** [comment]
(adding the `1.11.6` section to `CHANGES.md` here: https://github.com/dcos/dcos/pull/3430/files)

**Comment by kensipe** [comment]
@jgehrcke we update marathon on DCOS without an official release all the time... it is after the DCOS build and after soak that we deem marathon worth of a release.   We will not have release notes to link to.   I've provided a link the sha... but it doesn't seem valuable to me.

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
all errors appear to be based on known flaky vip tests.

**Comment by meichstedt** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/dcos-e2e/docker/static/strict https://jira.mesosphere.com/browse/DCOS-19790

**Comment by kensipe** [comment]
:(

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
