### PR TITLE
Bump dcos-test-utils version

### PR DESCRIPTION
**Pull request by oprinmarius**
## High-level description
Bumps dcos-test-utils version to remove .json from mesos slaves state endpoint .

## Related PRs (optional)
https://github.com/dcos/dcos-test-utils/pull/59

## Checklist for component/package updates:

- [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): 
https://github.com/dcos/dcos-test-utils/compare/5361c8623cd0751f9312cf79b66dde6f09da1e74...8f1820f537b0caa4bbb697beaae4d1e4940bfbb6

### CODE REVIEW

**Comment by oprinmarius** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Pull request merged**
