### PR TITLE
[master] Mergebot Automated Train PR - 2019-Jan-09-21-40

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #4100 - Add Metronome jobs to diagnostics bundle
* #4105 - Fix validation of overlay backends
* #4118 - DCOS-46756 - Replace dcos-e2e cli with minidcos.
* #4121 - Unmute test_vip
* #4133 - Delete .DS_Store
* #4141 - Bump dcos-diagnostics

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label work in progress

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Pull request merged**
