### PR TITLE
Hide secret keys from user.config.yaml

### PR DESCRIPTION
**Pull request by makkes**
## High-level description

What features does this change enable? What bugs does this change fix?

The configuration variables `aws_secret_access_key` and `exhibitor_azure_account_key` (https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/#exhibitor-storage-backend) must be marked as secret so that they are not accidentally revealed by diagnostics tools.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-51751](https://jira.mesosphere.com/browse/DCOS-51751) aws_secret_access_key is not hidden in diagnostics bundle

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: 
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: I tested this manually.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by makkes** [comment]
@jgehrcke What about this?

**Comment by makkes** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mhrabovcin** [comment]
@makkes was this tested manually?

**Comment by makkes** [comment]
@jongiddy @adamtheturtle @timaa2k @ahairape @mhrabovcin would you mind reviewing this?

**Comment by makkes** [comment]
> @makkes was this tested manually?

I'm in the process of spinning up a cluster and testing it...

**Comment by adamtheturtle** [comment]
@makkes Please can you fill in the "Checklist for all PRs" in the description as it is key for a reviewer?

**Comment by makkes** [comment]
> > @makkes was this tested manually?
> 
> I'm in the process of spinning up a cluster and testing it...

```
[centos@ip-172-12-12-36 dcos]$ sudo grep -A1 secret /opt/mesosphere/etc/user.config.yaml /opt/mesosphere/etc/user.config.full.yaml
/opt/mesosphere/etc/user.config.yaml:"aws_secret_access_key": |-
/opt/mesosphere/etc/user.config.yaml-  **HIDDEN**
--
/opt/mesosphere/etc/user.config.full.yaml:"aws_secret_access_key": |-
/opt/mesosphere/etc/user.config.full.yaml:  myawssecretaccesskey
/opt/mesosphere/etc/user.config.full.yaml-"bootstrap_url": |-```

**Comment by mhrabovcin** [comment]
I'd definitely add a changelog entry for 1.12 and 1.11 versions. CC @jgehrcke

**Comment by makkes** [comment]
> I'd definitely add a changelog entry for 1.12 and 1.11 versions. CC @jgehrcke

I added an entry to `CHANGES.md`.

**Pull request merged**
