### PR TITLE
Bump dcos-diagnostics

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

Fixes flaky test by https://github.com/dcos/dcos-diagnostics/pull/76

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  -[DCOS_OSS-4463](https://jira.mesosphere.com/browse/DCOS_OSS-4463)

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-diagnostics/compare/2ec443d7227940345bcedc7a4f352f0f9df031dc..8f6ed832b63d4f2a0b815a96ad8166955eed6fafe)
  - [x] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-cluster-ops/job/dcos-diagnostics/job/dcos-diagnostics-master/39/)
  - [x] Code Coverage (if available): [link to code coverage report](https://codecov.io/gh/dcos/dcos-diagnostics)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by zen-dog** [comment]
Ping @janisz  @orsenthil @gpaul - what do ween need to get a `ship-it` and merge this one? It kind of blocks Marathon when debugging our integration tests.

**Comment by janisz** [comment]
It looks like we need some approvals

**Comment by gpaul** [comment]
@zen-dog one more approval required on this PR

**Comment by zen-dog** [comment]
> one more approval required on this PR

who else has to approve it? the "authorized personnel"?

**Comment by gpaul** [comment]
@zen-dog just you and me is good enough. The PR changed since your last approval, expiring both our approvals, so we each had to approve it once more.

**Comment by janisz** [comment]
@mesosphere-mergebot sync

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@zen-dog @gpaul Pleas reapprove one more time. I need to update branch to get EE tests pass

**Pull request merged**
