### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Aug-10-00-16

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3231 - [Backport 1.11] bump cni plugins version to v0.7.1
* #3233 - [Backport][1.11] locks the glide version to fix build issue 
* #3241 - Update owners.json

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by cprovencher** [comment]
Merge #3241
Merge #3235
Merge #3233
Merge #3231
Merge #3205

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by urbanserj** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
