### PR TITLE
1.10 train 231

### PR DESCRIPTION
**Pull request by orsenthil**
* Bump dcos-ui for 1.10.1 #1982
* Bump dcos-metrics #1981
* Bump to marathon 1.5.1 #1967

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@vespian - failure in adminrouter
```The command '/bin/sh -c set -ex     && curl -fsSL "$OPENRESTY_DOWNLOAD_URL" -o openresty.tar.gz     && echo "$OPENRESTY_DOWNLOAD_SHASUM  openresty.tar.gz" | shasum -c -     && mkdir -pv $OPENRESTY_DIR     && tar --strip-components=1 -C $OPENRESTY_DIR -xzf openresty.tar.gz     && rm openresty.tar.gz' returned a non-zero code: 35
/jenkins/workspace/os-open-adminrouter_PR-1983-GKYAYVYCU4RJ4NQIDXCXQWEHKJRTWFSWN6OEKC4CBIQZMKGZHVZA/packages/adminrouter/extra/src/Makefile.common:78: recipe for target 'update-devkit' failed
```

**Comment by vespian** [comment]
@orsenthil The failure was caused by a problem with `openresty.org`. We may want to start hosting openresty tarball locally.

```
02:21:28 [91m+ curl -fsSL https://openresty.org/download/openresty-1.9.15.1.tar.gz -o openresty.tar.gz
02:21:28 [0m[91mcurl: (35) gnutls_handshake() failed: Internal error
```

**Comment by margaret** [comment]
I reran the adminrouter (jenkins/pr-head) test, works this time.

**Comment by orsenthil** [comment]
@vespian  - for a similar problem (with libsodium) we choose to download from a github mirror. Could we do something like this for openresty too?

**Comment by mellenburg** [comment]
Aggregate failure in the enterprise status checks is due to https://teamcity.mesosphere.io/viewLog.html?buildId=806540&buildTypeId=DcOs_Enterprise_Test_Inte_AwsOnpremWStaticBackendAndSecurityStrict

This is a known and common flake and will not block merge

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
