### PR TITLE
Train 249

### PR DESCRIPTION
**Pull request by lingmann**
## Train 249

* #2070 Jenkinsfile: sec-ci-libs version pinning

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
`continuous-integration/jenkins/pr-head ` is a known failure, and can be overridden as the change needs to be `branch` before it can go green - @vespian  ? 

I am not sure how the `4d93bc1` was green.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by lingmann** [comment]
@mesosphere-mergebot merge-it

**Comment by vespian** [comment]
@orsenthil  Please see below:

> continuous-integration/jenkins/pr-head is a known failure, and can be overridden as the change needs to be branch before it can go green - @vespian ?

correct. Also, see our conversation on slack: https://mesosphere.slack.com/archives/C0L6U3ECQ/p1509639242000259

> I am not sure how the 4d93bc1 was green.

 It was not, even now it is red. It could be that failure was not registered by github/status update was sent by Jenkins after all other CIs succeded. I had such situations with other CIs.

Anyway, I am happy that with this PR merged we can finally close INCIDENT-156. Thanks!

**Comment by orsenthil** [comment]
Thanks for the response, @vespian 👍  :-)

**Pull request merged**
