### PR TITLE
Octarine: Golang 1.7, godep, and parsing changes

### PR DESCRIPTION
**Pull request by nlsun**
Update to golang 1.7 and move parsing from general HTTP handler to just SRV records. Also updated the project to use godep, a golang dependency tracking tool.

### CODE REVIEW

**Comment by nlsun** [comment]
Ready for review.

**Comment by sargun** [comment]
@nlsun We don't use godep, we use govendor, as that's the preferred tool for 1.6+

**Comment by nlsun** [comment]
Well, when I search through large/popular golang projects they all seem to use godep. godep also has vendor support now.

**Comment by sargun** [comment]
We use govendor in Mesos-DNS: https://github.com/mesosphere/mesos-dns/

**Comment by nlsun** [comment]
Looking through large golang projects, they all use godep or roll their own so I'd assume it's more battle tested. Maybe Mesos-DNS should be switched to godep? Also, if this is going into 1.8.5 then perhaps I should remove the commit that switches to golang 1.7 @cmaloney ?

**Comment by cmaloney** [comment]
@nlsun not going into 1.8.5

**Comment by sargun** [comment]
We just switched away from Godep in Mesos-DNS. Do you want to file a bug, and kick off the conversation there?

**Comment by nlsun** [comment]
Is godep blocking this from getting merged?

**Comment by cmaloney** [comment]
There seems to be conflict between you and sargun about whether this is ready / what to do, you two as maintainers need to come to a resolution

**Comment by cmaloney** [comment]
Also, since there was the conflict and this was moved back to WIP, there hasn't been any new "ready for review" to tell me things are all resolved / I should look at it again.

**Comment by nlsun** [comment]
The godep stuff was figured out. Ready for review again.

**Comment by cmaloney** [comment]
to me this looks good, that said holding it off until 1.9 is `master` as we have a lot of things / critical bug fixes only for master which is 1.8.5 bound still.

**Pull request merged**
