### PR TITLE
Bump dcos-ui package for 1.8

### PR DESCRIPTION
**Pull request by rcorral**
## High Level Description

Fixes network type switching in service create form.

## Related Issues

  - https://mesosphere.atlassian.net/browse/DCOS-11559
  - https://mesosphere.atlassian.net/browse/DCOS-13530

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-ui/compare/48a10e1db8540d604a99f5f63b7ce22812cdbd67...73ba1f31093c6df04392656bb40930dad7fb8abb)
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-ui-pulls/6828/
  - [x] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by rcorral** [comment]
Working on fixing this [JIRA](https://mesosphere.atlassian.net/browse/DCOS-13530), I'll make it part of this bump as well

**Comment by rcorral** [comment]
Ready to go!

**Comment by mlunoe** [comment]
Looks good 🚢

**Comment by MatApple** [comment]
approved

**Pull request merged**
