### PR TITLE
Agent Adminrouter + 3DT Proxied 

### PR DESCRIPTION
**Pull request by malnick**

### CODE REVIEW

**Comment by spahl** [comment]
@malnick Still not green:-)

**Comment by malnick** [comment]
Tests need to be updated in conjunction with the new port change.

**Comment by malnick** [comment]
We need to merge https://github.com/dcos/adminrouter/pull/9 and point this back to dcos/adminrouter `master`.

**Comment by malnick** [comment]
@spahl Can we get a ship stamp on this to formally say review is complete?

**Comment by spahl** [comment]
No, when I'm ready to merge it all.

**Comment by spahl** [comment]
@malnick please update to the latest adminrouter

**Comment by malnick** [comment]
@spahl Updated and cleaned up commit history.

**Pull request merged**
