### PR TITLE
CHANGES.md: Remove incorrect iam-database-restore message

### PR DESCRIPTION
**Pull request by mhrabovcin**
## High-level description

Addresses PR feedback - https://github.com/dcos/dcos/pull/3864/files#r238655451

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-45870](https://jira.mesosphere.com/browse/DCOS-45870) Remove note about fixing bug in `iam-database-restore` from DC/OS Open - 1.13

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by mhrabovcin** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mhrabovcin** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
How about "not leave" -> "remove"?

**Comment by mhrabovcin** [comment]
> How about "not leave" -> "remove"?

Noted for future commit messages!

**Comment by mhrabovcin** [comment]
@mesosphere-mergebot label Ship It

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ship It

**Comment by jgehrcke** [comment]
Why did we manually apply the `ship-it` label here w/o discussing the test failure in `teamcity/dcos/test/aws/onprem/static/group3` @mhrabovcin @jongiddy?

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status @mesosphere-teamcity
teamcity/dcos/test/aws/onprem/static/group3 https://jira.mesosphere.com/browse/DCOS-41896

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static/group3 https://jira.mesosphere.com/browse/DCOS-41896

**Comment by jongiddy** [comment]
@jgehrcke Ship It was applied before completion of the tests on the basis that this is a doc change only. However, thanks for dealing with the flakes.

**Pull request merged**
