### PR TITLE
Don't display warrning about removing not existing file on upgrade

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

We do not need to display warring about deleting not existing file – debug will be enough.

Refs: https://github.com/dcos/dcos/pull/6924

## Corresponding DC/OS tickets (required)

  - [COPS-6506](https://jira.d2iq.com/browse/COPS-6506) 

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required internal

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @jongiddy @pierrebeitz  @DominikDary

**Review by jongiddy — APPROVED** [review]

**Comment by janisz** [comment]
@mesosphere-mergebot test all

**Comment by jongiddy** [comment]
All  tests have passed, although some have not notified GitHub

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ship It

**Comment by janisz** [comment]
@mesosphere-mergebot backport 2.1

**Pull request merged**
