### PR TITLE
Added 'max_completed_tasks_per_framework' Mesos flag to 'config.yaml'.

### PR DESCRIPTION
**Pull request by greggomann**
## High Level Description

This PR adds the `--max_completed_tasks_per_framework` Mesos master flag to `config.yaml` so that it can be set by users at install time.

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: This PR adds a new parameter which is currently only accessible via advanced installs, so manual testing is required.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by greggomann** [comment]
@adam-mesos @artemharutyunyan @vinodkone @hatred here's the PR for the `max_completed_tasks_per_framework` flag.

I did an advanced install with the build artifact from this PR, and set `mesos_max_completed_tasks_per_framework: 10` in `config.yaml`. I verified that the flag was set in `/opt/mesosphere/etc/mesos-master`, and verified via the Mesos UI that the # of completed tasks per framework maxes out at 10 in the resulting DC/OS cluster.

I also launched a vanilla CCM cluster and verified that the flag was not set in `/opt/mesosphere/etc/mesos-master`, and that the list of max completed tasks for a framework could grow large.

**Comment by hatred** [comment]
LGTM!

**Comment by jgehrcke** [comment]
`integration-test/azure` and `integration-test/upgrade-onprem` failed. Tracked via https://jira.mesosphere.com/browse/DCOS_OSS-1215 and ttps://jira.mesosphere.com/browse/DCOS_OSS-1065.

**Comment by jgehrcke** [comment]
Is there a DC/OS JIRA ticket that needs to be updated now that this has landed?

**Pull request merged**
