### PR TITLE
[master] Mergebot Automated Train PR - 2019-Jul-24-22-48

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #5922 - Bump to latest Marathon snapshot

### CODE REVIEW

**Comment by orsenthil** [comment]
Hey @urbanserj  / @GoelDeepak  - 

The terraform 0.2.0 has caused unsuitability to the test-suite. Switching back to 0.1.0 seems like a good idea. However, we are now limited by the networking test. (https://jira.mesosphere.com/browse/DCOS-49805) 

I recommend skipping this test until a fix for the terraform 0.1.0 or terraform 0.2.0 is found. This will be stop gap solution until terraform 0.2.0 is stable again.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group3  DCOS-56983

**Comment by urbanserj** [comment]
@orsenthil test_dcos_cni_l4lb should work fine with dcos-terraform 0.1/0.2. if it runs on a buggy kernel, the test will be skipped. The build failed cuz there was an issue with a container image. It's not a networking issue:

```
2019-07-24 23:42:41.207136 +0000 UTC I0724 23:42:41.205564 12315 slave.cpp:6832] Executor 'integration-test_cni-l4lb_client-40426837fbff47afa3a7973728a034c5.instance-b2e69ee8-ae6c-11e9-8500-f20321bf865d._app.1' of framework 4281b86a-0d86-4377-bb15-bae7376e2d6f-0001 exited with status 0
2019-07-24 23:42:41.207442 +0000 UTC I0724 23:42:41.205677 12315 slave.cpp:5726] Handling status update TASK_FAILED (Status UUID: 3d46084d-b4ea-4a6d-9274-e9cf1e26954e) for task integration-test_cni-l4lb_client-40426837fbff47afa3a7973728a034c5.instance-b2e69ee8-ae6c-11e9-8500-f20321bf865d._app.1 of framework 4281b86a-0d86-4377-bb15-bae7376e2d6f-0001 from @0.0.0.0:0
2019-07-24 23:42:41.207705 +0000 UTC E0724 23:42:41.205915 12315 slave.cpp:6091] Failed to update resources for container cba52d24-2f57-47d9-9394-b9fd774762e7 of executor 'integration-test_cni-l4lb_client-40426837fbff47afa3a7973728a034c5.instance-b2e69ee8-ae6c-11e9-8500-f20321bf865d._app.1' running task integration-test_cni-l4lb_client-40426837fbff47afa3a7973728a034c5.instance-b2e69ee8-ae6c-11e9-8500-f20321bf865d._app.1 on status update for terminal task, destroying container: Container not found
```

**Comment by orsenthil** [comment]
@urbanserj  - Okay, even if this is not networking issue. I recommend that we disable that until a resolution is found for this test and terraform installer 0.1.0.

Please notice the target branch failure. (https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackendGroup3TerraformSpotBlock&branch_DcOs_Open_Test_IntegrationTest_TerraformBasedIntegrationTests=%3Cdefault%3E&tab=buildTypeStatusDiv)

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by urbanserj** [comment]
@orsenthil it looks like an issue with our test infrastructure, not like a networking issue. If you disable it, well, it's your responsibility to find the root cause, fix it, and unmute the test. Also, there are no sandboxes in artifacts.

**Comment by orsenthil** [comment]
I agree. I was concerned with the a) Instability of the 0.2.0 provisioner, and b) consistent failure of this test in 0.1.0. I will unmute this test after we find out the reasons for the instability, and take appropriate actions. I don't desire this test to be muted too.

**Comment by orsenthil** [comment]
> Also, there are no sandboxes in artifacts.

This was fixed recently, but we will look.

**Comment by orsenthil** [comment]
@urbanserj - the log collection is fixed here: https://github.com/dcos/dcos/pull/5932 - this will help.

**Pull request merged**
