### PR TITLE
Handle Azure Exception During Copy and Upload.

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

* (DCOS-40442) AzureException during storage upload

### Background.

It is was important to note that problem was not neccessarily due to large file size on Azure platform.

This can be seen on this failure.

```
[15:21:26]Store to azure artifact testing/master/ee.bootstrap.latest by method copy
```

Where ee.bootstrap.latest is not a generate_config.sh that is the largest artifact file.

The failure was in the copy operation, the copy operation was handling only one kind of error `AzureConflictHttpError` and we can simply expand the scope to `AzureException` that was frequently observed.

* More over, instead of retry, we are doing a `abort copy` and copy again. 

(This is same the existing code, but little more stringent).

---- 

Another change was to retry upload 5 times instead of 3

```
-    @retry(stop_max_attempt_number=3)
+    @retry(stop_max_attempt_number=5)
     def upload(self,
```

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
> The failure was in the copy operation, the copy operation was handling only one kind of error AzureConflictHttpError and we can simply expand the scope to AzureException that was frequently observed.

Thank you, Senthil!

**Comment by orsenthil** [comment]
@jgehrcke  - Actually, thanks to @jongiddy  for the tip in the JIRA ticket!

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
