### PR TITLE
Update 1.10 version to 1.10.11-dev.

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

* Update the 1.10 version to 1.10.11-dev

* DCOS-53938 - Set UI versions consistently across all in-development branches

### CODE REVIEW

**Comment by jgehrcke** [comment]
I would like to refer to my comment in https://github.com/dcos/dcos/pull/5496.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@jgehrcke , please take a look again.

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Pull request merged**
