### PR TITLE
Train 184

### PR DESCRIPTION
**Pull request by jgehrcke**
This train includes:
* #1698 ("Bump dcos-diagnostics")
* #1699 ("Admin Router: rebase of https://github.com/dcos/dcos/pull/1628")

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
We are currently ignoring the `integration-test/azure` test outcome, but this looks [so bad](https://teamcity.mesosphere.io/viewLog.html?buildId=697238&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_LaunchAzureResourceMana) that I have created a [JIRA ticket for review](https://jira.mesosphere.com/browse/DCOS_OSS-1359).

**Comment by jgehrcke** [comment]
Tests that failed in https://teamcity.mesosphere.io/viewLog.html?buildId=697234:
```
test_networking.test_vip[Container_DOCKER-Network_USER-Network_BRIDGE] 	
test_networking.test_l4lb_teardown 
```

https://teamcity.mesosphere.io/viewLog.html?buildId=697240:
```
test_networking.test_vip[Container_DOCKER-Network_USER-Network_USER] 	
 test_networking.test_l4lb_teardown 
```

Re-running both of them. CC @asridharan @cdaw

**Comment by adamtheturtle** [comment]
@jgehrcke Any reason to not include https://github.com/dcos/dcos/pull/1693 ?

**Comment by adamtheturtle** [comment]
Assuming tests pass, this train looks like it includes the entirety of two Ship It'd PRs and therefore it gets my approval.

**Comment by jgehrcke** [comment]
> @jgehrcke Any reason to not include #1693 ?

Yes, that is for the 1.9.1 branch :).

**Comment by adamtheturtle** [comment]
@jgehrcke Ah, my mistake.

**Comment by lingmann** [comment]
Looks good, thanks everyone! 🚢

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
