### PR TITLE
update dcos-ansible container to latest stable Windows GA with ugrade ready

### PR DESCRIPTION
**Pull request by sergiimatusEPAM**
## High-level description
Updating dcos-ansible container at terraform main.tf for integration tests to latest stable Windows GA, where Upgrade functionality is ready and tested. 

Docker tag "windows" associated with latest commit in feature/windows branch of Ansible (https://github.com/dcos/dcos-ansible/tree/feature/windows)

## Corresponding DC/OS tickets (required)

  - [D2IQ-65864](https://jira.d2iq.com/browse/D2IQ-65864) dcos_install.yml has no attribute 'ansible_dcos_installation' - undefined variable error

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot changelog-not-required Windows GA minor fix

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request-review  @janisz

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request-review @jeschkies

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request-review  @DominikDary

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @fatz

**Comment by DominikDary** [comment]
we should wait with this until the bug is fixed i reported to @fatz and @sergiimatusEPAM is merged

**Comment by sergiimatusEPAM** [comment]
> we should wait with this until the bug is fixed i reported to @fatz and @sergiimatusEPAM is merged:
> https://teamcity.mesosphere.io/viewLog.html?buildId=2664326&buildTypeId=DcOs_Open_Test_IntegrationTest_WindowsIntegrationTEsts&tab=buildLog&_focus=2864#_state=2893,315,457

Just tested the fixed container so it can be safely use. 
Jan agreed to use ":windows" tag over hashed one, as the branch has been stabilized and Ansible CI is pretty stable. Integration tests will be able to catch an error , if even smth goes wrong.

**Comment by sergiimatusEPAM** [comment]
@DominikDary , @janisz , please re-approve

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by DominikDary** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
Fixed in https://github.com/dcos/dcos/pull/7087

**Pull request closed without merging**
