### PR TITLE
Bump to the latest marathon 1.5

### PR DESCRIPTION
**Pull request by kensipe**
## High Level Description

What features does this change enable? What bugs does this change fix? High-Level description of how things changed.

## Related Issues

  - [DCOS_OSS-17336](https://jira.mesosphere.com/browse/DCOS-17336) Bump to latest Marathon 1.5

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results:  https://jenkins.mesosphere.com/service/jenkins/buildStatus/icon?job=marathon-pipelines/master
  - [x] Code Coverage (if available): https://jenkins.mesosphere.com/service/jenkins/buildStatus/icon?job=marathon-pipelines/master

___

### CODE REVIEW

**Comment by jgehrcke** [comment]
```
[21:00:59][Building package marathon variant <default>] Downloading source tarball https://s3.amazonaws.com/marathon/snapshots/marathon-1.5.0-SNAPSHOT-661-g097378f.tgz
[21:01:00][Building package marathon variant <default>] Traceback (most recent call last):
[21:01:00][Building package marathon variant <default>]   File "/teamcity/work/19ad0dff41587ee6/build/env/lib/python3.5/site-packages/pkgpanda/util.py", line 87, in download
[21:01:00][Building package marathon variant <default>]     raise Exception("got a 301")
[21:01:00][Building package marathon variant <default>] Exception: got a 301
```

**Comment by jgehrcke** [comment]
@orsenthil if you have a little time for that I'd love to understand why `mergebot/enterprise/build-status/aggregate` does not report back here. Not sure where to start looking.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Train 193 landed, we can close this.

**Comment by orsenthil** [comment]
@jgehrcke   Since the PR is closed, we could see the status checks on it.

Essentially, any EE upstream.json that is being exercised should have a SHA of this PR. EE tests will forward the status back to this PR.  Do you remember if that was the case and it still missed?
I see Other PR reporting EE status properly: https://github.com/dcos/dcos/pull/1746

**Comment by orsenthil** [comment]
@jgehrcke - there is no corresponding enterprise PR for this open PR, and  so the EE PR status did not go green.

**Pull request closed without merging**
