### PR TITLE
Remove unneeded `test_min_allocatable_resources`

### PR DESCRIPTION
**Pull request by bbannier**
This test was introduced to test the correct behavior of a custom
setting for Mesos' `min_allocatable_resources` flag. We have since
removed this custom flag setting which both caused this test to fail
while also removing any need for this test, so we are removing the test
in this patch.

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by bbannier** [comment]
@mesosphere-mergebot bump-ee

**Comment by jdef** [comment]
@bbannier I still see a custom value for this flag:
https://github.com/dcos/dcos/blob/113b8abacfd6d517594f329b621aaf4641b535e7/gen/dcos-config.yaml#L1310

**Comment by bbannier** [comment]
@jdef, there is no special `disk` setting anymore that the test tested for.

**Comment by jdef** [comment]
OK, so to clarify, this test case was trying to test a change to the value of `min_allocatable_resources` - and that change has since been reverted, obviating the need for this test.

https://github.com/dcos/dcos/commit/08ffd4a102f4784607f5b65296e4f2c8b9cb54a9

**Comment by orsenthil** [comment]
Hi @bbannier  - Please backport this PR to other applicable versions of DC/OS too. TIA!

**Comment by bbannier** [comment]
@orsenthil, I created #5590 to backport both the flag update and the test removal.

**Pull request merged**
