### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Sep-12-10-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3414 - [1.10] Backported detailed resource logging for some allocator errors in Mesos.
* #3419 - Replaced poll_marathon_for_app_deployment method for test_packaging_api.

### CODE REVIEW

**Comment by pcrews** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-1258

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot merge-it

**Comment by cprovencher** [comment]
@mesosphere-mergebot ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status mergebot/enterprise/has_ship-it https://jira.mesosphere.com/browse/DCOS-39073

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
