### PR TITLE
Disable NTLM proxy auth for cosmos

### PR DESCRIPTION
**Pull request by cruhland**
## High Level Description

We don't support cosmos using proxies with NTLM authentication at this time. This change will allow Cosmos to use a different authentication scheme, such as Basic, instead of NTLM.

EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1008

## Related Issues

  - [DCOS-15096](https://jira.mesosphere.com/browse/DCOS-15096) Unable to access Universe on a cluster configured with proxy using basic auth

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: We plan to comprehensively test cosmos' treatment of proxies in [DCOS_OSS-1113](https://jira.mesosphere.com/browse/DCOS_OSS-1113).
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by cruhland** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by cruhland** [comment]
@jsancio @jgehrcke please review!

**Comment by jsancio** [comment]
@spahl Can we include this in the next train?

**Comment by orsenthil** [comment]
@jsancio  please review this. We need additional reviewer. I cannot make a call for the cosmos change.

**Comment by jsancio** [comment]
I did. https://github.com/dcos/dcos/pull/1632#pullrequestreview-42481222

Is there anything else you want me to do?

**Comment by orsenthil** [comment]
I thought, i wanted to send a note to @larioj  
Yeah, 2 reviewers for the PR.

**Comment by jsancio** [comment]
He is on vacation.

**Comment by orsenthil** [comment]
I read the bug report and verified the fix ( by checking the flag for jdk).

The changes look good to me.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
