### PR TITLE
[1.13] packages/cockroach: use golang 1.10.8 for build

### PR DESCRIPTION
**Pull request by mhrabovcin**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by DominikDary** [comment]
Windows  Build is failing:

> [16:18:22][Building packages] Failure building package(s): package python is supposed to have variant windows included in the tree according to the treeinfo, but variant <default> was found.

@cgawron1 @orsenthil:  Due to the fact that 1.13 is not supposed to have a windows build, how should we proceed? This change has touched only linux code path.

**Comment by orsenthil** [comment]
@DominikDary  : This is not a required test. The windows team can either investigate or ignore it?
We cannot selective trigger PRs based on head branch of master of 1.13 (or 1.9) etc. All PRs essentially see the same test suites, except that some tests are marked as "required" for branch specific merges. HTH.

**Comment by mhrabovcin** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mhrabovcin** [comment]
@mesosphere-mergebot request-review @DominikDary @jongiddy @timaa2k

**Comment by jongiddy** [comment]
For the record, this PR is associated with https://jira.mesosphere.com/browse/DCOS-61502

**Pull request merged**
