### PR TITLE
[master] Mergebot Automated Train PR - 2018-Oct-22-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3393 - Alignment of authentication architectures: start to adjust Admin Router (iteration 1)
* #3567 - Do not pull overlay data when overlay is disable
* #3592 - Add mesos metrics to telegraf
* #3605 - Decrease Telegraf poll frequency
* #3623 - Update dcos-diagnostics
* #3633 - Bump dcos-net
* #3655 - Update owners.json

### CODE REVIEW

**Comment by jgehrcke** [comment]
I restarted the `teamcity/dcos/build/tox` job. It failed before as of the current GitHub instabilities.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jgehrcke** [comment]
@mesosphere-mergebot sync

**Comment by urbanserj** [comment]
@mesosphere-mergebot sync

**Comment by urbanserj** [comment]
@mesosphere-mergebot sync

**Pull request merged**
