### PR TITLE
Add dcos-net overlay metrics

### PR DESCRIPTION
**Pull request by ichernetsky**
## High-level description

Expose overlay networking metrics from `dcos-net`.

## Corresponding DC/OS tickets

  - [DCOS_OSS-5324](https://jira.mesosphere.com/browse/DCOS_OSS-5324) Expose metrics from dcos-overlay

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/dcos/dcos-net/compare/db3b8f3991896e382c587ea418c0429372d4b7ca...dbce08db228d1f3fc59874b81558d11f7593dc1e)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [x] Test Results: [CI job](https://circleci.com/gh/dcos/dcos-net/1278)
  - [x] Code Coverage (if available): [report](https://codecov.io/gh/dcos/dcos-net/pull/161)

### CODE REVIEW

**Comment by ichernetsky** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by urbanserj** [comment]
dcos-net PRs:
https://github.com/dcos/dcos-net/pull/161
https://github.com/dcos/dcos-net/pull/162

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot sync

**Comment by ichernetsky** [comment]
@mesosphere-mergebot sync

**Pull request merged**
