### PR TITLE
[master] Train 232

### PR DESCRIPTION
**Pull request by sschneid**
#1989 extend function calculate_fault_domain_enabled

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
:ship: once the upgrade to enterprise test passes as it should be functional on master

**Comment by mellenburg** [comment]
Wow, concerning upgrade test failure there ...https://teamcity.mesosphere.io/viewLog.html?buildId=807072&buildTypeId=DcOs_Open_Test_UpgradeTest_FromStable&tab=buildLog&_focus=1308#_state=1308

**Comment by lingmann** [comment]
@sschneid you can go ahead and close out the PR's for train 232

**Pull request closed without merging**
