### PR TITLE
Train 301 (1.10)

### PR DESCRIPTION
**Pull request by falseperfection**
#2264 -bootstrap: Fix small logging bug

### CODE REVIEW

**Comment by falseperfection** [comment]
@mesosphere-mergebot bump-ee

**Comment by falseperfection** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1902

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker https://jira.mesosphere.com/browse/DCOS_OSS-1902

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
