### PR TITLE
Bump Mesos to 4faca73e9608664a5fcf46cc95951c318a64861f.

### PR DESCRIPTION
**Pull request by karya0**
## High Level Description

This change contains file-based secrets and image pull secrets. 

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
    This PR relies upon Mesos test suite.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Mesos diff](https://github.com/mesosphere/mesos/compare/5724bfbf390502c79d7f53d6c9bb0ce92e6d9454...9cc627d9f32d56f14f277e823a759183ef4b234d)
  - [x] Test Results: [ASF CI Results](https://builds.apache.org/job/Mesos-Buildbot/3720/)
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by karya0** [comment]
@mesosphere-mergebot bump-ee

**Comment by karya0** [comment]
@adam-mesos : here is a bump with file-based secrets and image pull secrets.

**Comment by karya0** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by karya0** [comment]
@mesosphere-mergebot bump-ee

**Comment by karya0** [comment]
@mesosphere-mergebot bump-ee

**Comment by karya0** [comment]
@mesosphere-mergebot bump-ee

**Comment by karya0** [comment]
@vinodkone @greggomann @Gilbert88: Could you review this please?

**Comment by vinodkone** [comment]
LGTM

**Comment by karya0** [comment]
Closed in lieu of https://github.com/dcos/dcos/pull/1612

**Pull request closed without merging**
