### PR TITLE
gen: Generate config packages with new IDs after editing files under genconf/

### PR DESCRIPTION
**Pull request by branden**
## High-level description

This PR fixes genconf to allow changing config values that are provided as files under `genconf/` as part of an upgrade. Without this PR, editing `genconf/detect_ip` and re-running genconf will create a new config package with an updated IP detect script, but with the same ID as the prior config package. Because the ID hasn't changed, Pkgpanda will assume it has the same contents as the config package currently present on cluster nodes, and reuse it instead of downloading the updated package. With this PR, the new config package will have a different ID, causing Pkgpanda to recognize that it is different and use it.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-2389](https://jira.mesosphere.com/browse/DCOS_OSS-2389) Upgrades Fails to Update the agents ip-detect script

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by branden** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple DCOS_OSS-2310

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple DCOS_OSS-2310

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple DCOS_OSS-2310

**Pull request merged**
