### PR TITLE
Grab latest fix to package describe and install

### PR DESCRIPTION
**Pull request by jsancio**
High level description including:
 - What does this change enable
 - What bugs does this change fix
 - High-Level how things changed

# Issues

[DCOS-12411](https://mesosphere.atlassian.net/browse/DCOS-12411)

# Checklist

 - [x] Included a test which will fail if code is reverted but test is not:
  1. https://github.com/dcos/cosmos/commit/da39604cdacbc4f79c84f397ec7fc0d14b83c47c#diff-c51a7c12e1cf4f27093f6f1caf7b54b4
  1. https://teamcity.mesosphere.io/viewQueued.html?itemId=520272
 - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

If this is a component/package update, include

- [x] Change Log from last:
 -  Return postInstallNotes instead of uninstall notes ([#560](https://github.com/dcos/cosmos/pull/560)) 
 - Make sure that we set None to false for selected and framework ([#559](https://github.com/dcos/cosmos/pull/559))
 - Add ServiceAlreadyStarted error ([#557](https://github.com/dcos/cosmos/pull/557))
 - Fix package ordering ([#558](https://github.com/dcos/cosmos/pull/558))
 - Remove appId field from ServiceStartRequest ([#555](https://github.com/dcos/cosmos/pull/555))
 - Integration tests for /service/start ([#552](https://github.com/dcos/cosmos/pull/552))
- [x] Test Results: Cosmos integration tests pass.
- [ ] Code Coverage:

### CODE REVIEW

**Comment by jsancio** [comment]
@lingmann Can we add this to the next train?

**Comment by lingmann** [comment]
@jsancio can you suggest two people to do a review of this and ping them on the PR?

**Comment by lingmann** [comment]
Also @jsancio please update the template summary section.

**Comment by lingmann** [comment]
NM I see the summary details now.

**Comment by jsancio** [comment]
@cruhland, @spahl, @adam-mesos, @tamarrow can two of you review this?

**Comment by adam-mesos** [comment]
SHA is correct, but the PR links in the description point to dcos/dcos PRs, not cosmos PRs.
Should be:
https://github.com/dcos/cosmos/pull/558
https://github.com/dcos/cosmos/pull/555
https://github.com/dcos/cosmos/pull/552

**Comment by tamarrow** [comment]
Looks like buildinfo.json is correct from: https://teamcity.mesosphere.io/repository/download/DcosIo_Cosmos_PublishSnapshot/518527:id/buildinfo.json

@jsancio why are we publishing a snapshot instead of doing a cosmos release?

**Comment by jsancio** [comment]
Good catch Adam. Fixed the description. GitHub replaces #number with link to PRs/Issues in this repo.

**Comment by jsancio** [comment]
@tamarrow We are publishing snapshot build while we are fixing bugs or in EA. We are going to create a release build before we release.

**Comment by lingmann** [comment]
@jsancio waiting on another review and the `integration-test/vagrant-bash` failure needs to be investigated or re-run if the test is flaky.

**Comment by jsancio** [comment]
@darkonie Can you approve this one too? It is the same Cosmos.

**Comment by darkonie** [comment]
@jsancio done

**Pull request merged**
