### PR TITLE
Update centos AMIs to version 7.4

### PR DESCRIPTION
**Pull request by margaret**
## High Level Description

Doing this via changing the build scripts in the cloud_images dcos package to read in environment variable for `CENTOS_VERSION`.

- Defaults to 7.3.1611 (initial hard-coded value) in scripts, but I set it to 7.4 in TeamCity.

Manually-kicked-off CI job that created the DC/OS-ready AMIs:
https://teamcity.mesosphere.io/repository/download/DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImage/798303:id/cloud_images/centos7/artifacts.txt

GovCloud DC/OS-ready AMIs generated with https://teamcity.mesosphere.io/viewLog.html?buildId=816581&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImagesForGovcloud

Details of testing are in the comments below, but the images were tested manually by bringing up different types of clusters and then running the integration tests.

## Related Issues

This is in support of
 - https://jira.mesosphere.com/browse/DCOS_OSS-1646
Generating images that will be added to dcos-launch configuration.

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by margaret** [comment]
I have tried using `dcos-launch` to create a cluster based on the template
```
---
launch_config_version: 1
deployment_name: msy-20170927-test-centos-dcos-prereqs-1
platform: aws
provider: onprem
aws_region: us-west-2
installer_url: https://downloads.dcos.io/dcos/testing/pull/1961/dcos_generate_config.sh
key_helper: true
num_masters: 1
num_private_agents: 2
num_public_agents: 1
os_name: cent-os-7-dcos-prereqs
instance_type: m4.xlarge
dcos_config:
  cluster_name: The Best DC/OS
  master_discovery: static
  exhibitor_storage_backend: zookeeper
  exhibitor_zk_path: /exhibitor
  resolvers:
    - 8.8.8.8
    - 8.8.4.4
```
trying each of `cent-os-7-dcos-prereqs` and `cent-os-7`

the plain centos one errors out with 
```
(env) 15:51:53 margaretsy ~/mesosphere/dcos-launch:$ dcos-launch create -c aws-onprem-test.yaml
[2017-09-27 15:51:55,845|dcos_launch.platforms.aws|INFO]: Creating KeyPair: msy-20170927-test-centos-1
[2017-09-27 15:51:57,170|dcos_launch.platforms.aws|INFO]: Requesting AWS CloudFormation: msy-20170927-test-centos-1
(env) 15:51:59 margaretsy ~/mesosphere/dcos-launch:$ dcos-launch wait
[2017-09-27 15:52:49,137|dcos_launch.onprem|INFO]: Waiting for bare cluster provisioning status..
[2017-09-27 15:52:50,582|dcos_launch.platforms.aws|WARNING]: No recognized resources found; using generic stack
[2017-09-27 15:52:50,589|dcos_launch.platforms.aws|INFO]: Waiting for stack operation to complete
[2017-09-27 15:52:51,804|dcos_launch.platforms.aws|INFO]: Continuing to wait...
[2017-09-27 15:53:53,759|dcos_launch.platforms.aws|INFO]: Continuing to wait...
[2017-09-27 15:54:55,227|dcos_launch.platforms.aws|INFO]: Continuing to wait...
[2017-09-27 15:56:00,843|dcos_launch.onprem|INFO]: Waiting for SSH connectivity to cluster host...
ssh: connect to host 35.165.38.205 port 22: Operation timed out
ssh: connect to host 35.165.38.205 port 22: Operation timed out
ssh: connect to host 35.165.38.205 port 22: Operation timed out
ssh: connect to host 35.165.38.205 port 22: Operation timed out
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
ssh: connect to host 35.165.38.205 port 22: Connection refused
Exit request sent.
Exit request sent.
Exit request sent.
Exit request sent.
Exit request sent.
[2017-09-27 15:57:44,549|dcos_launch.onprem|INFO]: No installation state file detected; beginning fresh install...
[2017-09-27 15:57:44,550|dcos_test_utils.onprem|INFO]: Setting up installer on bootstrap host
usermod: group 'docker' does not exist
Traceback (most recent call last):
  File "/Users/margaretsy/mesosphere/dcos-launch/env/bin/dcos-launch", line 9, in <module>
    load_entry_point('dcos-launch==0.1', 'console_scripts', 'dcos-launch')()
  File "/Users/margaretsy/mesosphere/dcos-launch/dcos_launch/cli.py", line 125, in main
    return do_main(args)
  File "/Users/margaretsy/mesosphere/dcos-launch/dcos_launch/cli.py", line 91, in do_main
    launcher.wait()
  File "/Users/margaretsy/mesosphere/dcos-launch/dcos_launch/onprem.py", line 116, in wait
    cluster.setup_installer_server(self.config['installer_url'], False)
  File "/Users/margaretsy/mesosphere/dcos-launch/env/lib/python3.5/site-packages/dcos_test_utils/onprem.py", line 130, in setup_installer_server
    self.ssh_client, self.bootstrap_host.public_ip, installer_url, offline_mode)
  File "/Users/margaretsy/mesosphere/dcos-launch/env/lib/python3.5/site-packages/dcos_test_utils/onprem.py", line 168, in api_session_from_host
    ssh_client.add_ssh_user_to_docker_users(host)
  File "/Users/margaretsy/mesosphere/dcos-launch/env/lib/python3.5/site-packages/dcos_test_utils/ssh_client.py", line 138, in add_ssh_user_to_docker_users
    self.command(host, ['sudo', 'usermod', '-aG', 'docker', self.user], port=port)
  File "/Users/margaretsy/mesosphere/dcos-launch/env/lib/python3.5/site-packages/dcos_test_utils/ssh_client.py", line 124, in command
    return t.command(cmd, **kwargs)
  File "/Users/margaretsy/mesosphere/dcos-launch/env/lib/python3.5/site-packages/dcos_test_utils/ssh_client.py", line 39, in command
    return check_output(run_cmd, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/ssh', '-oConnectTimeout=10', '-oControlMaster=auto', '-oControlPath=/var/folders/fr/j7h7hd617jjfp3mc3qyk7nrw0000gp/T/tmp8_8flg7k/control_socket', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oLogLevel=ERROR', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p', '22', 'centos@34.215.6.159', 'sudo', 'usermod', '-aG', 'docker', 'centos']' returned non-zero exit status 6
```

and with-prereqs ends up as 
```
(env) 16:00:10 margaretsy ~/mesosphere/dcos-launch:$ dcos-launch create -c aws-onprem-test.yaml
[2017-09-27 16:00:25,516|dcos_launch.platforms.aws|INFO]: Creating KeyPair: msy-20170927-test-centos-dcos-prereqs-1
[2017-09-27 16:00:25,974|dcos_launch.platforms.aws|INFO]: Requesting AWS CloudFormation: msy-20170927-test-centos-dcos-prereqs-1
(env) 16:00:27 margaretsy ~/mesosphere/dcos-launch:$ dcos-launch wait
[2017-09-27 16:00:36,429|dcos_launch.onprem|INFO]: Waiting for bare cluster provisioning status..
[2017-09-27 16:00:36,750|dcos_launch.platforms.aws|WARNING]: No recognized resources found; using generic stack
[2017-09-27 16:00:36,757|dcos_launch.platforms.aws|INFO]: Waiting for stack operation to complete
[2017-09-27 16:00:37,116|dcos_launch.platforms.aws|INFO]: Continuing to wait...
[2017-09-27 16:01:37,419|dcos_launch.platforms.aws|INFO]: Continuing to wait...
[2017-09-27 16:02:37,704|dcos_launch.platforms.aws|INFO]: Continuing to wait...
[2017-09-27 16:03:37,957|dcos_launch.platforms.aws|INFO]: Continuing to wait...
[2017-09-27 16:04:40,519|dcos_launch.onprem|INFO]: Waiting for SSH connectivity to cluster host...
Received disconnect from 34.211.92.232 port 22:2: Too many authentication failures
Authentication failed.
Received disconnect from 34.211.92.232 port 22:2: Too many authentication failures
Authentication failed.
Received disconnect from 34.211.92.232 port 22:2: Too many authentication failures
Authentication failed.
Received disconnect from 34.211.92.232 port 22:2: Too many authentication failures
Authentication failed.
Received disconnect from 34.211.92.232 port 22:2: Too many authentication failures
Authentication failed.
Received disconnect from 34.211.92.232 port 22:2: Too many authentication failures
Authentication failed.
```

**Comment by margaret** [comment]
(And the above was done on a branch of dcos-launch that had the centos amis in aws.py set to point at the 7.4 images. Will link when not on mobile)

**Comment by margaret** [comment]
rebased again

**Comment by margaret** [comment]
Tested this by running dcos-launch with this config file
```
---
launch_config_version: 1
deployment_name: msy-20171010-test-centos-dcos-prereqs-1
platform: aws
provider: onprem
aws_region: us-west-2
installer_url: https://downloads.dcos.io/dcos/testing/pull/1961/dcos_generate_config.sh
key_helper: true
num_masters: 1
num_private_agents: 2
num_public_agents: 1
os_name: cent-os-7-dcos-prereqs
instance_type: m4.xlarge
dcos_config:
  cluster_name: The Best DC/OS
  master_discovery: static
  exhibitor_storage_backend: zookeeper
  exhibitor_zk_path: /exhibitor
  resolvers:
    - 8.8.8.8
    - 8.8.4.4
  ip_detect_filename: ../ip-detect/aws.sh
```

dcos-launch was not able to authenticate with the cluster due to my ssh config not being compatible with it, but I could manually ssh into the bootstrap node and then download the installer for this PR and install with the config.yaml as per https://dcos.io/docs/1.10/installing/custom/cli/

```
---
agent_list:
    - 10.10.0.59
    - 10.10.0.74
bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: The Best DC/OS
exhibitor_storage_backend: zookeeper
exhibitor_zk_hosts: <bootstrap host ip>:22
master_discovery: static
master_list:
    - 10.10.0.237
public_agent_list:
    - 10.10.0.96
resolvers:
    - 8.8.4.4
    - 8.8.8.8
ssh_port: 22
ssh_user: centos
```
The UI worked and I was able to run the pytests on the master node and 109 tests passed, 7 skipped, and none failed.

Also need to test this on the AMIs that don't have the prereqs installed (I skipped the `sudo bash dcos_generate_config.sh --install-prereqs` here since it was for the AMIs with prereqs), and on the enterprise PR after fixing that linting error.

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
✅ dcos installs and integration tests run successfully on all three security modes

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
I am able to create clusters from the govcloud cloudformation templates, and log into the dashboards. I'm currently having issues ssh-ing into them.

**Comment by margaret** [comment]
@mesosphere-mergebot label ready for review

**Comment by karlkfi** [comment]
This PR is blocking https://github.com/dcos/dcos/pull/2015 which enhances the prereqs installer.
Need to use the newer CentOS >= 7.3 installer in order to get XFS `ftype=1` in the `teamcity/dcos/test/aws/onprem/static` tests.

**Comment by margaret** [comment]
Testing GovCloud images with the https://downloads.dcos.io/dcos/testing/pull/1961/cloudformation/el7-zen-1.json and related (public, private, master, infra) config files, but I have to host them in the us-gov-west-1 region because govcloud's cloudformation can't access the us-west-2 hosted files.

OSS: integration tests pass, but test_vip and test_pkgpanda_api failed.

Tests for EE (strict, permissive, disabled) on govcloud are in progress.

**Comment by margaret** [comment]
Testing GovCloud images with the https://downloads.dcos.io/dcos/testing/pull/1961/cloudformation/el7-zen-1.json and related (public, private, master, infra) config files, but I have to host them in the us-gov-west-1 region because govcloud's cloudformation can't access the us-west-2 hosted files. Also bringing up a cluster seems to work on dcos-launch 👍 

OSS: integration tests pass, but test_vip and test_pkgpanda_api failed.

Tests for EE (strict, permissive, disabled) on govcloud are in progress.

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
azure test_vip failed, but something also failed with ssh after the test suite was run 
https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=822907&_focus=1948
```
[19:31:11][2017-10-18 19:31:11,783|dcos_launch.util|INFO]: Running integration test...
[19:31:13]Exit request sent.
[20:21:15][2017-10-18 20:21:15,256|dcos_launch.util|ERROR]: Test run failed!
[20:21:15]Traceback (most recent call last):
[20:21:15]  File "dcos_launch/util.py", line 143, in try_to_output_unbuffered
[20:21:15]  File "site-packages/dcos_test_utils/ssh_client.py", line 124, in command
[20:21:15]  File "site-packages/dcos_test_utils/ssh_client.py", line 37, in command
[20:21:15]  File "subprocess.py", line 581, in check_call
[20:21:15]subprocess.CalledProcessError: Command '['/usr/bin/ssh', '-oConnectTimeout=10', '-oControlMaster=auto', '-oControlPath=/teamcity/temp/buildTmp/tmpea0yojgd/control_socket', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oLogLevel=ERROR', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p', '2200', 'dcos@dcos6tpl8ts9mzmaster.eastus2.cloudapp.azure.com', 'bash', '-c', ' "source /opt/mesosphere/environment.export &&\ncd `find /opt/mesosphere/active/ -name dcos-integration-test* | sort | tail -n 1` &&\nDNS_SEARCH=false DCOS_PROVIDER=azure DCOS_DNS_ADDRESS=http://172.16.0.5 PUBLIC_SLAVE_HOSTS=10.0.0.5 TEAMCITY_VERSION=\'2017.1.4 (build 47070)\' MASTER_HOSTS=172.16.0.5 PUBLIC_MASTER_HOSTS=172.16.0.5 SLAVE_HOSTS=10.32.0.5,10.32.0.7 py.test --teamcity -vv -rs" ']' returned non-zero exit status 1
[20:21:15]Process exited with code 1
```

**Comment by margaret** [comment]
@lingmann @sschneid Can you review? Thanks

**Comment by jgehrcke** [comment]
@margaret can you comment on the `mergebot/enterprise/build-status/aggregate` failure?

**Comment by margaret** [comment]
@jgehrcke https://github.com/mesosphere/dcos-enterprise/pull/1544#issuecomment-337982394 Comments are on the enterprise PR. That is a bug from the new mesos API tests in strict mode, which is currently being fixed

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Hi @margaret  - If you update this branch and bump-ee again, you would pick up the changes for `tox` and we will get a `green` build.

**Comment by orsenthil** [comment]
Also, when doing, just squash the commits.

**Comment by margaret** [comment]
I messed up the rebase, but the squashed changes are cherry-picked to this PR https://github.com/dcos/dcos/pull/2040

**Pull request closed without merging**
