### PR TITLE
D2IQ-65520: added missing AppRotate* params of NSSM while Winpanda setup

### PR DESCRIPTION
**Pull request by sergiimatusEPAM**
## High-level description

When the user tries to configure any Windows service with help of NSSM extra parameter - e.q. setting APPROTATEFILES = 1, the nssm.py skips adding the attribute because validation doesn't pass. The validation consist of matching user's specified param vs pre-defined allowed list of optional/required params in NSSMParameter class of nssm.py.

Therefore the solution is to add all available params listed in http://nssm.cc for ver. >2.22 to existing 
NSSMParameter optional list.

## Corresponding DC/OS tickets (required)

  - [D2IQ-65520](https://jira.d2iq.com/browse/D2IQ-65520) Add log rotation for all of DCOS components via NSSM.

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot changelog-not-required Windows GA minor bugfix

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request-review @vadymzagorodko

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request-review @jongiddy

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required Windows GA minor bugfix

**Comment by janisz** [comment]
Was it tested? It looks like this PR breaks [Windows CI](https://teamcity.mesosphere.io/viewLog.html?buildId=2649245&buildTypeId=DcOs_Open_Test_IntegrationTest_WindowsIntegrationTEsts&tab=buildLog)

```log
[06:44:53][Step 2/3] test_auth.test_logout (2h:07m:49s)
[08:52:42][Step 2/3] The build Integration test::Windows Integration Tests #178 {buildId=2649245} has been running for more than 150 minutes. Terminating...
[08:52:42][Step 2/3] Execution timeout
```

I prepared revert of this change: https://github.com/dcos/dcos/pull/7052

**Comment by sergiimatusEPAM** [comment]
@vadymzagorodko performed tests on the DC/OS cluster.
Why do you think the fix is causing issue? ( I am unable to find evidence)

**Comment by janisz** [comment]
I looked at the all builds in #7035 and in all other PRs test were able to run (some of them failed – this is fine) and only in this PR [test timed out](https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2649245&_focus=2978). Let's see if revert PR pass tests. If not we should search for another change – maybe it's in ansible?

**Pull request merged**
