### PR TITLE
[master] Mergebot Automated Train PR - 2018-Sep-14-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3384 - Allow configuring dcos-diagnostics bundles dir
* #3397 - Pass origin info to custom managers in cosmos 
* #3428 - exhibitor package: bump ZooKeeper to 3.4.13 release
* #3429 - Grant more folks owners karma.
* #3432 - Ensure that statsd socket is cleaned up before launching telegraf

### CODE REVIEW

**Comment by gpaul** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by pcrews** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41751

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41751

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS_OSS-4073

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
> @mesosphere-mergebot label ship it

You already got one :)

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
