### PR TITLE
Don't offer port 53 on agent nodes to frameworks.

### PR DESCRIPTION
**Pull request by lava**
This port is required for `dcos-net`, and a framework
attempting to make use of it will fail with an error.

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4184](https://jira.mesosphere.com/browse/DCOS_OSS-4148) Mesos offers ports that are already in use.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:

    - Frameworks not using the DNS port won't see any difference.
    - Frameworks using the DNS port couldn't have successfully run on DC/OS before, due to dcos-net using this port.

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:

    No test since this is purely a preventive change, as explained above

  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by lava** [comment]
@mesosphere-mergebot bump-ee

**Comment by lava** [comment]
@mesosphere-mergebot bump-ee

**Comment by lava** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-39971
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41677
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41676

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-39971

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41677

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41676

**Comment by rukletsov** [comment]
@lava I have two high-level questions when I look at this PR:
1) Why does `docs-net` use a port from the first hundred range?
2) What about other dcos components that likely use specific ports as well? Shouldn't we allocate a range of reserved ports in DC/OS for them instead of punching holes one by one?

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-39971

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-41679

**Comment by lava** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by lava** [comment]
> @lava I have two high-level questions when I look at this PR:
> 
>     1. Why does `docs-net` use a port from the first hundred range?
> 
>     2. What about other dcos components that likely use specific ports as well? Shouldn't we allocate a range of reserved ports in DC/OS for them instead of punching holes one by one?

1) `dcos-net` uses the DNS port because it provides a DNS resolution service
2) You can look at https://jira.mesosphere.com/browse/DCOS_OSS-4184 for more context. I looked at the documentation linked there and determined that right now, only port 53 is problematic

**Comment by lava** [comment]
@mesosphere-mergebot label Holding

**Comment by orsenthil** [comment]
@mesosphere-mergebot label holding

**Pull request closed without merging**
