### PR TITLE
Default calico network CIDR

### PR DESCRIPTION
**Pull request by wavesoft**
## High-level description

_Imported and rebased https://github.com/dcos/dcos/pull/6633_

This PR set the `calico_network_cidr` default to be `172.29.0.0/16`. Overlapped subnets of calico and infrastructure may bring unrecoverable/tremendous problems into the infrastructure especially for an on-premise environment.

This PR is blocked by the task described in [DCOS-62550](https://jira.mesosphere.com/browse/DCOS-62550), which make calico configurations configurable through terraform.
Also, before we can turn all tests into green, we need to first `addcalico_network_cidr` into main.tf defined in teamcity project.

## Corresponding DC/OS tickets (required)

- [DCOS-60734](https://jira.d2iq.com/browse/D2IQ-60734) make calico-network-cidr mandatory to set by the operator

## Related tickets (optional)

This PR is currently blocked my this task

- [D2IQ-64346](https://jira.d2iq.com/browse/D2IQ-64346) add calico network for cluster running CI.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by wavesoft** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by DominikDary** [comment]
@mesosphere-mergebot bump-ee

**Comment by DominikDary** [comment]
@mesosphere-mergebot changelog-not-required part of the calico feature

**Comment by jkoelker** [comment]
@mesosphere-mergebot changelog-not-required part of the calico feature

**Comment by jkoelker** [comment]
@mesosphere-mergebot label Work In Progress

**Comment by jkoelker** [comment]
I had erroneously commented that the changelog is not required on this pr, but it is, and is included now

**Pull request merged**
