### PR TITLE
[1.11][DCOS-22384] Dump diagnostics bundles for TeamCity artifacts

### PR DESCRIPTION
**Pull request by adamtheturtle**
**This is a backport of @Margaret 's work from https://github.com/dcos/dcos/pull/2411**

This is tracked by https://jira.mesosphere.com/browse/DCOS-22384.

Description from that PR:

```
High-level description

Fixture that will download the diagnostics bundles if provided a directory via environment variable. Uses the dcos_api_session fixture because otherwise this would require installing and auth for the dcos CLI.

Change to TeamCity dcos-launch test template to get this to work:

add environment variable env.DIAGNOSTICS_DIRECTORY which is set to teamcityWorkingDir/diagnostics
add teamcityWorkingDir/diagnostics to artifacts paths
add env.DIAGNOSTICS_DIRECTORY to PYTEST_PASS_ENV parameter
add lines in 'run tests' build step to scp the diagnostics bundle back and then upload it as an artifact
Additionally, the 3 enterprise integration tests that inherit from the dcos-test-utils template need to have the PYTEST_PASS_ENV updated because they override the default from dcos-launch test. The enterprise test Manual trigger project also needs to have that environment variable updated to include DIAGNOSTICS_DIRECTORY.

As stated in the conversation with branden below, this is the """""quick""""" update to get this working and after this is merged in, the functionality will be implemented in dcos-test-utils and dcos-launch in a more stable/reusable way. https://jira.mesosphere.com/browse/QUALITY-1819

Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

https://jira.mesosphere.com/browse/QUALITY-1802

Checklist for all PRs

  Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  Read the DC/OS contributing guidelines
  Followed relevant code rules Rules for Packages and Systemd
Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath packages), then in addition to the above please also include:

  Change log from the last version integrated (this should be a link to commits for easy verification and review): example
  Test Results: [link to CI job test results for component]
  Code Coverage (if available): [link to code coverage report]
```

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot override-status  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot label [Ready For Review |Request For Comment |Holding |Work In Progress |Ship It] 
@mesosphere-mergebot merge-it  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by adamtheturtle** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by adamtheturtle** [comment]
@mesosphere-mergebot label Ready For Review

**Pull request merged**
