### PR TITLE
Train 231

### PR DESCRIPTION
**Pull request by lingmann**
## Train 231

* #1965 Fix tests for 1.9 (backports)
* #1958 version bump for 1.9.5

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
https://teamcity.mesosphere.io/viewLog.html?buildId=802046 failed and I pressed `run`. Maybe it helps :)

**Comment by lingmann** [comment]
Looks like this is a problem with `teamcity/dcos/test/aws/cloudformation/simple` is between the TC job config and the AWS simple template parameter changes introduced in 1.10 and master, which have not been backported to 1.9. I'm manually running the  job but removing the `DefaultInstanceType` from the parameters. cc: @BenWhitehead and @mellenburg

**Comment by lingmann** [comment]
Filed a bug for the 1.9 test issue here: https://jira.mesosphere.com/browse/QUALITY-1579

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
