### PR TITLE
Linux modules split.

### PR DESCRIPTION
**Pull request by akornatskyy**
https://jira.d2iq.com/browse/D2IQ-65483

### CODE REVIEW

**Comment by akornatskyy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by akornatskyy** [comment]
@mesosphere-mergebot request-review

**Comment by akornatskyy** [comment]
@mesosphere-mergebot request-review  @asekretenko @DominikDary @jongiddy

**Comment by DominikDary** [comment]
@mesosphere-mergebot request-review @asekretenko @DominikDary @jongiddy

**Comment by DominikDary** [comment]
@mesosphere-mergebot request-review  @tillt

**Pull request closed without merging**
