### PR TITLE
CODEOWNERS for dcos/dcos repo.

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

* https://jira.mesosphere.com/browse/DCOS_OSS-1906

Testing https://help.github.com/articles/about-codeowners/ feature for dcos/dcos repo.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mellenburg  / @lingmann  - please help with overriding the failures in this PR. They are not related to the change.

**Comment by lingmann** [comment]
@orsenthil i created a bug + override on the enterprise failure, and I'm just re-running `teamcity/dcos/test/azure/arm` here since it looks to me like a transitory Azure infrastructure issue.

**Comment by lingmann** [comment]
@orsenthil cool happy to override since you have a Jira I can link to. I was not feeling like doing additional Jira spelunking after the enterprise override. ;-) Can we override a build status in progress? I will try...

**Comment by lingmann** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS_OSS-1830

**Comment by orsenthil** [comment]
@lingmann  - sorry for ping again, this requires one more approval because your previous approval was invalidated by my merge e55c45f above. Then we could merge this.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
