### PR TITLE
[master] Mergebot Automated Train PR - 2018-Aug-02-01-23

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3174 - Adding some members of the security team to `owners.json`

Also included

* #3120 - Add Telegraf as a DC/OS component 
* #3180 - Fix the mesos webui master log view / download links.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by nLight** [comment]
Can we please also include https://github.com/dcos/dcos/pull/3185? May I just merge it here?

**Comment by orsenthil** [comment]
@nLight  - Let's include it in the next one.

**Comment by branden** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
