### PR TITLE
(ui) Update owners.json 

### PR DESCRIPTION
**Pull request by Poltergeist**
Since we had a team change in the recent history I would like to propose two new owners for this repository.

### CODE REVIEW

**Comment by Poltergeist** [comment]
@mesosphere-mergebot sync

**Comment by Poltergeist** [comment]
@mesosphere-mergebot Ready-for-review

**Comment by Poltergeist** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by Poltergeist** [comment]
@mesosphere-mergebot changelog-not-required "Not a user-facing change."

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group2 teamcity/dcos/test/terraform/aws/onprem/static/strict/group/1

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group2  DCOS-62478

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
