### PR TITLE
[1.9] Mergebot Automated Train PR - 2018-Aug-28-10-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3330 - chore(dcos-ui):  bump DC/OS UI 1.9+v1.9.11-rc1

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static 
 https://jira.mesosphere.com/browse/DCOS_OSS-4007

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
