### PR TITLE
Remove package list from cloud config

### PR DESCRIPTION
**Pull request by branden**
## High-level description

This PR shrinks cloud templates and prevents them from growing when new packages are added. This is accomplished by removing a cluster's full list of packages from its cloud config, and replacing it with a fixed-length ID which refers to an artifact containing the list of cluster packages. `pkgpanda setup` then retrieves this artifact when bootstrapping DC/OS on a cluster node.

```
branden@crateria ~$ curl -s https://downloads.dcos.io/dcos/testing/master/cloudformation/single-master.cloudformation.json | wc -c
   50222
branden@crateria ~$ curl -s https://downloads.dcos.io/dcos/testing/pull/2177/cloudformation/single-master.cloudformation.json | wc -c
   45932
branden@crateria ~$
```

This change introduces a new type of build artifact: a package list (example [here](https://downloads.dcos.io/dcos/testing/package_lists/cbdb97763d3442533fd95bc3b2cd18cb8f87129f.package_list.json)). A package list artifact contains a JSON-encoded list of Pkgpanda package IDs, and is identified by the SHA1 hash of its contents.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-13824](https://jira.mesosphere.com/browse/DCOS-13824) Remove cluster-packages.json from cloud config and turn it into a build artifact

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Covered by existing tests
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot label ready-for-review

**Comment by adam-mesos** [comment]
@branden Do we need to `bump-ee` again before we can review this?

**Comment by branden** [comment]
@adam-mesos https://github.com/mesosphere/dcos-enterprise/pull/1846 is up to date.

**Comment by adam-mesos** [comment]
@branden Ok, but it's got a failed smoke test which blocks the `enterprise/build-status/aggregate` check here, and the EE PR still needs 2 approvals before we can put this one on a train.

**Comment by branden** [comment]
@adam-mesos The failed check is a test flake. Do we have a process for PR authors identifying test flakes?

Do we review testing-only EE PRs? I've been scolded in the past for getting reviews and putting ship-it on an EE PR that was only needed for testing an upstream bump.

**Comment by adam-mesos** [comment]
@branden With the new mergebot process we also review EE PRs that are bump-ee only, so that we can confirm a) that the EE tests pass as expected, and b) the OSS changes don't have any unexpected/unintended consequences in EE.
If you can name the new/existing JIRA that tracks the flaky/failing test, then a repo 'owner' can use mergebot's override-status command to make that check go green (with a comment/link to the JIRA).

**Comment by adam-mesos** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by falseperfection** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Pull request merged**
