### PR TITLE
[master] Mergebot Automated Train PR - 2018-Nov-23-16-54

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3787 - [DCOS-45166] Add a file which separates tests into groups
* #3800 - [master] Bump Mesos to nightly master 49cab93

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by adamtheturtle** [comment]
I have reported the {{teamcity/dcos/test/aws/cloudformation/simple}} issue at [DCOS-18825](https://jira.mesosphere.com/browse/DCOS-18825).

**Comment by orsenthil** [comment]
https://teamcity.mesosphere.io/viewLog.html?buildId=1306038&buildTypeId=DcOs_Windows_Build_BuildDcOs The windows build failure needs deeper analysis.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS-44935

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple 
 https://jira.mesosphere.com/browse/DCOS-41896

**Comment by adamtheturtle** [comment]
The flakes are as follows:

`teamcity/dcos/test/aws/cloudformation/simple`

* [DCOS-41896](https://jira.mesosphere.com/browse/DCOS-41896)
* [DCOS-19790](https://jira.mesosphere.com/browse/DCOS-19790)
* [DCOS-44935](https://jira.mesosphere.com/browse/DCOS-44935)

**Comment by adamtheturtle** [comment]
@jgehrcke please can you run:

```
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple
https://jira.mesosphere.com/browse/DCOS-19790
```

**Comment by adamtheturtle** [comment]
https://github.com/dcos/dcos/pull/3808#issuecomment-441681509

> https://teamcity.mesosphere.io/viewLog.html?buildId=1306038&buildTypeId=DcOs_Windows_Build_BuildDcOs The windows build failure needs deeper analysis.

@orsenthil - before merging this? Who will do that?

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple
https://jira.mesosphere.com/browse/DCOS-19790

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcos/windows
https://jira.mesosphere.com/browse/DCOS-45547

**Comment by orsenthil** [comment]
@adamtheturtle - Right now, it will be me (tools infra). If you look at the CI history of the target branch, this CI was green so far (https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Windows_Build_BuildDcOs&branch_DcOs_Windows_Build=%3Cdefault%3E&tab=buildTypeStatusDiv) and I thought, we find at-least the reason of what is happening and why? A moving dependency, something introduced by this PR, etc?

**Comment by orsenthil** [comment]
@adamtheturtle / @jgehrcke  - I have triaged the problem here - https://jira.mesosphere.com/browse/DCOS-45547 
It was related to landing of PR - https://github.com/dcos/dcos/pull/3669

**Pull request merged**
