### PR TITLE
bump dcos-diagnostics

### PR DESCRIPTION
**Pull request by mnaboka**
## High Level Description

Bump dcos-diagnostics sha.
Change naming convention for diagnostics bundle to
`bundle-$year-$month-$day-$unixtimestamp.zip`

This PR is to solve a problem for windows environment, where colons in a filename is causing problems.

## Related Issues

[COPS-1875](https://jira.mesosphere.com/browse/COPS-1875)

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
Unittest has been updated for this improvement. Current set of integration tests fully cover this. 
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/dcos/dcos-diagnostics/compare/f2ea907c1857c166aa733a9292c46ad190b413ed...4dcba18b90502de2944ebc951cfc968fe40cddea)
  - [X] Test Results: [dcos-diagnostics](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-diagnostics-pulls/41/console)
  - [X] Code Coverage (if available): [dcos-diagnostics](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-diagnostics-pulls/41/console)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by mnaboka** [comment]
@mesosphere-mergebot bump-ee

**Comment by mnaboka** [comment]
@mesosphere-mergebot bump-ee

**Comment by mnaboka** [comment]
@mesosphere-mergebot bump-ee

**Comment by mnaboka** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by surdy** [comment]
Looks good :D

**Comment by amitaekbote** [comment]
The failed test is a CI failure, its being muted right now. good for ship it

**Comment by amitaekbote** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
