### PR TITLE
Master Train PR

### PR DESCRIPTION
**Pull request by orsenthil**
Master Train PR

* Merge #2890 - Fix upgrade issues with ipv6 and flaky service discovery integration test
* Merge #2922 - Bump Mesos to nightly master 285d820

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Work In Progress |Ready For Review |Holding |Ship It |Request For Comment] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by branden** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
