### PR TITLE
Fix the hyperlink for DC/OS overview.

### PR DESCRIPTION
**Pull request by orsenthil**
* Fix the hyperlink for DC/OS overview.

-- 

Test PR for the JIRA:
     
* DCOS-62554 - Mergebot backport fails with unhelpful details.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot backport  2.0

**Comment by orsenthil** [comment]
@mesosphere-mergebot backport 2.0

**Comment by orsenthil** [comment]
@mesosphere-mergebot backport 2.0

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot backport 2.0

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot backport 2.0

**Comment by orsenthil** [comment]
@mesosphere-mergebot backport 1.13

**Comment by orsenthil** [comment]
@mesosphere-mergebot backport  1.12

**Comment by orsenthil** [comment]
@mesosphere-mergebot backport 1.11

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot backport 2.0

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
