### PR TITLE
Update cosmos to version 0.3.0

### PR DESCRIPTION
**Pull request by cruhland**
## High Level Description

Three improvements to cosmos:
1. Prevent the `/package/list` endpoint responding with status 400 when a deployed service's package is not present in its origin repository (https://github.com/dcos/cosmos/pull/563).
1. Add an optional command-line flag to configure the maximum acceptable HTTP response size from services that cosmos makes API calls to (https://github.com/dcos/cosmos/pull/569).
1. Log all HTTP requests cosmos makes to package repositories (https://github.com/dcos/cosmos/pull/573).

## Related Issues

Respectively:
1. [DCOS-13213](https://jira.mesosphere.com/browse/DCOS-13213)
1. [DCOS-13595](https://jira.mesosphere.com/browse/DCOS-13595)
1. [DCOS-10270](https://jira.mesosphere.com/browse/DCOS-10270)

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: this is not a code change, just updating a package version
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/dcos/cosmos/compare/3bd27057a6...v0.3.0)
  - [x] Test Results:
    - [CI](https://teamcity.mesosphere.io/viewLog.html?buildId=575301&buildTypeId=DcosIo_Cosmos_Ci&tab=buildResultsDiv)
    - [Full Cluster Integration Tests](https://teamcity.mesosphere.io/viewLog.html?buildId=575337&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_FullClusterIntegrationTests)
    - [Publish Release](https://teamcity.mesosphere.io/viewLog.html?buildId=575347&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_PublishRelease)
  - [x] Code Coverage (if available): [report](https://teamcity.mesosphere.io/repository/download/DcosIo_Cosmos_Scoverag/575300:id/scoverage-report.zip%21/index.html)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by cruhland** [comment]
@jsancio @spahl please review

I can't edit labels or milestones, but this is intended for 1.9. Will this change be integrated into Enterprise automatically or is that what the mergebot command is for?

**Comment by spahl** [comment]
That is what the command is for, just call it and you'll get a corresponding ent PR

**Comment by cruhland** [comment]
@mesosphere-mergebot bump-ee

**Comment by jsancio** [comment]
@cruhland in EE Cosmos is a different package. I think we need to manually make a similar change in EE. cc @orsenthil

**Comment by spahl** [comment]
@jsancio @cruhland yes it is a separate package but you need to udpdate it in the pr created by mergebot. That helps us track it in a consistent manner

**Comment by cruhland** [comment]
@spahl is this ready to go?

**Pull request merged**
