### PR TITLE
[1.10] Bump Mesos to nightly 1.4.x e7b117e

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
## High-level description

This is a routine bump to the latest Mesos and mesos-modules.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Changelog:
    https://github.com/apache/mesos/compare/6144242b80bbcd3c02e01d9c5f76715c1b872a06...e7b117e0d9072a50756dd90e12d691af572aed7c
    
    
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot bump-ee

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot merge-it  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Work In Progress |Holding |Ship It |Request For Comment |Ready For Review] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by tillt** [comment]
We did tediously confirm that the Mesos CI shows no regressions based on the incorporated fix of MESOS-8830. This PR should go into ready for review.

**Comment by tillt** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by tillt** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by tillt** [comment]
This fixes: https://issues.apache.org/jira/browse/MESOS-8830 - Agent gc on old slave sandboxes could empty persistent volume dat.

**Comment by jgehrcke** [comment]
> This bump incorporates the intended, back-ported fix for MESOS-8830.

This seems to be "urgent" -- why, and what does that mean from the point of view of the `1.10` branch in this repository? Is it OK to land this with the usual process via the next train?

**Pull request merged**
