### PR TITLE
Marathon 1.3.10 in DC/OS 1.8.9

### PR DESCRIPTION
**Pull request by unterstein**
## High Level Description

Bug fix release addressing recent performance issues.

## Related Issues

* 21d4d70  Fixes #4948 | Lazy event parsing in HTTP callbacks. (#5114) (janisz)
* 8b0ee47  undo def -> lazy val toProto change (Tim Harper)
* a09ea81  Improve performance of zookeeper layer and groups (Tim Harper)
* 17a082e  Fixes #4978 |  AppDefinition.Conteiner validation (#4989) (janisz)
* 1613ae1  Fixes #4948 | Lazy event parsing (#4986) (janisz)
* 553b27f  Initial stab at making deployment plans cheaper. Back port of https://phabricator.mesosphere.com/D476 (Johannes Unterstein)
* 1027968  A group is accessible, if the group is selected, a subgroup is selected or a pod/app in that group is selected. (Matthias Veit)

See also: https://github.com/mesosphere/marathon/commits/releases/1.3

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review):  https://github.com/mesosphere/marathon/releases/tag/v1.3.10
  - [x] Test Results: https://teamcity.mesosphere.io/viewType.html?buildTypeId=Oss_Marathon_PublishTar&branch_Oss_Marathon=v1.3.10&tab=buildTypeStatusDiv
  - [ ] Code Coverage (if available): n/a

### CODE REVIEW

**Comment by unterstein** [comment]
cc @aquamatthias @jeschkies

**Comment by unterstein** [comment]
Maybe CI could be confused, used wrong base (master) and changed to 1.8.8 afterwards

**Comment by adam-mesos** [comment]
1.8.8 has shipped. Do we need a 1.8.9 for this?

**Comment by adam-mesos** [comment]
@unterstein Should we update this for 1.8.9?

**Comment by unterstein** [comment]
Yes please,

I`ll update the PR. https://phabricator.mesosphere.com/D476 has critical performance enhancements.

Thanks
Johannes

**Comment by adam-mesos** [comment]
@unterstein Ping? Can we get an updated Marathon bump for 1.8.9?
cc: @meichstedt

**Comment by meichstedt** [comment]
@unterstein can you rebase and update please? If not, give me a heads up so we'll find someone else. Thanks

**Comment by unterstein** [comment]
rebased

**Comment by unterstein** [comment]
rebased to 1.8.9

We will stick to 1.3.10 for DC/OS 1.8.9 and will release a Marathon 1.3.11 which includes only an updated Marathon UI version.

**Comment by adam-mesos** [comment]
Dropping in favor of 1.3.11: https://github.com/dcos/dcos/pull/1563

**Comment by unterstein** [comment]
thanks!

**Pull request closed without merging**
