### PR TITLE
Bump CNI

### PR DESCRIPTION
**Pull request by GoelDeepak**
## High Level Description

Bump CNI plugins to latest master

## Related Issues

  - [DCOS_OSS-1357](https://jira.mesosphere.com/browse/DCOS_OSS-1357) Upgrade [Lib]CNI to v0.5.2

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@asridharan  Please review

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by asridharan** [comment]
@karlkfi do you want give this a read? @jieyu can you give it a read as well?

**Comment by asridharan** [comment]
@jieyu could you give this a look as well? Don't think anyone else is qualified enough to give this a look. @drewkerrigan Maybe you can give it a look as well?

**Comment by GoelDeepak** [comment]
@karlkfi The CNI community split the original repo into two - Specs (https://github.com/containernetworking/cni) and Plugins (https://github.com/containernetworking/plugins). In DC/OS, we are mainly interested in plugins so moved to plugin repo.

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
Please fill out the component checklist with at least a changelist describing what's changed since the last CNI SHA, ideally CI as well.

**Comment by GoelDeepak** [comment]
@adam-mesos This is a bump for external repo. In this particular case, the community has also split the original repo into two different repos. We point to one of them. How do you want me to produce the diff? Also, the necessary plugins are tested as part of dcos integration test.

**Comment by adam-mesos** [comment]
@GoelDeepak Does the CNI community have a changelog of what's happening in the project? The motivation for asking for a list of changes is so that we can identify if something in the CNI bump may have caused/impacted issues that come up. A naked SHA isn't very informative.
Looks like the repo split kept the old commit history, so https://github.com/containernetworking/plugins/compare/e0ea82b229f6517d033462c5cf57b698c6a89d1f...5544d9ced0d6e908fe26e9dbe529c7feb87d21f5 seems to work.

**Comment by GoelDeepak** [comment]
@adam-mesos awesome! Thx

**Comment by cdaw** [comment]
ping ... we need this for beta2
also, does this have to be in EE?

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by spahl** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
