### PR TITLE
Add pods endpoint to diagnostics bundle

### PR DESCRIPTION
**Pull request by alenkacz**
## High-level description

Add pods marathon endpoint to diagnostics bundle.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-1869](https://jira.mesosphere.com/browse/DCOS_OSS-1869) Marathon pods not captured by diagnostic bundle.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by alenkacz** [comment]
@mesosphere-mergebot label ready for review

**Comment by alenkacz** [comment]
@jgehrcke @mnaboka I cannot add reviewers here for some reason but can you please check this out?

**Comment by jgehrcke** [comment]
Looks good to me, but I don't understand a lot about the diagnostics service. @mnaboka and @klueska please review.

I know that most of the times when we add something to the diagnostics bundle we also add a corresponding test ([example](https://github.com/dcos/dcos/commit/6eea79cc81c125998790b802b9959044dcdcdb14#diff-76bef05f42988941a282be82652c94c9)).

@mnaboka can we add something to https://github.com/dcos/dcos/blob/master/packages/dcos-integration-test/extra/test_dcos_diagnostics.py  that confirms that the diagnostics service has received an expected HTTP response from Mararthon?

**Comment by mnaboka** [comment]
@alenkacz please update the [integration test](https://github.com/dcos/dcos/blob/master/packages/dcos-integration-test/extra/test_dcos_diagnostics.py#L515-L516) with `8080-v2_pods.json` if the endpoint supports gzip the file must have .gz appended, for example `8080-v2_pods.json.gz`

cc @jgehrcke

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  work in progress

**Comment by janisz** [comment]
This PR is stale. Can we close it in favor of #3148 @surdy  @alenkacz @klueska

**Comment by alenkacz** [comment]
@janisz sure!

**Pull request closed without merging**
