### PR TITLE
Update owners.json

### PR DESCRIPTION
**Pull request by cprovencher**
## High-level description

Adding a dcos-owner for helping with the train process

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@cprovencher Same request that I pasted on 1.9 PR

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot Ready For Review

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
Applying ship-it label since it is an owners file change, and has the required approvals.

**Pull request merged**
