### PR TITLE
Bumped Mesos package to Mesos 1.2.x head d95a031.

### PR DESCRIPTION
**Pull request by Gilbert88**
## High Level Description

This PR bumps the Mesos package to the latest HEAD of the 1.2.x branch, to bring in the recent backported bugfix.

## Related Issues

  - [MESOS-7926](https://issues.apache.org/jira/browse/MESOS-7926) - Abnormal termination of default executor can cause MesosContainerizer::destroy to fail.
  - [MESOS-7934](https://issues.apache.org/jira/browse/MESOS-7934) - OOM due to LibeventSSLSocket send incorrectly returning 0 after shutdown.
  - [MESOS-6743](https://issues.apache.org/jira/browse/MESOS-6743) - Docker executor hangs forever if docker stop fails.

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: This PR relies on the Mesos test suite
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Mesos diff](https://github.com/mesosphere/mesos/compare/e91c7bd05671e56e9ae8fbf0304aa1c74dd27fdd...def524d5bf9c8d02a4307aa745e654706a848b33)
  - [x] Test Results: [CI results](https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/Mesos_CI-build/1724/)
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by tillt** [comment]
This will also fix MESOS-6743 for DCOS - assigning https://jira.mesosphere.com/browse/DCOS-18338 to you @Gilbert88 as you are covering that already.

**Comment by tillt** [comment]
Please add the following to your changelist;

[[MESOS-6743](https://issues.apache.org/jira/browse/MESOS-6743)] - Docker executor hangs forever if `docker stop` fails.

**Comment by orsenthil** [comment]
The EE failure needs investigation: https://teamcity.mesosphere.io/viewLog.html?buildId=769956&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_UpgradeTestEnterprise 
The failure is on this PR - `TestUpgrade.test_mesos_task_state_remains_consistent `

**Comment by Gilbert88** [comment]
@orsenthil the EE failure might be a flaky test. Please see https://jira.mesosphere.com/browse/DCOS_OSS-1503

**Comment by tillt** [comment]
checked if it does indeed use Apache Mesos 1.2.3 WIP (1.2.x): ✅ 
checked if it covers the mentioned issues entirely: ✅ 
checked if it contains the needed cherry-picks:  ✅ 

🚀

**Comment by tillt** [comment]
@gilbert please add the following to the list of covered items:
[[MESOS-7934](https://issues.apache.org/jira/browse/MESOS-7934)] - OOM due to LibeventSSLSocket send incorrectly returning 0 after shutdown.

**Comment by tillt** [comment]
checked if it does indeed use Apache Mesos 1.2.3 WIP (1.2.x): ✅
checked if it covers the mentioned issues entirely: ✅  (misses MESOS-7934 in description though)
checked if it contains the needed cherry-picks: ✅

:rocket: (assuming it will go green on non flakys)

**Comment by orsenthil** [comment]
@tillt  / @chhsia0  - new commit was pushed beyond approvals. Please review again.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot  label ready for review

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
