### PR TITLE
Update version to reflect 1.11.0 development

### PR DESCRIPTION
**Pull request by lingmann**
## High Level Description

Update version string to reflect 1.11.0 development.

JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-1765

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
The docker tests fail because universe needs an update, here is the pr I have been working on: https://github.com/dcos/dcos/pull/1933 

Here is the jira for the universe fix: https://jira.mesosphere.com/browse/DCOS-19044

**Comment by jgehrcke** [comment]
Do we have a JIRA ticket for this change?

**Comment by jgehrcke** [comment]
The `[21:39:51]	Unexpected down stream http error: GET https://universe.mesosphere.com/repo 403` error is tracked via https://jira.mesosphere.com/browse/DCOS_OSS-1764.

**Comment by takirala** [comment]
The fix is merged to master. We need to deploy this to prod cluster. This is being looked at by @lloesche and Viktor Harutyunyan

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
The `teamcity/dcos/test/aws/cloudformation/simple` [failure ](https://teamcity.mesosphere.io/viewLog.html?buildId=832507) needs inspection and needs to be properly tracked in JIRA. Help appreciated.

**Comment by karlkfi** [comment]
I think the version should probably be `1.11-dev`, not `1.11.0-dev`, otherwise we have to bump it every minor release. Plus, those minor releases have code that isn't necessarily in master because they get both cherrypicks AND custom commits.

**Comment by orsenthil** [comment]
@karlkfi 's comment above is important. We have another PR that accomplishes the suggestion, is on top master and is ready for review: https://github.com/dcos/dcos/pull/1933   - we are going with @amitaekbote 's PR and let's close this one.

**Pull request closed without merging**
