### PR TITLE
Update version to 1.10.6

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Update 1.10 branch version to 1.10.6

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@branden  / @amitaekbote  - please review this and EE counterpart.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
The failure in `teamcity/dcos/test/azure/arm` needs to be investigated (flake, most probably, and we should override it correspondingly).

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm  DCOS_OSS-2313

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

The EE status is not rolling up. The bug is noted here (https://jira.mesosphere.com/browse/DCOS-19905)

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
