### PR TITLE
Admin Router: AR-NEXT #4

### PR DESCRIPTION
**Pull request by vespian**
## High Level Description

This PR is an aggregate of multiple smaller PRs. PRs included:
~~https://github.com/mesosphere/dcos/pull/41~~
~~https://github.com/mesosphere/dcos/pull/42~~
~~https://github.com/mesosphere/dcos/pull/43~~
~~https://github.com/mesosphere/dcos/pull/44~~
~~https://github.com/mesosphere/dcos/pull/45~~
~~https://github.com/mesosphere/dcos/pull/46~~
~~https://github.com/mesosphere/dcos/pull/47~~

Failures in all individual PRs (both EE and Open) are expected.

## Related Issues

See individual PRs

## Related PRs

DC/OS EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1350

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot label work in progress

**Comment by vespian** [comment]
@mesosphere-mergebot  label ready-for-review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label Request For Comment

**Comment by orsenthil** [comment]
Hi @vespian, Apologies for holding it here.  I know you follow this `AR-NEXT` train model. 
What concerned me was a - many merge commits in your `AR-NEXT` and when those lands in `dcos/dcos` master, I felt the code presented a difficult to read picture.

The suggestion that I had was 

1. In AR-NEXT, when you had your individual PRS (hopefully clean ones), could you rebase those so that each one lands on top of the other.

2. When you create a `dcos/dcos` PR, could that be a rebased sha of AR-NEXT against the `dcos/dcos` master. 

I know this adds a bit of work on you, however by avoiding these `sub-merge` commits we have a cleaner picture in the `dcos/dcos` history. What's opinion on this?

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
