### PR TITLE
Update version to 1.10.8

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Update version to 1.10.8

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
The `teamcity/dcos/test/azure/arm`  is captured in https://jira.mesosphere.com/browse/DCOS-38027

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@urbanserj  - could you please with overriding `teamcity/dcos/test/azure/arm` with https://jira.mesosphere.com/browse/DCOS-38027

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-38027

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
