### PR TITLE
Switch ELB port 80 from HTTP to TCP mode.

### PR DESCRIPTION
**Pull request by brndnmtthws**
cc @spahl

### CODE REVIEW

**Comment by cmaloney** [comment]
What about Azure?

**Comment by brndnmtthws** [comment]
Looks like Azure's already configured as TCP:

https://github.com/dcos/dcos/blob/master/gen/azure/templates/azuredeploy.json#L773-L790
https://github.com/dcos/dcos/blob/master/gen/azure/templates/acs.json#L981-L1000

**Comment by lingmann** [comment]
LGTM. I was initially concerned about the changes to InternalMasterLoadBalancer, since it may introduce subtle issues for internal services which poll adminrouter... But since the health checks are still explicitly HTTP, polling services won't see a difference.

@brndnmtthws how confident are you in this from a testing perspective?

**Comment by brndnmtthws** [comment]
@lingmann I've tested this, and we're using TCP on Azure already anyway, so it will be transparent to the user.

**Comment by brndnmtthws** [comment]
Also rebased on master.

**Comment by cmaloney** [comment]
:ship:

**Pull request merged**
