### PR TITLE
Train 186

### PR DESCRIPTION
**Pull request by falseperfection**
#1704 - Update libsodium dependency.
#1711 - Bumped Mesos to include some fixes.

### CODE REVIEW

**Comment by falseperfection** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Although https://github.com/dcos/dcos/pull/1706 should improve things in that regard, I supose that those test failures are known flakes:
```
test_networking.test_vip[Container_DOCKER-Network_BRIDGE-Network_USER] |  
test_networking.test_vip[Container_MESOS-Network_USER-Network_HOST] |  
test_networking.test_vip[Container_MESOS-Network_USER-Network_USER] |  
```
(https://teamcity.mesosphere.io/viewLog.html?buildId=701470)

**Comment by falseperfection** [comment]
Had to pull #1706 because it wasn't yet ready, should be good for the next train. Re-running tests.

**Comment by falseperfection** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@lingmann / @mellenburg / @BenWhitehead  - this and corresponding EE PR can be merged.

**Comment by orsenthil** [comment]
Will need additional review as the previous one was invalidated.

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
