### PR TITLE
bump dcos-cni

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

This is backport of #2492 

I have requested more information from @asridharan  on the late introduction of this feature. This may or may not be merged with 1.11.0 GA

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by asridharan** [comment]
@orsenthil  this PR fixes : https://jira.mesosphere.com/browse/DCOS_OSS-2171

We discovered a issue with DNS in K8s during the bug hunt. The fix for that bug was done as part of : https://jira.mesosphere.com/browse/KUB-145
A side-effect of KUB-145 was that K8s wouldn't function on networks such as Big-switch network (an SDN provider) . This bump in the DC/OS CNI plugins introduces a fix to mitigate the side-affect of KUB-145.

**Comment by asridharan** [comment]
@orsenthil thanks for creating this back-port.
@GoelDeepak need your reviews on this.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
```@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static  https://jira.mesosphere.com/browse/DCOS_OSS-2115```

@asridharan  / @urbanserj  / @jeschkies  - Can you help with the above^.

**Comment by orsenthil** [comment]
Also, please approve the EE PRs too.

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Pull request merged**
