### PR TITLE
Train 269 base:master

### PR DESCRIPTION
**Pull request by lingmann**
## Train 269 base:master

* #2049 Update cosmos to latest version

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1457

**Comment by lingmann** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
