### PR TITLE
[1.12] Mergebot Automated Train PR - 2019-Jan-11-20-20

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #4166 - (1.12) Fix container metrics tests for the v0 metrics API
* #4173 - [Backport][1.12] Exposes mesos flag to persist cni root directory across host reboot.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
This is failing with an error that I believe is meant to be fixed by a PR that it contains. In particular, 
https://github.com/dcos/dcos/pull/4166 is meant to fix [DCOS_OSS-4486](https://jira.mesosphere.com/browse/DCOS_OSS-4486) but we can see:

```
    @retrying.retry(wait_fixed=METRICS_INTERVAL, stop_max_delay=METRICS_WAITTIME)
    def get_container_metrics(dcos_api_session, node: str, container_id: str):
        """Return container_id's metrics from the metrics API on node.
    
        Retries on error, non-200 status, or missing response fields for up
        to 5 minutes.
    
        """
        response = dcos_api_session.metrics.get('/containers/' + container_id, node=node)
>       assert response.status_code == 200
E       assert 204 == 200
E        +  where 204 = <Response [204]>.status_cod
```

in the log.

**Comment by adamtheturtle** [comment]
> @branden - The fix really did not seem to help. Would you like to mute the test as part of this PR?

Can we first decide whether we want to keep the proposed changes (maybe they make things a bit better)?

**Comment by branden** [comment]
I think the cause is actually this other problem in metrics tests: https://jira.mesosphere.com/browse/DCOS_OSS-4682 This PR on this train is still an improvement, so I think it should stay. I'll override with DCOS_OSS-4682 and follow up with a new PR to address that ticket.

**Comment by branden** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS_OSS-4682

**Pull request merged**
