### PR TITLE
[1.9] Bump Mesos to nightly mesosphere/1.2.x cb79076

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
## High-level description

This is a routine bump to the latest mesosphere/1.2.x branch of Mesos.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last Mesos version integrated:
    [mesosphere/mesos diff](https://github.com/mesosphere/mesos/compare/bf8d2f21f403d8650ee9beeed7f7f2e55b79fc6f...1296f66a67cc498b522caae16c2617977592bd70)
    
    
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot bump-ee

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot override-status  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot label [Ready For Review |Request For Comment |Holding |Work In Progress |Ship It] 
@mesosphere-mergebot merge-it  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by karya0** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by mesosphere-mergebot-dev** [comment]
:wave: This PR has been inactive for 3 days. Please review the status checks to see what needs to be done to move it forward or change the label to Work in Progress. Thank you!

**Pull request merged**
