### PR TITLE
Train 237

### PR DESCRIPTION
**Pull request by lingmann**
## Train 237

* #1672 Merge major networking components into dcos-net service

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
`teamcity/dcos/test/aws/cloudformation/simple` is failing on:
* `test_networking.test_vip[Container_NONE-Network_USER-Network_HOST]`
* `test_networking.test_vip[Container_NONE-Network_HOST-Network_USER]`
* `test_networking.test_vip[Container_NONE-Network_HOST-Network_HOST]`
* `test_networking.test_vip[Container_MESOS-Network_USER-Network_HOST]`
* `test_networking.test_vip[Container_MESOS-Network_HOST-Network_USER]`
* `test_networking.test_vip[Container_MESOS-Network_HOST-Network_HOST]`
* ...

It seems like all permutations of this test are failing reproducibly.

@asridharan @urbanserj could you investigate? Is there anything we can do to help with your investigation?

**Comment by urbanserj** [comment]
@lingmann unfortunately it's not possible to connect to these clusters when tests are running, but the last attempt was successful and all checks are green.

**Comment by lingmann** [comment]
Unfortunately, the sole PR in this train appears to be introducing a great deal of instability to the teamcity/dcos/test/aws/cloudformation/simple integration test. I've written up more details on my findings here: https://jira.mesosphere.com/browse/DCOS_OSS-1757

**Pull request closed without merging**
