### PR TITLE
[master] Mergebot Automated Train PR - 2018-Oct-12-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3453 - Fix app metric names in v0 API
* #3465 - Remove mesos_id dimension from v0 metrics API
* #3558 - Add dcos-integration-test/extra/test_users.py
* #3594 - Assert system clock is synced before starting dcos-exhibitor
* #3604 - Bump dcos-net

### CODE REVIEW

**Comment by orsenthil** [comment]
@branden - your fix for the dcos build needs to be included for this train PR to go through.

**Comment by branden** [comment]
@orsenthil Telegraf build fix here: #3619

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
