### PR TITLE
updating to latest marathon 1.5

### PR DESCRIPTION
**Pull request by kensipe**
## Changes

* Introduces file based secrets.
* MARATHON-7090 Support passing a Docker config.json for app / pod being launched.

## Fixed Issues

* MARATHON-7457
* MARATHON-7468
* MARATHON-7204
* MARATHON-7430
* MARATHON-7479
* DCOS-16151
* MARATHON-7458
* MARATHON-7414

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Test Results: (results)[https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/34]
  - [x] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by kensipe** [comment]
replaces https://github.com/dcos/dcos/pull/1643

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@kensipe  - if you add any commits beyond the bump-ee state. Just run the bump-ee again. It will pick up the changes to the EE pr.

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by jdef** [comment]
File based secrets introduces changes to the Marathon plugin interface. bump-ee is not sufficient by itself, will likely need to manually bump the plugin interface artifact version

**Comment by orsenthil** [comment]
@jdef  Yes, the corresponding changes to EE should be included in the EE PR (https://github.com/mesosphere/dcos-enterprise/pull/1067) 

Also the cli-test failures and vagrant-bash failures here investigation.

**Comment by kensipe** [comment]
@jdef and @orsenthil the latest marathon plugin was already on ee master.  the marathon bump is the only thing necessary.

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Is there a JIRA ticket to be closed now that this landed?

**Pull request merged**
