### PR TITLE
[master] Bump Mesos to nightly master 6fcbd99

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
## High-level description

This is a routine bump to the latest Mesos and mesos-modules.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Changelog:
    https://github.com/apache/mesos/compare/ff8c9a96be6ae1ee47faf9d5b80a518dfb4a3db0...6fcbd99108b19c8dd1cf7a0f45a59d48d7aacd7e
    
    
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot bump-ee

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by Gilbert88** [comment]
Please close this PR in favor of #6076

**Comment by tillt** [comment]
We see plenty of agent crash caused failures here. @Gilbert88 is that something you guys fixed recently?

{noformat}
2.compute.internal mesos-agent[15819]: F0814 02:52:00.042616 15837 process.cpp:3057] Aborting libprocess: 'posix-disk-isolator(1)@172.12.0.15:5051' threw exception: _Map_base::at
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: *** Check failure stack trace: ***
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: I0814 02:52:00.056001 15838 authenticator.cpp:324] dstip=172.12.0.15 type=audit timestamp=2019-08-14 02:52:00.055941888+00:00 reason="Valid authentication token" uid="dcos_telegraf_agent" object="/slave(1)/api/v1" agent="Telegraf-prometheus/unknown" authorizer="mesos-agent" action="POST" result=allow srcip=172.12.0.15 dstport=5051 srcport=44852
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: I0814 02:52:00.056255 15838 http.cpp:1115] HTTP POST for /slave(1)/api/v1 from 172.12.0.15:44852 with User-Agent='Telegraf-prometheus/unknown'
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: I0814 02:52:00.056354 15838 http.cpp:1705] Processing GET_TASKS call
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal nginx[12469]: ip-172-12-0-15.us-west-2.compute.internal nginx: 127.0.0.1 - - [14/Aug/2019:02:52:00 +0000] "GET /nginx/metrics HTTP/1.1" 200 609793 "-" "Go-http-client/1.1" logtime_msec=1565751120.086 upstream_addr=- request_time=0.000 upstream_response_time=- upstream_connect_time=- upstream_header_time=-
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fbd11c79d  google::LogMessage::Fail()
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fbd11e9f8  google::LogMessage::SendToLog()
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fbd11c333  google::LogMessage::Flush()
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fbd11f339  google::LogMessageFatal::~LogMessageFatal()
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fbd07cf8d  process::ProcessManager::resume()
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fbd082af6  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN7process14ProcessManager12init_threadsEvEUlvE_vEEE6_M_runEv
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fb8d3a070  (unknown)
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fb8558e25  start_thread
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal mesos-agent[15819]: @     0x7f8fb8282bad  __clone
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal systemd[1]: dcos-mesos-slave.service: main process exited, code=killed, status=6/ABRT
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal systemd[1]: Unit dcos-mesos-slave.service entered failed state.
Aug 14 02:52:00 ip-172-12-0-15.us-west-2.compute.internal systemd[1]: dcos-mesos-slave.service failed.
{noformat}

**Pull request closed without merging**
