### PR TITLE
Train 118

### PR DESCRIPTION
**Pull request by adam-mesos**
Train includes the following PRs:
:rocket: :rocket: :rocket: #1108 journald+logrotate container logging
:rocket: :rocket: #1107 bump navstar for minuteman config
:rocket: :rocket: #1100 bump Mesos
:rocket: :rocket: #1084 bump dcos-ui
:rocket: :rocket: #1130 Explicit JAVA_HOME for exhibitor gradle build
:rocket: :rocket: #1119 Fix test_if_marathon_app_can_be_deployed_with_mesos_containerizer in EE
:rocket: :rocket: #1125 Mesos package readme
:rocket: :rocket: #1120 upgrade test

### CODE REVIEW

**Comment by alberts** [comment]
@adam-mesos please add https://github.com/dcos/dcos/pull/882

**Comment by lingmann** [comment]
@alberts @mellenburg #882 is not quite ready, but sounds like it is very very close. @mellenburg can you address @cmaloney's remaining feedback and let's get it in this train if possible.

**Comment by lingmann** [comment]
@adam-mesos would like to also request that we include #1115 (you promised me a review ;-) as well as #1120 (ready to go).

**Comment by amitaekbote** [comment]
lgtm 🚢

**Pull request merged**
