### PR TITLE
[master] Mergebot Automated Train PR - 2018-Jul-26-12-05

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3130 - Added support for toggling the logging of offers sent by Mesos.
* #3133 - gen/calc: normalize check timeouts
* #3143 - Metronome bump launch timeout 1.12

### CODE REVIEW

**Comment by gpaul** [comment]
Internal mesosphere slack conversation and a quick look at the Enterprise PR's strict mode intergration test cluster logs suggest this is useful and not too verbose. Also, this PR only enables `v=2` for the `master` module (`master.cpp`), the rest of the process retains the default log level.

Thanks @tillt, @rukletsov

**Comment by gpaul** [comment]
It doesn't look like a corresponding enterprise train was created. Due to conflicts?

**Comment by orsenthil** [comment]
> It doesn't look like a corresponding enterprise train was created. Due to conflicts?

True. Kind of conflicts that needs manual intervention (like conflicts in code).

* I will create the EE train for this PR.
* Need to improve the messaging to explain the above too.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by gpaul** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
