### PR TITLE
Admin Router: Minimizing software version information reported by the AR [1.10]

### PR DESCRIPTION
**Pull request by vespian**
Just a backport of https://github.com/dcos/dcos/pull/2154
  

Jira issue: https://jira.mesosphere.com/browse/DCOS-19765 `Admin Router: port software version scrubbing from DCOS-19534 to 1.10`

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1457

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke DCOS_OSS-1457

**Comment by vespian** [comment]
@mesosphere-mergebot label ready for review

**Comment by adamtheturtle** [comment]
@vespian Please could you explain the differences between this and https://github.com/dcos/dcos/pull/2154/files?

For example, there is a test there that is there but not here:

```
   - tests:
 +      are_response_headers_ok:
 +        nocaching_headers_are_sent: skip
 +        test_paths:
 +          - /system/v1/leader/mesos/foo/bar?key=value&var=num
 +          - /system/v1/leader/marathon/foo/bar?key=value&var=num
```

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@adamtheturtle  I added the missing test.

I have gone through the PRs (both EE and Open) and all other tests seem OK. It is impossible to cherry-pick the 1.11 changes 1:1 as:
* in Open, the `/service/metronome/` test was introduced in 1.11 dev cycle
* in EE, the `/vault` endpoint tests was replaced by `/cockroachdb` endpoint tests

Please have another look modulo CI and thank you for yet another thorough review :)

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS-19542

**Comment by amitaekbote** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS-19542

**Comment by vespian** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by vespian** [comment]
EE PR is all-green/has ship it, Mergebot applied Ship-it to this PR, but the `
mergebot/enterprise/build-status/aggregate` is still yellow - I do not know why :(

CC @orsenthil

**Comment by orsenthil** [comment]
@vespian - this is events getting lost between github services. If this happens again, please go to EE side, a re-run the `tox` or a simple status check again. The aggregate will be sent again.

**Pull request merged**
