### PR TITLE
fix cloud_images CI yum error

### PR DESCRIPTION
**Pull request by margaret**
## High-level description

Trying stuff to fix https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=884142&_focus=709 `Caching enabled but no local cache of /var/cache/yum/x86_64/7/base/packages/libseccomp-2.3.1-3.el7.x86_64.rpm from base/7/x86_64`.

Update: Tried running `yum clean all` and `yum makecache` before the broken line https://github.com/dcos/dcos/blob/10e4045a0eafd4eaba8d4356d3a23c99853d0cef/cloud_images/lib/el7/install_docker.sh#L9 but the same error was still there. Removing the `-C` flag which tells yum to only use the system cache removed the error, and doesn't seem to have increased the build time. I noticed that the /etc/yum.conf had `keepcache=0` which means it wasn't storing anything anyway, so not sure how that worked before.

Here are successful runs of the CI after these changes: 
[Standard regions](https://teamcity.mesosphere.io/viewLog.html?buildId=923100&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImage&tab=buildResultsDiv)
[Govcloud region](https://teamcity.mesosphere.io/viewLog.html?buildId=923185&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImagesForGovcloud) 

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [QUALITY-1727](https://jira.mesosphere.com/browse/QUALITY-1727) "AWS: Build and publish CentOS 7 base images" TeamCity jobs broken

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot label ready for review

**Comment by margaret** [comment]
@mellenburg @sschneid can you review please?

**Comment by sschneid** [comment]
I think the `-C` was required for building on Red Hat (they have no licenses and cannot update from yum), but we can revisit and add OS-specific logic if needed in the future.

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
https://teamcity.mesosphere.io/viewLog.html?buildId=926673&buildTypeId=DcOs_Open_Test_IntegrationTest_AzureArm

`azure/arm` test failure is `test_networking.test_vip` failing with a retry error for docker and mesos. `test_networking.test_ipv6` also  failed with the initial error ` TypeError: getresponse() got an unexpected keyword argument 'buffering'`, but the very bottom of the traceback is a `ReadTimeout`.

@orsenthil Needs an override with https://jira.mesosphere.com/browse/DCOS-19542

**Comment by mellenburg** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-19542

**Comment by spahl** [comment]
Signed off for merge

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
rebased onto master

**Pull request merged**
