### PR TITLE
Update Go to 1.7.4 (security fixes)

### PR DESCRIPTION
**Pull request by alberts**
Update Go to 1.7.4 (security fixes).

# Checklist

 - [x] Included a test which will fail if code is reverted but test is not (N/A)
 - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

If this is a component/package update, include

 - [x] Change Log from last: https://golang.org/doc/devel/release.html#go1.7
 - [x] Test Results: N/A
 - [x] Code Coverage: N/A

### CODE REVIEW

**Comment by amitaekbote** [comment]
@alberts can you include the template for the pr and fill it out?

**Comment by alberts** [comment]
@amitaekbote I included the parts of the template that seemed relevant. What else would you like me to add?

**Comment by amitaekbote** [comment]
The checklist 

# Checklist

 - [x] Included a test which will fail if code is reverted but test is not
 - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

If this is a component/package update, include

 - [ ] Change Log from last: <link>
 - [ ] Test Results: <link>
 - [ ] Code Coverage: <link>

**Comment by amitaekbote** [comment]
For context, we are trying to do this so we can speed up reviews by checking off basic things like tests and code guidelines. if there isnt a new test added a brief explanation as to why we didnt would be nice. 

Ideally we look at all these and see if they added value or not and tweak the template accordingly.

**Pull request merged**
