### PR TITLE
Bump curl from 7.48 to 7.59 in dcos 1.10

### PR DESCRIPTION
**Pull request by ahairape**
This PR bumps curl from 17.48 to 7.59.0 in 1.10

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
https://jira.mesosphere.com/browse/DCOS-21557

## Checklist for all PRs
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by ahairape** [comment]
@mesosphere-mergebot ee-bump

**Comment by ahairape** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by ahairape** [comment]
Failure in `teamcity/dcos/test/azure/arm - Execution timeout` - https://jira.mesosphere.com/browse/QUALITY-1956

**Comment by ahairape** [comment]
@orsenthil could you please review this PR?
Thank you!

**Comment by jgehrcke** [comment]
> Do we have specific reasons / customer requests for doing that kind of upgrade?

Looks like we have gotten the request to upgrade as of security vulnerabilities addressed in curl.

Approving again. However, this is a really significant change and a pretty risky thing to do in a point release. In the future we must do better in terms of following curl releases.

**Comment by orsenthil** [comment]
> Approving again. However, this is a really significant change and a pretty risky thing to do in a point release. In the future we must do better in terms of following curl releases.

I skimmed the discussion in the JIRA and then approved it. I read it was required. 

I didn't calculate the delta between the curl versions, however, as long as it is stable release of curl, I was expecting our non-deterministic cache to help us create a proper artifact. We shouldn't expect run time problems with this upgrade. And hopefully our soak-time, integration tests will catch if we observe anything different at runtime.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
