### PR TITLE
DCOS-48402 - Add new EnvironmentFiles to Mesos systemd units

### PR DESCRIPTION
**Pull request by fatz**
## High-level description

Backport #4630 // [DCOS-49092](https://jira.mesosphere.com/browse/DCOS-49092) Add three new EnvironmentFiles to Mesos systemd units - JIRA
 adding additional user managed environment files to mesos systemd units

## Corresponding DC/OS tickets (required)

  - [COPS-5699](https://jira.mesosphere.com/browse/COPS-5699) Add the possibility, in DC/OS 1.12, to customize Mesos Master parameters in /etc/mesosphere/mesos/master.env, as it happens in DC/OS 1.13
- [DCOS-48402](https://jira.mesosphere.com/browse/DCOS-49092) Create a Design Doc for adding support for custom Mesos roles to the DC/OS installer]
- [DCOS-49092](https://jira.mesosphere.com/browse/DCOS-49092) Add three new EnvironmentFiles to Mesos systemd units - JIRA

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by fatz** [comment]
@mesosphere-mergebot request-review

**Comment by fatz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by fatz** [comment]
@jongiddy that is a good point. In general I do not like this option and it is absolutely not needed for most of our customers.

The initial idea was making things like default roles for agents configurable so they survive an upgrade. @vinodkone want this to be in CHNAGELOG?

**Comment by vinodkone** [comment]
Documenting this in CHANGELOG seems fine. This seems like a valuable addition for customers.

**Comment by fatz** [comment]
@mesosphere-mergebot label Ship It

**Comment by fatz** [comment]
@mesosphere-mergebot label Ship It

**Comment by fatz** [comment]
@mesosphere-mergebot label Ship It

**Comment by jongiddy** [comment]
@mesosphere-mergebot sync

**Comment by fatz** [comment]
@mesosphere-mergebot sync

**Comment by fatz** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
