### PR TITLE
Train 235

### PR DESCRIPTION
**Pull request by colin-msphere**
* #1922 Increase recovery timeout in agent config
* #1991 Update CentOS docker packages
* #1999 Update Ubuntu Docker to 17.09.0

### CODE REVIEW

**Comment by colin-msphere** [comment]
@mesosphere-mergebot bump-ee

**Comment by colin-msphere** [comment]
@mesosphere-mergebot bump-ee

**Comment by colin-msphere** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
@vinodkone any reason for us to pull https://github.com/dcos/dcos/pull/1922 from the train? If there is just a low-priority follow-up action needed, then let's keep the train as is, since it is pretty time consuming to re-do all the train testing. And any changes @lava needs to make can go in a follow-up PR. WDYT?

**Comment by lingmann** [comment]
`teamcity/dcos/test/docker/smoke` failed, but did not see anything obvious in the build log. Re-triggering.

**Comment by vinodkone** [comment]
@lingmann No need to pull this PR from the train. This is good to go as is.

**Comment by colin-msphere** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
