### PR TITLE
[1.10.0] Train 214

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 214 with patches that are supposed to land in the 1.10.0 release. It contains the following pull requests:
- #1892 (Update DC/OS UI package to 1.10.0-rc.8 (1.10))
- #1900 (Bumped Mesos package to 1.4.x head 60b8d41)

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Failure: https://teamcity.mesosphere.io/viewLog.html?buildId=771538 -- re-running.

**Comment by jgehrcke** [comment]
`integration-test/vagrant-bash` failed again in https://teamcity.mesosphere.io/viewLog.html?buildId=771806.

**Comment by jgehrcke** [comment]
All checks in https://github.com/mesosphere/dcos-enterprise/pull/1393 passed. It stands to reason that all bad CI reports in this PR are as of test/CI instability.

**Comment by jgehrcke** [comment]
The report from `mergebot/enterprise/build-status/aggregate` seems to be a false negative. I probably have confused mergebot. CC @orsenthil.

**Comment by jgehrcke** [comment]
That PR and the corresponding dcos-enterprise PR actually look good to me now. We just need to properly track the CI failure in JIRA and then get the reviews :-) :rocket:

**Comment by lingmann** [comment]
@orsenthil can you investigate the 'build-status/aggregate' failure and link a ticket here if appropriate? Thanks!

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ship-it

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
> The report from mergebot/enterprise/build-status/aggregate seems to be a false negative. I probably have confused mergebot. 

It was github problem. The status update was not propagated. I re-run a code-quality test (~1 minute) at the other end, and the aggregate turned green.

**Pull request merged**
