### PR TITLE
Train master 11/08/2018

### PR DESCRIPTION
**Pull request by cprovencher**
Updating the fixVersions because Mergebot doesn't have the AI feature…  
#3748
 
 
Fix TLS handshake
#3718
 
 
Docker gc log fix  Ship It
#3710
 

Bump dcos-log  Ship It
#3644
 
 
Enable statsd plugin on telegraf  Ship It
#3636

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by gauripowale** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
