### PR TITLE
[DCOS-57291] make DC/OS Signal report the license ID

### PR DESCRIPTION
**Pull request by makkes**
## High-level description

DC/OS Signal must be able to read the license ID from the socket file `/run/dcos/dcos-licensing.sock` that's owned by the group `dcos_adminrouter`.

## Corresponding DC/OS tickets (required)

  - [DCOS-57291](https://jira.mesosphere.com/browse/DCOS-57291) DC/OS Signal doesn't report license ID

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): no change log necessary
  - [] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by makkes** [comment]
@mesosphere-mergebot changelog-not-required bugfix under the hood

**Comment by makkes** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by makkes** [comment]
@mesosphere-mergebot request-review @janisz @br-lewis @drewvanstone

**Comment by chandlerh** [comment]
Approved.

**Pull request merged**
