### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Apr-20-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2723 - [1.11] Bump dcos-metrics
* #2725 - (1.11) gen: Generate config packages with new IDs after editing files under genconf/
* #2764 - [1.11] Upgrade OTP version
* #2780 - (1.11) Add retries for pkgpanda when downloading packages

### CODE REVIEW

**Comment by orsenthil** [comment]
Extended Test Suite - https://teamcity.mesosphere.io/viewLog.html?buildId=1047120&tab=buildResultsDiv&buildTypeId=DcOs_Open_ManualTriggers_TriggerTrainBuilds

**Comment by margaret** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
