### PR TITLE
Bumping metronome to 0.6.0 due to memory issue on Azure/ARM

### PR DESCRIPTION
**Pull request by pcrews**
## High-level description
A change to metronome service version as we suspect the current version is exhibiting a memory leak on Azure ARM tests.  Tests with the metronome version that is currently in master results in perfect tests while the current version produces consistent OOM errors on Azure.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-41675](https://jira.mesosphere.com/browse/DCOS-41675) Azure Out of memory: Java heap space Exception. Observed on Azure platform.

## Checklist for all PRs

  - [ x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: metronome version bump
  - [x ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Azure ARM tests on TC
  - [ x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/metronome/commit/ad0ca697e424d205e367d8e49d9db1d44399afec
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by pcrews** [comment]
WIP: Do not merge!!!

**Comment by kensipe** [comment]
This should be closed as https://github.com/dcos/dcos/pull/4114 supersedes it

**Comment by kensipe** [comment]
@pcrews will you close this please?

**Comment by kensipe** [comment]
@orsenthil can you close this?

**Pull request closed without merging**
