### PR TITLE
[1.9] Bump curl from 7.48 to 7.59

### PR DESCRIPTION
**Pull request by ahairape**
## High-level description

This PR bumps curl from 7.48 to 7.59.0 in DC/OS 1.9

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
https://jira.mesosphere.com/browse/DCOS-21557
https://jira.mesosphere.com/browse/DCOS_OSS-2367

## Checklist for all PRs

  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by ahairape** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by adamtheturtle** [comment]
@ahairape I believe that the description should (also?) link to https://jira.mesosphere.com/browse/DCOS_OSS-2367.

**Comment by ahairape** [comment]
Thanks, @adamtheturtle, updated the description to include https://jira.mesosphere.com/browse/DCOS_OSS-2367

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ship-it

**Pull request merged**
