### PR TITLE
Add marathon pods endpoint to diagnostic bundle

### PR DESCRIPTION
**Pull request by surdy**
## High-level description
/v2/pods endpoint is useful in debugging pods related issues, however its not collected as part of diagnostics bundle creation. This PR includes the endpoint in the bundle

What features does this change enable? What bugs does this change fix?
Collect /v2/pods marathon endpoint

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [COPS-3191](https://jira.mesosphere.com/browse/COPS-3191) Add /v2/pods endpoint to diagnostic bundle collection

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___

### CODE REVIEW

**Comment by mesosphere-mergebot2** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot merge-it  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Ship It |Work In Progress |Ready For Review |Request For Comment |Holding] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by surdy** [comment]
@mnaboka Please review. Also who else should I ping for review on this ?

**Comment by mnaboka** [comment]
@amitaekbote can you take a look at this PR

**Comment by mnaboka** [comment]
disregard my previous comment EE PR is here https://github.com/mesosphere/dcos-enterprise/pull/2706

**Comment by surdy** [comment]
@amitaekbote Need another review for this to make it in. Can you please have a look ?

**Comment by surdy** [comment]
I have also updated CHANGES.md and updated the branch . So @mnaboka your review got dismissed :(

**Comment by surdy** [comment]
Going to close this and merge it into #3148

**Pull request closed without merging**
