### PR TITLE
[master] Mergebot Automated Train PR - 2018-Aug-17-12-01

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3250 - Implement bootstrap methods for telegraf
* #3282 - test_vip: purge proxy app
* #3290 - bump marathon 1.7.81

### CODE REVIEW

**Comment by cprovencher** [comment]
added #3156

**Comment by orsenthil** [comment]
> added #3156

@cprovencher  - Thank you, good call.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
