### PR TITLE
Bump CoreOS, CentOS, Docker

### PR DESCRIPTION
**Pull request by lloesche**
## High Level Description

This is a cherry-pick of:
#1277 
#1258
#1279
#1306

### CODE REVIEW

**Comment by lloesche** [comment]
This isn't ready to be merged, the updated NAT GW AMIs aren't compatible with our current CF config it seems.

**Comment by spahl** [comment]
Let's cherry pick this in: https://github.com/dcos/dcos/pull/1306 (and rebase this on master to prevent conflicts

**Comment by amitaekbote** [comment]
@lloesche https://github.com/dcos/dcos/pull/1245 will take care of new regions and upgrade of cf templates

**Comment by lloesche** [comment]
@amitaekbote nice, though I ended up with 15 regions total. What did you have to change to get it to work with the 2016 NAT AMIs? Was it just a matter of changing the instance type to m4? I only updated the AMI with no changes to the CF template and got a ROLLBACK with a very unspecific `The requested configuration is currently not supported. Please check the documentation for supported configurations.`. Haven't looked further into it yet.

**Comment by spahl** [comment]
Rebase vs merging master in please

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
