### PR TITLE
adminrouter: modify access_log format (DCOS_OSS-4129)

### PR DESCRIPTION
**Pull request by jgehrcke**
## High-level description

See https://jira.mesosphere.com/browse/DCOS_OSS-4129

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

https://jira.mesosphere.com/browse/DCOS_OSS-4129

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm  https://jira.mesosphere.com/browse/DCOS-41677

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS-42044

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcos/windows https://jira.mesosphere.com/browse/DCOS-42046

**Comment by jongiddy** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41677

**Comment by jongiddy** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcos/windows https://jira.mesosphere.com/browse/DCOS-42046

**Comment by jongiddy** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS-42044

**Comment by jongiddy** [comment]
Are all these changelog additions meant to be in this PR?

**Comment by jgehrcke** [comment]
> Are all these changelog additions meant to be in this PR?

The current `CHANGES.md` state of the `master` branch is a mess. I try to bring a bit of structure into it.

My goal is to make the 1.12.0 release only have "what's new" and "breaking changes". It is meant to contain all the things of all the 1.11.x releases released prior to 1.12.0 just intuitively anyway. If the goal was to make it contain _all the things_ that are currently in the `CHANGES.md` in the `1.11` branch then it would contain too little. That is, currently there is no consistency at all, and this PR starts to address that.

Removals mean that a change is already out there, and documented, in a corresponding 1.11.x release.

Additions are not real additions, but situations where I moved something into "what's new" or "breaking changes".

**Pull request merged**
