### PR TITLE
Update fetch_cluster_logs.bash

### PR DESCRIPTION
**Pull request by cprovencher**

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@cprovencher  - This was not getting a ship-it because it was out of date. Updated this.

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
