### PR TITLE
Train 278 (1.10)

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 278 for the 1.10.3 release. It contains:

- #2178 (Bump DC/OS version to 1.10.3)

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Triggered the train-specific CI runs.

**Comment by jgehrcke** [comment]
Dang, `teamcity/dcos/test/azure/arm` / https://teamcity.mesosphere.io/viewLog.html?buildId=891211 failed as of Azure flakiness. Rerunning.

**Comment by jgehrcke** [comment]
The currently shown failure of `mergebot/enterprise/build-status/aggregate` does not make sense to me. All downstream CI runs are still in progress.

**Comment by jgehrcke** [comment]
Another failure in teamcity/dcos/test/azure/arm / https://teamcity.mesosphere.io/viewLog.html?buildId=891324. Rerunning.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot pr-status-checks

**Comment by jgehrcke** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
@mesosphere-mergebot pr-status-checks

**Comment by jgehrcke** [comment]
Holding until further notice.

**Comment by orsenthil** [comment]
I responded to the observed problem here: https://jira.mesosphere.com/browse/DCOS-19905 - we can move forward with this train. :-)

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
