### PR TITLE
Train 282 (base:1.9)

### PR DESCRIPTION
**Pull request by sschneid**
#2185 backport to 1.9 - Include LICENSE, NOTICE file in dcos-image

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm 
 https://jira.mesosphere.com/browse/DCOS_OSS-1830

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/upgrade  https://jira.mesosphere.com/browse/DCOS-19906

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
