### PR TITLE
Use cached repo for ZooKeeper

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

Use cached version of ZooKeeper, since original site has stopped hosting

## Corresponding DC/OS tickets (required)

  - [D2IQ-72462](https://jira.d2iq.com/browse/D2IQ-72462) Build DC/OS Uncached Master Failing on missing Zookeeper download

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @pierrebeitz @janisz

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required not visible to operation

**Review by DominikDary — APPROVED** [review]

**Comment by jongiddy** [comment]
@mesosphere-mergebot backport 2.1 2.0 1.13

**Pull request merged**
