### PR TITLE
[master] Mergebot Automated Train PR - 2018-Oct-23-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3516 - Remove dcos-metrics from all builds except Windows

> Also added

* #3687 - Update dcos-test-utils

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
