### PR TITLE
Bump Mesos version to include fix for MESOS-7546.

### PR DESCRIPTION
**Pull request by gkleiman**
## High Level Description

Updates Mesos to a branch based on 4faca73e9608664a5fcf46cc95951c318a64861f with 55e7ea5ed788acb0e4f810dd4575a5a4479520d1 cherry-picked. This version of Mesos contains support for the Mesos Master `--filter_gpu_resources` flag and a fix for MESOS-7546.

## Related Issues

  - [MESOS-7546](https://issues.apache.org/jira/browse/MESOS-7546) WAIT_NESTED_CONTAINER sometimes returns 404.

## Checklist for all PR's

  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: This PR relies upon Mesos test suite.
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Mesos diff](https://github.com/mesosphere/mesos/compare/9cc627d9f32d56f14f277e823a759183ef4b234d...1a99252362a73134dd3e028c69016f98a3735a8d)
  - [X] Test Results: [Mesosphere CI Jenkins build result](https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/Mesos_CI-build/1171/)
  - [ ] Code Coverage (if available):

### CODE REVIEW

**Comment by gkleiman** [comment]
@adam-mesos @karya0 @vinodkone @rukletsov PTAL

**Comment by gkleiman** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by gkleiman** [comment]
The following test failed: `test_upgrade_vpc.marathon_app_tasks_survive_upgrade`

[It's known to be flaky](https://jira.mesosphere.com/browse/DCOS_OSS-1065), so I've restarted the `integration-test/upgrade-onprem` job and applied the `Ready For Review` label.

**Comment by karya0** [comment]
Now that FB secrets have landed, we need to rebase and upgrade the description to only mention the particular bug fix that we are targeting.

**Comment by gkleiman** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
All checks have passed 😂

**Comment by karya0** [comment]
LGTM :shipit:

**Comment by vinodkone** [comment]
LGTM

**Comment by jgehrcke** [comment]
Is there a DC/OS JIRA ticket that needs to be updated now that this has landed?

**Comment by gkleiman** [comment]
@jgehrcke there's no DC/OS OSS JIRA ticket that needs to be updated. Thanks for merging this!

**Comment by jgehrcke** [comment]
> there's no DC/OS OSS JIRA ticket that needs to be updated

OK. Next time we better have one :-).

**Pull request merged**
