### PR TITLE
[1.12] Mergebot Automated Train PR - 2019-Dec-26-07-12

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #6700 - Unicom 1.12.5

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Holding

**Comment by jongiddy** [comment]
@cprovencher @orsenthil @cgawron1 I put this 1.12 train in Holding because the linked PR has the description "test. don't merge". Please fix the description of the PR to explain the changes, or close the PR and this train.

**Comment by cprovencher** [comment]
@jongiddy Forgot to change the description! Applying ship it now.

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
