### PR TITLE
Remove checklist from pull request template.

### PR DESCRIPTION
**Pull request by jeschkies**
## High-level description

The checklist is removed for the following reasons:

* They are hardly ever filled out by any developer.
* There is no added value. Do we track test coverage? Are we evaluating the data. I think not.

### CODE REVIEW

**Comment by jeschkies** [comment]
@mesosphere-mergebot request-review @DominikDary @orsenthil @janisz @jongiddy

**Comment by janisz** [comment]
@jeschkies can you rebase on master

**Comment by DominikDary** [comment]
@mesosphere-mergebot changelog-not-required tooling related pr

**Comment by DominikDary** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
