### PR TITLE
bump of marathon 1.5.1.1

### PR DESCRIPTION
**Pull request by kensipe**
## High Level Description

What features does this change enable? What bugs does this change fix? High-Level description of how things changed.

## Related Issues

- [MARATHON-7848](https://jira.mesosphere.com/browse/MARATHON-7848) Fixes regression in which underscores were no longer permitted in network names

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [changelog](https://github.com/mesosphere/marathon/compare/v1.5.1...v1.5.1.1)
  - [x] Test Results: [ci test](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/releases%252F1.5.1.1/3/)

### CODE REVIEW

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by lingmann** [comment]
`teamcity/dcos/test/upgrade-to-next-major` is not expected to succeed because 1.11 is not released yet, rather `teamcity/dcos/test/upgrade` (known in TC as "from stable minor version") is accomplishing the test of 1.10 to "master". cc: @mellenburg

**Comment by lingmann** [comment]
@mesosphere-mergebot merge-it

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
