### PR TITLE
[master] Mergebot Automated Train PR - 2018-Nov-16-15-18

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3525 - Admin Router: adding clarifications of limitations to Readme
* #3589 - Add external Mesos master/agent logs in the bundle
* #3688 - Fix template links for new docs layout
* #3741 - Adding required ending forwardslash to download_url
* #3742 - Bump cosmos to latest version
* #3757 - Update README example for running command to new DC/OS E2E CLI
* #3763 - bump ui version to 2.36.5

### CODE REVIEW

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by takirala** [comment]
@mesosphere-mergebot sync

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot sync

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
missing this PR #3767

**Comment by pcrews** [comment]
@mesosphere-mergebot sync

> missing this PR #3767

seen, working to fix.

**Comment by pcrews** [comment]
> missing this PR #3767

seen and working to fix.

**Comment by orsenthil** [comment]
@pcrews  : `PR creators can apply one of [Ready For Review |Work In Progress]. Owners can apply any label.`

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
