### PR TITLE
[1.11] Backport adamdangoor/xfailflake-date

### PR DESCRIPTION
**Pull request by adamtheturtle**
Backport of various changes which include:

* Add `since` and `jira` to `xfailflake` marker
* Update pytest (required for above)
* Change a few `xfailflake`s to the right JIRA issues

### CODE REVIEW

**Comment by adamtheturtle** [comment]
@mesosphere-mergebot bump-ee

**Comment by adamtheturtle** [comment]
@mesosphere-mergebot bump-ee

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS-18825

**Comment by rukletsov** [comment]
@mesosphere-mergebot merge-it

**Comment by rukletsov** [comment]
@mesosphere-mergebot label Ship It

**Comment by rukletsov** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
