### PR TITLE
[Mesos] Limit logrotate module libprocess worker threads to 2.

### PR DESCRIPTION
**Pull request by jmlvanre**
This change depends on https://reviews.apache.org/r/50766/

### CODE REVIEW

**Comment by adam-mesos** [comment]
Cherry-picked "Added flag in logrotate module to control number of libprocess threads." onto Mesos 1.0.1-rc1 in #539 so we can (rebase and) merge this in as soon as that lands.

**Comment by adam-mesos** [comment]
@jmlvanre Mesos 1.0.1-rc1 has been merged into dcos/dcos with your cherry-pick on top.
Please rebase.

**Comment by cmaloney** [comment]
:ship:

**Comment by adam-mesos** [comment]
@cmaloney @alberts @spahl Merge at will!

**Comment by cmaloney** [comment]
@adam-mesos Already pulled into Train 55 #566, should land today and go out in 1.8.2 Thursday or before

**Comment by adam-mesos** [comment]
Nice. It'd be great to comment on the PRs when they've been pulled into a train, with a link to the train PR.

**Comment by cmaloney** [comment]
In the Train we link to every pr which means Github injects a blob in all the PRs that are part of that train. Trains get fairly large sometimes, commenting on every one would make a lot of noise.

**Comment by adam-mesos** [comment]
Ok, maybe you could just add the PR #s to the train PR description, so that GH links the PRs together. From the following, it isn't clear to me what (if any) train it was merged into:
```
cmaloney added a commit to mesosphere/dcos that referenced this pull request 35 minutes ago
	@cmaloney 	Merge #483
```
Whereas your approach of linking the PRs in the train description generates the much more helpful:
```
cmaloney referenced this pull request 6 days ago
Train 53 #553 (also shows if that train PR was merged yet)
```
Sorry to be a bother this time. I just don't want to have to bother you for future PRs or search for possible train PRs to find out if I can stop worrying about my individual PRs.

**Comment by cmaloney** [comment]
The general rule there is "once you have a :ship: don't worry about it, things will be managed until they land. @orsenthil is building out tooling around all of it.

**Pull request merged**
