### PR TITLE
chore(dcos-ui): update package to v1.10.0-rc.6

### PR DESCRIPTION
**Pull request by orlandohohmeier**
## High Level Description

Update the DC/OS UI package to include the latest fixes and improvements.

## Related Issues

- [DCOS-17705](https://jira.dcos.io/browse/DCOS-17705)   remove duplicated fetch parser
- [DCOS_OSS-1569](https://jira.dcos.io/browse/DCOS_OSS-1569) adjust SDK action handling
- [DCOS-17979](https://jira.dcos.io/browse/DCOS-17979) remove "open service" buttons for SDK services
- [DCOS-17982](https://jira.dcos.io/browse/DCOS-17982) remove suspend/resume for SDK service

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-ui/compare/v1.10.0-rc.5...v1.10.0-rc.6)
  - [x] Test Results: [Unit and Integration Test Results](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/269/)
  - [x] Code Coverage (if available):  [Codecoverage](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/269/)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Holding]

**Comment by orlandohohmeier** [comment]
@nLight @Poltergeist could you please review this PR?

**Comment by orlandohohmeier** [comment]
ℹ️  I've put bump on hold until we’re sure that removing the open service links ([DCOS-17979](https://jira.mesosphere.com/browse/DCOS-17705)) is the desired behavior.

**Comment by MatApple** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
