### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Jun-26-10-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2975 - [1.10] Bump Mesos to nightly 1.4.x 04f4967
* #3002 - Increase timeout for package download
* #3017 - Added second EBS drive to agents and public agents (1.10 backport).

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Ship It |Holding |Work In Progress |Ready For Review |Request For Comment] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by adamtheturtle** [comment]
`teamcity/dcos/test/aws/onprem/static` - `test_networking.test_vip` fails with `AssertionError`.

I cannot find a JIRA for this.
@urbanserj or @jeschkies  perhaps, can you look at this and decide whether it is a flake, and if so, create a JIRA?

I ask you because you are active on https://jira.mesosphere.com/browse/DCOS_OSS-2115.
The most recent override on that issue seems to be incorrect, and the same as this error.

**Comment by jeschkies** [comment]
@adamtheturtle, sorry, I cannot say if this is the same. What does the error say exactly?

**Comment by adamtheturtle** [comment]
@jeschkies Build log at https://teamcity.mesosphere.io/viewLog.html?buildId=1118050&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackend

```
test_networking.py:76 (test_vip[Container.DOCKER-Network.HOST-Network.USER])
dcos_api_session = <dcos_test_utils.dcos_api.DcosApiSession object at 0x7fb3a6658e80>
container = <Container.DOCKER: 'DOCKER'>, vip_net = <Network.HOST: 'HOST'>
proxy_net = <Network.USER: 'USER'>

    @pytest.mark.slow
    @pytest.mark.skipif(
        not lb_enabled(),
        reason='Load Balancer disabled')
    @pytest.mark.parametrize(
        'container,vip_net,proxy_net',
        generate_vip_app_permutations())
    def test_vip(dcos_api_session,
                 container: marathon.Container,
                 vip_net: marathon.Network,
                 proxy_net: marathon.Network):
        '''Test VIPs between the following source and destination configurations:
            * containers: DOCKER, UCR and NONE
            * networks: USER, BRIDGE (docker only), HOST
            * agents: source and destnations on same agent or different agents
            * vips: named and unnamed vip
    
        Origin app will be deployed to the cluster with a VIP. Proxy app will be
        deployed either to the same host or elsewhere. Finally, a thread will be
        started on localhost (which should be a master) to submit a command to the
        proxy container that will ping the origin container VIP and then assert
        that the expected origin app UUID was returned
        '''
        errors = 0
>       tests = setup_vip_workload_tests(dcos_api_session, container, vip_net, proxy_net)

test_networking.py:101: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_networking.py:144: in setup_vip_workload_tests
    wait_for_tasks_healthy(dcos_api_session, origin_app)
../../lib/python3.5/site-packages/retrying.py:49: in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
../../lib/python3.5/site-packages/retrying.py:212: in call
    raise attempt.get()
../../lib/python3.5/site-packages/retrying.py:247: in get
    six.reraise(self.value[0], self.value[1], self.value[2])
../../lib/python3.5/site-packages/six.py:686: in reraise
    raise value
../../lib/python3.5/site-packages/retrying.py:200: in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dcos_api_session = <dcos_test_utils.dcos_api.DcosApiSession object at 0x7fb3a6658e80>
app_definition = {'acceptedResourceRoles': ['*', 'slave_public'], 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/...'type': 'DOCKER', 'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}]}, ...}

    @retrying.retry(wait_fixed=5000, stop_max_delay=20 * 60 * 1000)
    def wait_for_tasks_healthy(dcos_api_session, app_definition):
        info = dcos_api_session.marathon.get('v2/apps/{}'.format(app_definition['id'])).json()
>       assert info['app']['tasksHealthy'] == app_definition['instances']
E       assert 0 == 1

test_networking.py:174: AssertionError
------- Stderr: -------
[2018-07-05 03:52:21,957|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134

[2018-07-05 03:52:21,975|test_networking|INFO]: Starting apps :: VIP: /namedvip:10108, Hosts: ['10.10.0.148']
[2018-07-05 03:52:21,975|test_networking|INFO]: Origin app: {'id': 'integration-test-42b4c6c594084dd19175eddc9e797698', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'HOST', 'image': 'debian:jessie'}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py $PORT0', 'env': {'DCOS_TEST_UUID': '42b4c6c594084dd19175eddc9e797698', 'HOME': '/'}, 'portDefinitions': [{'port': 0, 'name': 'test', 'protocol': 'tcp', 'labels': {'VIP_0': '/namedvip:10108'}}], 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'portIndex': 0, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.148']], 'cpus': 0.1}
[2018-07-05 03:52:21,979|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,044|test_networking|INFO]: Proxy app: {'id': 'integration-test-3b56530affba49748cdd78b4e072832b', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'USER', 'image': 'debian:jessie', 'portMappings': [{'name': 'test', 'protocol': 'tcp', 'containerPort': 10109, 'hostPort': 10109}]}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py 10109', 'env': {'DCOS_TEST_UUID': '3b56530affba49748cdd78b4e072832b', 'HOME': '/'}, 'ipAddress': {'networkName': 'dcos'}, 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'port': 10109, 'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.148']], 'cpus': 0.1}
[2018-07-05 03:52:22,047|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,108|test_networking|INFO]: Starting apps :: VIP: /namedvip:10110, Hosts: ['10.10.0.214', '10.10.0.148']
[2018-07-05 03:52:22,109|test_networking|INFO]: Origin app: {'id': 'integration-test-da05b9ed1bbf401c8d7be91e248e9c89', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'HOST', 'image': 'debian:jessie'}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py $PORT0', 'env': {'DCOS_TEST_UUID': 'da05b9ed1bbf401c8d7be91e248e9c89', 'HOME': '/'}, 'portDefinitions': [{'port': 0, 'name': 'test', 'protocol': 'tcp', 'labels': {'VIP_0': '/namedvip:10110'}}], 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'portIndex': 0, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.148']], 'cpus': 0.1}
[2018-07-05 03:52:22,112|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,164|test_networking|INFO]: Proxy app: {'id': 'integration-test-1cc481c3056f4dca80b4bc8cb50555e6', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'USER', 'image': 'debian:jessie', 'portMappings': [{'name': 'test', 'protocol': 'tcp', 'containerPort': 10111, 'hostPort': 10111}]}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py 10111', 'env': {'DCOS_TEST_UUID': '1cc481c3056f4dca80b4bc8cb50555e6', 'HOME': '/'}, 'ipAddress': {'networkName': 'dcos'}, 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'port': 10111, 'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.214']], 'cpus': 0.1}
[2018-07-05 03:52:22,166|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,214|test_networking|INFO]: Starting apps :: VIP: 1.1.1.7:10112, Hosts: ['10.10.0.148']
[2018-07-05 03:52:22,214|test_networking|INFO]: Origin app: {'id': 'integration-test-0e023c3f3d1e4ab392ab12ee2c764547', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'HOST', 'image': 'debian:jessie'}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py $PORT0', 'env': {'DCOS_TEST_UUID': '0e023c3f3d1e4ab392ab12ee2c764547', 'HOME': '/'}, 'portDefinitions': [{'port': 0, 'name': 'test', 'protocol': 'tcp', 'labels': {'VIP_0': '1.1.1.7:10112'}}], 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'portIndex': 0, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.148']], 'cpus': 0.1}
[2018-07-05 03:52:22,217|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,263|test_networking|INFO]: Proxy app: {'id': 'integration-test-629a17110546459eba1611b722785048', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'USER', 'image': 'debian:jessie', 'portMappings': [{'name': 'test', 'protocol': 'tcp', 'containerPort': 10113, 'hostPort': 10113}]}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py 10113', 'env': {'DCOS_TEST_UUID': '629a17110546459eba1611b722785048', 'HOME': '/'}, 'ipAddress': {'networkName': 'dcos'}, 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'port': 10113, 'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.148']], 'cpus': 0.1}
[2018-07-05 03:52:22,266|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,299|test_networking|INFO]: Starting apps :: VIP: 1.1.1.7:10114, Hosts: ['10.10.0.214', '10.10.0.148']
[2018-07-05 03:52:22,299|test_networking|INFO]: Origin app: {'id': 'integration-test-92b4b725e401415bbb1bec3f1f498918', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'HOST', 'image': 'debian:jessie'}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py $PORT0', 'env': {'DCOS_TEST_UUID': '92b4b725e401415bbb1bec3f1f498918', 'HOME': '/'}, 'portDefinitions': [{'port': 0, 'name': 'test', 'protocol': 'tcp', 'labels': {'VIP_0': '1.1.1.7:10114'}}], 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'portIndex': 0, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.148']], 'cpus': 0.1}
[2018-07-05 03:52:22,303|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,327|test_networking|INFO]: Proxy app: {'id': 'integration-test-0308b1af8c3e4868a2aad3c2ab5ed989', 'instances': 1, 'container': {'volumes': [{'containerPath': '/opt/mesosphere', 'hostPath': '/opt/mesosphere', 'mode': 'RO'}], 'type': 'DOCKER', 'docker': {'network': 'USER', 'image': 'debian:jessie', 'portMappings': [{'name': 'test', 'protocol': 'tcp', 'containerPort': 10115, 'hostPort': 10115}]}}, 'cmd': '/opt/mesosphere/bin/dcos-shell python /opt/mesosphere/active/dcos-integration-test/util/python_test_server.py 10115', 'env': {'DCOS_TEST_UUID': '0308b1af8c3e4868a2aad3c2ab5ed989', 'HOME': '/'}, 'ipAddress': {'networkName': 'dcos'}, 'acceptedResourceRoles': ['*', 'slave_public'], 'healthChecks': [{'port': 10115, 'path': '/ping', 'gracePeriodSeconds': 5, 'maxConsecutiveFailures': 120, 'protocol': 'MESOS_HTTP', 'intervalSeconds': 10, 'timeoutSeconds': 10}], 'mem': 32, 'constraints': [['hostname', 'CLUSTER', '10.10.0.214']], 'cpus': 0.1}
[2018-07-05 03:52:22,330|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:22,369|test_networking|INFO]: Deploying apps :: VIP: /namedvip:10108, Hosts: ['10.10.0.148']
[2018-07-05 03:52:22,369|test_networking|INFO]: Deploying origin app: integration-test-42b4c6c594084dd19175eddc9e797698
[2018-07-05 03:52:22,372|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:27,384|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:32,396|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:37,405|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:42,415|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:47,425|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:47,432|test_networking|INFO]: Deploying proxy app: integration-test-3b56530affba49748cdd78b4e072832b
[2018-07-05 03:52:47,434|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:47,438|test_networking|INFO]: Apps are ready
[2018-07-05 03:52:47,439|test_networking|INFO]: Deploying apps :: VIP: /namedvip:10110, Hosts: ['10.10.0.214', '10.10.0.148']
[2018-07-05 03:52:47,439|test_networking|INFO]: Deploying origin app: integration-test-da05b9ed1bbf401c8d7be91e248e9c89
[2018-07-05 03:52:47,441|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:47,448|test_networking|INFO]: Deploying proxy app: integration-test-1cc481c3056f4dca80b4bc8cb50555e6
[2018-07-05 03:52:47,450|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:47,461|test_networking|INFO]: Apps are ready
[2018-07-05 03:52:47,462|test_networking|INFO]: Deploying apps :: VIP: 1.1.1.7:10112, Hosts: ['10.10.0.148']
[2018-07-05 03:52:47,462|test_networking|INFO]: Deploying origin app: integration-test-0e023c3f3d1e4ab392ab12ee2c764547
[2018-07-05 03:52:47,464|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:52,476|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:52:57,488|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:02,503|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:07,514|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:12,524|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:17,545|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:22,554|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:27,565|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:32,577|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:37,590|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:42,604|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:47,616|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:52,630|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:53:57,642|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:54:02,656|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:54:07,667|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
[2018-07-05 03:54:12,681|requests.packages.urllib3.connectionpool|INFO]: Starting new HTTP connection (1): 10.10.0.134
...
```

**Comment by jeschkies** [comment]
@adamtheturtle, the flake is reported as the app being stuck in deployment. At least that's how I understand the error. This seems like a different issue.

**Comment by adamtheturtle** [comment]
@jeschkies Thank you - that's what I think too.
The question now is what to do with this PR.

We can:
* Work on the assumption that this is a newly discovered, unrelated issue, and make a JIRA.
* Investigate this a potential new error and block this PR on it.

Do you have any thoughts on that @jeschkies ?

**Comment by jeschkies** [comment]
> Do you have any thoughts on that @jeschkies ?

Hehe, well, I'm the strict one on flaky tests and say that nothing merges if it is red. No overrides, no ignores. How about retriggering the test?

**Comment by jgehrcke** [comment]
We do have a new mixed load test going on soon and want these changes in. Who invests time into inspecting the test failures?

**Comment by jgehrcke** [comment]
> @adamtheturtle, the flake is reported as the app being stuck in deployment. At least that's how I understand the error. 

Is any of the changes contained in this PR likely to cause this error? (The Mesos bump?)

**Comment by adamtheturtle** [comment]
>  How about retriggering the test?

@jeschkies I'm not sure what that achieves.

If it passes, we know it is "flaky" but we do not know if this PR contributes to that flakiness.
If it fails, we do not know if it is flaky or just broken.
I'd like someone with knowledge of `test_networking.test_vip[Container_DOCKER-Network_HOST-Network_USER]` to look at this which is why I pinged you and @urbanserj .

**Comment by adamtheturtle** [comment]
@jgehrcke That is what I referred to in:

```
I ask you because you are active on https://jira.mesosphere.com/browse/DCOS_OSS-2115.
The most recent override on that issue seems to be incorrect, and the same as this error.
```

**Comment by adamtheturtle** [comment]
That this error has been seen before does not tell us that this PR does not make that error more likely, and I do not have the knowledge to rule out that possibility. We at this point need to:

* Get someone who does know about this topic to contribute here
* Ignore the possibility that this PR makes the error more likely and just merge anyways

Either way we really should have an issue about the `assert 0 == 1` error in JIRA.

**Comment by jgehrcke** [comment]
> @jeschkies I'm not sure what that achieves.

It would _most likely_ have shown us that this _is_ a flake. Now, as of time pressure, I bluntly assume that this is a flake, which is worse.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-3747

**Comment by jgehrcke** [comment]
> @mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-3747

Adding to that: all test_vip passed in https://teamcity.mesosphere.io/viewLog.html?buildId=1117995, i.e. in `
teamcity/dcos/test/aws/cloudformation/simple`. I think that basically proves that classification as `flake` is correct.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot pr-status-checks

**Comment by adamtheturtle** [comment]
That makes it look like the option:

> If it passes, we know it is "flaky" but we do not know if this PR contributes to that flakiness.

Is the one we have.
We ideally will not be ignoring flake occurrences without first giving some informed opinion that a failure is unrelated to the PR in question.

**Comment by jgehrcke** [comment]
> We ideally will not be ignoring flake occurrences without first giving some informed opinion that a failure is unrelated to the PR in question.

I do not disagree. But after two weeks of failing to do so there is a trade-off to be found.

**Comment by jgehrcke** [comment]
`mergebot/enterprise/build-status/aggregate` is red although downstream is completely green. Created https://jira.mesosphere.com/browse/DCOS-39073 for tracking that.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status mergebot/enterprise/build-status/aggregate https://jira.mesosphere.com/browse/DCOS-39073

**Comment by jgehrcke** [comment]
@mergebot-bot ship-it-label-status-check

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
> @mesosphere-mergebot override-status mergebot/enterprise/build-status/aggregate https://jira.mesosphere.com/browse/DCOS-39073

Mergebot would not like to see that. He or she is a machine, fortunately.

**Comment by orsenthil** [comment]
@jgehrcke  - it is funny to use mergebot to override mergebot's behavior. 

There is alternate to resolve this 2 repo synchronization problem. Retrigger a test that publishes the status check again on the sender's side (EE).  Until the bug with synchronization is fixed, using overides with mergebot is fine.

**Pull request merged**
