### PR TITLE
Train 155

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

* #1439 - Python Style Guide for DC/OS.
* #1463 - pkgpanda-api: don't use systemd socket - (The corresponding enterprise bump changes are merged in from https://github.com/mesosphere/dcos-enterprise/pull/822)

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@lingmann , @spahl , @gpaul  - this is ready for review and merging.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by lingmann** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
