### PR TITLE
Add information about deprecation DC/OS

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

Add information about deprecation DC/OS

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-51011](https://jira.mesosphere.com/browse/DCOS-51011)

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review
:wave: @drewvanstone @br-lewis @makkes  Can you review, please?

**Comment by jgehrcke** [comment]
As I argued before (elsewhere) I think we can just remove this service, applying some structured thinking around private and public interface: this service can be looked at as an implementation detail of a UI feature (connected via a private interface). That UI feature (which is the public interface to users) was removed, and so that very implementation detail can also be removed.

What do I miss; why do we think we need to keep the service around?

High level point of view: what we do here seems like a measure of precaution, which I honor, but I'd like us to approach this more systematically, so that we can iterate faster and focus our energy on deprecation cycles that we actually need :-).

**Comment by makkes** [comment]
> As I argued before (elsewhere) I think we can just remove this service, applying some structured thinking around private and public interfaces: this service can be looked at as an implementation detail of a UI feature (connected via a private interface). That UI feature (which is the public interface to users) was removed, and so that very implementation detail can also be removed.
> 
> What do I miss; why do we think we need to keep the service around? Did we identify unexpected consumers that we cannot break yet?
> 
> High level point of view: what we do here seems like a measure of precaution, which I honor, but I'd like us to approach this more systematically, so that we can iterate faster and focus our energy on deprecation cycles that we actually need :-).

Thanks @jgehrcke for your valuable input. I think the reason for deprecating it before removal is that we just applied our standard deprecation policy to it and honestly no one on the team is 100% sure that this service is not used by any customer. So we're riding the safe road here. If anyone could assure us that the standard deprecation policy doesn't have to be applied here we'd be more than happy to shortcut our way to getting rid of dcos-history.

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@jgehrcke At least one user is dcos-diagnostic https://github.com/dcos/dcos-diagnostics/blob/1389e1499b0790a9bdf041514fe173a395a4b7b8/dcos/finder.go#L28

**Comment by jgehrcke** [comment]
> If anyone could assure us that the standard deprecation policy doesn't have to be applied here we'd be more than happy to shortcut our way to getting rid of dcos-history.

I'd be happy to take the responsibility for that; this is what I was trying to say.

The major conceptual argument is that this is an implementation detail where a deprecation policy built for a public interface does not apply.

The most important practical argument is that it is _extremely_ unlikely for external tooling to consume the history service API. The information it provides is pretty much useless for consumers except for our UI.

"Not knowing with 100 % certainty" of course always implies a risk, and I am rarely willing to take it. Here, however, I am convinced that it's the right thing to do.

Let's talk about the very unlikely event of an external dependency:

1) In the unlikely event that anyone out there depends on the history service API: once we remove it we will most likely surprise them -- the deprecation notice will _most likely_ not prevent that surprise from happening.
2) Based on (1) the major reason to do the deprecation is to, in the event of the surprise, be able to say "but we properly deprecated it!", preventing embarrassment from happening. 
3) A similar diplomatic advantage can be achieved by saying "but you consumed an implementation detail, probably accidentally, sorry for the hassle", also preventing embarrassment from happening. 

So, what arguments do we have for removing the history service? Getting rid of maintenance burden (see e.g. COPS-4652). The earlier we simplify the less work we have in the future.

**Comment by makkes** [comment]
Ok, if we want to got for just removing dcos-history service, I'd be happy to do so. Let's do it! First, though, we should at least talk once to Ernest and/or Seth from Product about this because there's a whole bunch of tickets in Jira referring dcos-history service decommisioning, removing dependencies and so forth. If they agree and we get rid of all the Caps/Features in JIRA we can go for it.

**Pull request merged**
