### PR TITLE
Train 152

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

* #1434  - Ignore task failures for viplisten in upgrade test 
* #1436 - Add ConnectionError retrying Mixin 
* #1440  - more useful parameter help

### CODE REVIEW

**Comment by orsenthil** [comment]
There was one failure/ flake in

[deploy-vpi-cli] (https://teamcity.mesosphere.io/viewLog.html?buildId=613779&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssCcmIntegration_2)

```
[17:34:13]	====> END OF SUMMARY FOR install_dcos
[17:34:13]	Traceback (most recent call last):
[17:34:13]	  File "/teamcity/work/267d73d0adfa84a6/env/bin/ccm-deploy-test", line 11, in <module>
[17:34:13]	    sys.exit(main())
[17:34:13]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/test_aws_vpc.py", line 207, in main
[17:34:13]	    install_prereqs_only=options.test_install_prereqs_only,
[17:34:13]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/cluster.py", line 286, in install_dcos
[17:34:13]	    installer.deploy()
[17:34:13]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/installer_api_test.py", line 332, in deploy
[17:34:13]	    self.run_cli_cmd('--deploy', expect_errors=expect_errors)
[17:34:13]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/installer_api_test.py", line 253, in run_cli_cmd
[17:34:13]	    output = self.tunnel.remote_cmd(cmd, timeout=MAX_STAGE_TIME)
[17:34:13]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/ssh/tunnel.py", line 41, in remote_cmd
[17:34:13]	    return check_output(run_cmd, timeout=timeout)
[17:34:13]	  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
[17:34:13]	    **kwargs).stdout
[17:34:13]	  File "/usr/lib/python3.5/subprocess.py", line 708, in run
[17:34:13]	    output=stdout, stderr=stderr)
[17:34:13]	subprocess.CalledProcessError: Command '['/usr/bin/ssh', '-oConnectTimeout=10', '-oControlMaster=auto', '-oControlPath=/teamcity/temp/buildTmp/tmpvcza1xus/control_socket', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p', '22', 'centos@52.58.155.166', 'bash', '/home/centos/dcos_generate_config.sh', '--deploy']' returned non-zero exit status 1

```

Another one in [deploy-vpi-api](https://teamcity.mesosphere.io/viewLog.html?buildId=613777&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssCcmInstallTestAp)

```
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/installer_api_test.py", line 166, in postflight
[17:49:17]	    self.do_and_check('postflight', expect_errors)
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/installer_api_test.py", line 175, in do_and_check
[17:49:17]	    wait=30000, stop_max_delay=MAX_STAGE_TIME * 1000)
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/installer_api_test.py", line 203, in wait_for_check_action
[17:49:17]	    host_data = wait_for_finish()
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/retrying.py", line 49, in wrapped_f
[17:49:17]	    return Retrying(*dargs, **dkw).call(f, *args, **kw)
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/retrying.py", line 212, in call
[17:49:17]	    raise attempt.get()
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/retrying.py", line 247, in get
[17:49:17]	    six.reraise(self.value[0], self.value[1], self.value[2])
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/six.py", line 686, in reraise
[17:49:17]	    raise value
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/retrying.py", line 200, in call
[17:49:17]	    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
[17:49:17]	  File "/teamcity/work/267d73d0adfa84a6/env/lib/python3.5/site-packages/test_util/installer_api_test.py", line 200, in wait_for_finish
[17:49:17]	    assert finished_run, 'Action timed out! Last output: {}'.format(output)
[17:49:17]	AssertionError: Action timed out! Last output: {'total_hosts': 4, 'chain_name': 'postflight', 'total_masters': 1, 'hosts': {'10.10.0.119:22': {'host_status': 'success', 'commands': [{'stderr': ['', 'Connection to 10.10.0.119 closed.', '', ''], 'returncode': 0, 'stage': 'Creating temp directory', 'date': '2017-04-08 00:34:11.392442', 'stdout': [''], 'cmd': ['/usr/bin/ssh', '-oConnectTimeout=10', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p22', '-i', 'genconf/ssh_key', '-tt', 'centos@10.10.0.119', 'sudo', 'mkdir', '-p', '/opt/dcos_install_tmp'], 'pid': 993}, {'stderr': ['', 'Connection to 10.10.0.119 closed.', '', ''], 'returncode': 0, 'stage': 'Ensuring centos owns temporary directory', 'date': '2017-04-08 00:34:11.698706', 'stdout': [''], 'cmd': ['/usr/bin/ssh', '-oConnectTimeout=10', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p22', '-i', 'genconf/ssh_key', '-tt', 'centos@10.10.0.119', 'sudo', 'chown', 'centos', '/opt/dcos_install_tmp'], 'pid': 999}, {'stderr': ['', 'Connection to 10.10.0.119 closed.', '', ''], 'returncode': 0, 'stage': 'Executing post-flight check', 'date': '2017-04-08 00:34:12.078188', 'stdout': ['time="2017-04-08T00:34:12Z" level=info msg="/opt/mesosphere/etc/endpoints_config.json not found" \r', ''], 'cmd': ['/usr/bin/ssh', '-oConnectTimeout=10', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p22', '-i', 'genconf/ssh_key', '-tt', 'centos@10.10.0.119', "\n#!/usr/bin/env bash\n# Run the DC/OS diagnostic script for up to 15 minutes (900 seconds) to ensure\n# we do not return ERROR on a cluster that hasn't fully achieved quorum.\nT=900\nuntil OUT=$(sudo /opt/mesosphere/bin/./3dt -diag) || [[ T -eq 0 ]]; do\n    sleep 1\n    let T=T-1\ndone\nRETCODE=$?\nfor value in $OUT; do\n    echo $value\ndone\nexit $RETCODE"], 'pid': 1003}, {'stderr': ['', 'Connection to 10.10.0.119 closed.', '', '...le=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p22', '-i', 'genconf/ssh_key', '-tt', 'centos@10.10.0.87', 'sudo', 'mkdir', '-p', '/opt/dcos_install_tmp'], 'pid': 994}, {'stderr': ['', 'Connection to 10.10.0.87 closed.', '', ''], 'returncode': 0, 'stage': 'Ensuring centos owns temporary directory', 'date': '2017-04-08 00:34:11.678984', 'stdout': [''], 'cmd': ['/usr/bin/ssh', '-oConnectTimeout=10', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p22', '-i', 'genconf/ssh_key', '-tt', 'centos@10.10.0.87', 'sudo', 'chown', 'centos', '/opt/dcos_install_tmp'], 'pid': 996}, {'stderr': ['', 'Connection to 10.10.0.87 closed.', '', ''], 'returncode': 0, 'stage': 'Executing post-flight check', 'date': '2017-04-08 00:34:12.053120', 'stdout': ['time="2017-04-08T00:34:11Z" level=info msg="/opt/mesosphere/etc/endpoints_config.json not found" \r', ''], 'cmd': ['/usr/bin/ssh', '-oConnectTimeout=10', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p22', '-i', 'genconf/ssh_key', '-tt', 'centos@10.10.0.87', "\n#!/usr/bin/env bash\n# Run the DC/OS diagnostic script for up to 15 minutes (900 seconds) to ensure\n# we do not return ERROR on a cluster that hasn't fully achieved quorum.\nT=900\nuntil OUT=$(sudo /opt/mesosphere/bin/./3dt -diag) || [[ T -eq 0 ]]; do\n    sleep 1\n    let T=T-1\ndone\nRETCODE=$?\nfor value in $OUT; do\n    echo $value\ndone\nexit $RETCODE"], 'pid': 1000}, {'stderr': ['', 'Connection to 10.10.0.87 closed.', '', ''], 'returncode': 0, 'stage': 'Cleaning up temporary directory', 'date': '2017-04-08 00:34:12.362665', 'stdout': [''], 'cmd': ['/usr/bin/ssh', '-oConnectTimeout=10', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p22', '-i', 'genconf/ssh_key', '-tt', 'centos@10.10.0.87', 'sudo', 'rm', '-rf', '/opt/dcos_install_tmp'], 'pid': 1005}], 'tags': {'role': 'agent'}}}, 'total_agents': 3}
[17:49:17]	Process exited with code 1
```

**Comment by orsenthil** [comment]
@lingmann , @spahl  this is ready for review and merge.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review.

**Comment by lingmann** [comment]
@falseperfection and @orsenthil can you review #1440 and this train per @branden's comment above?

**Comment by orsenthil** [comment]
@lingmann  - done.
@branden  - the latest commit is included in this train.

**Comment by falseperfection** [comment]
@lingmann - #1440 looks good. i'm following up in slack about the correct way to handle squashing commits in the future.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
