### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Dec-19-19-30

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #4013 - [1.10] Backport adamdangoor/xfailflake-date

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label work in progress

**Comment by rukletsov** [comment]
@mesosphere-mergebot label Ship It

**Comment by rukletsov** [comment]
This looks strange: mergebot removed "Ship It!" right after adding it?

**Comment by rukletsov** [comment]
@mesosphere-mergebot label work in progress

**Comment by janisz** [comment]
@mesosphere-mergebot help

**Comment by janisz** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
