### PR TITLE
Bump dcos-ui package

### PR DESCRIPTION
**Pull request by rcorral**
## High Level Description

Bug fixes for 1.9

## Related Issues

 - [DCOS-12872](https://jira.mesosphere.com/browse/DCOS-12872)
 - [DCOS-12416](https://jira.mesosphere.com/browse/DCOS-12416)
 - [DCOS-13017](https://jira.mesosphere.com/browse/DCOS-13017)
 - [DCOS-13340](https://jira.mesosphere.com/browse/DCOS-13340)
 - [DCOS-11968](https://jira.mesosphere.com/browse/DCOS-11968)
 - [DCOS-12608](https://jira.mesosphere.com/browse/DCOS-12608)
 - [DCOS-13773](https://jira.mesosphere.com/browse/DCOS-13773)
 - [DCOS-13362](https://jira.mesosphere.com/browse/DCOS-13362)
 - [DCOS-12890](https://jira.mesosphere.com/browse/DCOS-12890)
 - [DCOS-12589](https://jira.mesosphere.com/browse/DCOS-12589)
 - [DCOS-13661](https://jira.mesosphere.com/browse/DCOS-13661)
 - [DCOS-13579](https://jira.mesosphere.com/browse/DCOS-13579)
 - [DCOS-13519](https://jira.mesosphere.com/browse/DCOS-13519)
 - [DCOS-13709](https://jira.mesosphere.com/browse/DCOS-13709)
 - [DCOS-13707](https://jira.mesosphere.com/browse/DCOS-13707)
 - [DCOS-12247](https://jira.mesosphere.com/browse/DCOS-12247)
 - [DCOS-13660](https://jira.mesosphere.com/browse/DCOS-13660)
 - [DCOS-12399](https://jira.mesosphere.com/browse/DCOS-12399)
 - [DCOS-12567](https://jira.mesosphere.com/browse/DCOS-12567)
 - [DCOS-13586](https://jira.mesosphere.com/browse/DCOS-13586)
 - [DCOS-13439](https://jira.mesosphere.com/browse/DCOS-13439)
 - [DCOS-13585](https://jira.mesosphere.com/browse/DCOS-13585)

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-ui/compare/0a1ccbb96b8b123bcbf5b665954a59184c668745...ba2c05ecf0b47583ad808347300e1bf2ff6fe1fc)
  - [ ] Test Results: [unit](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-ui-pulls/7013/), [integration](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-ui-pulls-integration/3849/)
  - [ ] Code Coverage (if available): [link to code coverage report]

@MatApple & @orlandohohmeier could you please review?

### CODE REVIEW

**Comment by MatApple** [comment]
shit it!

**Comment by lingmann** [comment]
@MatApple can you please add your review using the github reviews feature? makes it a bit easier for us to see the "shit-its" ;-)

**Comment by spahl** [comment]
@MatApple ping;-)

**Comment by MatApple** [comment]
@spahl @lingmann I don't have permissions to add my review, hence the comment :)

**Pull request merged**
