### PR TITLE
[1.8.9] Train 162

### PR DESCRIPTION
**Pull request by adam-mesos**
Train 162 for 1.8.9 :steam_locomotive: 
Includes:
#1453 Bump networking components
#1532 Make AdminRouter route to history-service backend, conditionally

### CODE REVIEW

**Comment by jgehrcke** [comment]
This looks good, but I have do not have enough experience with the failed upgrade test to understand if it is "just" flaky or actually negatively affected by the patch in this PR.

Broken test log (`integration-test/upgrade-onprem`): https://teamcity.mesosphere.io/viewLog.html?buildId=651418&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssUpgradeTestOnPre&tab=buildLog

**Comment by GoelDeepak** [comment]
@jgehrcke The default upgrade test tries to upgrade from stable to PR. Since stable is 1.9.0 the default upgrade test will always fail for 1.8.9. You need to change the parameter in upgrade test to 1.8.8

**Comment by jgehrcke** [comment]
> You need to change the parameter in upgrade test to 1.8.8

How is that done?

**Comment by amitaekbote** [comment]
@jgehrcke for reference - https://github.com/dcos/dcos/pull/1532

I updated the upgrade test with correct params in that pr

**Comment by jgehrcke** [comment]
@GoelDeepak and @nlsun can you please have a look at the new upgrade failure? It seems to be networking component related.

**Comment by nlsun** [comment]
@jgehrcke seems like timeout problems, just re-run them, some tests should just have longer timeouts

**Pull request merged**
