### PR TITLE
pkgpanda/build: hash build script contents

### PR DESCRIPTION
**Pull request by gpaul**
## High-level description

What features does this change enable? What bugs does this change fix?

This PR fixes a regression introduced in https://github.com/dcos/dcos/pull/2445 where the package build script contents are no longer considered as part of the package hash for purposes of reusing cached artifacts.

I ran the tests manually as they are not run by CI as of today:

```
[gustav@gpaul-dell dcos]$ tox -e py35-pkgpanda-build
GLOB sdist-make: /home/gustav/repos/dcos/dcos/setup.py
py35-pkgpanda-build inst-nodeps: /home/gustav/repos/dcos/dcos/.tox/dist/dcos_image-0.1.zip
py35-pkgpanda-build installed: adal==0.4.7,aiohttp==0.22.5,analytics-python==1.2.9,asn1crypto==0.24.0,attrs==17.4.0,azure-common==1.1.4,azure-mgmt-network==0.30.0rc4,azure-mgmt-nspkg==2.0.0,azure-mgmt-resource==0.30.0rc4,azure-nspkg==2.0.0,azure-storage==0.32.0,boto3==1.7.4,botocore==1.10.4,certifi==2018.4.16,cffi==1.11.5,chardet==3.0.4,checksumdir==1.1.4,click==6.7,coloredlogs==9.0,cryptography==2.2.2,dcos-image==0.1,docopt==0.6.2,docutils==0.14,Flask==0.12.2,Flask-Compress==1.4.0,humanfriendly==4.10,idna==2.6,isodate==0.6.0,itsdangerous==0.24,Jinja2==2.10,jmespath==0.9.3,keyring==9.1,MarkupSafe==1.0,msrest==0.4.17,msrestazure==0.4.15,multidict==1.2.2,oauthlib==2.0.7,passlib==1.7.1,pluggy==0.6.0,py==1.5.3,pycparser==2.18,PyJWT==1.6.1,pytest==3.3.2,python-dateutil==2.6.1,PyYAML==3.12,requests==2.18.4,requests-oauthlib==0.8.0,retrying==1.3.3,s3transfer==0.1.13,schema==0.6.7,six==1.11.0,teamcity-messages==1.21,urllib3==1.22,Werkzeug==0.14.1
py35-pkgpanda-build runtests: PYTHONHASHSEED='2190284331'
py35-pkgpanda-build runtests: commands[0] | pytest --basetemp=/home/gustav/repos/dcos/dcos/.tox/py35-pkgpanda-build/tmp build_integration_test.py
================================================================================================================================================================ test session starts =================================================================================================================================================================
platform linux -- Python 3.5.2, pytest-3.3.2, py-1.5.3, pluggy-0.6.0 -- /home/gustav/repos/dcos/dcos/.tox/py35-pkgpanda-build/bin/python3.5
cachedir: ../../../.cache
rootdir: /home/gustav/repos/dcos/dcos, inifile: tox.ini
plugins: teamcity-messages-1.21
collected 10 items                                                                                                                                                                                                                                                                                                                                   

build_integration_test.py::test_build PASSED                                                                                                                                                                                                                                                                                                   [ 10%]
build_integration_test.py::test_build_bad_sha1 PASSED                                                                                                                                                                                                                                                                                          [ 20%]
build_integration_test.py::test_hash_build_script PASSED                                                                                                                                                                                                                                                                                       [ 30%]
build_integration_test.py::test_url_extract_tar PASSED                                                                                                                                                                                                                                                                                         [ 40%]
build_integration_test.py::test_url_extract_zip PASSED                                                                                                                                                                                                                                                                                         [ 50%]
build_integration_test.py::test_single_source_with_extra PASSED                                                                                                                                                                                                                                                                                [ 60%]
build_integration_test.py::test_bad_buildinfo PASSED                                                                                                                                                                                                                                                                                           [ 70%]
build_integration_test.py::test_restricted_services PASSED                                                                                                                                                                                                                                                                                     [ 80%]
build_integration_test.py::test_single_source_corrupt PASSED                                                                                                                                                                                                                                                                                   [ 90%]
build_integration_test.py::test_bootstrap PASSED                                                                                                                                                                                                                                                                                               [100%]

============================================================================================================================================================= 10 passed in 65.15 seconds =============================================================================================================================================================
______________________________________________________________________________________________________________________________________________________________________ summary _______________________________________________________________________________________________________________________________________________________________________
  py35-pkgpanda-build: commands succeeded
  congratulations :)

```

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-2385](https://jira.mesosphere.com/browse/DCOS_OSS-2385) pkgpanda: build script not hashed
  - [DCOS-22173](https://jira.mesosphere.com/browse/DCOS-22173) pkgpanda: changes to ee.build file ignored

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.


## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: The changes.md file isn't ready yet.
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)


## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___

### CODE REVIEW

**Comment by gpaul** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by gpaul** [comment]
@klueska @orsenthil @jgehrcke PTAL

**Comment by jgehrcke** [comment]
Nice, this triggered a number of package builds so that the overall build step took more than 1 hour.

Thanks, Gustav!

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke DCOS_OSS-1546

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke DCOS_OSS-1546

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1546

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1546

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1546

**Comment by gpaul** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
> I ran the tests manually as they are not run by CI as of today

If it is not already done, I think, this should be included as part of `teamcity/dcos/build/tox ` in CI. (I can enable this).

**Comment by gpaul** [comment]
> If it is not already done, I think, this should be included as part of teamcity/dcos/build/tox in CI. (I can enable this).

Agreed! I ran them manually and they took maybe a minute.

**Comment by jgehrcke** [comment]
> If it is not already done, I think, this should be included as part of teamcity/dcos/build/tox in CI. (I can enable this).

Super cool, @orsenthil -- if you enable this, please also leave a note in https://jira.mesosphere.com/browse/DCOS-22186 (I created this today to keep track of some test suites which we have, but which we do not execute as part of the DC/OS CI).

**Comment by gpaul** [comment]
Cool! Thanks for the speedy reviews - this PR isn't even a day old and already has a Ship It label

**Pull request merged**
