### PR TITLE
[1.10] Merge dependent tests into one big scenario

### PR DESCRIPTION
**Pull request by janisz**
### Backpots: #3438

Currently, we have 4 tests that depend on creating a bundle test. This commit merges them into one big integration test simulation basic use case for diagnostics bundles. This means we will create, check status, download and delete the bundle in a single test. This should prevent tests from failing because due to order.

This commit also rearrange entries in `tests_dcos_diagnostics.py`. All tests are at the top and helper functions were moved to the bottom. This makes code clear and easier to read.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4115](https://jira.mesosphere.com/browse/DCOS_OSS-4115) 

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by philipnrmn** [comment]
Looks like we have a genuine test failure here.

**Comment by janisz** [comment]
It looks like history service is broken or cluster does not start properly

```
E                   AssertionError: summaryErrorsReport.txt must be empty. Got 2018-10-23 13:12:21.943090053 +0000 UTC [could not fetch url: http://172.17.0.2:15055/history/minute] 172.17.0.2 master Get http://172.17.0.2:15055/history/minute: dial tcp 172.17.0.2:15055: getsockopt: connection refused
E                   2018-10-23 13:12:22.643367429 +0000 UTC [wrong status code returned] 172.17.0.2 master unable to fetch http://172.17.0.2:8080/v2/eventSubscriptions. Return code 404
E                   2018-10-23 13:12:22.739974378 +0000 UTC [could not fetch url: http://172.17.0.2:15055/history/hour] 172.17.0.2 master Get http://172.17.0.2:15055/history/hour: dial tcp 172.17.0.2:15055: getsockopt: connection refused
E                   2018-10-23 13:12:22.740136702 +0000 UTC [could not fetch url: http://172.17.0.2:15055/history/last] 172.17.0.2 master Get http://172.17.0.2:15055/history/last: dial tcp 172.17.0.2:15055: gets
```

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Pull request closed without merging**
