### PR TITLE
Wait on ZooKeeper instead of Exhibitor during bootstrap

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

Wait for ZooKeeper to enter a suitable mode for the cluster, rather than waiting for Exhibitor.

Since the tests add to fixtures, triggering all e2e tests, I took the opportunity to refine skip patterns and to upgrade requirements for the e2e tests.

## Corresponding DC/OS tickets (required)

  - [D2IQ-70393](https://jira.d2iq.com/browse/D2IQ-70393) Wait for ZooKeeper instead of Exhibitor in bootstrap

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot test all

**Comment by jongiddy** [comment]
@mesosphere-mergebot test all

**Comment by jongiddy** [comment]
@mesosphere-mergebot test all

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @jkoelker

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required to be back-ported

**Comment by orsenthil** [comment]
The mergebot isn't triggering the `merge-it` from the train. (We need to look into it - @AliakseiKhomchanka ) - do a direct merge-it for now.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
