### PR TITLE
Marathon 1.8.104 bump to dcos 1.13

### PR DESCRIPTION
**Pull request by kensipe**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [MARATHON-8516](https://jira.mesosphere.com/browse/MARATHON-8516) Race condition when provisioning an instance while changing a goal.
  - [MARATHON-8503](https://jira.mesosphere.com/browse/MARATHON-8503) Marathon should run on Java 9.
  - [MARATHON-8505](https://jira.mesosphere.com/browse/MARATHON-8505) Default backoff changed from 1 hour to 5 mins.
  - [MARATHON-8458](https://jira.mesosphere.com/browse/MARATHON-8458) Remove API heavy events from Marathon repository.
  - [MARATHON-8512](https://jira.mesosphere.com/browse/MARATHON-8512) Simplify AppStartActor.
  - [MARATHON-8509](https://jira.mesosphere.com/browse/MARATHON-8509) Use single Apache Curator instance.
  - [MARATHON-8466](https://jira.mesosphere.com/browse/MARATHON-8466) Fixed Issue with apps with specific names.
  - [MARATHON-8498](https://jira.mesosphere.com/browse/MARATHON-8498) Remove validation for app updates and validate the whole app instead.
- [PR-6659](https://github.com/mesosphere/marathon/pull/6659) Clean up instance update op resolver.
- [MARATHON-8482](https://jira.mesosphere.com/browse/MARATHON-8482) Fix application of timeouts in OverdueInstancesActor.
- [MARATHON-8470](https://jira.mesosphere.com/browse/MARATHON-8470) Remove InstanceUpdateActor.
- [MARATHON-8133](https://jira.mesosphere.com/browse/MARATHON-8133) Drop connection for slow event consumers.

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-4563](https://jira.mesosphere.com/browse/DCOS_OSS-4563) Bump Marathon 1.8.x on DCOS 1.13.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/mesosphere/marathon/compare/66d21ba2bf39bce0053a719e766ece4995681dc0...2faff8dd2)
  - [x] Test Results: [CI](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/1144/consoleFull)
  - [ ] Code Coverage (if available):  N/A

### CODE REVIEW

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
@mesosphere-mergebot label ready for review

**Comment by kensipe** [comment]
@orsenthil failure on `group2` is NOT related to this PR

```
  @retrying.retry(wait_fixed=5000, stop_max_delay=150 * 1000)
    def wait_for_package_teardown():
        state_response = dcos_api_session.get('/state', host=dcos_api_session.masters[0], port=5050)
        assert state_response.status_code == 200
        state = state_response.json()
    
        for framework in state['frameworks']:
            if framework['name'] == framework_name:
>               raise Exception('Framework {} still running'.format(framework_name))
E               Exception: Framework hello-world still running

test_metrics.py:184: Exception
```

`Exception: Framework hello-world still running`

**Comment by kensipe** [comment]
@orsenthil failure on `dcos-docker/static` is NOT related to this PR

```
The build dcos-docker::DC/OS E2E Docker Integration Tests #3498 {buildId=1332079} has been running for more than 300 minutes. Terminating...
```

**Comment by orsenthil** [comment]
Hi @kensipe  - I had not seen your pings here. Sorry.
Master has moved, and the status of the target state of these tests are good. I'd suggest rebasing and re-running. I personally think, that the errors are genuine, but we can find out in the run against the latest SHA.

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
rebased and bumped to the latest marathon 1.8.   It is expected to be the better option at this pt

**Comment by kensipe** [comment]
rebase again

**Comment by orsenthil** [comment]
@mesosphere-mergebot label work in progress

**Comment by orsenthil** [comment]
Hi @kensipe - the problems with integration test seem to be related. This needs to be investigated. The application of ship-it by mergebot was a mistake.

**Comment by kensipe** [comment]
looks like I missed this as I thought we had a ship it.   I will investigate

**Comment by kensipe** [comment]
looks like we are not ready to bump marathon 1.8... closing

**Pull request closed without merging**
