### PR TITLE
[master] Mergebot Automated Train PR - 2018-Jan-26-17-41

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2294 - [Release scripting] Use native boto3 session interface for AWS authentication
* #2340 - Add port 9273 to admin-ports.md

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by adamtheturtle** [comment]
Approved given an override of `teamcity/dcos/test/aws/onprem/static-redhat` for https://jira.mesosphere.com/browse/DCOS_OSS-2115 - though maybe not - can an owner please check that this does apply because the exact test parameter mentioned is not right.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by orsenthil** [comment]
@adamtheturtle  - Yes, the error was due to the same root-cause.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
