### PR TITLE
Train 124

### PR DESCRIPTION
**Pull request by amitaekbote**
## High Level Description

Train 124 🚋  

## Related Issues

#645 Add platform field to config.yaml
#1138 Assorted tooling fixes
#1066 Late binding config
#1082 added ucr deployment with healthcheck
#1111 bump 3dt
#1135 add mesos files api integration test
#1178 openssl bump 

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by amitaekbote** [comment]
@spahl @adam-mesos @lingmann reviews please :)

**Comment by adammesos** [comment]
This train also includes #1134 again, right? Looks that way from the commits

**Comment by amitaekbote** [comment]
yes it does include #1134

**Comment by adammesos** [comment]
All green here and downstream. @lingmann are you ready to approve and merge now?

**Pull request merged**
