### PR TITLE
[master] Mergebot Automated Train PR - 2019-Feb-08-23-10

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #4449 - DCOS-46438 - Support collecting integration tests locally without a cluster.

### CODE REVIEW

**Comment by jbarrick-mesosphere** [comment]
@mesosphere-mergebot sync

**Comment by jbarrick-mesosphere** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
Until DCOS-48258 is resolved, applying the ship-it manually.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
Looks like the revert https://github.com/dcos/dcos/pull/4473 landed headed. We will rebase it and merge it.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
