### PR TITLE
Fix systemd unit files to work with modern systemd

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by alberts** [comment]
@sargun what did they change to break this?

**Comment by sargun** [comment]
@alberts Env variable setting with spaces has to be in quotes now

**Comment by cmaloney** [comment]
Can you add a line to `docs/systemd-rules.md` about that?

**Comment by sargun** [comment]
Updated.

**Comment by alberts** [comment]
@sargun @drewkerrigan do we want this one or https://github.com/dcos/dcos/pull/739 or both?

**Pull request closed without merging**
