### PR TITLE
Train 296 (master)

### PR DESCRIPTION
**Pull request by adam-mesos**
:steam_locomotive: :two: :nine: :six: :train: :tada: 

#2230 fault domain script improvements
#2232 Disable ipv6 for l4lb
#2245 Bump dc/os metrics
#2242 Bump dcos-mesos
#2182 VIP integ tests for ipv6

### CODE REVIEW

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
The `test_rexray.test_move_external_volume_to_new_agent` issue in `teamcity/dcos/test/aws/cloudformation/simple` looks like https://jira.mesosphere.com/browse/DCOS_OSS-1841

The other failures in CF simple are `test_dcos_diagnostics.test_dcos_diagnostics_runner_cluster` and
`test_dcos_diagnostics.test_dcos_diagnostics_runner_poststart` but I don't see anything there since https://jira.mesosphere.com/browse/DCOS-17706 which was Closed in August.

**Comment by adam-mesos** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by spahl** [comment]
@mesosphere-mergebot merge-it

**Comment by lingmann** [comment]
@mesosphere-mergebot override-status mergebot/enterprise/build-status/aggregate https://jira.mesosphere.com/browse/DCOS-19844

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
