### PR TITLE
Train 192

### PR DESCRIPTION
**Pull request by lingmann**
## Train 192

PR | Description
------------ | -------------
#1740 | bump dcos-diagnostics sha
#1738 | Changes name of CNI conf file from .cni to .conf

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
integration-test/deploy-vpc-api failed with:
```
test_networking.test_vip[Container_MESOS-Network_HOST-Network_USER] 
```

re-running

**Comment by jgehrcke** [comment]
`test_networking.test_vip[Container_NONE-Network_USER-Network_USER]` is a known flake.

**Comment by jgehrcke** [comment]
The enterprise aggregate PR (1202) has 100 % green CI. I am not sure why `mergebot/enterprise/build-status/aggregate` did not update.

**Pull request merged**
