### PR TITLE
added ucr deployment with healthcheck

### PR DESCRIPTION
**Pull request by kensipe**
High level description including:
 - tests for UCR container deployment
 - tests http health check on UCR

# Issues

[DCOS-9437](https://mesosphere.atlassian.net/browse/DCOS-9437)
...

# Checklist

 - [x ] Included a test which will fail if code is reverted but test is not
 - [ x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by sargun** [comment]
Can we add an HTTP, and MESOS_HTTP healthcheck here?

**Comment by kensipe** [comment]
The base app from which this app def derives from uses an http health check:
https://github.com/kensipe/dcos/blob/ken/fix-9437/test_util/marathon.py#L33

**Comment by kensipe** [comment]
@sargun ok.. http and mesos_http tests are passing.

**Comment by kensipe** [comment]
@sargun how do we get this merged?

**Comment by kensipe** [comment]
@adam-mesos The failure on AWS has nothing to do with the change I made... and I can't tell on vagrant but it looks unrelated.

**Comment by adam-mesos** [comment]
Vagrant was broken for unrelated reasons. If you rebase against latest master, it should go green now.

**Comment by adam-mesos** [comment]
@kensipe It looks like your new ucr test fails in EE strict mode (does it use pods?)
https://teamcity.mesosphere.io/viewLog.html?buildId=534831&buildTypeId=ClosedSource_Dcos_DcOsEnterpriseCcmDeployTestSecurityStrict
If this isn't expected, I'm tempted to remove it from the train so we can merge without new broken tests.
It looks like it might be the same error as the other 2 tests that already fail in strict mode. cc: @amitaekbote

**Comment by amitaekbote** [comment]
@adam-mesos I will retry the test, looks like the socket thing has been flaky for a while

**Comment by adammesos** [comment]
The test infrastructure issue has been fixed in #1147 
Please rebase, and we can get this in the next train.

**Comment by kensipe** [comment]
@adam-mesos this is ready to go

**Pull request merged**
