### PR TITLE
anatoly/dcos-13620 minuteman upgrade test vips

### PR DESCRIPTION
**Pull request by aeyakovenko**
please add these reviewers @orsenthil @travisvan @GoelDeepak 

## High Level Description

upgrade test to make sure that an active connection to a VIP survives minuteman upgrades.  (@nlsun as network reviewer)

## Related Issues

  - [DCOS-13620](https://mesosphere.atlassian.net/browse/DCOS-13620) TRACKING: dcosjira-13620 upgrade tests to make sure VIP connections survive minuteman upgrades

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
this is the test
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review):
na
  - [ ] Test Results: [link to CI job test results for component]
this is the test
  - [ ] Code Coverage (if available): [link to code coverage report]
na
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orsenthil** [comment]
@aeyakovenko , is this ready for review? Please rebase on top of origin/master HEAD and update the PR template as well.

**Comment by aeyakovenko** [comment]
@orsenthil i think this is ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
Please get rebase/rerun to get the CI green enough that we can confidently ShipIt

**Comment by aeyakovenko** [comment]
@adam-mesos done!

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
