### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Aug-23-10-03

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3256 - [1.10] Prevent dcos-history leaking auth tokens

Also included

* #3213 - chore(dcos-ui): bump DC/OS UI 1.10+v1.10.9-rc2
* #3332 - [1.10] Add timestamp for dmesg, distro version, timedatectl, systemd unit status and pods endpoint to diag bundle

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
I do not know why the bump-ee failed for 1.10

* The failure was not captured in dcos service and either in lambda logs.

I ended up creating a EE branch for this train PR - https://github.com/mesosphere/dcos-enterprise/pull/3340

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
