### PR TITLE
1.11 train 08/29

### PR DESCRIPTION
**Pull request by cprovencher**
#3298 [1.11] Added Mesos patches for per-framework metrics.
#3273 [1.11] Add more information to diagnostics bundle
#3212 [1.11] Add timestamp for dmesg, distro version, timedatectl, systemd unit status and pods endpoint to diag bundle

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ready for review

**Comment by adamtheturtle** [comment]
It seems that this train breaks `test_dcos_diagnostics.test_dcos_diagnostics_bundle_download_and_extract` - for example on `teamcity/dcos/test/dcos-docker/static`.

**Comment by orsenthil** [comment]
This manual Train PR can be closed in favor of https://github.com/dcos/dcos/pull/3385

**Pull request closed without merging**
