### PR TITLE
Bumped Mesos to master 00b6888 and enabled all cgroup subsystems.

### PR DESCRIPTION
**Pull request by Gilbert88**
## High-level description

This PR bumped Mesos SHA to the latest master branch 00b6888 and enabled all cgroup subsystems for DC/OS.

## Corresponding DC/OS tickets (obligatory)

These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-3680](https://jira.mesosphere.com/browse/DCOS_OSS-3680) Enable auto cgroup in DC/OS.

## Related tickets (optional)

Other tickets related to this change:

  - [MESOS-7691](https://issues.apache.org/jira/browse/MESOS-7691) Support local enabled cgroups subsystems automatically.
  - [MESOS-8327](https://issues.apache.org/jira/browse/MESOS-8327) Add container-specific CGroup FS mounts under /sys/fs/cgroup/* to Mesos containers.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not: [See here](https://github.com/apache/mesos/commit/7616c4caec9d1bbb9f2ac645971244b55d2b9f42)
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/apache/mesos/compare/abef72521a9a74fe4d6e7c796d6c99f02ad811dd...00b688815be6f3d429b2035e7e926a56f00fd18b)
  - [x] Test Results: [Jenkins results](https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/Mesos_CI-build/3796/)
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Ship It |Holding |Work In Progress |Ready For Review |Request For Comment] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by Gilbert88** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by mesosphere-mergebot-dev** [comment]
@Gilbert88, an [owner](https://raw.githubusercontent.com/dcos/dcos/master/owners.json) other than the PR creator needs to issue that command.

**Comment by Gilbert88** [comment]
@mesosphere-mergebot bump-ee

**Comment by Gilbert88** [comment]
Close this PR in favor of pull/3022

**Pull request closed without merging**
