### PR TITLE
[1.10] Train 211

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 211. It includes:

- #1875 (Bump 1.9 api links to 1.10)
- #1873 (test_networking.test_vip test is flaky [2])

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
`integration-test/azure` failed in https://teamcity.mesosphere.io/viewLog.html?buildId=763133. I re-run this now, but the failure still needs to be inspected.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
