### PR TITLE
Validate SSH key is not a public key

### PR DESCRIPTION
**Pull request by malnick**
Ensure the SSH key is not a public key by attempting to fingerprint it as though it was a public key. 

CC @pyronicide

### CODE REVIEW

**Comment by malnick** [comment]
@spahl This needs `In Review` label.

**Comment by pyronicide** [comment]
👍

**Comment by cmaloney** [comment]
I don't believe we have the `ssh-keygen` binary inside of the dcos_generate_config.sh alpine based docker container

**Comment by malnick** [comment]
It's there, I believe it ships with `openssh`

**Comment by spahl** [comment]
Why don't you add a test for that. Then we'll see for sure:-D

**Comment by malnick** [comment]
Added two tests: one for testing validation of pub key and one for testing validation of encrypted key.

**Comment by malnick** [comment]
Currently blocked by https://github.com/dcos/dcos/pull/

**Comment by malnick** [comment]
I am not sure what's changed, but the openssl error has gone away. I'm rebase'ing this on master and we'll see if it's still solid.

**Comment by cmaloney** [comment]
No progress for a month, closing

**Pull request closed without merging**
