### PR TITLE
Cherry-pick Bump Marathon to 1.4.7.

### PR DESCRIPTION
**Pull request by orsenthil**
## High-Level Description

* https://jira.mesosphere.com/browse/DCOS-18246 - This cherry-picks marathon-pr #1863

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Please review and approve @jeschkies , @lingmann , @mellenburg - This is a cherry of what was committed in 1.9.3 to 1.9 branch. (Originally, it should have been against 1.9 branch and picked up to a the minor release.).

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
Without a JIRA ticket which explains the goal this is hard to review :-(.

**Comment by orsenthil** [comment]
> Without a JIRA ticket which explains the goal this is hard to review :-(.

Thanks for raising this @jgehrcke  - I have added the JIRA (https://jira.mesosphere.com/browse/DCOS-18246) and the context for this PR now. 

Thank you!

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
