### PR TITLE
bump dcos-diagnostics sha

### PR DESCRIPTION
**Pull request by darkonie**
## High Level Description

- bump dcos-diagnostics sha.
- update integration test to exclude `system` field validation.

## Related Issues

  - [DCOS_OSS-143](https://jira.mesosphere.com/browse/DCOS_OSS-1430) Remove `system` field from dcos-diagnostics health response.
  - [DCOS_OSS-671](https://jira.mesosphere.com/browse/DCOS_OSS-671) Diagnostics bundle naming improvement. 

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
Current set of integration tests provides a good coverage. 
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [dcos-diagnostics](https://github.com/dcos/dcos-diagnostics/compare/0f0f7a1a7824e223875c3e37b45549550ca9eb80...422d00ed1a3a47ecb605f4d3adcafe5945d4e3bc)
  - [X] Test Results: [jenkins#11](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-diagnostics-pulls/11/console)
  - [X] Code Coverage (if available): [jenkins#11](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-diagnostics-pulls/11/console)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by darkonie** [comment]
@mesosphere-mergebot bump-ee

**Comment by darkonie** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by lingmann** [comment]
Hi @darkonie can you find someone to do a second review on this? thanks!

**Comment by darkonie** [comment]
@lingmann done! approved

**Comment by lingmann** [comment]
Awesome, thank you @darkonie ! 🚀

**Pull request merged**
