### PR TITLE
[1.12] Bump Mesos to nightly 1.7.x a6c3804

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
## High-level description

This is a routine bump to the latest Mesos and mesos-modules.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Changelog:
    https://github.com/apache/mesos/compare/8419b870c571ac11825c883fa20ea3b7d4348d34...a6c3804372aaf512145196782c5731f0da58b0e3
    https://github.com/dcos/dcos-mesos-modules/compare/29561f11a12372752b77839be73418d1d75abe63...bf88ce16e8b868cf5d66e4794db0c55235510fe6
    
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot bump-ee

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcos/windows https://jira.mesosphere.com/browse/DCOS-41386

**Comment by vinodkone** [comment]
@rukletsov These are the JIRAs that need to be attached AFAICT
[DCOS-41859](https://jira.mesosphere.com/browse/DCOS-41859)
[COPS-3172](https://jira.mesosphere.com/browse/COPS-3172)
[DCOS-40120](https://jira.mesosphere.com/browse/DCOS-40120)

**Comment by Gilbert88** [comment]
I re-run teamcity/dcos/test/aws/onprem/static in case the build failure is a flakyness.

**Comment by orsenthil** [comment]
Hi @vinodkone - Which one do you want to land for 1.12 this or https://github.com/dcos/dcos/pull/3477? Let us please close one in the favor other.

**Comment by vinodkone** [comment]
Let’s do 3477. Kapil can you close the old one?

Thanks,
Vinod

**Pull request closed without merging**
