### PR TITLE
Bump cosmos to latest version

### PR DESCRIPTION
**Pull request by takirala**
## High-level description

What features does this change enable? What bugs does this change fix?

Bump cosmos version to `0.6.2`. DC/OS 2.0 backport via #6322 

## Corresponding DC/OS tickets (required)

  - [DCOS-58438](https://jira.mesosphere.com/browse/DCOS-58438) Add support for new fields in packaging : `hasKnownIssues` and `lastUpdated` fields
  - [DCOS-57014](https://jira.mesosphere.com/browse/DCOS-57014) Relax cosmos validation on DC/OS version string

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [9afd051e46...v0.6.2](https://github.com/dcos/cosmos/compare/9afd051e46...v0.6.2)
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain : No breaking changes, no such tests.
  - [x] Test Results: [link to CI job test results for component](https://teamcity.mesosphere.io/viewLog.html?buildId=2310682&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_FullClusterIntegrationTests)
  - [x] Code Coverage (if available): [link to code coverage report](https://teamcity.mesosphere.io/viewLog.html?buildId=2310683&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_Scoverag)

### CODE REVIEW

**Comment by takirala** [comment]
@mesosphere-mergebot changelog-not-required added change log entry to DC/OS 2.0 backport PR via #6322

**Comment by takirala** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by takirala** [comment]
@mesosphere-mergebot request-review  @kvish @kaiwalyajoshi

**Comment by kaiwalyajoshi** [comment]
seems I didn't understand the changelog process correctly, disregard previous request.

**Comment by takirala** [comment]
@mesosphere-mergebot sync

**Comment by takirala** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
