### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-May-09-22-15

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2852 - [1.11][DCOS-22384] Dump diagnostics bundles for TeamCity artifacts
* #2855 - improve dcos-diagnostics integration test 1.11

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot override-status  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot label [Ready For Review |Request For Comment |Holding |Work In Progress |Ship It] 
@mesosphere-mergebot merge-it  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
