### PR TITLE
Fix ftype=1 check for dcos-docker

### PR DESCRIPTION
**Pull request by surdy**
## High-level description
Fixes ftype=1 install time check for dcos-docker

What features does this change enable? What bugs does this change fix?
https://github.com/dcos/dcos/pull/2768 breaks dcos-docker for very specific (rare but valid dcos-docker) configuration (https://jira.mesosphere.com/browse/DCOS_OSS-3549). This fixes that

If the device being used for docker root directory is not accessible the xfs_info check fails. I have added a block device check before xfs_info check to skip ftype=1 check
 
## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-3549](https://jira.mesosphere.com/browse/DCOS_OSS-3549) ftype=1 pre-flight check has broken dcos-docker for configurations using devicemapper 

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [X] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

@adamtheturtle @vespian hopefully this will fix the issue we discussed. I will test it out once I have a build

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Work In Progress |Ready For Review |Holding |Ship It |Request For Comment] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by surdy** [comment]
OK this is now ready for review. I will backport this to 1.11 and 1.10 as well right away

@branden @adamtheturtle @vespian

**Comment by surdy** [comment]
Thanks @orsenthil  . This is why I should not commit code late at night. 

Fixed it.

**Comment by surdy** [comment]
Latest commit is a fix for https://jira.mesosphere.com/browse/DCOS_OSS-3549

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by mesosphere-mergebot-dev** [comment]
Your pull request's branch is not based on the most recent version of `master`. Please rebase your changes against this repo's `master` branch.

**Comment by vespian** [comment]
@surdy Do you think you could rebase and bump-ee?

**Comment by surdy** [comment]
@mesosphere-mergebot bump-ee

**Comment by mesosphere-mergebot-dev** [comment]
Your pull request's branch is not based on the most recent version of `master`. Please rebase your changes against this repo's `master` branch.

**Comment by surdy** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@surdy  Ping?

**Comment by surdy** [comment]
@vespian pong ?

**Comment by vespian** [comment]
> @vespian pong ?

 @surdy  Do you think we could ship this PR and finalize the bugfix?  Pretty please :)

**Comment by surdy** [comment]
@vespian I was not under the impression that this was blocked on me . Is it ?

**Comment by adamtheturtle** [comment]
I have reported the `teamcity/dcos/build/dcos` failure on https://jira.mesosphere.com/browse/DCOS_OSS-3523. I will re-run the builder.

**Comment by vespian** [comment]
@surdy  It is - you need to triage Integration Tests failure, ask an owner to override them if they are flakes, s and get the `Ship it` label. Also, the PR itself is labeled as `Work in Progress` - it should probably be `Ready for review` if it is ready to go :)

**Comment by surdy** [comment]
@mesosphere-mergebot label ready for review

**Comment by surdy** [comment]
@adamtheturtle dcos-docker/static test is failing with "docker.errors.InvalidVersion: mounts param is not supported in API versions < 1.30" . If I'm not mistaken we see this if older version of docker were being used. I do not think this would failure would be due to any of my changes. I would have expect our tests to have configured hosts correctly (for docker version etc). Should I be pinging someone from tools-infra to look at this ?

**Comment by adamtheturtle** [comment]
@surdy This was a temporary issue that @orsenthil has resolved (see https://jira.mesosphere.com/browse/DCOS-38121). I have started a re-run of the job.

**Comment by vespian** [comment]
@orsenthil When do you think the next train will depart?

**Comment by orsenthil** [comment]
@vespian  - you should ask dcos-owners! :) Please help with reviewing the pending PR - https://github.com/dcos/dcos/pull/2968 | https://github.com/mesosphere/dcos-enterprise/pull/2891 - that was in waiting state for more than 6 days now.

**Comment by vespian** [comment]
@orsenthil  The PR you mentioned was merged, any chance to get it merged soon? This PR fixes a bug that makes my life difficult :(

**Comment by orsenthil** [comment]
@vespian  - You must ping dcos-owners! This is train https://github.com/dcos/dcos/pull/2986 and please approve the train and EE part and should request dcos-owners to merge-it!

**Pull request merged**
