### PR TITLE
Use the same golang version for all projects

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

By removing specific docker version in buildinfo.json, pkgpanda will use
dcos/dcos-builder.

https://github.com/dcos/dcos/blob/c9e43e3af91c54c4b3f13fb12c3b935a3517c276/pkgpanda/docker/dcos-builder/Dockerfile#L54-L56

https://golang.org/doc/go1.13

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5517](https://jira.mesosphere.com/browse/DCOS_OSS-5517) Switch to go 1.13

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required change build scripts

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required change build scripts

**Comment by janisz** [comment]
:wave: @drewvanstone @br-lewis @makkes @bamarni @rgo3  Can you review, please?

**Comment by bamarni** [comment]
For historical purpose it'd be nice to explain why telegraf is pinned to Go 1.11 in the commit description.

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Pull request merged**
