### PR TITLE
Bump marathon to 1.6 dev

### PR DESCRIPTION
**Pull request by alenkacz**
## High-level description

Latest build of Marathon 1.6 Dev

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [MARATHON-7916](https://jira.mesosphere.com/browse/MARATHON-7916) Release Latest Marathon to DCOS 1.11

## Latest features

- Simplify LeaderElection 
- Change `Int.MaxValue` to 8 for maximum concurrency
- Introduction of Workload Bursting 
- Allow underscore for network names
- Improved Reliability for Persistence Migration

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/mesosphere/marathon/compare/7501d6f...66a63ef
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/493/console
  - [x] Code Coverage (if available): None

### CODE REVIEW

**Comment by alenkacz** [comment]
@mesosphere-mergebot label Ready for review

**Comment by alenkacz** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
@orsenthil these failures do not seem related to the marathon bump
any help here?

**Comment by orsenthil** [comment]
@mesosphere-mergebot label merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
