### PR TITLE
[1.13] Bump Marathon to 1.8.245

### PR DESCRIPTION
**Pull request by pierrebeitz**
## High-level description

Bump Marathon to 1.8.245

## Corresponding DC/OS tickets (required)

* https://jira.d2iq.com/browse/MARATHON-8762
* https://jira.d2iq.com/browse/COPS-5897

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot bump-ee

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot ready-for-review-label

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot ready-for-review-label

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Review by DominikDary — APPROVED** [review]

**Pull request merged**
