### PR TITLE
[master] Automated Bump DC/OS UI v6.1.19

### PR DESCRIPTION
**Pull request by pierrebeitz**
* [COPS-6624](https://jira.d2iq.com/browse/COPS-6624)

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot backport 2.2

**Review by jongiddy — APPROVED** [review]

**Comment by pierrebeitz** [comment]
thanks @jongiddy!

**Comment by jongiddy** [comment]
Testing GitHub's race conditions there!

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot sync

**Pull request merged**
