### PR TITLE
Pin Flake8 to 3.3.0

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

Backport to 1.9

### CODE REVIEW

**Comment by jgehrcke** [comment]
`TestUpgrade.test_mesos_task_state_remains_consistent` failed: https://teamcity.mesosphere.io/viewLog.html?buildId=720658

@sambatyon do you happen to know (why) this is expected?

**Comment by sambatyon** [comment]
So this tests checks that after an update no fields are removed from the mesos task state. Now, the issue I had to dealt with was unrelated with this failure. 

@mellenburg pointed out to me, while I was working on the test, that it might be flaky on exactly that point: https://teamcity.mesosphere.io/project.html?projectId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests&tab=testDetails&testNameId=7561668161787586690#analysis

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
That's the only PR against the `1.9.3` branch that is ready to land, and it's a requirement to land so that the `code-quality` check of other PRs against the 1.9.3 branch can go green.

**Comment by jgehrcke** [comment]
Corresponding JIRA ticket: https://jira.mesosphere.com/browse/DCOS_OSS-1477

**Pull request merged**
