### PR TITLE
[master] Automated Bump DC/OS UI v6.1.5

### PR DESCRIPTION
**Pull request by pierrebeitz**
* [COPS-6491](https://jira.d2iq.com/browse/COPS-6491)
* [D2IQ-71334](https://jira.d2iq.com/browse/D2IQ-71334)
* [COPS-6555](https://jira.d2iq.com/browse/COPS-6555)

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by DominikDary** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by DominikDary** [comment]
@mesosphere-mergebot sync

**Review by DominikDary — APPROVED** [review]

**Comment by orsenthil** [comment]
@mesosphere-mergebot test all

**Comment by orsenthil** [comment]
Applying ship-it since the CI test was successful and only the status was not reported back.

**Pull request merged**
