### PR TITLE
[1.11] packages/java: Update to 8u192

### PR DESCRIPTION
**Pull request by mhrabovcin**
## High-level description

Update Java to `8u192`.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4382](https://jira.mesosphere.com/browse/DCOS_OSS-4382) Update DC/OS Java JDK 8 to 8u192

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://www.java.com/en/download/faq/release_changes.xml
  - [ ] Test Results: n/a - external package
  - [ ] Code Coverage (if available): n/a - external package

### CODE REVIEW

**Comment by mhrabovcin** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mhrabovcin** [comment]
@mesosphere-mergebot bump-ee

**Comment by mhrabovcin** [comment]
@jongiddy @adamtheturtle @ahairape @timaa2k @sambatyon please review this PR and EE bump.

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
