### PR TITLE
Add support for CoreOS 1688.4.0

### PR DESCRIPTION
**Pull request by urbanserj**
## High-level description

Add support for CoreOS 1688.4.0

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-2417](https://jira.mesosphere.com/browse/DCOS_OSS-2417) Add support for CoreOS 1688.4.0

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: let's mention this change only after we migrate all our AIMs on coreos 16xx.
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: none.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label [Work In Progress]

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orsenthil** [comment]
This change will need a CHANGES.md addition (https://github.com/dcos/dcos/blob/master/CHANGES.md) - For now, we will add this in the train PR, but please include CHANGES.md changes as part of your next PR (Reviewers, please ensure this).

**Comment by urbanserj** [comment]
@orsenthil Please see the description.

>  Added a comprehensible changelog entry to CHANGES.md or explain why this is not a user-facing change: let's mention this change only after we migrate all our AIMs on coreos 16xx.

**Comment by jdef** [comment]
does this also fix the flaky SSH service issues that we've been seeing in CI w/ coreos-based test runs?

**Comment by jdef** [comment]
#2834 is the 1.11 backport

**Comment by urbanserj** [comment]
@jdef I'm afraid not, this PR fixes only an issue with networkd. if you use dcos-launch on AWS you shouldn't worry about this particular issue because it still uses CoreOS 1632 as a base image (see [aws.py](https://github.com/dcos/dcos-launch/blame/3b44111d5c23a1cac5305b6dd3e1a43412e23b4e/dcos_launch/platforms/aws.py#L640)).

Could you please create a JIRA for the tool infrastructure team?

**Pull request merged**
