### PR TITLE
Update CoreOS AMI images

### PR DESCRIPTION
**Pull request by sschneid**
## High-level description
Updates CoreOS to 1632.2.1 in the AWS CloudFormation Templates, which also includes a bump to docker 17

AMIs lifted from https://coreos.com/os/docs/latest/booting-on-ec2.html

## Corresponding DC/OS tickets (obligatory)

https://jira.mesosphere.com/browse/DCOS_OSS-2130

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: N/A update to cloud-provided underlying operating system
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label work in progress

**Comment by orsenthil** [comment]
@sschneid  - should we close this?

**Pull request closed without merging**
