### PR TITLE
[2.0][BACKPORT] 6765 from  master: [master] Automated Bump DC/OS UI v2.154.12

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
This is a backport of the following PR:

https://github.com/dcos/dcos/pull/6765

### CODE REVIEW

**Comment by Poltergeist** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot request-review @pierrebeitz

**Comment by Poltergeist** [comment]
@mesosphere-mergebot label Ship It

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ship It

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot sync

**Pull request merged**
