### PR TITLE
Train 119

### PR DESCRIPTION
**Pull request by amitaekbote**
Merging the following pr's: 

#882 Add dcos-launch
#1000 Add an anonymous module to Mesos that modifies logging behavior. 
#1089 Reduce 3dt test verbosity
#1103 Factor out common / duplicate code 

All of the above has two approvals and all tests are green.

### CODE REVIEW

**Comment by lingmann** [comment]
@amitaekbote can you list out the PR's and a one line summary for each in the description? I find that has been pretty useful on past trains.

**Comment by amitaekbote** [comment]
@adam-mesos @lingmann what tests do we want to run with this train?

**Comment by spahl** [comment]
@amitaekbote we need to build an upstream bump version in our downstream repositories and see if it passes.

**Comment by alberts** [comment]
If the door of this train is still open, passenger https://github.com/dcos/dcos/pull/1129 is waiting. If not, we'll wait for the next one. :bullettrain_front:

**Comment by spahl** [comment]
Next one. This is ready to merged and only has a problem with github

**Comment by amitaekbote** [comment]
thanks @spahl !

**Pull request merged**
