### PR TITLE
Backport of #5766

### PR DESCRIPTION
**Pull request by ahairape**
## High-level description

See https://github.com/dcos/dcos/pull/5766

## Corresponding DC/OS tickets (required)

https://jira.mesosphere.com/browse/DCOS-59406

### CODE REVIEW

**Comment by ahairape** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by ahairape** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by ahairape** [comment]
@mesosphere-mergebot sync

**Pull request merged**
