### PR TITLE
Upgrade marathon to 1.4.2-snapshot2

### PR DESCRIPTION
**Pull request by jasongilanfarr**
## High Level Description

Upgrades Marathon to 1.4.2-snapshot2 (candidate) which has the correct version.

## Related Issues

- [MARATHON-4570](https://jira.mesosphere.com/browse/MARATHON-4570) Don't destroy persistent volumes when killing unreachable tasks
- [MARATHON-4390](https://jira.mesosphere.com/browse/MARATHON-4390) Lazy event parsing
- Improve health checks to log less warnings.
- [MARATHON-1712](https://jira.mesosphere.com/browse/MARATHON-1712) Loosen SSL requirements for HTTPS health checks.
- [MARATHON-1408](https://jira.mesosphere.com/browse/MARATHON-1408) Fix serialization of maxSize for persistent volumes.
- [MARATHON-2311](https://jira.mesosphere.com/browse/MARATHON-2311) Publish a TASK_GONE mesos update when an unreachable instance's resources are seen.
- [MARATHON-1682](https://jira.mesosphere.com/browse/MARATHON-1682) Persist kill selection.
- Disable unreachable strategy for resident tasks
- Add a migration to fix the unreachable strategy for resident apps.
- Read LaunchedOnReservation and ReservedTasks.
- ForceExpunge for a missing task is a noop rather than a failure.
- Use non-deployment-interacting kill service during kill and wipe.
- Validation of application dependencies is too restrictive, loosed the requirements.
- Retry failed integration tests once.
- Fix stability in many integration tests.
## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Covered by marathon tests
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&buildTypeId=Oss_Marathon_PublishTar&buildId=581009#_state=59,37,27&focus=55
  - [x] Code Coverage (if available): not available for this branch.

### CODE REVIEW

**Comment by jasongilanfarr** [comment]
@mesosphere-mergebot bump-ee

**Comment by timcharper** [comment]
updated release note items:

- [MARATHON-4570](https://jira.mesosphere.com/browse/MARATHON-4570) Don't destroy persistent volumes when killing unreachable tasks
- [MARATHON-4390](https://jira.mesosphere.com/browse/MARATHON-4390) Lazy event parsing
- Improve health checks to log less warnings.
- [MARATHON-1712](https://jira.mesosphere.com/browse/MARATHON-1712) Loosen SSL requirements for HTTPS health checks.
- [MARATHON-1408](https://jira.mesosphere.com/browse/MARATHON-1408) Fix serialization of maxSize for persistent volumes.
- [MARATHON-2311](https://jira.mesosphere.com/browse/MARATHON-2311) Publish a TASK_GONE mesos update when an unreachable instance's resources are seen.
- [MARATHON-1682](https://jira.mesosphere.com/browse/MARATHON-1682) Persist kill selection.
- [MARATHON-2645](https://jira.mesosphere.com/browse/MARATHON-2645), [MARATHON-2184](https://jira.mesosphere.com/browse/MARATHON-2184) Never auto-expunge unreachable resources, nor reserve more volumes than # of instances specified.
- [MARATHON-2391](https://jira.mesosphere.com/browse/MARATHON-2391) Fix issue in which task residency status was lost during Marathon restart
- [MARATHON-4523](https://jira.mesosphere.com/browse/MARATHON-4523) Fix issue in which resources were not released for deleted resident apps
- [MARATHON-2415](https://jira.mesosphere.com/browse/MARATHON-2415) Fix issue in which kill and wipe did not kill the task.
- Validation of application dependencies is too restrictive, loosed the requirements.
- Retry failed integration tests once.
- Fix stability in many integration tests.

**Comment by jasongilanfarr** [comment]
@mesosphere-mergebot bump-ee

**Comment by jasongilanfarr** [comment]
@seb This update has the correct version metadata as there is actually a new migration.

**Pull request merged**
