### PR TITLE
chore(dcos-ui): update package

### PR DESCRIPTION
**Pull request by orlandohohmeier**
## High-level description

Update the DC/OS UI package to include the latest fixes, improvements and features.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

- [DCOS-20156](https://jira.mesosphere.com/browse/DCOS-20156) Fix MesosStream memory leak
- [DCOS-19292](https://jira.mesosphere.com/browse/DCOS-19292) Add an extra edit button to Services
- [DCOS-19033](https://jira.mesosphere.com/browse/DCOS-19033) Update Badges to match UI Kit 
- [DCOS_OSS-2011](https://jira.mesosphere.com/browse/DCOS_OSS-2011) Add IPv6 to the networks table
- [DCOS_OSS-2017](https://jira.mesosphere.com/browse/DCOS_OSS-2017) Fixes the description of the IS operator
- [DCOS_OSS-2011](https://jira.mesosphere.com/browse/DCOS_OSS-2011) Update review screen volumes for Pods
- [DCOS-20070](https://jira.mesosphere.com/browse/DCOS-20070) Restores the close X on all form groups
- [DCOS-19403](https://jira.mesosphere.com/browse/DCOS-19403) Remove external volumes section from single container
- [DCOS-19401](https://jira.mesosphere.com/browse/DCOS-19401) Add external volumes to the types of volumes to single container
- [DCOS-19400](https://jira.mesosphere.com/browse/DCOS-19400) Rename local volumes component
- [DCOS_OSS-1783](https://jira.mesosphere.com/browse/DCOS_OSS-1783) Update Modals to match UI Kit

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-ui/releases/tag/v1.11.0-rc.9
  - [ ] Test Results: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2005/testReport/
  - [ ] Code Coverage (if available): https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2005/cobertura/
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by spahl** [comment]
Signed off for merge

**Comment by cdaw** [comment]
Signed off for merge

**Pull request merged**
