### PR TITLE
[master] Mergebot Automated Train PR - 2018-Jul-04-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3006 - Adds network information to be collected as part of diagnostic bundle

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot merge-it  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Ship It |Work In Progress |Request For Comment |Holding |Ready For Review] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ship It]

**Comment by urbanserj** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
