### PR TITLE
Scripts to create DC/OS compatible cloud images

### PR DESCRIPTION
**Pull request by malnick**
Continuation of https://github.com/dcos/dcos/pull/205

### CODE REVIEW

**Comment by malnick** [comment]
@spahl @lingmann This is ready for review.

**Comment by malnick** [comment]
@lingmann @spahl Should we close this? Merge it?

**Comment by spahl** [comment]
We need the automatic build of the image to be done before merging. Until then we keep it open.

**Comment by luhkevin** [comment]
What do these cloud images entail? Do they bake the entire DCOS suite into the image, or just install the initial dependencies?

**Comment by spahl** [comment]
They build a centos 7 ami that is compatible with our AWS cloudformation template. DC/OS is not installed on it by default but all the pre requirements that are needed.

**Comment by lingmann** [comment]
Replaced by #516

**Pull request closed without merging**
