### PR TITLE
Bump Mesos for 1.0.1 (pre-rc) and another fix cherry-picked from master.

### PR DESCRIPTION
**Pull request by adam-mesos**

### CODE REVIEW

**Comment by adam-mesos** [comment]
@spahl @cmaloney Sounds like we want these Mesos changes ASAP, so I prepared a branch of pre-rc 1.0.1 (plus Joris' O_SYNC patch)

**Comment by adam-mesos** [comment]
CI passes except for the flaky minuteman test. Ready to merge?
We'll be updating this again whenever the actual 1.0.1 rc1 comes out, but that could be days away.

**Comment by spahl** [comment]
Let's get them in. :ship:

**Comment by adam-mesos** [comment]
Merge me please

**Pull request merged**
