### PR TITLE
Update latest Installer UI SHA

### PR DESCRIPTION
**Pull request by jfurrow**
This includes:
* "Stage of Stage" UI Updates
* Telemetry and OAuth toggles
* Public agent form field

### CODE REVIEW

**Comment by malnick** [comment]
@jfurrow Is this still WIP?

**Comment by jfurrow** [comment]
@malnick No, this is ready to go!

**Comment by malnick** [comment]
@spahl Can we get an updated label for this PR?

**Comment by spahl** [comment]
:ship:

**Pull request merged**
