### PR TITLE
[1.12] Mergebot Automated Train PR - 2018-Oct-17-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3632 - [1.12] Bump dcos-net
* #3635 - [1.12] Lowercase metrics 
* #3646 - Bump dcos-log

> Updated the version 1.12.0-rc3.  Successor the previous version.

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-41675

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm  https://jira.mesosphere.com/browse/DCOS-41675

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
