### PR TITLE
Build teamcity windows

### PR DESCRIPTION
**Pull request by oprinmarius**
## High-level description

Adds Powershell equivalents for the Teamcity build scripts.

## Checklist for all PRs

  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by oprinmarius** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@oprinmarius  - How is this tested?

**Comment by cgawron1** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
Applying ship-it label as the changes affect teamcity in windows, and it was already tested before the last merge from master and bump-ee

**Pull request merged**
