### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Mar-28-00-29

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2656 - Update version to 1.10.6
* #2607 - Bumped Mesos SHA to the latest 1.4.x
* #2647 - Bump curl from 7.48 to 7.59 in dcos 1.10

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Extended Tests Triggered - https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_ManualTriggers_TriggerTrainBuilds&branch_DcOs_Open_ManualTriggers=pull%2F2673&tab=buildTypeStatusDiv

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
I updated the EE reference manually as bump-ee didn't give me update. (No mergebot changes were done. More of a transient issue with github/lambda)

**Comment by gpaul** [comment]
The cluster failed to become stable on teamcity/dcos/test/azure/arm:
https://teamcity.mesosphere.io/viewLog.html?buildId=1018481&buildTypeId=DcOs_Open_Test_IntegrationTest_AzureArm

I've re-triggered the build in case it was some AWS infrastructure flake.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-2313

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
Github's service api is b0rken at the moment.

```
2018-03-28 17:32:13,559 mergebot     INFO     GET /
2018-03-28 17:32:28,688 mergebot     INFO     POST /github
2018-03-28 17:32:28,688 mergebot     INFO     Handling event: fc7fb900-32ad-11e8-9e2e-7df4dcff19f8.
2018-03-28 17:32:28,840 mergebot     DEBUG    Failed with an Exception: runexpected response for 'https://api.github.com/repos/dcos/dcos/contents/mergebot-config.json': 403
```

**Comment by orsenthil** [comment]
It's not able get the config to verify permissions.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
Github is up again. :)

**Pull request merged**
