### PR TITLE
Do not require diagnostics on destroy.

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

This leads to weird situations when we want to destroy cluster but first we need to create a diagnostics bundle for it. It's especially annoying when you want to stop cluster creation and free resources but first need to finish cluster creation and then destroy it.

After merging this change we need to add step to our CI to generate diagnostics bundle even if previous step failed.

## Corresponding DC/OS tickets (required)

  - [D2IQ-65565](https://jira.d2iq.com/browse/D2IQ-65565)

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by janisz** [comment]
> If we do this we won't have a diagnostic bundle after each run. What we can do is remove the cluster.json dependency.

But `cluster.json` is required by `make ssh` which is used by diagnostics. After merging this I'll edit CI steps and add bundle creation as a step after `make test` and `make destroy` after all to run even if there was an error.

**Comment by jeschkies** [comment]
> After merging this I'll edit CI steps and add bundle creation as a step

You'll have the same issue then. I guess we could just hard code `cluster.json` instead of using `$<` as the effect is the same.

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @jongiddy @jeschkies @DominikDary

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @fatz

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required internal

**Pull request merged**
