### PR TITLE
Train 298 (base: master)

### PR DESCRIPTION
**Pull request by gauripowale**
PR's included:
#2257 : Fix error when custom check bins are provided during onprem install
#2228 : Admin Router: DRY up the AR code related to leader proxing
#2223 : Bumped `mesos-dns`.

### CODE REVIEW

**Comment by gauripowale** [comment]
@mesosphere-mergebot bump-ee

**Comment by gauripowale** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by mesosphere-teamcity** [comment]
Corresponding DC/OS PR: https://github.com/dcos/dcos/pull/2464

**Pull request merged**
