### PR TITLE
DCOS_OSS-5648: added prerequisites.zip; updated dcos_install.ps1

### PR DESCRIPTION
**Pull request by sergiimatusEPAM**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5648](https://jira.mesosphere.com/browse/DCOS_OSS-5648) Update Ansible Bootstrap roles to download/execute Windows installer.
- [DCOS_OSS-5647](https://jira.mesosphere.com/browse/DCOS_OSS-5647) Update Ansible Winagent role to invoke the dcos_install.ps1 on Windows nodes

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request review @DominikDary

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request review @orsenthil

**Comment by sergiimatusEPAM** [comment]
> Does `RunOnce` replace `dcos-install.ps1`? And does this mean that this first artifact that is downloaded to the agent is the same for all clusters, with no cluster-specific configuration?
> 
> Note that adding a zip file to the Git repo means that we can't see easily what is in it, and how it changes over time. We can't see a diff that tells us what specific lines may have changed.
> 
> This also dramatically increases the size of the Git repo, especially as we make changes to the contents of the zip file - adding multiple megabytes each time. Unlike Subversion, for Git each artifact in the entire history of the git repo gets downloaded whenever the repo is cloned.
> 
> I'd suggest looking at whether we can build the prerequisites.zip from a script that downloads specific URL's and creates the zip file, to restrict the size of the PR and provide better history.

1) No, it doesn't. `RunOnce.ps1` is the mechanism to start `winpanda.py` after server reboot, when `dcos_install.ps1`. You're correct, the `prerequisites.zip` is not cluster-specific. It's single one.
2) The zip file is just 6.5 MB. If there is concern, I will look on to build this

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request review @DominikDary

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot request review @DominikDary

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot changelog-not-required as "existing" enhancements to Windows BETA

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot label Ship It

**Comment by sergiimatusEPAM** [comment]
@mesosphere-mergebot label ship it

**Comment by cgawron1** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Pull request merged**
