### PR TITLE
chore(dcos-ui): update package

### PR DESCRIPTION
**Pull request by bstavroulakis**
## High-level description

Update the DC/OS UI package to include the latest fixes, improvements and features.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

- [DCOS-20247](https://jira.mesosphere.com/browse/DCOS-20247) Fix zone and region column
- [DCOS-20498](https://jira.mesosphere.com/browse/DCOS-20498) add broken link finding script
- [DCOS_OSS-2062](https://jira.mesosphere.com/browse/DCOS_OSS-2062) Change debug message from danger to warning
- [DCOS-20939](https://jira.mesosphere.com/browse/DCOS-20939) add version query
- [DCOS-19693](https://jira.mesosphere.com/browse/DCOS-19693) fix labels reducer to accept empty strings
- [DCOS-20948](https://jira.mesosphere.com/browse/DCOS-20948) keep unknown attributes
- [DCOS-20978](https://jira.mesosphere.com/browse/DCOS-20978) update to correct link for install cli
- [DCOS-20975](https://jira.mesosphere.com/browse/DCOS-20975) node link throwing error
- [DCOS-20956](https://jira.mesosphere.com/browse/DCOS-20956) disable id field on service edit
- [DCOS-21063](https://jira.mesosphere.com/browse/DCOS-21063) set default value for dsl Filters
- [DCOS-21115](https://jira.mesosphere.com/browse/DCOS-21115) fallback to type: "object" for config
- [DCOS-19301](https://jira.mesosphere.com/browse/DCOS-19301) open to form when deploying
- [DCOS-21044](https://jira.mesosphere.com/browse/DCOS-21044) flag all SDK tasks

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-ui/releases/tag/v1.11.0-rc.13)
  - [x] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2864/)
  - [ ] Code Coverage (if available): [link to code coverage report]()
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by bstavroulakis** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label {Ready For Review}

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot pr-status-checks

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by orlandohohmeier** [comment]
See https://github.com/dcos/dcos/pull/2470 for the respective master PR.

**Pull request merged**
