### PR TITLE
Bumped Mesos to latest 1.2.x (f8706e5).

### PR DESCRIPTION
**Pull request by karya0**
## High-level description

Bumped Mesos to latest 1.2.x (f8706e5).

## Corresponding DC/OS tickets (obligatory)
* [DCOS_OSS-1897](https://jira.mesosphere.com/browse/DCOS_OSS-1897)

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
    Tests covered by Mesos test suite.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Mesos Changelog](https://github.com/mesosphere/mesos/compare/def524d5bf9c8d02a4307aa745e654706a848b33...7fdb5cb179a15a63240590a2c3e0a6cdbdab89b5)
  - [ ] Test Results:
  - [ ] Code Coverage
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by karya0** [comment]
@mesosphere-mergebot bump-ee

**Comment by karya0** [comment]
The `teamcity/dcos/test/aws/cloudformation/simple` failure due to `ProviderError: An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [DefaultInstanceType] do not exist in the template` seems to be a known problem and not caused by this PR.

**Comment by karya0** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by karya0** [comment]
@vinodkone @adam-mesos: When you get a chance, can you fellas review this PR?

**Comment by jgehrcke** [comment]
We need to have a DC/OS JIRA ticket that tracks this change, and it must be linked in this pull request.

**Comment by karya0** [comment]
@jgehrcke Updated PR with https://jira.mesosphere.com/browse/DCOS_OSS-1897

**Pull request merged**
