### PR TITLE
Update DC/OS configuration to remove marathon GPU defaults on installation

### PR DESCRIPTION
**Pull request by meln1k**
## High-level description

Update of the DC/OS config generator to remove the default value for gpu_scheduling_behavior for marathon

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [MARATHON-8090](https://jira.mesosphere.com/browse/MARATHON-8090) Update DC/OS configuration to set appropriate marathon defaults on installation.

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): 
  - [x] Test Results: 
  - [x] Code Coverage (if available):

### CODE REVIEW

**Comment by meln1k** [comment]
@mesosphere-mergebot bump-ee

**Comment by meln1k** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
We are reverting GPU defaults in 1.11. The reason isn't given, the statement on revert is mentioned here - https://jira.mesosphere.com/browse/MARATHON-8090?focusedCommentId=146718&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-146718

**Comment by urbanserj** [comment]
@orsenthil could you please check why only EE PR was merged and add this PR to the next train manually?

**Comment by orsenthil** [comment]
@urbanserj  - We are doing a poor job of reviewing our trains. :(

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
