### PR TITLE
Update Marathon to v1.4.11

### PR DESCRIPTION
**Pull request by ichernetsky**
## High-level description

Various fixes and optimizations.

## Corresponding DC/OS tickets (obligatory)

- [DCOS-20098](https://jira.mesosphere.com/browse/DCOS-20098) - Release Marathon v1.4.11

## Other tickets

- [MARATHON-7992](https://jira.mesosphere.com/browse/MARATHON-7992) - Validation errors on root group in large clusters can lead Marathon to crash.
- [MARATHON-7974](https://jira.mesosphere.com/browse/MARATHON-7974) - If a non-super-user was explicitly given access to some resource, such as GroupResources, they were denied. This has been resolved.
- [MARATHON-7962](https://jira.mesosphere.com/browse/MARATHON-7962) - Enable killGracePeriodSeconds for Pods.
- [MARATHON_EE-1770](https://jira.mesosphere.com/browse/MARATHON_EE-1770) - Optimized port assignments and performance enhancements.
- [MARATHON_EE-1764](https://jira.mesosphere.com/browse/MARATHON_EE-1764) - Optimized port assignments and performance enhancements.

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Github comparison](
https://github.com/mesosphere/marathon/compare/v1.4.9...v1.4.11)
  - [x] Test Results: [CI Job](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/releases%252F1.4/124/)
  - [ ] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by ichernetsky** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
@mesosphere-mergebot label ready for review

**Comment by ichernetsky** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
