### PR TITLE
Mergebot Train - May 4th

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

*  Add support for CoreOS 1688.4.0 #2833
* Check that ifconfig is available on cluster nodes #2819
* Add owners from the Mesos pool of committers. #2816

* Add MTU configuration for vtep1024 #2793
* Add checks for ftype=1 for docker and mesos directories if using XFS #2768
* Increase executor reregistration timeout to 10 seconds. #2693
* accessability to zk is requirement for a marathon start #1690
* Check that ifconfig is available on cluster nodes #2819
* Prune owners - #2813

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot merge-it  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Ship It |Work In Progress |Ready For Review |Request For Comment |Holding] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Hi @gpaul  / @jgehrcke  / @adamtheturtle  - Please ensure if we need to add any thing to CHANGES.md. I tried pinging individual PRs to determine and we didn't have anything.  Additional review will be helpful.

**Comment by gpaul** [comment]
It looks OK to me, but I'm vague on what constitutes "notable changes." The heuristic I use is "If I was operating DC/OS, would I want to know about this commit?" These changes seem mostly internal to me.

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1902

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Reverted - * [master] Bump Mesos to nightly master a1c6a7a #2808

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
