### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Jul-31-10-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3128 - [Backport][1.10] Adds dataDir to ucr bridge cni configuration
* #3163 - 1.10: Accessibility to zk is a requirement for Marathon to start
* #3167 - Bump the timeout to 10 minutes

> Log - Manually added:  Tue Jul 31 14:40:12 PDT 2018

* #3160 - Prune owners.json
* #3158 - Bump dcos-ui to 1.10.9-rc.1

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by branden** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status mergebot/enterprise/build-status/aggre https://jira.mesosphere.com/browse/DCOS-39073

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status mergebot/enterprise/build-status/aggregate https://jira.mesosphere.com/browse/DCOS-39073

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
