### PR TITLE
chore(dcos-ui): update package

### PR DESCRIPTION
**Pull request by ahoskins**
## High-level description

Update the DC/OS UI package to include the latest fixes, improvements, and features.

## Corresponding DC/OS tickets (obligatory)

- [DCOS-21122](https://jira.mesosphere.com/browse/DCOS-21122) fixes focus/change/blur behaviour
- [DCOS-21229](https://jira.mesosphere.com/browse/DCOS-21229) Sort pods with zones & regions
- [DCOS-21229](https://jira.mesosphere.com/browse/DCOS-21229) fix sorting in tables

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2927/testReport/
  - [x] Code Coverage (if available): [link to code coverage report]: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/2927/testReport/
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by ahoskins** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Hi @ahoskins  - Will be this the final 1.11.0 GA PR?
Also, `packages/dcos-ui/buildinfo.json` seems to have a conflicts. Can you update your branch after resolving the conflict and please push again.

**Comment by ahoskins** [comment]
@orsenthil Yes, this is our final PR for 1.11.0 GA. I've also resolved conflicts.

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot [Ready For Review]

**Comment by ichernetsky** [comment]
Does this build contain the fix for DCOS-19219?

**Comment by orlandohohmeier** [comment]
@ichernetsky  yes, we weren't able to update the changelog but these are all of the issues addressed with this PR:

- [DCOS-19219](https://jira.mesosphere.com/browse/DCOS-19219) fix mount paths for pods
- [DCOS-20080](https://jira.mesosphere.com/browse/DCOS-20080) fix Review & Run button
- [DCOS-20673](https://jira.mesosphere.com/browse/DCOS-20673) fixes system test setup
- [DCOS-20976](https://jira.mesosphere.com/browse/DCOS-20976) fixes naming terminal to command for cli install on windows 
- [DCOS-21122](https://jira.mesosphere.com/browse/DCOS-21122) fixes focus/change/blur behaviour
- [DCOS-21229](https://jira.mesosphere.com/browse/DCOS-21229) Sort pods with zones & regions
- [DCOS-21229](https://jira.mesosphere.com/browse/DCOS-21229) fix sorting in tables
- [DCOS_OSS-1553](https://jira.mesosphere.com/browse/DCOS_OSS-1553) fix vip input for virtual networks with multi-container services.

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot override-status https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Pull request merged**
