### PR TITLE
  chore: Bump DC/OS UI v5.4.0

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [D2IQ-ID](https://jira.d2iq.com/browse/D2IQ-ID) JIRA title / short description.

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @jongiddy @pierrebeitz  @DominikDary

**Review by DominikDary — APPROVED** [review]

**Review by DominikDary — APPROVED** [review]

**Comment by DominikDary** [comment]
@mesosphere-mergebot sync

**Comment by DominikDary** [comment]
@mesosphere-mergebot changelog-not-required intermediate ui update.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
