### PR TITLE
[Experimental] bump navstar

### PR DESCRIPTION
**Pull request by GoelDeepak**
This PR is just to create a DCOS build.

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@GoelDeepak  - should this be closed?

**Comment by orsenthil** [comment]
Closing this. Please reopen, if required.

**Pull request closed without merging**
