### PR TITLE
Fix CentOS 7 AMI journald directory permissions and rebuild AMIs

### PR DESCRIPTION
**Pull request by lloesche**
## High Level Description

Fixes CentOS 7 AMI journald log permissions

## Related Issues

  - [DCOS_OSS-711](https://jira.mesosphere.com/browse/DCOS_OSS-711) Logging API integration tests fail on CentOS 7.3.

### CODE REVIEW

**Comment by lloesche** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@lloesche  and @branden  - the upgrade integration tests failed for this PR.

```
[14:33:32]	[install dcos] ====> 10.10.0.87:22 FAILED
[14:33:32]	[install dcos]      TASK:
[14:33:32]	[install dcos] /usr/bin/ssh -oConnectTimeout=10 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oBatchMode=yes -oPasswordAuthentication=no -p22 -i genconf/ssh_key -tt centos@10.10.0.87 sudo bash /opt/dcos_install_tmp/dcos_install.sh master
[14:33:32]	[install dcos]      STDERR:
[14:33:32]	[install dcos]           Connection to 10.10.0.87 closed.
[14:33:32]	[install dcos]      STDOUT:
[14:33:32]	[install dcos]           Starting DC/OS Install Process
[14:33:32]	[install dcos] 
[14:33:32]	[install dcos]           Running preflight checks
[14:33:32]	[install dcos] 
[14:33:32]	[install dcos]           Creating directories under /etc/mesosphere
[14:33:32]	[install dcos] 
[14:33:32]	[install dcos]           Creating role file for master
[14:33:32]	[install dcos] 
[14:33:32]	[install dcos]           Configuring DC/OS
[14:33:32]	[install dcos] 
[14:33:32]	[install dcos]           Setting and starting DC/OS
[14:33:32]	[install dcos] 
[14:33:32]	[install dcos]           Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

**Comment by branden** [comment]
Looks like the upgrade test is failing because DC/OS 1.8.8 is failing to install on Centos 7.3. Still drilling down into exactly why. Docker daemon log:

```
[centos@ip-10-10-0-12 ~]$ journalctl -u docker.service | head -n 25
-- Logs begin at Thu 2017-03-09 23:45:27 UTC, end at Fri 2017-03-10 00:11:34 UTC. --
Mar 09 23:45:54 ip-10-10-0-12 systemd[1]: Starting Docker Application Container Engine...
Mar 09 23:45:54 ip-10-10-0-12 ip[974]: Cannot find device "docker0"
Mar 09 23:46:02 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:02.325565617Z" level=info msg="libcontainerd: new containerd process, pid: 4050"
Mar 09 23:46:04 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:04.097046933Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Mar 09 23:46:04 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:04.099440209Z" level=info msg="Loading containers: start."
Mar 09 23:46:04 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:04.636417607Z" level=info msg="Firewalld running: false"
Mar 09 23:46:05 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:05.022446802Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Mar 09 23:46:05 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:05.085593487Z" level=info msg="Loading containers: done."
Mar 09 23:46:05 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:05.868108072Z" level=info msg="Daemon has completed initialization"
Mar 09 23:46:05 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:05.868151249Z" level=info msg="Docker daemon" commit=092cba3 graphdriver=overlay version=1.13.1
Mar 09 23:46:05 ip-10-10-0-12 dockerd[985]: time="2017-03-09T23:46:05.876825165Z" level=info msg="API listen on /var/run/docker.sock"
Mar 09 23:46:05 ip-10-10-0-12 systemd[1]: Started Docker Application Container Engine.
Mar 09 23:49:26 ip-10-10-0-12 systemd[1]: Stopping Docker Application Container Engine...
Mar 09 23:49:27 ip-10-10-0-12 systemd[1]: Starting Docker Application Container Engine...
Mar 09 23:49:27 ip-10-10-0-12 ip[12218]: Cannot find device "docker0"
Mar 09 23:49:27 ip-10-10-0-12.us-west-2.compute.internal docker[12234]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
Mar 09 23:49:27 ip-10-10-0-12.us-west-2.compute.internal docker[12234]: no sockets found via socket activation: make sure the service was started by systemd
Mar 09 23:49:27 ip-10-10-0-12.us-west-2.compute.internal systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Mar 09 23:49:27 ip-10-10-0-12.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Mar 09 23:49:27 ip-10-10-0-12.us-west-2.compute.internal systemd[1]: Unit docker.service entered failed state.
Mar 09 23:49:27 ip-10-10-0-12.us-west-2.compute.internal systemd[1]: docker.service failed.
Mar 09 23:49:42 ip-10-10-0-12.us-west-2.compute.internal systemd[1]: docker.service holdoff time over, scheduling restart.
Mar 09 23:49:42 ip-10-10-0-12.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Mar 09 23:49:42 ip-10-10-0-12.us-west-2.compute.internal ip[12327]: Cannot find device "docker0"
[centos@ip-10-10-0-12 ~]$
```

**Comment by branden** [comment]
This should be closed in favor of #1350.

**Pull request closed without merging**
