### PR TITLE
Testing m4 xlarge

### PR DESCRIPTION
**Pull request by amitaekbote**
### Default AWS template instance type change

Use m4.xlarge as default instance type for aws templates
- The descriptions/wording in the template had to be modified because we were hitting aws cloudformation template size limits. 
- The ami's are generated from:
   - https://teamcity.mesosphere.io/viewLog.html?buildId=774490&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImage
    - https://teamcity.mesosphere.io/viewLog.html?buildId=774489&tab=buildResultsDiv&buildTypeId=DcosIo_Dcos_BuildCloudBaseImages_AwsBuildAndPublishCentOS7baseImagesForGovcloud
Lukas has tested these ami's. 

m4.xlarge doesnt work with only one test for data agility which is a low priority issue and does not block this pr - https://jira.mesosphere.com/browse/INFINITY-2428 

### Default OS version updates

* CoreOS version unchanged at 1235.12.0 (just updating from m3 AMI's to m4 AMI's)
* CentOS 7.3 image updated to include latest CentOS 7.3 security patches & bug fix updates

## Related Issues

 https://jira.mesosphere.com/browse/OPS-684

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@mellenburg @lloesche this is ready for review

**Comment by amitaekbote** [comment]
@mesosphere-mergebot bump-ee

**Comment by lloesche** [comment]
The NATInstance is still m3 type. If we update all nodes to m4 should we update the NATInstance as well? That would also fix the current failure where DC/OS fails to start up in eu-central-1 1 out of 3 times because the new AZ eu-central-1c doesn't support m3 anymore.

**Comment by lloesche** [comment]
LGTM - I tested an EE simple multimaster and an EE EL7 Zen 3 cluster.
:shipit:

**Comment by lingmann** [comment]
Updated the description with the OS specific delta. This should be in the 1.11 release notes.

**Pull request merged**
