### PR TITLE
Removing dcos-metrics and using azure for releases.

### PR DESCRIPTION
**Pull request by DominikDary**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5589](https://jira.mesosphere.com/browse/DCOS_OSS-5589) Remove dcos-metrics

## Related tickets (optional)

  - [DCOS_OSS-5556](https://jira.mesosphere.com/browse/DCOS_OSS-5556) Build Telegraf for WIndows packages
 - [DCOS-58008](https://jira.mesosphere.com/browse/DCOS-58008) Port the open source metrics module to Windows

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by DominikDary** [comment]
@mesosphere-mergebot request-review  cgawron1

**Comment by DominikDary** [comment]
@mesosphere-mergebot request-review orsenthil

**Comment by DominikDary** [comment]
@mesosphere-mergebot changelog-not-required  fixing build artifact upload for windows

**Comment by orsenthil** [comment]
Hi @DominikDary  - LGTM.

Please add a JIRA to the Github text that explains.

* Why the dcos-metrics for windows is removed.

* Adding the JIRA will also help track with the FixVersions that is used in release notes, etc.

Thank you!

**Comment by DominikDary** [comment]
> Hi @DominikDary - LGTM.
> 
> Please add a JIRA to the Github text that explains.
> 
>     * Why the dcos-metrics for windows is removed.
> 
>     * Adding the JIRA will also help track with the FixVersions that is used in release notes, etc.
> 
> 
> Thank you!

@orsenthil done, provided the corresponding Jira as well 2 other related tickets.

**Pull request merged**
