### PR TITLE
Mergebot's manual test feature: addition to mergebot-config.json

### PR DESCRIPTION
**Pull request by AliakseiKhomchanka**
This PR adds new fields to mergebot-config.json related to the upcoming manual test trigger feature.

### CODE REVIEW

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
The test feature needs to be tested. merging this directly enable the config update.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
