### PR TITLE
Train 264 (master)

### PR DESCRIPTION
**Pull request by margaret**
## 🚂 :two: :six: :four: :train: (master)

This one has most of the PRs on the bump-ee

https://github.com/dcos/dcos/pull/2126 – **Enable override-status**
> DCOS-19387 - Mergebot to support overriding status

### CODE REVIEW

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot label ready for review

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
