### PR TITLE
[1.9.5] Train 225

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 225 which is supposed to land for the 1.9.5 release. It contains:

* #1942 
* #1946

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
`installer-cli-test` does not report back. Is that known / a problem?

**Comment by jgehrcke** [comment]
The `mergebot/enterprise/build-status/aggregate` failure is fine, after manual inspection.

**Comment by mellenburg** [comment]
@jgehrcke the failure in upgrade test is a failure by the onprem installer to deploy the INITIAL cluster. The upgrade never even ran: Job for docker.service failed because the control process exited '
E                        'with error code. See "systemctl status docker.service" and '

**Comment by mellenburg** [comment]
@jgehrcke The issue here is that in the launch config used, cent-os-7-dcos-prereqs was used as a OS, but this OS has docker installed such that it borks the install. Thus, do not use the prereqs image for 1.8.X builds

**Comment by mellenburg** [comment]
Here is a rerun of that test with the "correct" parameters: https://teamcity.mesosphere.io/viewQueued.html?itemId=794476

**Comment by mellenburg** [comment]
@jgehrcke new problem: this test now includes Pods in the setup. if setup happens in 1.8 then there are no pods. I think we can push a super fast fix for this....

**Comment by mellenburg** [comment]
PR is about to merge: https://github.com/mesosphere/advanced-tests/pull/7

**Comment by mellenburg** [comment]
Ok, pods are now optional in the test, running again: https://teamcity.mesosphere.io/viewLog.html?buildId=794663&

**Comment by mellenburg** [comment]
Finally got the configuration right on the upgrade test: https://teamcity.mesosphere.io/viewLog.html?buildId=794986&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_UpgradeTest

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
