### PR TITLE
[master] Mergebot Automated Train PR - 2018-Sep-25-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3496 - AR [master forward-port]: add 'Connection: close' header  DCOS-42098

> Removed / Ignored.

* #3460 - Bump DC/OS UI to v2.21.8 (Merged already. Brings in 0 diff).

### CODE REVIEW

**Comment by orsenthil** [comment]
#3460 - Bump DC/OS UI to v2.21.8 - was already merged. That's why we have 0 files in the diff. We should update this train PR with other ship-it labelled PRs, and we could merge this train.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud 
 https://jira.mesosphere.com/browse/DCOS-41386

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@cprovencher - For some reason the merge did not close the PRs - https://github.com/dcos/dcos/pull/3496

**Pull request merged**
