### PR TITLE
Train 208

### PR DESCRIPTION
**Pull request by cprovencher**
#1827 - Admin Router: Prevent forwarding dcos-* cookies to upstreams
#1840 - Adding skip checks flag to the upgrade script
#1848 - add journald directory ownership/permissions check

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
`mergebot/enterprise/build-status/aggregate` is failing as of known flake in the downstream CI.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
