### PR TITLE
Update version to 1.9.7

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Update 1.9 version to 1.9.7

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
Merging, since this is just a version update.

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
