### PR TITLE
[master] Mergebot Automated Train PR - 2018-Apr-04-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2648 - Bump curl from 7.48 to 7.59 in dcos 1.12/master
* #2689 - fix windows docker file dependencies

### CODE REVIEW

**Comment by paulcallen** [comment]
@orsenthil looks like there needs to be an override on the rexray tests

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple 
 https://jira.mesosphere.com/browse/DCOS_OSS-2310

**Comment by orsenthil** [comment]
@paulcallen  - Thanks for the ping. Yes, I or Branden could have helped you here.

**Comment by paulcallen** [comment]
@orsenthil thanks for your help moving it along

**Comment by paulcallen** [comment]
@orsenthil something else failed. I don't have permission to see the specifics though.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
