### PR TITLE
Bump Telegraf to have Mesos overlay module metrics collected

### PR DESCRIPTION
**Pull request by ichernetsky**
## High-level description

Bump the Telegraf version in order to have Mesos overlay module metrics collected and pushed to Prometheus.

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5323](https://jira.mesosphere.com/browse/DCOS_OSS-5323) Adjust Telegraf's Mesos plugin to collect overlay metrics from Mesos

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/dcos/dcos-mesos-modules/compare/4dba7d98691a4f9970b9421159c6a4cb1f49725e...cfe8725d26ea8092caef014bde284d04994e3a32)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [x] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-cluster-ops/job/telegraf/job/telegraf-dcos-pulls/278/)
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by philipnrmn** [comment]
If you want these metrics available by default, you should enable these metrics by adding the `overlay` config to each occurrence of `[inputs.mesos]` in [dcos-config.yaml](https://github.com/dcos/dcos/blob/master/gen/dcos-config.yaml).  

https://github.com/dcos/dcos/blob/master/gen/dcos-config.yaml#L2432-L2444
https://github.com/dcos/dcos/blob/master/gen/dcos-config.yaml#L2620-L2634
https://github.com/dcos/dcos/blob/master/gen/dcos-config.yaml#L2769-L2783

You should probably add an integration test to [test_metrics.py](https://github.com/dcos/dcos/blob/master/packages/dcos-integration-test/extra/test_metrics.py)

**Comment by ichernetsky** [comment]
@philipnrmn, thanks. I was 100% sure that this step wasn't required because these tests were added in the PR that bumped the Mesos module itself, and they passed.

**Comment by ichernetsky** [comment]
@philipnrmn could you please kindly re-review these two PRs?

**Comment by ichernetsky** [comment]
@mesosphere-mergebot label Ready For Review

**Pull request merged**
