### PR TITLE
Train 142

### PR DESCRIPTION
**Pull request by orsenthil**
#1240 - Provide an Ability to give AWS Stack name prefix
#1275 - Fix style: python class definition statements
#1342 - Admin Router: Deduplication of `cache.lua/agent.lua/marathon-leader.lua` and friends
#1361 - Fix logrotate URL and sha1
#1362 - Add tags to pkgpanda swagger
#1373 - Check CI flags in upgrade tests
#1374 - Fix logging statements

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@lingmann , @spahl , @alberts , @adam-mesos  - this is ready for review / ready to ship.

**Comment by adam-mesos** [comment]
@orsenthil This all goes into master (1.10+), but should any of it be backported to 1.9?
cc: @spahl

**Comment by orsenthil** [comment]
@adam-mesos - that will not be my call. That will be for @spahl to take.

**Comment by lingmann** [comment]
@orsenthil please add high level description for each PR in the issue summary (makes it easier for a high level review).

@spahl some of these are likely needed for 1.9. for example #1373 which enables upgrade tests to succeed. Have any 1.10 features landed yet? If not I propose we cut the next 1.9 point release off of master.

**Comment by orsenthil** [comment]
@lingmann  - done for both open and ee.

**Comment by lingmann** [comment]
@orsenthil @vespian @mellenburg @karlkfi @amitaekbote can all of you please review your PR's in this train for work that should be backported to 1.9? If a PR should be backported, please add a comment or annotate in the train summary. Thanks!

**Comment by amitaekbote** [comment]
#1373 - Check CI flags in upgrade tests, should get back ported

**Comment by vespian** [comment]
@lingmann EE Train has changes that would make my life much easier if they got into 1.9 EE You can find them here: https://github.com/mesosphere/dcos-enterprise/pull/715 These changes are already in Open.

**Pull request merged**
