### PR TITLE
Train 262 base:master

### PR DESCRIPTION
**Pull request by mellenburg**
Includes:
[bump dcos-log sha](https://github.com/dcos/dcos/pull/1935)
[bump dcos-test-utils](https://github.com/dcos/dcos/pull/2124)

### CODE REVIEW

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mellenburg  - Please do a manual rebase on EE side.

The sequence that happened was not recognized by mergebot.

**Comment by mellenburg** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
