### PR TITLE
[Backport] [1.12-beta1] bump mesos-module to bring in fix for SOAK-118

### PR DESCRIPTION
**Pull request by GoelDeepak**
## High-level description

This patch brings in two fixes:
1. The new docker version (18.x) has changed its iptables CHAIN name from `DOCKER-ISOLATION` to `DOCKER-ISOLATION-STAGE-1` and `DOCKER-ISOLATION-STAGE-2`. As DC/OS overlay modifies docker isolation rules, the change in CHAIN name has broken the DC/OS overlay. This patch bumps mesos-module which fixes the issue

2. The dcos-net watchdog has been modified to restart the stuck Erlang VM. This fix should work as a good workaround till we have the actual fix for the SSL deadlock issue from the Erlang community

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-38600](https://jira.mesosphere.com/browse/DCOS-38600) Deadlock when SSL sockets are simultaneously sending/receiving data and buffers are full
  - [SOAK-118](https://jira.mesosphere.com/browse/SOAK-118) - Elastic does not deploy to Soak 112 Strict

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): 
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
