### PR TITLE
Bump Marathon to 1.11.24

### PR DESCRIPTION
**Pull request by pierrebeitz**
## Corresponding DC/OS tickets (required)

  - [MARATHON-8771](https://jira.d2iq.com/browse/MARATHON-8771)

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot backport 2.2

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ship It

**Comment by pierrebeitz** [comment]
labeled with ship it as all tests are green

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
The sync summary shows that the status is successful

```
             'teamcity/dcos/test/terraform/aws/onprem/static/strict/group/1': ('success',
                                                                               '2020-11-13T11:51:03Z'),
```

However the UI is showing as Pending!

**Comment by pierrebeitz** [comment]
@orsenthil i'm a 100% sure that about 75 minutes ago the UI reported that job as green.

**Comment by orsenthil** [comment]
Since time you alerted and I saw this. 

* The TC was Green. The API of status check returned success.
* But the Github UI was showing pending, which is the problem.

image

**Pull request merged**
