### PR TITLE
Train 169

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

* Fix Partial download of dcos_generate_config.sh results in unrecoverable error that requires manual intervention. #1516
* bump(DCOS-UI): latest bits #1540
* Update DC/OS to the latest cosmos #1591

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mellenburg:

```
[20:34:39]	[Step 4/5] [2017-06-01 03:34:39,543|dcos_test_utils.aws|WARNING]: No recognized resources found; using generic stack
[20:34:39]	[Step 4/5] Failed to execute script cli
[20:34:39]	[Step 4/5] Traceback (most recent call last):
[20:34:39]	[Step 4/5] File "dcos_launch/cli.py", line 154, in <module>
[20:34:39]	[Step 4/5] File "dcos_launch/cli.py", line 146, in main
[20:34:39]	[Step 4/5] File "dcos_launch/cli.py", line 135, in do_main
[20:34:39]	[Step 4/5] File "dcos_launch/util.py", line 98, in test
[20:34:39]	[Step 4/5] File "dcos_launch/onprem.py", line 138, in describe
[20:34:39]	[Step 4/5] File "dcos_launch/onprem.py", line 44, in get_onprem_cluster
[20:34:39]	[Step 4/5] File "dcos_launch/aws.py", line 148, in get_hosts
[20:34:39]	[Step 4/5] AttributeError: 'CfStack' object has no attribute 'get_host_ips'
```

**Comment by orsenthil** [comment]
The previous failure were due to AWS not returning cloud stack. I have re-triggered our tests.

**Comment by orsenthil** [comment]
@mellenburg  @lingmann @spahl  - please review and merge this.

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it ( it's already merged).

**Pull request merged**
