### PR TITLE
Train 331

### PR DESCRIPTION
**Pull request by gauripowale**
Added following PRs:
#1914: Support adding custom check executables during on-prem installation

### CODE REVIEW

**Comment by gauripowale** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by gauripowale** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
