### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Mar-14-10-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2602 - [1.10] Bump navstar
*  #2621 - Avoid python dependency break for python-dateutil

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@mesosphere-mergebot override-status 
teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/QUALITY-1956

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
