### PR TITLE
[1.10] Bump dcos-diagnostics

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

This changes add better error handling and updates the vendor folder packages:

* github.com/coreos/go-systemd
* github.com/godbus/dbus

Full list of changes https://github.com/dcos/dcos-diagnostics/compare/f0e7cc0eddce6672f45fbb930c0f967023a99fb1...1a532f890b7e05b604309e53b0b5d8f67d1f2940

Bacport:

* https://github.com/dcos/dcos/pull/2389
* https://github.com/dcos/dcos/pull/2390

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4064](https://jira.mesosphere.com/browse/DCOS_OSS-4064) Bump dcos-diagnostics in 1.10

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@collinvandyck @amitaekbote Can you take a look?

**Comment by janisz** [comment]
@branden @jimenez Can you take a look?

**Comment by gpaul** [comment]
Please add the link to the diff in the PR description that is required for component bumps. Without looking at the diff, approving the PR is very difficult.

**Comment by janisz** [comment]
@gpaul Added https://github.com/dcos/dcos-diagnostics/compare/f0e7cc0eddce6672f45fbb930c0f967023a99fb1...1a532f890b7e05b604309e53b0b5d8f67d1f2940

**Comment by gpaul** [comment]
OK - I'm approving, but are you sure you want to bump to a really really old version of dcos-diagnostics? You're bumping to a commit that was made in January 2018...

**Pull request merged**
