### PR TITLE
Enable continuous-integration/jenkins/pr-head as a required status check

### PR DESCRIPTION
**Pull request by ahairape**
## High-level description

This PR enables continuous-integration/jenkins/pr-head as a required status check

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
https://jira.mesosphere.com/browse/DCOS-51360

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by ahairape** [comment]
@jgehrcke @mhrabovcin @adamtheturtle @jongiddy PTAL. Thank you.

**Comment by adamtheturtle** [comment]
When is this picked up @ahairape ? Please can you fill in the description field about the changelog? (explaining that this is internal-only).

**Comment by jongiddy** [comment]
I think someone from DevProd (@orsenthil ?) should provide the second review.

**Comment by ahairape** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by ahairape** [comment]
@orsenthil Could you take a look please? Thank you

**Comment by orsenthil** [comment]
Hi @ahairape  - Thanks for this change!

I wanted to dig a little bit into this job itself. I have not looked yet, but what we should look for is.

Is there any moving dependency in this job? Does it depend on the sources outside of  DC/OS? Does it rely on the head of any docker image  that is continuously updated by an external Repo?

If it is a No to all these, then +1 to this change.

**Pull request merged**
