### PR TITLE
tests: consolidate marathon purge fixture

### PR DESCRIPTION
**Pull request by jgehrcke**
See code comments in the patch; downstream this will address https://jira.mesosphere.com/browse/DCOS-45746.

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by gpaul** [comment]
approved for fast merge

**Comment by jgehrcke** [comment]
This PR pair unbreaks downstream master. Moving forward.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
This needs to be back-ported to 1.12 branch!.

**Pull request merged**
