### PR TITLE
2.1 - bump Marathon to 1.9.109

### PR DESCRIPTION
**Pull request by timcharper**
## High-level description

This fixes a Marathon migration error that would occur during upgrade if a Marathon deployment was in progress during the upgrade attempt.

## Corresponding DC/OS tickets (required)

JIRA Issues:
  - [MARATHON-8712](https://jira.mesosphere.com/browse/MARATHON-8712)
  - [MARATHON-8711](https://jira.mesosphere.com/browse/MARATHON-8711)
  - [MARATHON-8713](https://jira.mesosphere.com/browse/MARATHON-8713)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [c2204b998..b9c866838](https://github.com/mesosphere/marathon/compare/c2204b998...b9c866838)

### CODE REVIEW

**Comment by timcharper** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by timcharper** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot changelog-not-required changes-md will added as a follow up

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot changelog-not-required will be added as a followup

**Pull request merged**
