### PR TITLE
[D2IQ-67995] Remove DC/OS Windows Packages and their dependencies

### PR DESCRIPTION
**Pull request by vadymzagorodko**
## High-level description

This PR should cleanup and mainly remove the windows packages, ps build scripts, nssm files and remove the packages from the treeinfo file.

## Corresponding DC/OS tickets (required)

  - [D2IQ-67995](https://jira.d2iq.com/browse/D2IQ-67995) Remove DC/OS Open Windows Packages.

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by vadymzagorodko** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by vadymzagorodko** [comment]
@mesosphere-mergebot request-review @jongiddy

**Comment by vadymzagorodko** [comment]
@mesosphere-mergebot changelog-not-required Windows isn't a part of DC/OS release anymore

**Comment by vadymzagorodko** [comment]
dcos_e2e._subprocess_tools:ImportError: cannot import name 'upgrade_win' - upgrade_win isn't exist anymore, looks like tests have to be reviewed and fixed

**Comment by jongiddy** [comment]
Rebasing onto current `master` should fix this

**Comment by DominikDary** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
