### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-Jan-23-14-17

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2312 - Update DCOS-UI to 1.10.3 
* #2331 - Metronome 0.3.4 bump for DC/OS 1.10

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@urbanserj  - The `teamcity/dcos/test/aws/onprem/static-redhat` failure is related to https://jira.mesosphere.com/browse/DCOS-14948 - Could you please help me to override this?

**Comment by urbanserj** [comment]
@mesosphere-mergebot override teamcity/dcos/test/aws/onprem/static-redhat DCOS-14948

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat DCOS-14948

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat DCOS-14948

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat DCOS-14948

**Comment by mellenburg** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat DCOS-14948

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
