### PR TITLE
Admin Router: AR-NEXT #5

### PR DESCRIPTION
**Pull request by vespian**
## High Level Description

This PR is an aggregate of multiple smaller PRs. PRs included:
~~https://github.com/mesosphere/dcos/pull/48~~

Failures in all individual PRs (both EE and Open) are expected.

@orsenthil As agreed in https://github.com/dcos/dcos/pull/1887#issuecomment-326331781 I have rebase-merged the sub-PRs.

## Related Issues

See individual PRs

## Related PRs

EE DC/OS PR: https://github.com/mesosphere/dcos-enterprise/pull/1415

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot label work in progress

**Comment by vespian** [comment]
smoke-test/dcos-docker reported in https://jira.mesosphere.com/browse/DCOS-17652

**Comment by vespian** [comment]
As per https://mesosphere.slack.com/archives/C0L6U3ECQ/p1505329101000375, the `smoke-test/dcos-docker` test failure can be safely ignored until next week.

**Comment by vespian** [comment]
@mesosphere-mergebot label read for review

**Comment by amitaekbote** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
