### PR TITLE
[master] Mergebot Automated Train PR - 2018-Feb-05-11-47

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2356 - Bump dcos-test-utils

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by adamtheturtle** [comment]
Please can an owner override `teamcity/dcos/test/azure/arm` with https://jira.mesosphere.com/browse/DCOS_OSS-1877.

**Comment by vespian** [comment]
@mesosphere-mergebot override-status  teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-1877

**Comment by adamtheturtle** [comment]
@mesosphere-mergebot pr-status-checks

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
Thank you @adamtheturtle  and @vespian  for the reviews and pushing this across the crossing-line. Appreciate it.

**Pull request merged**
