### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Mar-29-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2670 - bump dcos-checks sha
* #2684 - Bumped Mesos SHA to the latest 1.5.x. 
* #2679 - Bump dcos log sha for 1.11

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Extended Tests Triggered - https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_ManualTriggers_TriggerTrainBuilds&branch_DcOs_Open_ManualTriggers=pull%2F2683&tab=buildTypeStatusDiv

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by mnaboka** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
