### PR TITLE
Add ClusterOpsFnd in codeowners

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot  sync

**Comment by janisz** [comment]
@mesosphere-mergebot sync

**Comment by janisz** [comment]
@mesosphere-mergebot sync

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot sync

**Pull request merged**
