### PR TITLE
1.9.2 train 191

### PR DESCRIPTION
**Pull request by mellenburg**
Includes:
#1735 
#1736

### CODE REVIEW

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
This PR is PASSED on tests. the only failure in the enterprise aggregate status is due to a recent check added that does NOT work for 1.9.2

**Comment by orsenthil** [comment]
Can we disable those status for 1.9 ? I see github allows per branch status reporting.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
