### PR TITLE
Use Marathon 1.4.0-RC4.

### PR DESCRIPTION
**Pull request by aquamatthias**
High level description including:

- Bug fix release for Marathon. We discovered a serious migration issue in RC3.

# Issues

- Fixes https://github.com/mesosphere/marathon/issues/4873 - Tasks with configured Marathon HealthChecks fail HealthChecks after migration to 1.4
- Fixes https://github.com/mesosphere/marathon/issues/4842 - by also writing deprecated pods to the proto.
- Fixes https://github.com/mesosphere/marathon/issues/4828 - Use async InstanceTracker methods in SchedulerActor
- Fixes https://github.com/mesosphere/marathon/issues/4882 - by renaming KillSelection enum values
- Fixes https://github.com/mesosphere/marathon/issues/4890 - Quote some vars and make sed more explicit 
- Fixes https://github.com/mesosphere/marathon/issues/4872 - Disallow usage of Command Checks on Pods until mesos supports them
- Fixes https://github.com/mesosphere/marathon/issues/4863 - Inform the rate limiter for pods and apps
- Fixes https://github.com/mesosphere/marathon/issues/4818 - Update kill selection in App as well.
- Fixes https://github.com/mesosphere/marathon/issues/4877 - fix various bugs in our RAML specification. add omitEmpty to some fields for cleaner output.

# Checklist

 - [x] Included a test which will fail if code is reverted but test is not
 - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

If this is a component/package update, include

 - [x] Change Log from last: https://github.com/mesosphere/marathon/releases/tag/v1.4.0-RC4
 - [x] Test Results: https://teamcity.mesosphere.io/viewType.html?buildTypeId=Oss_Marathon_Packages&branch_Oss_Marathon=v1.4.0-RC4&tab=buildTypeStatusDiv
 - [ ] Code Coverage: we have the data, but they are currently not published

### CODE REVIEW

**Comment by orsenthil** [comment]
This should fix the upgrade integration test as well. Triggered a run here: https://teamcity.mesosphere.io/viewLog.html?buildId=519599

**Comment by orsenthil** [comment]
@aquamatthias , the upgrade test is not successful yet. I ran the upgrade test on this PR.

The logs indicated that (https://teamcity.mesosphere.io/viewLog.html?buildId=519599) when a task is already running and the DCOS is upgraded (Marathon Migration happens),  requests  to ` /marathon/v2/tasks` is returning empty details.

This certainly wasn't the case before the RC3 upgrade.
* [TC Build Link](https://teamcity.mesosphere.io/viewLog.html?buildId=514890) for the Test PR https://github.com/dcos/dcos/pull/1074

**Comment by aquamatthias** [comment]
@orsenthil I tested this manually:
```
- Start Marathon (MoM) version 1.3.6 
- Create app (a) with health check (successfull health check)
- Create app (b) with health check (failing health check)
- Create app (c) without health check
- Wait for deployment (a) and (c), deployment (b) will never finish
- Get /v2/tasks
- Stop Marathon 
- Start Marathon (MoM) version 1.4.0-RC4
- Wait until Marathon has successfully started
- Get /v2/tasks
- Compare the task lists
```
All apps get migrated correctly. No task of of (a) and (c) is restarted.
Task of app (b) gets killed since it has a failing health check.

**Comment by aquamatthias** [comment]
@orsenthil now the test is green - shaky? 

Can you try to wait for the deployment to finish, before you upgrade?
(`/v2/deployments` should be empty)
We can also add another tests for running deployments, but this should be clear from the test setup.

**Comment by orsenthil** [comment]
@aquamatthias , that's interesting. I ran it twice to make sure if it was not flaky and it became 3rd time lucky. I will make the changes that you have suggested in the upgrade tests to make it more predictable.

This change, LGTM.

**Pull request merged**
