### PR TITLE
WIP: Simplify signal service integration test

### PR DESCRIPTION
**Pull request by mellenburg**
Units will be better checked by post-flight

### CODE REVIEW

**Comment by mellenburg** [comment]
@cmaloney This is ready for review

**Comment by cmaloney** [comment]
I don't think that units will actually be better-checked by a postflight. It was also very intentional design @spahl and I went back and forth on for whether the services / units should be included here, and we concluded they should. For cases where people add more units, they should just be able to specify the additional units via some config.

I think it's pretty important we make sure we're running exactly the services we expect through the entire cluster. A _lot_ of the other tests in this repo can pass while individual pieces of software may not be working.

**Comment by malnick** [comment]
I agree with Cody on this one, this test has provided us with some very specific insights to what broke a cluster in other troubleshooting I've had. We don't have the bullet proof test coverage on all services, and it's important that we verify the information we get from 3DT is correct. This test is the only way to prove that 3DT is returning all expected services in a cluster.

**Comment by mellenburg** [comment]
So, how about a json or a yaml that you can input that overrides all all of the units in properties?

**Comment by cmaloney** [comment]
I think in general we're getting very close to the point (if not at it), that all of the integration test config should go into one big config file, definitely happy to have things move in that direction.

Something like:
test_config.yaml
I think in general we're getting very close to the point (if not at it), that all of the integration test config should go into one big config file, definitely happy to have things move in that direction.

Something like (with all the services):
test_config.yaml
```yaml
3dt_services:
  master_units:
    - adminrouter-reload-service
    - adminrouter-reload-timer
  all_node_units:
    - ddt-service
    - epmd-service
  slave_units:
    - mesos-slave-service
  slave_public_units:
    - mesos-slave-public-service
  all_slave_units:
    - logrotate-agent-service
```

**Comment by mellenburg** [comment]
Given that this would require bundling a config to the test, this: https://github.com/dcos/dcos/pull/68 would help greatly. So I'll give that a cleanup first

**Comment by malnick** [comment]
@mellenburg Can we close this?

**Pull request closed without merging**
