### PR TITLE
gen: add two configuration parameters for container IPC.

### PR DESCRIPTION
**Pull request by qianzhangxa**
## High-level description

What features does this change enable? What bugs does this change fix?

Add two configuration parameters for container IPC.

## Corresponding DC/OS tickets (required)

  - [DCOS-56619](https://jira.mesosphere.com/browse/DCOS-56619) Add IPC related configuration parameters in DC/OS

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by vinodkone** [comment]
@qianzhangxa  Is it possible to write a test for these changes?

**Comment by vinodkone** [comment]
@qianzhangxa  Also, do we need any CHANGELOG update for these flags?

**Comment by qianzhangxa** [comment]
@vinodkone @Gilbert88 I have updated the `CHANGES.md` and also added a test, thanks!

**Comment by Gilbert88** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
