### PR TITLE
(1.12) Fix 500 responses from v0 metrics API

### PR DESCRIPTION
**Pull request by branden**
## High-level description

This is a 1.12 backport of #3436.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4088](https://jira.mesosphere.com/browse/DCOS_OSS-4088) metrics v0 API 500 error: "Failed to encode value to JSON"

## Related tickets (optional)

Other tickets related to this change:

N/A

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: This fixes a bug that has yet to be released.
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/telegraf/compare/ccb5eb8c53842b690ace1af2c40ff6101e0dc93e...071b143b1c93f03e5469378d082ec14dacf41674
  - [x] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/public-dcos-cluster-ops%2Ftelegraf%2Ftelegraf-dcos/detail/telegraf-dcos/40/pipeline)
  - [x] Code Coverage (if available): [link to code coverage report](https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/public-dcos-cluster-ops%2Ftelegraf%2Ftelegraf-dcos/detail/telegraf-dcos/40/pipeline)

### CODE REVIEW

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by branden** [comment]
`teamcity/dcos/test/aws/onprem/static ` needs an override with https://jira.mesosphere.com/browse/DCOS_OSS-2115.

**Comment by jongiddy** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static DCOS_OSS-2115

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
