### PR TITLE
[master] Mergebot Automated Train PR - 2018-Jun-22-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2901 - Bump cosmos to latest snapshot version
* #2987 - Bump dcos-net

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot label [Ready For Review |Ship It |Holding |Work In Progress |Request For Comment] 
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot override-status  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by urbanserj** [comment]
@mesosphere-mergebot merge-it

**Comment by mesosphere-mergebot-dev** [comment]
PR Status Checks are not Green. Refusing to merge.

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-38435

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
