### PR TITLE
[DCOS 1.8.9] Use metronome 0.2.3

### PR DESCRIPTION
**Pull request by aquamatthias**
## High Level Description

Security fix for Cross-Site Scripting Vulnerabilities

## Related Issues

  - [DCOS-14866](https://jira.mesosphere.com/browse/DCOS-14866) Cross-Site Scripting Vulnerabilities

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by aquamatthias** [comment]
@zen-dog @meichstedt please review

**Comment by aquamatthias** [comment]
@mesosphere-mergebot bump-ee

**Comment by aquamatthias** [comment]
The problem reported in `integration-test/upgrade-onprem` does not look related to this patch.

**Comment by adam-mesos** [comment]
Still needs a corresponding Metronome bump in 1.8.9 EE downstream:
https://github.com/mesosphere/dcos-enterprise/blob/1.8.9/packages/metronome/ee.buildinfo.json#L6

**Pull request merged**
