### PR TITLE
Bump dcos-ui package for 1.9.  Adds multi container form.

### PR DESCRIPTION
**Pull request by rcorral**
High level description including:
 - Adds multiple container create form 

# Issues

[DCOS-<number>](https://dcosjira.atlassian.net/browse/DCOS-<number>)
...

# Checklist

 - [ ] Included a test which will fail if code is reverted but test is not
 - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

If this is a component/package update, include

 - [x] Change Log from last: [link](https://github.com/dcos/dcos-ui/compare/1d300f156c88195d60c87a643d83f1f301bfe8a8...4fe5207c0ac9bd52ab3c6cf8ed4975c0988e69fa)
 - [x] Test Results: [unit](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-ui-pulls/6236/)
 - [ ] Code Coverage: <link>

This is what it looks like
gif

cc/ @spahl

### CODE REVIEW

**Comment by rcorral** [comment]
@adam-mesos yes, they're flaky because of some issue we are trying to track down with Chrome. I've removed them from here just so it's not confusing. I've also updated the sha as this hasn't merged yet.

**Comment by lingmann** [comment]
@rcorral who else can do a review of this?

**Comment by rcorral** [comment]
Give me a day to update the PR and then I think @orlandohohmeier would be good to review, unless we don't want managers to do so. Then I can find someone else.

**Comment by adam-mesos** [comment]
@rcorral Could you find somebody/anybody from your team to give a :rocket: ?
It's just a SHA bump in dcos-ui master, which will soon be updated with a newer master SHA. Nothing controversial, as long as we're going forward in time in the same branch (which I verified).

**Comment by mlunoe** [comment]
Looks good :shipit:

**Comment by rcorral** [comment]
@adam-mesos can we use #1137 instead?

**Comment by adam-mesos** [comment]
@rcorral It looks like #1137 doesn't have any reviews, and this train is ready to leave the station. I could drop this PR from the train, but that doesn't seem necessary, since it's still a forward bump of the SHA.
Get your 2 shipits on #1137 and then we can pull it into the next train.

**Pull request merged**
