### PR TITLE
[master] Train 239

### PR DESCRIPTION
**Pull request by sschneid**
#1980 Adding xvdb

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by lingmann** [comment]
@jgehrcke at this point (especially after all tests are passing) we don't want to add additional PR's to this train. It's better to just merge this and start the next train.

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
