### PR TITLE
Bumped Mesos and Mesos modules to include ContainerLogger changes.

### PR DESCRIPTION
**Pull request by greggomann**
## High Level Description

Recent [breaking changes](https://reviews.apache.org/r/57121/) to the `ContainerLogger` interface landed in Mesos. This PR incorporates updates to the DC/OS journald logging module (https://github.com/dcos/dcos-mesos-modules/pull/11) to accommodate these changes. The PR also bumps Mesos to the latest master. Note that these Mesos changes will not be brought into DC/OS 1.9, so this PR is relevant for DC/OS 1.10, when Mesos will be bumped past version 1.2.0.

## Related Issues

  - [MESOS-7050](https://issues.apache.org/jira/browse/MESOS-7050) IOSwitchboard FDs leaked when containerizer launch fails -- leads to deadlock.

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Relies on the Mesos test suite, specifically the `ContainerLoggerTest`s. Note that the `test_mesos_task_state_remains_consistent` test in the DC/OS upgrade suite is updated in this PR; without the changes here it would fail due to a new field in the Mesos master state.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-mesos-modules/compare/36ce01e6cf869b4bb2bfe9e91766f984f333f742...55ac711639f101a81756b7477fa916f9b17d0058
  - [x] Test Results: [ASF CI results](https://builds.apache.org/job/Mesos-Buildbot/BUILDTOOL=autotools,COMPILER=gcc,CONFIGURATION=--verbose,ENVIRONMENT=GLOG_v=1%20MESOS_VERBOSE=1,OS=ubuntu:14.04,label_exp=(docker%7C%7CHadoop)&&(!ubuntu-us1)&&(!ubuntu-eu2)/3351/)
  - [ ] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by greggomann** [comment]
Failing test (`test_upgrade_vpc.test_mesos_task_state_remains_consistent`) is due to [this commit](https://github.com/apache/mesos/commit/2ee98b040927ec80371f1850717fe4add91b8b77) in Mesos, which added the task `role` to master state. The test could be updated to expect that the new task state will be a superset of the previous task state in order to avoid failures after changes like this.

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by greggomann** [comment]
@mellenburg when you have a cycle, could you review the test change in this PR?

**Comment by greggomann** [comment]
@orsenthil I would love to get this into the first 1.10 train if possible. @mellenburg could you review the small test change here when you have a cycle? Merging this PR should fix the Mesos/DCOS CI build. cc @spahl

**Comment by lingmann** [comment]
@greggomann besides @mellenburg we'll need a second review. Can you ping some more people that would be good candidates to review this change?

**Comment by greggomann** [comment]
@lingmann looking at the current `mesos-modules` in DC/OS master, it looks like this fix was merged in another PR, so this one is no longer necessary. I'll submit a separate PR soon to bump the Mesos package to include recent changes.

**Pull request closed without merging**
