### PR TITLE
Bumped Mesos and mesos-modules.

### PR DESCRIPTION
**Pull request by ArmandGrillet**
Mesos is now bumped to the latest master (ae08193).

## High-level description

- Bumped Mesos to latest master (apache/mesos@ae08193).
- Bumped dcos-mesos-modules to latest master (dcos/dcos-mesos-modules@6ffea42)
- Bumped dcos-net to handle TASK_STARTING: https://github.com/dcos/dcos-net/pull/21

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-1912](https://jira.mesosphere.com/browse/DCOS_OSS-1912) Bump mesos and mesos-modules packages to latest master
  - [DCOS_OSS-1924](https://jira.mesosphere.com/browse/DCOS_OSS-1924) Same set of tests fails reproducibly with current Mesos bump PR
  - [DCOS_OSS-1932](https://jira.mesosphere.com/browse/DCOS_OSS-1932) flaky test test_dcos_log.test_log_v2_api

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [mesos changelog](https://github.com/mesosphere/mesos/compare/09df58e9a83dbebf1ae8b32c28cb450294d92612...dc243c64da2eb6984a6d65af67e1918c04742074) and  [mesos-modules changelog](https://github.com/dcos/dcos-mesos-modules/compare/9adfabc5d07048f55c3da5a1bad17d2109750f0e...6ffea4242dd39e7f84a39bf40855ae11a9d2d0a8)
  - [X] Test Results: [Apache Mesos Jenkins CI Job](https://builds.apache.org/job/Mesos-Buildbot/4509/) - lacks the two last commits but :+1: on internal CI and will update the link as soon as I have a new build.
  - [X] dcos-net bump includes https://github.com/dcos/dcos-net/pull/21

### CODE REVIEW

**Comment by ArmandGrillet** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@ArmandGrillet, @sambatyon said that this will need some "fixes in the dcos-mesos-modules-private" to get the downstream / enterprise build to work.

**Comment by jgehrcke** [comment]
All these tests failed in https://teamcity.mesosphere.io/viewLog.html?buildId=876868 / `teamcity/dcos/test/aws/onprem/static`:
```
test_networking.test_vip[Container_MESOS-Network_HOST-Network_USER] |  
test_networking.test_vip[Container_MESOS-Network_USER-Network_HOST] |  
test_networking.test_vip[Container_MESOS-Network_USER-Network_USER] |  
test_networking.test_vip[Container_NONE-Network_HOST-Network_HOST] |  
test_networking.test_vip[Container_NONE-Network_HOST-Network_USER] |  
test_networking.test_vip[Container_NONE-Network_USER-Network_HOST] |  
test_networking.test_vip[Container_NONE-Network_USER-Network_USER] |  
test_dcos_log.test_log_v2_api
```
Rerunning, for hopefully being able to distinguish breakage from instability.

**Comment by jgehrcke** [comment]
In a second test run for `teamcity/dcos/test/aws/onprem/static` (https://teamcity.mesosphere.io/viewLog.html?buildId=877950) the exact *same* set of tests failed:
```
test_dcos_log.test_log_v2_api |  
test_networking.test_vip[Container_MESOS-Network_HOST-Network_USER] |  
test_networking.test_vip[Container_MESOS-Network_USER-Network_HOST] |  
test_networking.test_vip[Container_MESOS-Network_USER-Network_USER] |  
test_networking.test_vip[Container_NONE-Network_HOST-Network_HOST] |  
test_networking.test_vip[Container_NONE-Network_HOST-Network_USER] |  
test_networking.test_vip[Container_NONE-Network_USER-Network_HOST] |  
test_networking.test_vip[Container_NONE-Network_USER-Network_USER]
```

I am triggering a re-run for having even more confidence in the distinction between breakage and test instability.

**Comment by jgehrcke** [comment]
The exact same set of tests also failed in `teamcity/dcos/test/aws/cloudformation/simple` (https://teamcity.mesosphere.io/viewLog.html?buildId=876881).

It stands to reason that this is a breakage, not an instability.

**Comment by jgehrcke** [comment]
Debugging the test breakage is tracked via https://jira.mesosphere.com/browse/DCOS_OSS-1924.

**Comment by adam-mesos** [comment]
If we can get this passing, we can drop #2100 and #2063 in favor of this more recent bump.

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
Great, now we're passing the test_vips tests, but failing on test_dcos_log.test_log_v2_api
Maybe @klueska or @mnaboka can help us debug that?

**Comment by mnaboka** [comment]
@adam-mesos dcos-log v2 uses files API to read the logs. The test fails because it can't read the logs, so there must be something changed in files API / sandbox layout

**Comment by mnaboka** [comment]
ok, i've just checked a cluster from this PR. it all looks good. I think it's a flaky test, i am currently trying to reproduce this issue

**Comment by urbanserj** [comment]
@mnaboka test_dcos_log.test_log_v2_api is not a flaky test. it fails consistently.
2 out of 2 [teamcity/dcos/test/aws/onprem/static-redhat](https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackendRedHat&branch_DcOs_Open_Test_IntegrationTest=pull%2F2142&tab=buildTypeStatusDiv)
6 out of 6 [teamcity/dcos/test/aws/onprem/static](https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackend&branch_DcOs_Open_Test_IntegrationTest=pull%2F2142&tab=buildTypeStatusDiv)
3 out of 3 [teamcity/dcos/test/aws/cloudformation/simple](https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_IntegrationTest_AwsCloudFormationSimple&branch_DcOs_Open_Test_IntegrationTest=pull%2F2142&tab=buildTypeStatusDiv)

**Comment by adam-mesos** [comment]
@urbanserj That failing test is being tracked in https://jira.mesosphere.com/browse/DCOS_OSS-1932 with a potential fix in https://github.com/dcos/dcos/pull/2153
I think we can ignore that specific failure in this PR, tracking that test failure separately.

**Comment by urbanserj** [comment]
@adam-mesos @mnaboka if so, may I ask you to mute that failing test in this PR please?

**Comment by adam-mesos** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple DCOS_OSS-1932

**Comment by adam-mesos** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static DCOS_OSS-1932

**Comment by urbanserj** [comment]
@adam-mesos could you please use `@pytest.mark.xfail(reason="DCOS-XXXXX")` or something like that? otherwise you will break our master branch and each team member will have to spend their time figuring out that this test failure is not their problem.

**Comment by adam-mesos** [comment]
I'm not sure if mergebot override-status works yet, and if we're going to spend an hour re-running the tests anyway, I figure we might as well pull in https://github.com/dcos/dcos/pull/2153 to see if we can get this thing full green.

**Comment by adam-mesos** [comment]
@urbanserj I see your point. The Mesos bump introduces the failure, so we should either disable the test in master (as part of this PR), or fix it in this PR/train before merging to master. Just telling github to go green isn't going to help if this is a consistent new failure.

**Comment by mnaboka** [comment]
@urbanserj it is probably flaky, the success rate is 93% https://teamcity.mesosphere.io/project.html?projectId=DcOs_Open_Test_IntegrationTest&testNameId=2479530473806658388&tab=testDetails

i also manually provisioned a cluster from this PR and was able to successfully run this specific test. It failed 1 in ~ 50 runs. So my assumption is that something was changed in mesos,  and now it's taking longer to save files to sandbox.

**Comment by mnaboka** [comment]
@adam-mesos i would not mute dcos-log test. It uses mesos API. If the flakiness has nothing to do with this failure, then it might be a legit failure, can you try to cherry pick my commit and run the tests? We will see if that helps

**Comment by adam-mesos** [comment]
@mnaboka I cherry-picked the version before you fixed tox errors, so let's let that run to completion here to see if it goes green, then we can update to use the tox-compliant commit.

**Comment by adam-mesos** [comment]
Ok, that looks much better on the dcos-logs front, although #2153 itself still needs to be all-green/reviewed. I'll rebase/re-cherrypick on #2153 to get the tox fix and see if this PR will go all green (and in EE)
However, this run showed test_networking.test_vip[Container_NONE-Network_USER-Network_HOST] failing in https://teamcity.mesosphere.io/viewLog.html?buildId=880592&buildTypeId=DcOs_Open_Test_IntegrationTest_AzureArm

**Comment by adam-mesos** [comment]
Rebased with latest dcos/dcos master and latest cherry-pick from #2153 , then force-pushed. Please pull fresh @ArmandGrillet , etc.

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
Looks like #2153 will merge on its own, after which we can rebase this down to the mesos, modules, and dcos-net bumps. LGTM as long as we can get EE green.

**Comment by sambatyon** [comment]
Could you add [DCOS_OSS-1932](https://jira.mesosphere.com/browse/DCOS_OSS-1932) to the list of related issues? Other than that, it looks great 🚀

**Comment by ArmandGrillet** [comment]
@sambatyon ✅

**Pull request merged**
