### PR TITLE
Bump Metronome to 0.6.67

### PR DESCRIPTION
**Pull request by pierrebeitz**
## Corresponding DC/OS tickets (required)

  - [D2IQ-72421](https://jira.d2iq.com/browse/D2IQ-72421)

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot changelog-not-required bump

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot bump-ee

**Comment by DominikDary** [comment]
@mesosphere-mergebot request-review  @DominikDary

**Review by DominikDary — APPROVED** [review]

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot backport 2.2

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ship It

**Comment by pierrebeitz** [comment]
@orsenthil teamcity/dcos/test/terraform/aws/onprem/static/group3  not reporting back

**Pull request merged**
