### PR TITLE
Train 144

### PR DESCRIPTION
**Pull request by spahl**
## High Level Description

* #1371 Bump Mesos to the 1.2.x branch and bump Mesos modules to include ContainerLogger changes
* #1380 Enable PID namespace isolator in mesos for the UCR
* Marathon 1.4.2-snapshot5 (commit https://github.com/dcos/dcos/pull/1388/commits/03da1fda839958b1ca6e232a6aad92417bcd5135 from #1388)
* #1391 upgrade spartan and navstar to improve the logging
* #1387 Bump for dcos-ui package for 1.9
* #1376 Fix octarine, tests, and increase coverage
* #1353 Launch package
* #1341 Add script that fixes /etc/hosts in CentOS 7 on EC2 upon boot
* #1271 Add DNS Tests

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Comment by spahl** [comment]
#1388 is listed in the description but hasn't been added to the train.

I cherry picked marathon in because it was not against the master branch but 1.9.0-rc4.
Commit: 37a26b05cc4e9a0c3271aab03f0368950dd111dd

#1370 is on the train but the PR is closed?
This was closed by @vespian by mistake

#1271 has yet to pass the integration-test/deploy-vpc-api check.

Seems like a flake should go fine.

**Comment by adam-mesos** [comment]
`test_applications.test_octarine` introduced in https://github.com/dcos/dcos/pull/1376 fails in EE strict mode. Time to take it out of the train until @nlsun can fix it.

**Comment by vespian** [comment]
@spahl  Thanks for taking care of it.

 #1370 was merged in #1390, but between its inclusion in the train and train merge I have made a mistake of rebasing it. Because of that, after the train was merged the PR was not automatically marked as merged as well :(

Not sure what is our policy on that. Rebasing the Train against master should remove the commit. Sorry for the mess :)

**Comment by spahl** [comment]
@vespian ok understood. I'm about to rebuild the train anyways. Thanks I'll exclude it.

**Comment by spahl** [comment]
@adam-mesos I'll comment in the upstream PR. Nick investigated and we found a solution

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Comment by spahl** [comment]
Build in upstream fails because of: https://github.com/dcos/dcos/pull/1304. Removing for this train

**Comment by spahl** [comment]
@mesosphere-mergebot  bump-ee

**Comment by spahl** [comment]
All tests passed on azure but it's taking forever to take down the stack at the end. Merging.

**Pull request merged**
