### PR TITLE
Add mountinfo to diagnostic bundle

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

This captures the host mount table allowing us to triage mount related issues. Note that getting the mount table for the dcos-diagnosis service (i.e., `/proc/self`) is OK because we don't put the service into a separate mount namespace: see: [dcos-diagnostics-agent.service](https://github.com/dcos/dcos/blob/1.11/packages/dcos-diagnostics/extra/dcos-diagnostics-agent.service).

[`man proc`](http://man7.org/linux/man-pages/man5/proc.5.html)

## Corresponding DC/OS tickets (obligatory)

  - [DCOS_OSS-3961](https://jira.mesosphere.com/browse/DCOS_OSS-3961) Add `/proc/self/mountinfo` to diagnostic bundle.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jieyu** [comment]
The title of this PR has a typo :)

**Comment by janisz** [comment]
Fixed!

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bumpe-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@jieyu @orsenthil Can you review this?

**Comment by branden** [comment]
@mesosphere-mergebot override-status mergebot/enterprise/build-status/aggregate DCOS-37539

**Comment by branden** [comment]
@mesosphere-mergebot override-status mergebot/review/approved/min_2 DCOS-35423

**Pull request merged**
