### PR TITLE
Train 160

### PR DESCRIPTION
**Pull request by orsenthil**
* #1491 - spartan: Add bind ip blacklist and forward zones
* #1504 - Bumped Mesos to latest master.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by greggomann** [comment]
All my changes are here; LGTM!

**Comment by orsenthil** [comment]
@greggomann  - you could give the approval in the ticket. (Review Changes - Approve, so mark it with Green CheckMark)

@nlsun  - same.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
The failure with dcos-tweeter is a Jenkins Infrastructure problem.  @spahl  or @lingmann  - please merge this in.

**Comment by sschneid** [comment]
> The failure with dcos-tweeter is a Jenkins Infrastructure problem.

This is inacurate; the error is:

````
No cluster is attached. Please run `dcos cluster attach <cluster-name>`
````

...which is a test configuration or an issue with Tweeter and the new `dcos-cli` library.

**Comment by orsenthil** [comment]
@sschneid. Thanks for pointing.  I'll rephrase. The issue is unrelated to changes introduced in this PR. (The Jenkins tests are not run at all).

**Comment by lingmann** [comment]
Thanks @orsenthil and @sschneid, I will proceed with the merge. Is there a ticket tracking the need to fix the CLI in order to get the tweeter demo test working again? If so, let's please make sure it is marked as high priority.

**Pull request merged**
