### PR TITLE
Bump cosmos version

### PR DESCRIPTION
**Pull request by takirala**
## High-level description

What features does this change enable? What bugs does this change fix?
Cosmos should send `force=true` flag during marathon app update. This needs to be merged in to `1.11`.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  -  [DCOS-19500](https://jira.mesosphere.com/browse/DCOS-19500) cosmos/service/update fails if Marathon is deploying

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-2102](https://jira.mesosphere.com/browse/DCOS_OSS-2102) Bump cosmos

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: No test to reproduce this behavior.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] [Cosmos Release](https://github.com/dcos/cosmos/releases/tag/v0.5.1)
  - [x] Test Results: [link to CI job test results for component](https://teamcity.mesosphere.io/viewLog.html?buildId=944404&buildTypeId=DcosIo_Cosmos_PublishRelease&tab=testsInfo)
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by takirala** [comment]
@larioj @jsancio please review!

**Comment by takirala** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review.

**Comment by takirala** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by cdaw** [comment]
approved for merge

**Pull request merged**
