### PR TITLE
chore(dcos-ui): update package

### PR DESCRIPTION
**Pull request by weblancaster**
## High-level description

Update the DC/OS UI package to include the latest fixes, improvements and features.

## Corresponding DC/OS tickets (obligatory)

- [DCOS_OSS-1965](https://jira.mesosphere.com/browse/DCOS_OSS-1965): Change DC/OS favicon to Mesosphere DC/OS favicon
- [DCOS-19946](https://jira.mesosphere.com/browse/DCOS-19946): @dcos/mesos-client bump 0.1.9
- [DCOS_OSS-2021](https://jira.mesosphere.com/browse/DCOS_OSS-2021): add flags to identify and stub Mesos requests
- [DCOS-18993](https://jira.mesosphere.com/browse/DCOS-18993): introduce new select with descriptions
- [DCOS-19882](https://jira.mesosphere.com/browse/DCOS-19882): remove escaping from constraint output

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-ui/releases/tag/v1.11.0-rc.7
  - [x] Test Results: 
  - [x] Code Coverage (if available):
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by weblancaster** [comment]
@mesosphere-mergebot bump-ee

**Comment by weblancaster** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by weblancaster** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
LGTM! 🚢

**Comment by vespian** [comment]
@mesosphere-mergebot merge-it

**Comment by vespian** [comment]
> @mesosphere-mergebot merge-it 

I am sorry, copy paste error - it is pretty late here :(

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by mesosphere-teamcity** [comment]
Corresponding DC/OS PR: https://github.com/dcos/dcos/pull/2448

**Pull request merged**
