### PR TITLE
Train 140

### PR DESCRIPTION
**Pull request by branden**
## High Level Description

#1269
#1320 
#1350 
#1352 
#1354
#1356
#1357

## Related Issues

See PRs above.

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by spahl** [comment]
Closed by mistake.

@adam We can still have everyone review inside of the train. Most of the changes to the test were found after integration and we don't have the time to get them all done separately.

As long as people pay attention and review the code in this train there should be no problem.

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
Is there space for https://github.com/dcos/dcos/pull/1255? It's a mesos-dns bump with all tests passing and two approvals.

**Pull request merged**
