### PR TITLE
Winpanda App: Add Support For dcos-config-windows.yaml

### PR DESCRIPTION
**Pull request by anatolii-borysov**
1) decline execution of the NSSM executable verification procedure at service
   manager instance creation time to allow the NSSM application itself to be
   installed as a regular DC/OS package
2) introduce support for shared executables an sharedd libraries directories
   within DC/OS installation storage structure
3) extended the generic resource contex object with elements for DC/OS
   installation storage 'work', 'run', 'log', 'bin' and 'lib' directories
4) add support for aggregated DC/OS configuration object
   (dcos-config-windows.yaml)
5) refine log messages

JIRA: DCOS_OSS-5687 - Fix placement of the NSSM executable verification procedure
JIRA: DCOS_OSS-5655 - Winpanda App: Add Support For dcos_config_windows.yaml

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @jongiddy

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot changelog-not-required Internal Windows change

**Comment by jongiddy** [comment]
@tillt EPAM cannot see DCOS issues. Current aims for the path hierarchy are described in https://jira.mesosphere.com/browse/DCOS_OSS-5689

**Comment by anatolii-borysov** [comment]
> 
> 
> @tillt EPAM cannot see DCOS issues. Current aims for the path hierarchy are described in https://jira.mesosphere.com/browse/DCOS_OSS-5689

@jongiddy @tillt
I'll update the DCOS_OSS-5689 with description of the Windows DC/OS installation storage layout which is currently implemented in the Winpanda app. The very basic idea of how it's designed can be inferred from the comments to Winapnda source code - https://github.com/dcos/dcos/blob/master/packages/winpanda/extra/src/winpanda/common/storage.py#L1-L30, but it definitely definitely worth a separate design definition doc.

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required Part of Windows build

**Pull request merged**
