### PR TITLE
[1.13] now reflects 1.13.2-dev

### PR DESCRIPTION
**Pull request by jgehrcke**

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by adamtheturtle** [comment]
This absolutely should be automated - is there an issue for that?

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
> This absolutely should be automated - is there an issue for that?

@adamtheturtle  - Agree on automation. I am still experimenting to find out the best possible method.

Here is what is usually done.

1. Create a minor branch with update to minor version
2. Update the changes the major branch
3. Update the master branches' various config values.

Now, we can do all these and merge without "testing" and pushing to the remote directly as an automatic action, but this brings some drawbacks and I am uncertain if we want to live with those drawbacks of merging without testing.

Alternative is to invoke mergebot to do these actions, and create PRs, and follow through with the automated merge of these PRs without requiring any approval.

Let's discuss our ideas further here: https://jira.mesosphere.com/browse/DCOS-54535

**Pull request merged**
