### PR TITLE
Update DC/OS Version for master.

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

`master` of dcos/dcos is now DC/OS version 1.13

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by takirala** [comment]
@orsenthil  why was this merged without passing all the tests ?

FYI, we need to make bunch of changes for universe server whenever there is a version bump in DC/OS. I would be surprised if the CI passes for this without the universe server bump.

**Comment by elezar** [comment]
> FYI, we need to make bunch of changes for universe server whenever there is a version bump in DC/OS. I would be surprised if the CI passes for this without the universe server bump.

As @takirala points out, the smoke tests *all* failed here: https://teamcity.mesosphere.io/viewLog.html?buildId=1218287&buildTypeId=DcOs_Enterprise_Test_FrameworkTests_DcOsCommonsSmokeTest&guest=1

This was due to the interaction with the universe which needs a corresponding update (see https://jira.mesosphere.com/browse/DCOS-42285). It would be interesting to know why this was merged and I also don't see any explicit overrides.

**Comment by orsenthil** [comment]
@takirala and @elezar - We are reverting this - https://github.com/dcos/dcos/pull/3493

**Comment by orsenthil** [comment]
@elezar - it was merged as we need a way to differentiate `master` from `1.12` . It was also required to update the config so that mergebot applies the fix version corrrectly.

```
            "master": "DC/OS 1.13.0",
            "1.12": "DC/OS 1.12.0",
```

* Delaying the merge of this might have caused some process failures where automatic fixVersion might be applied incorrectly. However, that change alone can be come in separately from updating the version of DC/OS.

**Pull request merged**
