### PR TITLE
Train 293

### PR DESCRIPTION
**Pull request by kevinmiller-conley**
This is Train 293, against the master branch. It contains the following pull requests:

#2107 (Use the more recent marathon endpoint)
#2220 (Bump pkgpanda pkgs kazoo and gunicorn)
#2222 (update fault domain script)
#2224 (bump dcos log sha)

### CODE REVIEW

**Comment by kevinmiller-conley** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by margaret** [comment]
The cloudformation/simple failure is https://jira.mesosphere.com/browse/DCOS-19542

**Comment by margaret** [comment]
I think the azure/arm failure is https://jira.mesosphere.com/browse/DCOS_OSS-1830 . Should we separate that out into more specific tickets?

**Comment by lingmann** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple 
 https://jira.mesosphere.com/browse/DCOS-19542

**Comment by lingmann** [comment]
@margaret I agree that this looks like the Azure failure here is due to flakiness on the Azure side, but unfortunately our Azure details are so minimal it's really hard to know without logging in to Azure... However I reviewed all of the linked PR's, and they all passed the Azure tests at least once. @mellenburg I think we need to add some extra debug capture to dcos-launch when Azure cluster fails to come up like this. (this is the equivalent of AWS ROLLBACK for azure :-/

**Comment by lingmann** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-1830

**Comment by lingmann** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
