### PR TITLE
Master train 195

### PR DESCRIPTION
**Pull request by mellenburg**
Includes:
#1747 
#1752

### CODE REVIEW

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
@mellenburg what's the situation on the `integration-test/vagrant-bash` tests?

**Comment by jgehrcke** [comment]
Failed `integration-test/vagrant-bash` runs:
* https://teamcity.mesosphere.io/viewLog.html?buildId=717001
* https://teamcity.mesosphere.io/viewLog.html?buildId=716919
* https://teamcity.mesosphere.io/viewLog.html?buildId=716743

**Comment by jgehrcke** [comment]
Restarted, still failing:
https://teamcity.mesosphere.io/viewLog.html?buildId=717100
```
test_applications.test_octarine | 
test_networking.test_ip_per_container |  
test_service_discovery.test_service_discovery_docker_bridge |  
test_service_discovery.test_service_discovery_docker_bridged_network |  
test_service_discovery.test_service_discovery_docker_overlay_port_mapping |  
```

**Comment by jgehrcke** [comment]
Created https://jira.mesosphere.com/browse/DCOS_OSS-1467 for tracking the task of debugging the failed `integration-test/vagrant-bash` tests.

**Comment by lingmann** [comment]
@vespian @branden per some analysis of @mellenburg it looks like the combination of #1747 and #1752 is introducing some new failure modes with our integration tests, but independently they are ok. So we are going to pull one off the train and proceed... is one of these more important to land first? Also, if you have any feedback or thoughts on what might be causing the issue here with `test_applications.test_octarin` please let us know.

**Comment by BenWhitehead** [comment]
Ran a bisect on the two PRs that were included in this train.

train-195a: https://github.com/dcos/dcos/pull/1769
train-195b: https://github.com/dcos/dcos/pull/1770

train-195a, includes the changes from PR #1747 and that PR is the pr appears to be the one that results in the failure of `integration-test/vagrant-bash` that we're seeing on this train.

I'm going to close this train, bump #1747 back to WIP and ask that that PR be investigated before it merges.

**Pull request closed without merging**
