### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Mar-02-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2514 - Bump Marathon to 1.6.348-e45e6e08d.
* #2529 - [1.11] Don't bind dcos-dns on k8s cluster dns ip address
* #2538 - Admin Router: Prevent reusing tcp sockets by AR's cache code [1.11]

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
SHAs match.

**Comment by vespian** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
