### PR TITLE
Cluster ID for agent metrics (and bump dcos-metrics to 1.0.0-rc3)

### PR DESCRIPTION
**Pull request by rji**
This PR supersedes / carries https://github.com/dcos/dcos/pull/1063.

* Write `/var/lib/dcos/cluster-id` on agents for dcos-metrics service to use.
* Bump dcos-metrics component to 1.0.0-rc3.

# Issues

N/A

# Checklist

 - [x] Included a test which will fail if code is reverted but test is not
 - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by malnick** [comment]
Can we get an integration test on this which checks that cluster-id is available in at least one endpoint on each host?

**Comment by rji** [comment]
@malnick updated the existing metrics test to assert that `dimensions` exists in the `node` response, and that `cluster_id` contains a non-empty string.

**Comment by spahl** [comment]
:ship:

**Comment by rji** [comment]
Failed test on Azure is unrelated to this patch.

**Comment by rji** [comment]
Merged in #1071.

**Pull request closed without merging**
