### PR TITLE
Update cosmos to 0.2.0-SNAPSHOT-69-refs_heads_master-dcf390ff14

### PR DESCRIPTION
**Pull request by BenWhitehead**

### CODE REVIEW

**Comment by spahl** [comment]
Could you please rebase to solve the conflict? Thanks?

**Comment by BenWhitehead** [comment]
@spahl what is the blocker to being able to merge this? Got bit by an inconsistency with `testing/master` this afternoon.

**Comment by spahl** [comment]
No blocker. Maybe tag it as an rc?

**Comment by spahl** [comment]
:ship: after rebase

**Comment by BenWhitehead** [comment]
@spahl rebase complete

**Pull request merged**
