### PR TITLE
Updated Windows build script.

### PR DESCRIPTION
**Pull request by kaysoky**
## High-level description

What features does this change enable? What bugs does this change fix?

This makes a few small, but important changes:

* The `-DENABLE_LIBEVENT` configuration is buggy and unsupported on Windows.  So it has been removed.
* To produce an optimized release build, the build line needs to be run via `--config Release`.
* Multi-process builds are the default, so the `-- /m` arguments are extraneous.

## Corresponding DC/OS tickets (required)

  - None

## Related tickets (optional)

  - None

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): N/A
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain: The CI itself will attest to the change's viability.
  - [ ] Test Results: TODO
  - [ ] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by DominikDary** [comment]
@mesosphere-mergebot changelog-not-required Changelog not required because this is fixing build artifacts

**Comment by DominikDary** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by kaysoky** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by timaa2k** [comment]
@mesosphere-mergebot sync

**Pull request merged**
