### PR TITLE
Bump Marathon to 1.7.174

### PR DESCRIPTION
**Pull request by timcharper**
## High-level description

Bump Marathon dependency for 1.12.0 release. DCOS-42832

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

* DCOS-42671
* MARATHON-7941
* MARATHON-8372
* MARATHON-8438
* MARATHON-8420
* MARATHON-8442
* MARATHON-8437
* MARATHON-8436
* MARATHON-8430
* MARATHON-8433
* MARATHON-8434
* MARATHON-8432
* MARATHON-8398

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [1.7.149..1.7.174](https://github.com/mesosphere/marathon/compare/21b42dbb8...da9365d80)
  - [x] Test Results: [marathon](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/releases%252F1.7/1/)
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by timcharper** [comment]
@mesosphere-mergebot bump-ee

**Comment by timcharper** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
This is included in the train. Important tests with on-prem static was successful when I included this in the integration train.

**Pull request merged**
