### PR TITLE
bump dcos-checks sha

### PR DESCRIPTION
**Pull request by mnaboka**
## High-level description

bump dcos-checks sha

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-1878](https://jira.mesosphere.com/browse/DCOS_OSS-1878) Fix bug where `--detect-ip` parameter is ignored
  - [DCOS-21703](https://jira.mesosphere.com/browse/DCOS-21703) Fix bug bash exit code not matching check status in case of Go err

## Related tickets (optional)

Other tickets related to this change:

N/A

## Checklist for all PRs

  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [dcos-checks diff](https://github.com/dcos/dcos-checks/compare/38f448e00909f885f4ff2dcb591dfef221305c6f...b8f93e5b9c963cc2e59c10ac1d7821f60b95281f)
  - [X] Test Results: [jenkins#11](https://jenkins.mesosphere.com/service/jenkins/job/dcos-cluster-ops/job/public-dcos-checks-pulls-pipeline/11/console)
  - [X] Code Coverage (if available): [jenkins#11](https://jenkins.mesosphere.com/service/jenkins/job/dcos-cluster-ops/job/public-dcos-checks-pulls-pipeline/11/console)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by mnaboka** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
We are trying to increase the DCOS Test Coverage.

@mnaboka  - It might be a good idea to consider introducing / adding DCOS Integration Test with this bump. 

If it possible to add the tests, please add it. If it is not, please a create a JIRA ticket against DCOS where we can determine what needs to be done to enable integration test coverage and addition for dcos-checks component.

**Comment by mnaboka** [comment]
@orsenthil i have already opened a Jira and it's 1.12 blocker for now, feel free to adjust timeframe 
https://jira.mesosphere.com/browse/DCOS_OSS-2272

**Comment by mnaboka** [comment]
@orsenthil for some time dcos-checks was not tested very well at all.
Recently we [added](https://github.com/dcos/dcos-checks/pull/28) CI job to build and run unittests, so this should be fine for now

**Comment by orsenthil** [comment]
@mnaboka  - There is similar arguments made for other components too. Our understanding is DCOS_OSS-2272 covers the unittests for dcos-checks, which is required. Also adding CI for component != Increase in coverage in DC/OS.

The coverage for **DCOS** for dcos-checks component will be addition / enhancement of this test-suite: https://github.com/dcos/dcos/tree/master/packages/dcos-integration-test/extra 

Please determine if that can be  applicable / added. This addition ideally comes during the bump of the component, but it could come later too - https://jira.mesosphere.com/browse/DCOS_OSS-2272

Since we are early in this 1.12 time frame, my suggestion is to start the addition of the integration test suite inside DC/OS.

**Comment by mnaboka** [comment]
@orsenthil i agree we need integration tests. However this particular bump does not add any new features. These are bug fixes. We need to have them in for 1.11.1

**Comment by orsenthil** [comment]
@mnaboka  - How hard will it be add a new test module for dcos-checks, which does a simple query on service being up at a REST endpoint? We could start with that.

And yes, I will help reviews and inclusion by 28th and well before 1.11.1 timeframe.

**Comment by mnaboka** [comment]
@mesosphere-mergebot bump-ee

**Comment by mnaboka** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mnaboka** [comment]
@mesosphere-mergebot label Ship It

**Comment by mnaboka** [comment]
@mesosphere-mergebot label Work In Progress

**Comment by mnaboka** [comment]
@mesosphere-mergebot bump-ee

**Comment by mnaboka** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
Addition of Tests to the dcos-checks didn't go well as we couldn't get the integration test to succeed. 

@mnaboka  has removed the integration test, and this will come in a separate change.

We are including this PR for the merge to 1.11.1

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
