### PR TITLE
Fixed patch description in Mesos' `patch.json`.

### PR DESCRIPTION
**Pull request by gkleiman**
## High-level description

Fixes the description of a commit in Mesos' `patch.json` file.

## Corresponding DC/OS tickets (obligatory)

None =).

## Checklist for all PRs

  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: not a functional change.
  - X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by gkleiman** [comment]
cc/ @ArmandGrillet @greggomann @bmahler

**Comment by gkleiman** [comment]
mergebot label Ready For Review

**Comment by ArmandGrillet** [comment]
We should merge 3 PRs in one train:

1. Mesos bump.
2. This one.
3. #2527

Whom should we ask to do that?

**Comment by gkleiman** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
@ArmandGrillet @Gilbert88 can you review this one and https://github.com/mesosphere/dcos-enterprise/pull/2660 ? Thanks!

**Comment by gkleiman** [comment]
Superseded by https://github.com/dcos/dcos/pull/2808/.

**Pull request closed without merging**
