### PR TITLE
1.12 master train

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

* Adds dataDir to ucr bridge cni configuration #3092
* Adding gauripowale as a dcos owner. #3014
* Bump Mesos to nightly master 9147283  #3124
* [1.12/master] Use ngx.timer.every() for the AR cache update #3064

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by timaa2k** [comment]
@mesosphere-mergebot merge-it

**Comment by gpaul** [comment]
@mesosphere-mergebot merge-it

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-38027

**Comment by gpaul** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
