### PR TITLE
Don't skip checks that are limited to a specific role

### PR DESCRIPTION
**Pull request by branden**
## High-level description

This fixes a bug where checks that are defined to run only on masters or agents do not get executed by the check runner.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-38309](https://jira.mesosphere.com/browse/DCOS-38309) DC/OS checks with role limitations are not being run by dcos-check-runner

## Related tickets (optional)

N/A

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: This fixes a bug that has not made it into a release.
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Tests added upstream which verify that the check runner will fail with an error if its role is not "master" or "agent", and runs checks with a variety of roles and role filters and verifies that all expected checks are executed according to the role.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-check-runner/compare/519d5c7d3b94222f5b99d38893a8543819a18567...cca21b6180295de5daf21b5b1a9da0514c34f204
  - [x] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/public-dcos-cluster-ops%2Fdcos-check-runner%2Fdcos-check-runner-master/detail/dcos-check-runner-master/102/pipeline)
  - [x] Code Coverage (if available): [link to code coverage report](https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/public-dcos-cluster-ops%2Fdcos-check-runner%2Fdcos-check-runner-master/detail/dcos-check-runner-master/102/pipeline)

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot label [Request For Comment |Work In Progress |Holding |Ship It |Ready For Review] 
@mesosphere-mergebot override-status  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot bump-ee

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static DCOS_OSS-2115

**Pull request merged**
