### PR TITLE
Bumped Mesos to current master.

### PR DESCRIPTION
**Pull request by asridharan**
## High Level Description
This includes the Mesos bump including the following changes:
* The default executor to inject environment variables into launched tasks that will inform the tasks about the IP address available in its network namespace.
* Changes to support reservation refinement.

## Related Issues

  - [CORE-1136](https://jira.mesosphere.com/browse/CORE-1136) DefaultExecutor needs to inform tasks about IP addresses 
  - [MESOS-7631](https://issues.apache.org/jira/browse/MESOS-7631) DefautlExecutor needs to inform tasks about IP addresses
  - [CORE-849](https://jira.mesosphere.com/browse/CORE-849) Support DC/OS commons services on public agents 
  - [MESOS-7575](https://issues.apache.org/jira/browse/MESOS-7575) Support reservation refinement for hierarchical roles.
  - [CORE-992](https://jira.mesosphere.com/browse/CORE-992) Create Production Mesos which allows dynamic reservation of statically reserved resources
  - [DCOS-16115](https://jira.mesosphere.com/browse/DCOS-16115) Bump mesos for 1.10 

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: unit testing done in Mesos itself
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): 
https://github.com/mesosphere/mesos/compare/dcos-mesos-master-77d5075...mesosphere:dcos-mesos-master-abe9d1b
  - [x] Test Results: [mesos CI master-557ced0f](https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/Mesos_CI-build/1304/)

### CODE REVIEW

**Comment by asridharan** [comment]
@mesosphere-mergebot bump-ee

**Comment by asridharan** [comment]
@adam-mesos should we use this bump to get the `DefaultExecutor` changes?

**Comment by adam-mesos** [comment]
@asridharan the earlier Mesos bump has landed in dcos/dcos if/when you're ready to rebase.

**Comment by asridharan** [comment]
@mesosphere-mergebot bump-ee

**Comment by asridharan** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@sambatyon Looks like we're going to need to land https://github.com/mesosphere/mesos-modules-private/pull/179 to fix the build, now that your maintenance authz has landed in Mesos. cc: @tillt @karya0

**Comment by adam-mesos** [comment]
This now includes @mpark 's reservation specialization changes. Please update the PR description accordingly

**Comment by sambatyon** [comment]
We create PR #1095 against this one and it fails with some bad gateway when attempting to contact marathon.

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
Looking much better now. @asridharan Can you update the PR description with JIRA links, changelog, CI results, etc? Then we can actually review & merge this once it's green tonight

**Comment by asridharan** [comment]
@adam-mesos @mpark added the relevant details. Will re-base, but looks like we are ready to review this.

**Comment by asridharan** [comment]
@orsenthil any insights into why the upgrade test is failing?

**Comment by adam-mesos** [comment]
cc: @amitaekbote @branden

**Comment by adam-mesos** [comment]
Maybe the failure's related to #1657 (3dt rename) or #1561 (dcos-test-utils)? @darkonie @mellenburg

**Comment by amitaekbote** [comment]
Looks like mesos task fails after upgrading a host, 
[07:03:37][Step 2/2] advanced_tests.test_upgrade.TestUpgrade.test_mesos_task_state_remains_consistent

**Comment by tillt** [comment]
We need to debug what is happening under this hood:
```
subprocess.CalledProcessError: Command '['/usr/bin/ssh', '-oConnectTimeout=10', '-oControlMaster=auto', '-oControlPath=/teamcity/temp/buildTmp/tmpr639uqlz/control_socket', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oLogLevel=ERROR', '-oBatchMode=yes', '-oPasswordAuthentication=no', '-p', '22', 'centos@34.212.154.176', 'sudo', 'bash', 'dcos_node_upgrade.sh']' returned non-zero exit status 1
```

**Comment by asridharan** [comment]
@amitaekbote any logs to indicate that a Mesos task is failing?

**Comment by amitaekbote** [comment]
taking a look, the best way to debug this is to login to the cluster, teamcity logs has creds and the ips

**Comment by amitaekbote** [comment]
@tillt here's are the script contents: https://github.com/dcos/dcos/blob/master/dcos_installer/upgrade.py

**Comment by tillt** [comment]
The problem can not be reproduced on a plain DC/OS master PR (https://github.com/dcos/dcos/pull/1687).

**Comment by amitaekbote** [comment]
Potentially flaky test, we can keep an eye on it. I restarted the test for this pr and it seems to be chugging along fine

**Comment by adam-mesos** [comment]
@amitaekbote Certainly not flaky. It's failed the last 8 times on this PR.
https://teamcity.mesosphere.io/viewType.html?buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_UpgradeTest&branch_ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests=pull%2F1673&tab=buildTypeStatusDiv
I suspect the dcos-test-utils changes in @mellenburg 's #1561 and this Mesos bump.
Before MPark rebased on the latest train, the upgrade test passed fine in a similar Mesos bump PR #1524
https://teamcity.mesosphere.io/viewType.html?buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_UpgradeTest&branch_ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests=pull%2F1524&tab=buildTypeStatusDiv

**Comment by amitaekbote** [comment]
I have seen it fail on my pr too - https://github.com/dcos/dcos/pull/1677 , its weird that we dont see it on master. 

It failed again, looking..

**Comment by mpark** [comment]
It did pass before the #1679 merge yesterday from what I observed. @adam-mesos then merged master on top and it failed. Today I tried rebasing on top of master and it failed, then I added a revert of #1679 and it still fails.

**Comment by adam-mesos** [comment]
I think the 'TestUpgrade.test_mesos_task_state_remains_consistent' failure is a red herring. I've previously seen a case where that was just the first test to try to run, and it failed (as would any test) and that stopped the whole test suite.

**Comment by adam-mesos** [comment]
The 1.8.9 train failed the upgrade test like this, but for different reasons. https://github.com/dcos/dcos/pull/1663
Help me, Obi-wan @mellenburg , you're our only hope!

**Comment by adam-mesos** [comment]
But, given that non-Mesos bump PRs experience the same failure, I think we can go ahead with our reviews and get this onto a train where we'd have to solve the same upgrade test issue anyway.
@mpark Can you please review these PRs?

**Comment by asridharan** [comment]
@adam-mesos @mpark can sign off too. The only other concern in this PR was that I saw some conflicts when I cherry-picked the UI commits on top of Mesos changes. Would be great if someone can review that specific commit. It shouldn't break anything in DC/OS, but would good to make sure mesos UI is sane as well.

**Comment by tillt** [comment]
The problem has been identified as beeing Mesos caused.

```
2017-06-23 20:41:36: I0623 20:41:36.810322 28369 master.cpp:6296] Re-registered agent 86252c33-5b58-4967-aa6b-2d077a0f6171-S0 at slave(1)@10.10.0.55:5051 (10.10.0.55) with [{"name":"ports","ranges":{"range":[{"begin":1,"end":21},{"begin":23,"end":5050},{"begin":5052,"end":32000}]},"reservations":[{"role":"slave_public","type":"STATIC"}],"type":"RANGES"},{"disk":{"source":{"mount":{"root":"\/dcos\/volume0"},"type":"MOUNT"}},"name":"disk","reservations":[{"role":"slave_public","type":"STATIC"}],"scalar":{"value":51042.0},"type":"SCALAR"},{"name":"disk","reservations":[{"role":"slave_public","type":"STATIC"}],"scalar":{"value":51042.0},"type":"SCALAR"},{"name":"cpus","reservations":[{"role":"slave_public","type":"STATIC"}],"scalar":{"value":4.0},"type":"SCALAR"},{"name":"mem","reservations":[{"role":"slave_public","type":"STATIC"}],"scalar":{"value":14605.0},"type":"SCALAR"}]
2017-06-23 20:41:36: I0623 20:41:36.810535 28369 master.cpp:6403] Sending updated checkpointed resources {} to agent 86252c33-5b58-4967-aa6b-2d077a0f6171-S0 at slave(1)@10.10.0.55:5051 (10.10.0.55)
2017-06-23 20:41:36: I0623 20:41:36.811375 28368 master.cpp:6492] Received update of agent 86252c33-5b58-4967-aa6b-2d077a0f6171-S0 at slave(1)@10.10.0.55:5051 (10.10.0.55) with total oversubscribed resources {}
2017-06-23 20:41:36: I0623 20:41:36.811756 28372 replica.cpp:694] Replica received learned notice for position 124 from @0.0.0.0:0
2017-06-23 20:41:36: F0623 20:41:36.862709 28370 resources.cpp:1050] Check failed: !resource.has_role()
2017-06-23 20:41:36: *** Check failure stack trace: ***
2017-06-23 20:41:36: @     0x7f392635d1fd  google::LogMessage::Fail()
2017-06-23 20:41:36: @     0x7f392635f02d  google::LogMessage::SendToLog()
2017-06-23 20:41:36: @     0x7f392635cdec  google::LogMessage::Flush()
2017-06-23 20:41:36: @     0x7f392635f929  google::LogMessageFatal::~LogMessageFatal()
2017-06-23 20:41:36: @     0x7f3925558ca9  mesos::Resources::isEmpty()
2017-06-23 20:41:36: @     0x7f3925558d4c  mesos::Resources::add()
2017-06-23 20:41:36: @     0x7f392555a2bb  mesos::Resources::operator+=()
2017-06-23 20:41:36: @     0x7f392555a35a  mesos::Resources::operator+=()
2017-06-23 20:41:36: @     0x7f392555a47b  mesos::Resources::Resources()
2017-06-23 20:41:36: @     0x7f392580a2a1  mesos::internal::master::validation::resource::validateGpus()
2017-06-23 20:41:36: @     0x7f392580a523  mesos::internal::master::validation::resource::validate()
2017-06-23 20:41:36: @     0x7f392580aeec  mesos::internal::master::validation::master::message::reregisterSlave()
2017-06-23 20:41:36: @     0x7f392572a23a  mesos::internal::master::Master::reregisterSlave()
2017-06-23 20:41:36: @     0x7f39257b22d9  ProtobufProcess<>::handler8<>()
2017-06-23 20:41:36: @     0x7f3925758f05  std::_Function_handler<>::_M_invoke()
2017-06-23 20:41:36: @     0x7f39257027a3  mesos::internal::master::Master::_visit()
2017-06-23 20:41:36: @     0x7f392571acc2  mesos::internal::master::Master::visit()
2017-06-23 20:41:36: @     0x7f39262c61b1  process::ProcessManager::resume()
2017-06-23 20:41:36: @     0x7f39262cfe77  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN7process14ProcessManager12init_threadsEvEUt_vEEE6_M_runEv
2017-06-23 20:41:36: @     0x7f392448e230  (unknown)
2017-06-23 20:41:36: @     0x7f3923cacdc5  start_thread
2017-06-23 20:41:36: @     0x7f39239db76d  __clone
2017-06-23 20:41:36: dcos-mesos-master.service: main process exited, code=killed, status=6/ABRT
2017-06-23 20:41:36: Unit dcos-mesos-master.service entered failed state.
2017-06-23 20:41:36: dcos-mesos-master.service failed.
```

**Comment by asridharan** [comment]
Thanks @tillt !! @mpark ^^

**Comment by adam-mesos** [comment]
cc: @neilconway while MPark is on vacation

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
