### PR TITLE
Rename systemd unit dcos-ddt -> dcos-3dt

### PR DESCRIPTION
**Pull request by branden**
/cc @cmaloney @malnick

### CODE REVIEW

**Comment by cmaloney** [comment]
:100: consistency

:ship:

**Comment by malnick** [comment]
That's actually inconsistent. 3DT = DC/OS Distributed Diagnostics Tool. So, calling it dcos-3dt means "dcos-dcos-distributed-diagnostics-tool".

**Comment by malnick** [comment]
Votes on renaming to `dcos-diagnostics.service` -> CC @cmaloney @darkonie @spahl

**Comment by cmaloney** [comment]
:-1: on dcos-diagnostics. The repo is called 3dt. The package is called 3dt. Internal / dev name should be fully internally consistent

**Comment by spahl** [comment]
I'd rather call it dcos-3dt. Just like we have dcos-spartan and not dcos-dns-proxy

**Pull request merged**
