### PR TITLE
[master] Mergebot Automated Train PR - 2018-Sep-05-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3363 - metronome 0.5.3 bump
* #3376 - Fix various cosmos issues
* #3381 - [master] Bump Mesos to nightly master 6a98857
* #3382 - chore(dcos-ui): bump DC/OS UI dcos-ui/master+v2.19.4
* #3387 - Bumping marathon to 1.7.111

> Manual Addition

Also included

* https://github.com/dcos/dcos/pull/3366 -  Add plugins to Telegraf #3366

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
> Enterprise Bump updated.

mergebot in a bad mood? Usually it gives me the link to the enterprise bump PR! :D

**Comment by orsenthil** [comment]
> mergebot in a bad mood? Usually it gives me the link to the enterprise bump PR! :D

Not for the Train PRs. (Train PRs bump-ee is automatic, behind the scenes. So, Open PR did not know about the EE Train PR existence). Although, I think it is better to jump some hoops and provide a consistent experience.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcos/windows  https://jira.mesosphere.com/browse/DCOS-41386

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-41386

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-4045

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
