### PR TITLE
Marathon 1.6 Beta Release

### PR DESCRIPTION
**Pull request by kensipe**
## High-level description

* Workload bursting
* Significant performance improvement to deployments
* Docker IPv6 Support (Apache Mesos 1.5 Required)

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-19774](https://jira.mesosphere.com/browse/DCOS-19774) Bump Marathon for DC/OS 1.11 Beta2.

## Related tickets (optional)

Other tickets related to this change:
 
In addition there was a technical infrastructure update with a move to akka.http for controllers and a switch from joda time to java time.

- [MARATHON_EE-1713](https://jira.mesosphere.com/browse/MARATHON_EE-1713)
- [MARATHON_EE-1661](https://jira.mesosphere.com/browse/MARATHON_EE-1661)
- [MARATHON_EE-1770](https://jira.mesosphere.com/browse/MARATHON_EE-1770)
- [MARATHON_EE-1764](https://jira.mesosphere.com/browse/MARATHON_EE-1764)
- [MARATHON_EE-1768](https://jira.mesosphere.com/browse/MARATHON_EE-1768)
- [MARATHON_EE-1701](https://jira.mesosphere.com/browse/MARATHON_EE-1701)
- [MARATHON-7880](https://jira.mesosphere.com/browse/MARATHON-7880)
- [MARATHON-7878](https://jira.mesosphere.com/browse/MARATHON-7878)
- [MARATHON-7301](https://jira.mesosphere.com/browse/MARATHON-7301)
- [MARATHON-7877](https://jira.mesosphere.com/browse/MARATHON-7877)
- [MARATHON-7876](https://jira.mesosphere.com/browse/MARATHON-7876)
- [MARATHON-7299](https://jira.mesosphere.com/browse/MARATHON-7299)
- [MARATHON-7914](https://jira.mesosphere.com/browse/MARATHON-7914)
- [MARATHON-7873](https://jira.mesosphere.com/browse/MARATHON-7873)

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/mesosphere/marathon/compare/66a63ef...b0f6bda
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/530/
  - [x] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by kensipe** [comment]
@mesosphere-mergebot label review for review

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
https://jira.mesosphere.com/browse/DCOS-19790

**Comment by kensipe** [comment]
rebased to master

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by jgehrcke** [comment]
@mesosphere-mergebot should not have applied the `ship-it` label yet, because `mergebot/enterprise/has_ship-it` is still outstanding. Mhm.

**Pull request merged**
