### PR TITLE
[1.11] Bump Mesos to nightly 1.5.x b82d550

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
## High-level description

This is a routine bump to the latest 1.5.x branch of Mesos.

## Related JIRA Issues

* [MESOS-8480](https://issues.apache.org/jira/browse/MESOS-8480) Mesos returns high resource usage when killing a Docker task.
* [MESOS-8413](https://issues.apache.org/jira/browse/MESOS-8413) Zookeeper configuration passwords are shown in clear text
* [MESOS-8413](https://issues.apache.org/jira/browse/MESOS-8481) Agent reboot during checkpointing may result in empty checkpoints.
* [MESOS-7742](https://issues.apache.org/jira/browse/MESOS-7742) Race conditions in IOSwitchboard: listening on unix socket and premature closing of the connection.
* [MESOS-7742](https://issues.apache.org/jira/browse/MESOS-7742) CGROUPS_ROOT_PidNamespaceForward and CGROUPS_ROOT_PidNamespaceBackward tests fail
* [MESOS-8510](https://issues.apache.org/jira/browse/MESOS-8510) URI disk profile adaptor does not consider plugin type for a profile.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Mesos diff](https://github.com/mesosphere/mesos/compare/8436b76224c48a1a90aa7940fd52399ca7e8a9e7...5a89e16d36600327042de699334c19c0905448e4)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mesosphere-teamcity** [comment]
Corresponding EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2263

**Comment by greggomann** [comment]
## High-level description

This is a routine bump to the latest 1.5.x branch of Mesos.

## Related JIRA Issues

* [MESOS-8480|https://issues.apache.org/jira/browse/MESOS-8480] Mesos returns high resource usage when killing a Docker task.
* [MESOS-8413|https://issues.apache.org/jira/browse/MESOS-8413] Zookeeper configuration passwords are shown in clear text
* [MESOS-8413|https://issues.apache.org/jira/browse/MESOS-8481] Agent reboot during checkpointing may result in empty checkpoints.
* [MESOS-7742|https://issues.apache.org/jira/browse/MESOS-7742] Race conditions in IOSwitchboard: listening on unix socket and premature closing of the connection.
* [MESOS-7742|https://issues.apache.org/jira/browse/MESOS-7742] CGROUPS_ROOT_PidNamespaceForward and CGROUPS_ROOT_PidNamespaceBackward tests fail
* [MESOS-8510|https://issues.apache.org/jira/browse/MESOS-8510] URI disk profile adaptor does not consider plugin type for a profile.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)


## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Mesos diff](https://github.com/mesosphere/mesos/compare/8436b76224c48a1a90aa7940fd52399ca7e8a9e7...5a89e16d36600327042de699334c19c0905448e4)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

**Comment by greggomann** [comment]
We can close this in favor of #2472

**Comment by mesosphere-teamcity** [comment]
Closing PR in lieu of #2472

**Pull request closed without merging**
