### PR TITLE
[1.13] DC/OS UI LAtest [do not merge]

### PR DESCRIPTION
**Pull request by juliangieseke**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jgehrcke** [comment]
Can this be closed?

**Comment by juliangieseke** [comment]
Hey JP, no. we want to keep it open to be able to create clusters from this PR. since we're not bumping on every merged PR anymore, we need this PR to be able to get a cluster up from our release branches…

**Comment by juliangieseke** [comment]
just realized mergebot closed our PRs for 1.12 and 1.11 :(

**Comment by jgehrcke** [comment]
Looks like this is not needed anymore for now. Closing. Please leave a comment or ping someone on Slack if this should be re-opened!

**Pull request closed without merging**
