### PR TITLE
curl: bump to 7.58.0

### PR DESCRIPTION
**Pull request by ahairape**
This PR bumps curl from 7.48.0 to 7.58.0.

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:
https://jira.mesosphere.com/browse/DCOS-21557

  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by ahairape** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
Both `test_applications.test_if_ucr_app_can_be_deployed[Healthcheck_MESOS_HTTP]` and `test_applications.test_if_ucr_app_can_be_deployed[Healthcheck_MESOS_HTTP]` are likely failing because of this known flakiness: https://jira.mesosphere.com/browse/DCOS-18018

**Comment by adamtheturtle** [comment]
Given the failures on EE, @ahairape I'm not convinced that the failures here are due to flakiness. Please  re-run the tests if you think it might be flakiness.

**Comment by ahairape** [comment]
I think these are not flakes. I have re-run some of the tests several times (2 or 3) and got the same error every time. I am investigating it at the moment.

**Comment by ahairape** [comment]
Closing this PR in favour of https://github.com/dcos/dcos/pull/2647.
Please see https://jira.mesosphere.com/browse/DCOS-21557 for details.

**Pull request closed without merging**
