### PR TITLE
Update dcos-diagnostics

### PR DESCRIPTION
**Pull request by janisz**
Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5314

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5314](https://jira.mesosphere.com/browse/DCOS_OSS-5314)

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] [Change log from the last version integrated (this should be a link to commits for easy verification and review)](https://github.com/dcos/dcos-diagnostics/compare/d31bb5788361...8302fc32211e)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [x] Test Results: [link to CI job test results for component](https://travis-ci.org/dcos/dcos-diagnostics/builds/565370024)
  - [x] Code Coverage (if available): [link to code coverage report](https://codecov.io/gh/dcos/dcos-diagnostics/commit/8302fc32211ea47d05c070009d32a89db14ee44c )

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @drewvanstone @br-lewis @makkes

**Comment by janisz** [comment]
Can one of the @dcos/admins  @mesosphere/dcos-owners issue the following command?

```java
@mesosphere-mergebot override-status 
teamcity/dcos/test/terraform/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS-57092
```

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required minor package upgrade

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status 
teamcity/dcos/test/terraform/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS-57092

**Pull request merged**
