### PR TITLE
DCOS_OSS-5373 - Use master IP and not master FQDN to collect logs.

### PR DESCRIPTION
**Pull request by jbarrick-mesosphere**
## High-level description

This fixes collection of sandbox logs. Before, we tried to SSH to the ELB which did not work - we should SSH to the IP.

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5373](https://jira.mesosphere.com/browse/DCOS_OSS-5373) Failed test bundles should include sandbox logs

### CODE REVIEW

**Comment by jbarrick-mesosphere** [comment]
@mesosphere-mergebot request-review @jgehrcke @greggomann @orsenthil @cprovencher

**Comment by jbarrick-mesosphere** [comment]
@mesosphere-mergebot changelog-not-required tests

**Comment by jbarrick-mesosphere** [comment]
OSS tests running: https://teamcity.mesosphere.io/viewLog.html?buildId=2103025&tab=buildResultsDiv&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackendGroup1TerraformSpotBlock
EE tests running: https://teamcity.mesosphere.io/viewLog.html?buildId=2103034&tab=buildResultsDiv&buildTypeId=DcOs_Enterprise_Test_Inte_AwsOnpremWStaticBackendAndSecurityStrictGroup1Terraf_2

**Comment by jbarrick-mesosphere** [comment]
We got lucky (I guess) and that OSS test run flaked on us so we can see the sandbox there: https://teamcity.mesosphere.io/viewLog.html?buildId=2103025&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackendGroup1TerraformSpotBlock&tab=artifacts#!1miu9

@jgehrcke could you maybe look over those artifacts and make sure that you see everything you expect?

**Comment by greggomann** [comment]
woohoo!! yep @jbarrick-mesosphere I see Mesos task sandbox logs in the artifacts, which is exactly what we need. Looks great.

**Comment by jgehrcke** [comment]
> @jgehrcke could you maybe look over those artifacts and make sure that you see everything you expect?

Thanks! I had a look, and the file sizes are unexpectedly small, e.g. `mesos_master.log (2.62 KB)`. This is just one second worth of logs, also for the Mesos agent units. 

Created https://jira.mesosphere.com/browse/DCOS-57008 for tracking this.

**Pull request merged**
