### PR TITLE
Train 270 (1.9)

### PR DESCRIPTION
**Pull request by margaret**
## 🚂:two::seven::zero:🚋 (1.9)

* https://github.com/dcos/dcos/pull/2141 – **Admin Router: Pin pytest**
> https://jira.mesosphere.com/browse/DCOS_OSS-1910

### CODE REVIEW

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot label ready for review

**Comment by margaret** [comment]
Looks like the azure/arm failure is this https://jira.mesosphere.com/browse/DCOS_OSS-1830

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-1830

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
