### PR TITLE
Bump metrics git hash to incorporate default executor change

### PR DESCRIPTION
**Pull request by mrbrowning**
## High Level Description

 - This change bumps the commit hash of the `dcos-metrics` module so that the `STATSD_UDP_HOST` and `STATSD_UDP_PORT` envvars are exposed to tasks running on the Mesos default executor (https://github.com/dcos/dcos-metrics/pull/106).

## Related Issues

  - None

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: This merely changes a reference to a commit in another repo that has not seen any interface changes.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [commit](https://github.com/dcos/dcos-metrics/pull/109/commits/cdd30f703685b017ea1ce3964b8144a95ee9af5d)
  - [x] Test Results: [results](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/387/)
  - [x] Code Coverage (if available): [coverage](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-metrics/job/public-dcos-metrics-pulls/387/cobertura/)
___

### CODE REVIEW

**Comment by jgehrcke** [comment]
Does this override https://github.com/dcos/dcos/pull/1613/files? (which is a sad example for how bad our integration work sometimes is. Sorry @philipnrmn).

**Comment by mrbrowning** [comment]
@jgehrcke Yes, it bumps the ref of `dcos-metrics` to a later commit that includes all other changes that have been made in that repo since then. However, I'm waiting for https://github.com/dcos/dcos-metrics/pull/108 to land before I update this PR to actually reference a merged commit.

**Comment by mrbrowning** [comment]
@mesosphere-mergebot bump-ee

**Comment by philipnrmn** [comment]
If you want that latest commit to work @mrbrowning you'll need to change the `ref_origin` to your branch.

**Comment by mrbrowning** [comment]
@mesosphere-mergebot bump-ee

**Comment by benclarkwood** [comment]
@mesosphere-mergebot label ready for review

**Comment by mrbrowning** [comment]
@mesosphere-mergebot label ready for review

**Comment by mrbrowning** [comment]
@mesosphere-mergebot bump-ee

**Comment by benclarkwood** [comment]
Superceded by: https://github.com/dcos/dcos/pull/1715

**Comment by jgehrcke** [comment]
> Superceded by: #1715

Closing this PR as of this statement.

**Pull request closed without merging**
