### PR TITLE
Admin Router:  AR-NEXT

### PR DESCRIPTION
**Pull request by vespian**
## High Level Description

This PR is an aggregate of multiple smaller PRs, which in turn were extracted from https://github.com/dcos/dcos/pull/1702

PRs included:
~~https://github.com/mesosphere/dcos/pull/28~~
~~https://github.com/mesosphere/dcos/pull/29~~
~~https://github.com/mesosphere/dcos/pull/30~~
~~https://github.com/mesosphere/dcos/pull/31~~
~~https://github.com/mesosphere/dcos/pull/32~~
~~https://github.com/mesosphere/dcos/pull/33~~
~~https://github.com/mesosphere/dcos/pull/34~~
~~https://github.com/mesosphere/dcos/pull/35~~
~~https://github.com/mesosphere/dcos/pull/36~~
~~https://github.com/mesosphere/dcos/pull/37~~
~~https://github.com/mesosphere/dcos/pull/38~~

Failures in all individual PRs (both EE and Open) are expected.

## Related Issues

See individual PRs

## Related PRs

EE PR: https://github.com/mesosphere/dcos-enterprise/pull/1265

### CODE REVIEW

**Comment by vespian** [comment]
Failed  test_dcos_diagnostics.test_dcos_diagnostics_runner_poststart tracked in here: https://jira.mesosphere.com/browse/DCOS-17706

**Comment by lingmann** [comment]
Hi @vespian I've created a ticket to track what looks like a [bug with mergebot](https://jira.mesosphere.com/browse/DCOS-17889). Also regarding the removal of the ship-it label, technically this is what we want since the code has changed since the reviewers gave their +1. However, I don't think the process here is very streamlined yet so I'm going to re-add the ship-it label and just ask that @gpaul @mhrabovcin and @adamtheturtle to please take a look and chime in with a -1 ASAP if they see anything that is concerning with these latest changes.

**Comment by lingmann** [comment]
We are going to hold this until the next train to give the reviewers a chance to do a final +1/-1 review of latest changes. @vespian if you need this expedited, please ping myself or Cathy in #dcos-release. Thanks!

**Comment by vespian** [comment]
@mhrabovcin @adamtheturtle @gpaul  Comimt sha's are intact, so you just need to check the Merge commits, but they are nothing more than just adjusting code to the current master.

**Comment by vespian** [comment]
@lingmann Both PRs have been re-ACKed. Could you please include it on a train?

CC @jgehrcke

**Comment by lingmann** [comment]
@vespian 👍  landing on the train today. Thanks everyone!

**Comment by orsenthil** [comment]
I try to make a note every time I notice:

We should have squashed the commits here. These are cruft, we do not want them to be preserved in the history of a "shared" open source project. :(

https://www.dropbox.com/s/lzs2mm0i4wvbmtl/Screenshot%202017-08-15%2013.43.42.png?dl=0

**Comment by jgehrcke** [comment]
@vespian can you please update corresponding JIRA tickets now that this has been merged? Thank you!

**Pull request merged**
