### PR TITLE
Added changelog entry for DCOS_OSS_5152

### PR DESCRIPTION
**Pull request by makkes**
## High-level description

This is just the changelog for #5522 

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5152](https://jira.mesosphere.com/browse/DCOS_OSS-5152) Modify dcos-installer not to warn on missing optional ssh_* keys in dcos-config.yml

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by makkes** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jgehrcke** [comment]
@makkes a `.0` release is not supposed to have a "Fixed and improved" section.

Also see https://github.com/dcos/dcos/wiki/CHANGES.md-guidelines#major-releases


Or, maybe more helpful: is this a forward-port? Does this land in the near future in 1.13.x? If the answer is "yes" then this does not get a changelog entry in 1.14.0.

**Comment by janisz** [comment]
@jgehrcke > .0 release is not supposed to have a "Fixed and improved" section.

Any source for this? Why? [Mesos changelog](https://gitbox.apache.org/repos/asf?p=mesos.git;a=blob_plain;f=CHANGELOG;hb=1.8.0) has improvement section. I thought every release brings some improvements.

**Comment by makkes** [comment]
Ah yeah, as far as I understood it this is not needed in the `master` branch because 1.14 hasn't been released, yet and we're releasing this in 1.13.x before 1.14 gets released. Is that correct, @jgehrcke?

**Comment by jgehrcke** [comment]
> Is that correct, @jgehrcke?

Yes!

> Any source for this?

https://github.com/dcos/dcos/wiki/CHANGES.md-guidelines#major-releases

This really is based on the idea that we should focus our energy where it has most meaningful impact.

To your point:

>  I thought every release brings some improvements.

Yes, but the valid question always is "compared to what"? When one reads the 1.14.0 changelog then "compared to what" is actually not that easy to answer... 

- compared to 1.13.0? That is roughly equivalent with "spam": large parts would be duplicated from 1.13.1, 1.13.2, 1.13.3, ... and the actually meaningful items appear to be hidden in the noise.

- compared to the last 1.13.x release? Yeah, that seems to make sense! A user implicitly assumes that all the goodies released with (example dates) `1.13.5` on October 10 2019 are contained in `1.14.0` released on November 1 2019. That is the thinking behind https://github.com/dcos/dcos/wiki/CHANGES.md-guidelines#major-releases. Let me know what you think.

**Pull request closed without merging**
