### PR TITLE
Train 303 (master)

### PR DESCRIPTION
**Pull request by lingmann**
## Train 303

* #2282 chore(dcos-ui): update package
* #2279 Add basic integration test for Metronome
* #2276 Bump Marathon
* #2209 Get rid of dcos-net watchdogs
* #2199 [DCOS-19976] Make outside-facing TLS configuration of Master Admin Router configurable
* #2154 Admin Router: Minimizing software version information reported by the AR
* #2151 bump dcos diagnostics
* #2247 Licensing/installer

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
@orsenthil confirmed with @spahl and @jimenez and adding it now

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
@mesosphere-mergebot ready for review

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
