### PR TITLE
upgrade navstar and minuteman to support 1k node cluster

### PR DESCRIPTION
**Pull request by GoelDeepak**
## High Level Description

This patch fixes navstar crash in 1k node cluster

## Related Issues

  - [DCOS_OSS-796](https://jira.mesosphere.com/browse/DCOS_OSS-796) navstar unhealthy in 1k node cluster

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]

https://github.com/dcos/navstar/pull/82
https://github.com/dcos/minuteman/pull/113
https://github.com/dcos/lashup/compare/f2a20fa1033724cf47724e6c9d701f4dcd4b4e01...e831653c7a8eb3cb44e8ebed08c3164e31849975
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
@GoelDeepak @asridharan Please find reviewers for these component bumps, and fill in the component checklist for each bumped component. This PR is holding back our 1000-node testing of 1.8.9, which is currently the only thing holding up that release!

**Comment by asridharan** [comment]
@drewkerrigan @nlsun can you review this?

**Comment by nlsun** [comment]
Related to https://github.com/dcos/navstar/pull/82 and https://github.com/dcos/minuteman/pull/113

**Comment by orsenthil** [comment]
@mesosphere-mergebot label holding

We need to decide on what we should do with upgrade test.
This is failing on 1.8.9 branch itself: https://teamcity.mesosphere.io/viewType.html?buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_UpgradeTest&branch_ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests=1.8.9&tab=buildTypeStatusDiv

The call we need to make is - Should we ignore Upgrade test failure? That can be made if this is manually tested for upgrade and made sure that PR is not the cause.

On 1.8.9 upgrade test failure - that's bigger call and we need to find the root cause and decide.

**Comment by adam-mesos** [comment]
@GoelDeepak Can you please provide the navstar and minuteman changelog links? Technically you should fill out the component checklist part of the description for each component bumped, including CI test results (do the networking components have their own unit tests?)

**Comment by GoelDeepak** [comment]
I have updated the corresponding PRs. The actual fix went into a library. The library is bumped to the point where the fix went in. Yes, networking components have their own CI tests which is part of the PRs that I shared

**Pull request merged**
