### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Jul-19-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3109 - Metronome 0.4.3 bump for 1.11

### CODE REVIEW

**Comment by nLight** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-39310

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-39310

**Comment by nLight** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by nLight** [comment]
@orsenthil would you please add `ship it`?

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
