### PR TITLE
1.9 train 202

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

* #1807 - Add cluster-id file to diagnostics bundle
* #1814 - Bump version to 1.9.3
* #1820 -  bumping the marathon to version 1.4.6

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
Restarted `integration-test/vagrant-bash`.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
