### PR TITLE
[1.10.1] Train 223

### PR DESCRIPTION
**Pull request by sschneid**
#1923 chore(dcos-ui): bump dcos-ui for 1.10.1
#1937 (1.10) Fix method name in installer
#1943 [1.10.1] Bump dcos-metrics

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
We should add https://github.com/dcos/dcos/pull/1943 to this train.

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
