### PR TITLE
Minuteman support for named vips in metric tags.

### PR DESCRIPTION
**Pull request by aeyakovenko**

### CODE REVIEW

**Comment by aeyakovenko** [comment]
this is ready for review, @cmaloney @sargun

**Comment by cmaloney** [comment]
DC/OS 1.9 targeted?

**Comment by cmaloney** [comment]
Is there a way we can test / check this new feature is actually working?

**Comment by aeyakovenko** [comment]
this is tested in this integration test, https://github.com/mesosphere/dcos-enterprise/pull/319

**Comment by cmaloney** [comment]
@aeyakovenko with it only in a place people here can't see, I can't tell when making changes to this repository if it's badly broken or not. Really need something so if I revert your change to the package the test fails in this repository.

**Comment by aeyakovenko** [comment]
@sargun @cmaloney Do we have any general integration tests for minuteman already in dcos?  Those should verify that minuteman is working properly.  Otherwise this change enables an enterprise only feature, it would be hard to test for it outside of the enterprise component that uses it, since minuteman only exposes erlang endpoints.

**Comment by aeyakovenko** [comment]
@cmaloney @sargun, enterprise tests pass as well,
https://github.com/mesosphere/dcos-enterprise/pull/319

is there anything else blocking this?

**Comment by sargun** [comment]
@spahl @orsenthil

**Comment by cmaloney** [comment]
:ship:

**Pull request merged**
