### PR TITLE
Bug DCOS-9904: Points to navstar patch for overlay polling changes

### PR DESCRIPTION
**Pull request by GoelDeepak**

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@Sargun, @cmaloney  This PR is ready for review

**Comment by sargun** [comment]
@spahl

**Comment by sargun** [comment]
@GoelDeepak Can you merge:
https://github.com/dcos/navstar/pull/25
https://github.com/dcos/minuteman/pull/55

and update this PR to include hash bumps for both?

**Comment by GoelDeepak** [comment]
@sargun Done. This PR is ready to be reviewed and merged

**Comment by sargun** [comment]
LGTM.

**Comment by sargun** [comment]
@spahl -- This PR has been tested at 1K nodes. It appears to clean things up nicely. Please Merge?

**Pull request merged**
