### PR TITLE
[1.12] Update dcos-diagnostics

### PR DESCRIPTION
**Pull request by janisz**
### Bacports: https://github.com/dcos/dcos/pull/3623

* Update dcos-diagnostics to the latest version with small fixes and upgraded dependencies

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4322](https://jira.mesosphere.com/browse/DCOS_OSS-4322) 

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-diagnostics/compare/f612504f524c74f10b48c0e1a2cdb06820529e50...a6a4009d8610f947badf3d93bc4d0874cf50230d
  - [x] Test Results: https://travis-ci.org/dcos/dcos-diagnostics/builds/440056367
  - [x] Code Coverage (if available): https://codecov.io/gh/dcos/dcos-diagnostics/compare/cc04232576c777824ef7bb6bd8d3bc01aba0d602...a6a4009d8610f947badf3d93bc4d0874cf50230d

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jgehrcke** [comment]
Metronome broken again on ARM

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status 
teamcity/dcos/test/azure/arm  https://jira.mesosphere.com/browse/DCOS-41675

**Comment by jgehrcke** [comment]
@mesosphere-mergebot sync

**Comment by jgehrcke** [comment]
I would expect this PR to have a `ship-it` label by now. @orsenthil @cgawron1 why didn't this happen here?

**Comment by gpaul** [comment]
@mesosphere-mergebot sync

**Comment by gpaul** [comment]
I reissued the sync command, that appeared to update the enterprise/build-status/aggregate status to green. Now waiting for ship it.

**Comment by jgehrcke** [comment]
Which raises the question: why was `sync` required twice?

**Pull request merged**
