### PR TITLE
bump marathon to v1.4.0-RC8

### PR DESCRIPTION
**Pull request by jdef**
## High Level Description

* bump Marathon from 1.4.0-RC7 to 1.4.0-RC8

## Related Issues

  - [MARATHON-1378](https://jira.mesosphere.com/browse/MARATHON-1378) pod tasks are missing DiscoveryInfo; broken for minuteman
  - [MARATHON-1383](https://jira.mesosphere.com/browse/MARATHON-1383) Marathon is not setting `network-scope` flag for mesocontainerizer

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
    * dcos-networking team is providing tests for MARATHON-1378 and MARATHON-1383
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/mesosphere/marathon/blob/releases/1.4/changelog.md
  - [x] Test Results: https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&buildTypeId=Oss_Marathon_Packages&buildId=556839
  - [x] Code Coverage (if available): https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&buildTypeId=Oss_Marathon_Packages&buildId=556839
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by lingmann** [comment]
@jdef can we get a corresponding enterprise PR bump as well?

**Comment by spahl** [comment]
@lingmann there is one. I referenced this PR there

**Comment by lingmann** [comment]
I see it now, thanks

**Comment by jdef** [comment]
The JIRAs mentioned were the only ones linked to the GH tickets. Possible
that there are JIRAs for other changes mentioned in the change log.

**Pull request merged**
