### PR TITLE
Backport test_networking changes

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

As noted this in this comment - https://github.com/dcos/dcos/pull/2426#issuecomment-368958266 
this commit brings the changes from https://github.com/dcos/dcos/pull/2426

It could not be cherrypicked as the change spawned across 8 commits.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@urbanserj  / @jeschkies  / @mellenburg / @kensipe   - Please review this and EE counterpart.

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1902

**Comment by urbanserj** [comment]
@margaret could you please review it and EE PR again?

**Pull request merged**
