### PR TITLE
Upstream diagnostics methods

### PR DESCRIPTION
**Pull request by margaret**
## High-level description

You can do `py.test --diagnostics ...` to generate the diagnostics bundle to the home directory.

Moves the changes in https://github.com/dcos/dcos/pull/2411/ into `dcos-test-utils` 

Corresponds to (https://github.com/dcos/dcos-test-utils/pull/32)

To-do (in dcos-launch): modify the pytest method to also copy over the diagnostics report when the --diagnostics command is passed to pytest.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - https://jira.mesosphere.com/browse/QUALITY-1819

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by margaret** [comment]
Rebased

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
The `pytest_sessionfinish` hook is available in the [hookspec source](https://docs.pytest.org/en/latest/_modules/_pytest/hookspec.html#pytest_fixture_post_finalizer), but annoyingly (concerningly?) not documented. It still seems significantly less sketchy than relying on alphabetical execution of same-scope fixtures though.

**Comment by margaret** [comment]
`pytest_unconfigure` is in the docs and for the purposes of this also works, so going with that.

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
Temporarily changed the build step to always scp the diagnostics bundle so I could check that it works here (it does) https://teamcity.mesosphere.io/viewLog.html?buildId=998467&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsCloudFormationSimple&tab=artifacts

**Comment by margaret** [comment]
rebased

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
test_networking.test_ipv6 and test_networking.test_vip failed on arm/azure but since this is going to be re-run again anyway to point dcos-test-utils buildinfo.json to the right fork, no need to override

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
@margaret test-utils bump can now be pointed at master

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot label ready for review

**Comment by margaret** [comment]
open onprem static with `--diagnostics` https://teamcity.mesosphere.io/viewLog.html?buildId=1003283&
ee strict onprem static with `--diagnostics` https://teamcity.mesosphere.io/viewLog.html?buildId=1003285&

**Comment by margaret** [comment]
azure ARM failure https://teamcity.mesosphere.io/viewLog.html?buildId=1002018&buildTypeId=DcOs_Open_Test_IntegrationTest_AzureArm is the rlimits flaky test https://jira.mesosphere.com/browse/DCOS_OSS-782?jql=text%20~%20%22test_if_rlimits_can_be_used%22

**Comment by margaret** [comment]
(paused, might replace with https://github.com/dcos/dcos/pull/2661)

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  holding

**Comment by orsenthil** [comment]
I think, we won't be working on this or merging this as the targets have divulged. Best left closed. Thank you for your contribution.

**Pull request closed without merging**
