### PR TITLE
DCOS-54493 - Update DC/OS 1.13 reference to 1.13.2

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

* DCOS-54493 - Update DC/OS 1.13 reference to 1.13.2

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
Uppsie just seeing that I duplicated the effort with dcos/dcos#5615.

However, in my downstream PR I have also updates CHANGES.md which seems to be missing here.

**Comment by jgehrcke** [comment]
Closing in favor of  #5615 hope that's ok @orsenthil -- thanks!

**Comment by orsenthil** [comment]
Thanks, @jgehrcke !

**Pull request closed without merging**
