### PR TITLE
[1.12] Mergebot Automated Train PR - 2018-Sep-27-20-46

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3502 - release v0.6.1 cosmos to 1.12
* #3506 - [1.12] Bump dcos-net

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/tox/windows DCOS-41386

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status  teamcity/dcos/test/azure/arm DCOS-41677

**Comment by urbanserj** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
