### PR TITLE
[1.12] Run metrics tests on one node per role

### PR DESCRIPTION
**Pull request by gracedo**
## High-level description

Changes some metrics integration tests (where applicable) to run tests on one node per role (public/private agent, master).

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4356](https://jira.mesosphere.com/browse/DCOS_OSS-4356) Run metrics tests on one node from each role

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: integration test only change
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by gracedo** [comment]
@philipnrmn @janisz can I get a review on this one in your spare time? It's a backport of https://github.com/dcos/dcos/pull/4077 which has already been merged. Thanks!

**Comment by philipnrmn** [comment]
@mesosphere-mergebot sync

**Comment by philipnrmn** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
