### PR TITLE
[1.12] Added a Mesos patch for health check definitions in master API outputs.

### PR DESCRIPTION
**Pull request by greggomann**
## High-level description

This PR adds a patch on top of OSS Mesos which includes task health check definitions in Mesos master/agent API outputs.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

The related ticket for this PR exists in OSS Mesos JIRA:
  - [MESOS-8780](https://issues.apache.org/jira/browse/MESOS-8780) Expose Check and HealthCheck information on Mesos HTTP endpoints.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: The relevant tests are included in the Mesos test suite - see [this patch](https://reviews.apache.org/r/69110/).
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by greggomann** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
This PR is on head of the 1.12 branch and can be merged directly. There is no need for this train - https://github.com/dcos/dcos/pull/3821

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-41675

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
Github does not indicate that this rebase is required. I am not sure, what is happening here with merge-it.  We discarded the train PR as not required  (https://github.com/dcos/dcos/pull/3821) - But it did have the open integration tests successful. https://teamcity.mesosphere.io/viewLog.html?buildId=1309139&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackend 
Based on this, I am merging this PR directly.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
