### PR TITLE
Fix flask-compress build.

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

https://jira.mesosphere.com/browse/DCOS-41370 -  Uncached build on Master fails to download flask-compress package

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
This will fix the uncached build issue for master - https://teamcity.mesosphere.io/viewLog.html?buildId=1195744&tab=buildResultsDiv&buildTypeId=DcOs_Open_Build_BuildDcOsUncached

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-4045

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS_OSS-4045

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-4045

**Pull request merged**
