### PR TITLE
DC/OS UI v1.11.0 rc.8+1.11.0 beta3

### PR DESCRIPTION
**Pull request by orlandohohmeier**
## High-level description

 This PR _back-ports_  the latest DC/OS UI fixes, improvements and features introduced with #2256 to 1.11.0 beta3 .

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

- [DCOS-20068](https://jira.mesosphere.com/browse/DCOS-20068): rename GraphQLTaskUtil to TaskMergeDataUtil
- [DCOS-18860](https://jira.mesosphere.com/browse/DCOS-18860): add region/zone DSL filters to nodes page
- [DCOS-19579](https://jira.mesosphere.com/browse/DCOS-19579): introduces the support for persistent volumes in multi container services.
- [DCOS-19139](https://jira.mesosphere.com/browse/DCOS-19139): add DSL filter in tasks table page
- [DCOS-19719](https://jira.mesosphere.com/browse/DCOS-19719): improve advanced constraints with minor UX/design changes
- [DCOS-19114](https://jira.mesosphere.com/browse/DCOS-19114): add dsl filtering for nodes by health ([DCOS-19108](https://jira.mesosphere.com/browse/DCOS-19108), [DCOS-19109](https://jira.mesosphere.com/browse/DCOS-19109), [DCOS-19111](https://jira.mesosphere.com/browse/DCOS-19111))
- [DCOS-20040](https://jira.mesosphere.com/browse/DCOS-20040): fix regression in using progress bar
- [DCOS_OSS-1965](https://jira.mesosphere.com/browse/DCOS_OSS-1965): Change DC/OS favicon to Mesosphere DC/OS favicon
- [DCOS-19946](https://jira.mesosphere.com/browse/DCOS-19946): @dcos/mesos-client bump 0.1.9
- [DCOS_OSS-2021](https://jira.mesosphere.com/browse/DCOS_OSS-2021): add flags to identify and stub Mesos requests
- [DCOS-18993](https://jira.mesosphere.com/browse/DCOS-18993): introduce new select with descriptions
- [DCOS-19882](https://jira.mesosphere.com/browse/DCOS-19882): remove escaping from constraint output

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-ui/releases/tag/v1.11.0-rc.7  https://github.com/dcos/dcos-ui/releases/tag/v1.11.0-rc.8
  - [ ] Test Results:  https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1743/testReport/
  - [ ] Code Coverage (if available): https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1743/cobertura/
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by orsenthil** [comment]
Hi @orlandohohmeier  - It might always a be good idea to raise PR against `master` or `1.11` branch and let the DC/OS team to cherry-pick (or --ff-merge) to the Branch under soak. 

Otherwise this might get missed in landing in actual 1.11 (currently master) branch and thus miss out of the next release cut.

**Comment by orsenthil** [comment]
I noticed that this is backport. I am +1 in merging this.

**Comment by orsenthil** [comment]
@orlandohohmeier  - the number of JIRAs that are addressed in this PR vs what this as the backport of ( dcos/dcos/pull/2256) is not matching and that's bit confusing.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
