### PR TITLE
Added patches.json that contains patch list for Mesos.

### PR DESCRIPTION
**Pull request by karya0**
## High-level description

A non-code update that makes it easier for tooling to find patches to apply on top of Apache Mesos.

### CODE REVIEW

**Comment by karya0** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by karya0** [comment]
@orsenthil @tillt: Can you take a quick look at this no-code-change PR? Thanks! :-)

**Comment by karya0** [comment]
@mesosphere-mergebot bump-ee

**Comment by karya0** [comment]
@orsenthil: Since there are no code changes, can we override the failure and apply ship-it label?

**Comment by karya0** [comment]
@orsenthil: Can we merge this in please? :-)

**Comment by orsenthil** [comment]
@karya0 sure!

**Pull request merged**
