### PR TITLE
Update CentOS Docker packages

### PR DESCRIPTION
**Pull request by sschneid**
Update the `docker-engine` packages pulled by CentOS to `17.05.0.ce` (latest).

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by sschneid** [comment]
Failing test (`teamcity/dcos/test/aws/cloudformation/zen/centos`) is flaky and an expected failure.

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by sschneid** [comment]
> Any reason to not go with 17.09.0-ce ?

Aye, `17.05.0` is the latest published to the official (`main`) CentOS repository (yum.dockerproject.org/repo/main/centos/7/Packages/)

**Comment by jgehrcke** [comment]
> Failing test (teamcity/dcos/test/aws/cloudformation/zen/centos) is flaky and an expected failure.

Thanks for investigating. Please link to a JIRA ticket that tracks said instability, and also add a comment to that JIRA ticket which links back to this PR, as well as to the build log. And ideally add a build log snipped to said PR.

**Comment by sschneid** [comment]
> Please link to a JIRA ticket that tracks said instability, and also add a comment to that JIRA ticket which links back to this PR, as well as to the build log. And ideally add a build log snipped to said PR.

It looks like this test (https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_IntegrationTest_AwsCloudFormationZenCentOS) doesn't _ever_ pass; I think it is shows up here b/c I accidentally triggered it while doing manual verification test runs.

**Comment by orsenthil** [comment]
@sschneid  - You could add the reason for Upgrade here: https://jira.mesosphere.com/browse/DCOS_OSS-1737

It's useful/important to have the JIRA , just in case, this needs to be tracked from JIRA or needs to be added to release notes.

**Comment by orsenthil** [comment]
@sschneid  - The AWS CloudFormation CentOS test for both Open and EE seems to have failed with this change. This needs to be investigated before this lands.

* On Open, the problem seems to be a Pkgpanda failure. It could be flaky, I am going to retrigger it.
* On EE, the failure reason is not known. It seems some process terminated as/before the tests were run. So, that needs to be retriggered and brought to green too.

**Comment by sschneid** [comment]
> The AWS CloudFormation CentOS test for both Open and EE seems to have failed with this change. This needs to be investigated before this lands.

See my [above comment](https://github.com/dcos/dcos/pull/1991#issuecomment-334805748) -- the only failing tests for both Open and EE are the "`zen/centos`" tests which are fault (have never successfuly passed) and were accidentally triggered.

**Comment by orsenthil** [comment]
@sschneid / @lingmann  - Got it.

When I looked at the test traceback, it seemed to me that it is something that could be **fixed**. I assume it should be outside the scope of this PR.

```
test_packaging.py:7 (test_pkgpanda_api)
dcos_api_session = <dcos_test_utils.dcos_api.DcosApiSession object at 0x7fba78e44ac8>

    def test_pkgpanda_api(dcos_api_session):
    
        def get_and_validate_package_ids(path, node):
            r = dcos_api_session.get(path, node=node)
            assert r.status_code == 200
            package_ids = r.json()
            assert isinstance(package_ids, list)
            for package_id in package_ids:
                r = dcos_api_session.get(path + package_id, node=node)
                assert r.status_code == 200
                name, version = package_id.split('--')
                assert r.json() == {'id': package_id, 'name': name, 'version': version}
            return package_ids
    
        active_buildinfo = dcos_api_session.get('/pkgpanda/active.buildinfo.full.json').json()
        active_buildinfo_packages = sorted(
            # Setup packages don't have a buildinfo.
            (package_name, info['package_version'] if info else None)
            for package_name, info in active_buildinfo.items()
        )
    
        def assert_packages_match_active_buildinfo(package_ids):
            packages = sorted(map(lambda id_: tuple(id_.split('--')), package_ids))
            assert len(packages) == len(active_buildinfo_packages)
            for package, buildinfo_package in zip(packages, active_buildinfo_packages):
                if buildinfo_package[1] is None:
                    # No buildinfo for this package, so we can only compare names.
                    assert package[0] == buildinfo_package[0]
                else:
                    assert package == buildinfo_package
    
        for node in dcos_api_session.masters + dcos_api_session.all_slaves:
            package_ids = get_and_validate_package_ids('pkgpanda/repository/', node)
            active_package_ids = get_and_validate_package_ids('pkgpanda/active/', node)
    
            assert set(active_package_ids) <= set(package_ids)
>           assert_packages_match_active_buildinfo(active_package_ids)

```

And another thing to note. When a failure is present in the status' checks only admins can merge it, I was trying to avoid that, and trying to get this to green, if possible.

I'll see if this error is tracked somewhere, if not, create a JIRA for it.

**Comment by orsenthil** [comment]
LGTM.

**Comment by orsenthil** [comment]
The `centos` issue is tracked here: https://jira.mesosphere.com/browse/DCOS_OSS-1746 
If we have to get this status to green, then we could disable the test and re-run those suites.

**Comment by lingmann** [comment]
Thanks for the ticket @orsenthil. No need to worry about the status check for this PR, but I'm making this ticket a high priority to investigate and get resolved, since it is a blocker for our TC job `teamcity/dcos/test/aws/cloudformation/zen/centos`

**Pull request merged**
