### PR TITLE
match provider, not platform

### PR DESCRIPTION
**Pull request by jr0d**
always set values for gen.

## High-level description

Corrects an issue causing integration tests to fail

## Corresponding DC/OS tickets (required)
DCOS-56036
  - [DCOS-56036](https://jira.mesosphere.com/browse/DCOS-DCOS-56036)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jr0d** [comment]
@mesosphere-mergebot bump-ee

**Comment by jr0d** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by timaa2k** [comment]
I assume you manually tested this with `dcos-launch` :)

**Comment by timaa2k** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS-57770

**Comment by ArmandGrillet** [comment]
@mesosphere-mergebot changelog-not-required regression on master

**Comment by ArmandGrillet** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
