### PR TITLE
[master] Mergebot Automated Train PR - 2018-Oct-09-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3558 - Add dcos-integration-test/extra/test_users.py
* #3561 - Handle exceptions during Metronome startup

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jgehrcke** [comment]
@orsenthil I always forget... are there special CI runs that need to be triggered in a train PR?

**Comment by orsenthil** [comment]
Hi @jgehrcke  - Nope. Nothing extra. If these had everything, we should move this to review, triage the CI failures and work towards merging this.

**Comment by pcrews** [comment]
@mesosphere-mergebot sync

**Comment by jgehrcke** [comment]
@alenkacz is this train still good?

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-43318

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Thank you, Senthil!

**Pull request merged**
