### PR TITLE
Set 1.11 version to 1.11.7-dev

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Set 1.11 version to 1.11.7-dev

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@orsenthil @gauripowale this PR did not treat `CHANGES.md` correctly.

@orsenthil let us please please work on a checklist which _precisely_ covers what to change when we branch and release.

**Pull request merged**
