### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Jul-17-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3091 - Marathon 1.6 Bump
* #3094 - [1.11] Increase the limit on worker_connections to 10K for Agent AR
* #3100 - dcos-check-runner: run dcos-checks-poststart.service as root 
* #3103 - Set DC/OS version to 1.11.4

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-39310

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@urbanserj  / @gpaul  / @gauripowale  / @branden  - Please review and let's merge this.

**Comment by urbanserj** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
