### PR TITLE
Train 255 (master)

### PR DESCRIPTION
**Pull request by orlandohohmeier**
## Train 255 (master)

* #2096 Rename py.test to pytest

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by jgehrcke** [comment]
The CI failure in `mergebot/enterprise/build-status/aggregate` is as of known instabilities. They are tracked in JIRA.

**Comment by jgehrcke** [comment]
Manually applying ship-it as of my previous comment.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ship It

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
> PR Status Checks are not Green. Refusing to merge.

OK, let's spend some time and money and re-run these tests until they are green (on it) :-).

**Comment by orsenthil** [comment]
> OK, let's spend some time and money and re-run these tests until they are green (on it) :-).

@jgehrcke  - Haha :) And sorry for that.
 
We will have an `override-status` command soon that could help with these scenarios.  The idea is

```
@mesosphere-mergebot override-status teamcity/dcos/test/upgrade OPEN-JIRA
```

Will override the status, so that we don't re-run them and log the information in the OPEN-JIRA. 
This will greatly benefit us with the velocity.  (Tracking JIRA: https://jira.mesosphere.com/browse/DCOS-19387)

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
