### PR TITLE
Bump Cosmos to Snapshot build 260

### PR DESCRIPTION
**Pull request by jsancio**
## High Level Description

What features does this change enable? What bugs does this change fix? High-Level description of how things changed.

## Related Issues

  - [DCOS-15938](https://jira.dcos.io/browse/DCOS-15938) Re-implement SDK uninstall so that it doesn't block
  - [DCOS-15995](https://jira.dcos.io/browse/DCOS-15995) Supported media type error for universe should include v4
  - [DCOS-16321](https://jira.mesosphere.com/browse/DCOS-16321) Compress large Envelope values.

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] [Change log](https://github.com/dcos/cosmos/compare/86957306cf29475fbc6ab665fe1d0a727d3ab241...df1223f0d00599f40412e1417589b44894779fcc)
  - [x] [Test Results](https://teamcity.mesosphere.io/viewLog.html?buildId=690446&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_PublishSnapshot)
  - [x] [Code Coverage](https://teamcity.mesosphere.io/viewLog.html?buildId=690447&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_Scoverag)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by jsancio** [comment]
@mesosphere-mergebot bump-ee

**Comment by jsancio** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jsancio** [comment]
@cruhland @larioj please review!

**Comment by jsancio** [comment]
@spahl @lingmann @orsenthil Can we merge this?

**Comment by orsenthil** [comment]
@jsancio - with two required statuses failing, this will be rejected from merging (by our status checks). 

* Two actions needs to be done. The deploy-vpc-cli failure is a flake. I will retrigger it.
* The enterprise-pr status needs to go green (if there are any EE flakes, those need to be retriggered).

**Comment by jsancio** [comment]
@orsenthil How do I rerun `enterprise-pr`?

**Comment by orsenthil** [comment]
@jsancio  from https://github.com/mesosphere/dcos-enterprise/pull/1101  - You could see if the failures there are related to your changes and act on it an appropriate way.

**Comment by jsancio** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
