### PR TITLE
Upgrade to MyPy 0.782

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

Upgrade MyPy to work with Python 3.8

## Corresponding DC/OS tickets (required)

  - [D2IQ-69787](https://jira.d2iq.com/browse/D2IQ-69787) tox fails with Python 3.8

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required test code only

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @janisz @wavesoft @jkoelker

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
