### PR TITLE
[1.10] Bump Mesos to nightly 1.4.x ee18cf9

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
## High-level description

This is a routine bump to the latest Mesos and mesos-modules.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Changelog:
    https://github.com/apache/mesos/compare/e7b117e0d9072a50756dd90e12d691af572aed7c...ee18cf95f10f790fe96a847ae4b6a80dfdc66f9d
    
    
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by gkleiman** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by gkleiman** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@gkleiman 

> @mesosphere-mergebot label ready for review

Didn't work for you because, you are not the creator of this PR and neither are you the owner.  It is mentioned in the  help text.

> PR creators can apply one of [Ready For Review |Work In Progress]. Owners can apply any label.

**Comment by gkleiman** [comment]
This bump is superseded by #3055

**Comment by sambatyon** [comment]
We should close this one then.

**Comment by gkleiman** [comment]
@orsenthil can you close it? or someone with DC/OS super powers? =)

**Pull request closed without merging**
