### PR TITLE
Train 261 base:master

### PR DESCRIPTION
**Pull request by lingmann**
## Train 261

* #2114 Admin Router: bump openresty

### CODE REVIEW

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
`TestUpgrade.test_mesos_task_state_remains_consistent` has failed in the same way on:

* `teamcity/dcos/test/upgrade`
* `teamcity/dcos/test/upgrade-from-previous-major`


Reported on https://jira.mesosphere.com/browse/DCOS-19612

**Comment by jgehrcke** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
@mesosphere-mergebot pr-status-checks

**Comment by jgehrcke** [comment]
`mergebot/enterprise/build-status/aggregate` is red although all `required` status checks on the downstream PR are green.

@orsenthil I would appreciate if you can take it from here!

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
