### PR TITLE
Update cosmos to version 0.2.1, for 1.8.9

### PR DESCRIPTION
**Pull request by cruhland**
## High Level Description

This updates cosmos to version 0.2.1, which backports the bugfix to the `/package/list` endpoint from this PR: https://github.com/dcos/cosmos/pull/563.

This should be merged at the same time as the corresponding downstream Enterprise PR: https://github.com/mesosphere/dcos-enterprise/pull/807

## Related Issues

  - [DCOS-15077](https://jira.mesosphere.com/browse/DCOS-15077) Backport handling the case when a service from a package is running but the package doesn't exist

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: this is a backported feature; the test is in mainline cosmos
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [change log with diff](https://github.com/dcos/cosmos/releases/tag/v0.2.1)
  - [X] Test Results: [here](https://teamcity.mesosphere.io/viewLog.html?buildId=618203&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_PublishRelease)
  - [ ] Code Coverage (if available):
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by cruhland** [comment]
@spahl ready for review

**Comment by cruhland** [comment]
@mesosphere-mergebot bump-ee

**Comment by cruhland** [comment]
@mesosphere-mergebot Ready For Review

**Comment by cruhland** [comment]
cc @jsancio

**Comment by cruhland** [comment]
Actual enterprise PR: https://github.com/mesosphere/dcos-enterprise/pull/807

**Comment by cruhland** [comment]
@larioj are you able to leave a review on this?

**Comment by cruhland** [comment]
@mesosphere-mergebot Ready For Review

**Comment by cruhland** [comment]
Closing and re-opening to trigger builds.

**Comment by cruhland** [comment]
Hmm, guess that doesn't work...

**Comment by cruhland** [comment]
For the "integration-test/upgrade-onprem" check, @amitaekbote realized that because this PR is for 1.8.9, one of the build parameters needed to be adjusted. So the latest run has the parameter set to a custom value: https://teamcity.mesosphere.io/viewLog.html?buildId=624842&buildTypeId=ClosedSource_Dcos_IntegrationTests_CloudIntegrationTests_DcosOssUpgradeTestOnPre&tab=buildResultsDiv

**Comment by orsenthil** [comment]
@cruhland  :-)  `@mesosphere-mergebot label` is the command, then, you could specify the desired label.

**Comment by cruhland** [comment]
@orsenthil yeah I eventually figured that out on another PR, thanks for the reminder! :smile:

**Pull request merged**
