### PR TITLE
Train 280 (master)

### PR DESCRIPTION
**Pull request by margaret**
# 🚂 :two::eight::zero::train: (master)

https://github.com/dcos/dcos/pull/2169 – **Set new --reconfiguration_policy mesos flag.**
> * This commit sets the newly added reconfiguration policy for mesos-agent to additive, in order to allow agents to add new domains without draining all tasks.
> [DCOS_OSS-1959](https://jira.mesosphere.com/browse/DCOS_OSS-1959)

https://github.com/dcos/dcos/pull/2167 – **Enabled UCR auto image gc for DC/OS.**
> * Enabled UCR auto image gc for dc/os.
> * This PR builds on top of pull/2165(DCOS_OSS-1945).
> [DCOS_OSS-1933](https://jira.mesosphere.com/browse/DCOS_OSS-1933) Enable UCR basic auto image GC for DC/OS.

https://github.com/dcos/dcos/pull/2158 – **bumping metronome to 0.3.1**
> * Upgraded to a released version of Marathon Lib v1.3.13
> * Updates to dependencies (including an Akka update to fix schedule time wrap around bug)
> * Added /info end point for metronome version information
> * PR150 Added /info endpoint
> [MARATHON_EE-1717](https://jira.mesosphere.com/browse/METRONOME-176) 60s min between
> [MARATHON_EE-1725](https://jira.mesosphere.com/browse/METRONOME-166)
> [MARATHON_EE-1726](https://jira.mesosphere.com/browse/METRONOME-167) Upgrade Marathon libraries and dependencies

https://github.com/dcos/dcos/pull/2186 – **Update owners.json with JIRA**
> This will be used with mergebot override feature.
> https://jira.mesosphere.com/browse/DCOS-19647

### CODE REVIEW

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot label ready for review

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
