### PR TITLE
bootstrap: More robust handling of a zk.pid file while waiting for exhibitor[1.9]

### PR DESCRIPTION
**Pull request by vespian**
It is a backport of https://github.com/dcos/dcos/pull/2212

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@mesosphere-mergebot label ready for review

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@gpaul can you please review?

**Pull request merged**
