### PR TITLE
(1.13) Include task metadata with task logs sent to Fluent Bit

### PR DESCRIPTION
**Pull request by branden**
## High-level description

This is a 1.13 backport of #5503. This bumps mesos-modules to include https://github.com/dcos/dcos-mesos-modules/pull/111.

## Corresponding DC/OS tickets (required)

  - [DCOS-53834](https://jira.mesosphere.com/browse/DCOS-53834) Integrate Mesos task log module fix with DC/OS

## Related tickets (optional)

N/A

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-mesos-modules/compare/2633cb7135c978f640d08819f2408c541d6dedb2...1869381f77ff89e60fba20540e7775cd8d6fdbc2
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain: Fluent Bit doesn't output logs by default, so we can't cover this with an integration test. Instead I tested manually that task logs are emitted to an Elasticsearch cluster with the correct metadata.
  - [ ] Test Results: @kaysoky @greggomann Do you know where I can find CI results for the new ref?
  - [x] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by jgehrcke** [comment]
Shouldn't this have a changelog entry under "fixed and improved"?

CC @orsenthil is it now intended that we do not have the checkbox anymore which reminds about the `CHANGES.md` modification.

**Comment by branden** [comment]
This will have a changelog entry before it's ready for review.

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by branden** [comment]
@kaysoky @greggomann This PR is ready for your review. Do you know where I can find CI results for the new ref? I usually check https://github.com/dcos/dcos-mesos-modules/commits/1.13, but the current tip of the branch doesn't have a build status yet.

**Comment by branden** [comment]
@mesosphere-mergebot request-review @kaysoky @greggomann

**Pull request merged**
