### PR TITLE
Train 201

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 201. It includes:

- #1747 (Admin Router: Remove periodic AR reloading in favour of DNS queries)
- #1784 ([DCOS_OSS-1470] Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger)
- #1811 ([next-beta] DCOS-UI: Update package for 1.10)
- #1819 (skip vagrant tests for DCOS_OSS-1532)

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
The dcos-vagrant tests will most probably be failing and will need to be muted after merging this PR:
* test_octarine
* test_service_discovery_docker_bridge
* test_service_discovery_docker_overlay
* test_service_discovery_docker_overlay_port_mapping
* test_ip_per_container

I have provided more detailed description of the problem in the description of https://github.com/dcos/dcos/pull/1747, section "Failing tests". Please check linked Jira issues for even more information.

**Comment by jgehrcke** [comment]
`smoke-test/dcos-docker` failed with `[17:29:27][Step 4/5] Makefile:121: recipe for target 'postflight' failed`, see https://teamcity.mesosphere.io/viewLog.html?buildId=733894.

**Comment by orsenthil** [comment]
I'd also request review from @karlkfi  for the request on muting the tests.  I read the JIRA (which explained about race conditions), but have not reviewed it closely. I will do it.

**Comment by orsenthil** [comment]
@karlkfi  - the failures that we are trying to mute are this: https://teamcity.mesosphere.io/viewLog.html?buildId=733402

**Comment by jgehrcke** [comment]
`smoke-test/dcos-docker` succeeded in a 2nd attempt, i.e. it is flaky. Would appreciate if someone can track that in JIRA, need to run now.

**Comment by orsenthil** [comment]
Hi @jgehrcke  / @vespian  - the `vagrant-bash`  tests is the only suite that exercises "multi-master" configuration. 

I looked at the related JIRAs, although it suggests that the failure is out of the scope of the changes being introduced,  it might be a good idea to try those "suggested" fixes alongside this PR and bring them in.

* https://jira.mesosphere.com/browse/DCOS_OSS-1523 - DC/OS Vagrant: Improve how memory resources are defined for agents
* https://jira.mesosphere.com/browse/DCOS_OSS-1524 - dcos-diagnostics --diag returns false positives during DC/OS install.

If we mute it, then this will be a contentious point when the tests are unmuted again.  The best approach will be to have a solution to those "multi-master" test failures before we introduce this change.

**Comment by mellenburg** [comment]
For the time being, another train has been started that will move forward that non-contentious PRs: https://github.com/dcos/dcos/pull/1813

**Comment by jgehrcke** [comment]
> For the time being, another train has been started that will move forward that non-contentious PRs: #1813

... and then #1813 was closed w/o leaving a corresponding comment.

**Comment by jgehrcke** [comment]
The call is to unblock this via https://jira.mesosphere.com/browse/DCOS_OSS-1531.

**Comment by adam-mesos** [comment]
Looks like https://github.com/dcos/dcos/pull/1808 was already merged (on its own?), so you may need to remove it from the train on rebase

**Comment by jgehrcke** [comment]
> Looks like #1808 was already merged (on its own?), so you may need to remove it from the train on rebase

Yeah, a small comment about that in this PR would have been good. I missed that :(. Now we really need to reassemble this train. Reflecting this with the 'work in progress' label.

**Comment by orsenthil** [comment]
This train has been updated.

This is train 201. It includes:

* #1747 (Admin Router: Remove periodic AR reloading in favour of DNS queries)
* #1784 ([DCOS_OSS-1470] Exhibitor: use PatternLayoutEscaped logger layout for structured journal logger)
* #1811 ([next-beta] DCOS-UI: Update package for 1.10)
* #1819 (skip vagrant tests for DCOS_OSS-1532)

**Comment by orsenthil** [comment]
I re-created the train and forced pushed with additional PRs, instead of closing and creating a new PR.  I wanted to keep the discussion that happened for the previous attempt.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Approved (cannot add a green checkmark, because I am the PR creator)!

**Comment by orsenthil** [comment]
> (cannot add a green checkmark, because I am the PR creator)!

I can!

**Comment by mellenburg** [comment]
Note: this is currently waiting on the downstream tests. Mergebot is reporting the aggregate as complete but it is not. Please be sure to check manually before merge

**Comment by orsenthil** [comment]
Github's delay in status forwarding. It's gone pending again.

It should have shown green briefly because for the EE train, it went completely green and then I added two more commits. :)

Status

**Comment by jgehrcke** [comment]
`mergebot/enterprise/build-status/aggregate` failed as of a known flake. I am in favor of just proceeding.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
