### PR TITLE
Update Ubuntu (Azure) Docker to `17.09.0`

### PR DESCRIPTION
**Pull request by sschneid**
Package has been renamed from `docker-engine` to `docker-ce`.

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by sschneid** [comment]
> It might be worthwhile to trigger the cd-demo on an Azure cluster as well

Done!  I manually ran `cd-demo` yesterday for both this PR and the CentOS one (#1991) -- both passed without error.

**Comment by lingmann** [comment]
`teamcity/dcos/test/aws/cloudformation/simple` failure is unrelated to this PR.

**Pull request merged**
