### PR TITLE
[DCOS-46107] Specify DC/OS and DC/OS Enterprise required branches with code in mergebot

### PR DESCRIPTION
**Pull request by AliakseiKhomchanka**
An update for the incoming mergebot feature that automatically updates branch protection based on repo config files.

### CODE REVIEW

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
The list is already sorted. Please ignore my comment.

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot bump-ee

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
