### PR TITLE
This is the fix for DCOS-196

### PR DESCRIPTION
**Pull request by feniix**
Verify if version is < 1.10 and if > remove force flag from `docker tag`

### CODE REVIEW

**Comment by cmaloney** [comment]
So unfortunately our CI is running Docker 1.9 currently, where the `-f` is required for correct operation. You can see that in the failed build job: 
https://teamcity.mesosphere.io/viewLog.html?buildId=314954&buildTypeId=DcosIo_Dcos_BuildPr&tab=buildLog#_focus=314

`[12:10:10]Error response from daemon: Conflict: Tag dcos-builder:latest is already set to image 73b194808209, if you want to replace it, please use -f option`

I'm working on updating the CI boxes to Docker 1.11 + Ubuntu 16.04 currently, although not sure when that will get done (landing stuff for the next release is higher priority currently, and keep hitting random brokenness with the new AMIs). 

So that leaves two options. Either have the code do a switch based on docker version, or wait for me to finish updating the CI. Which would you like to do? (Open to other suggestions as well).

**Comment by feniix** [comment]
I would not mind doing a version based switch

**Comment by feniix** [comment]
@cmaloney See now

**Comment by feniix** [comment]
@cmaloney Can you help me figure out which code quality changes do I need to make? if I look at details it asks me for a login

**Comment by cmaloney** [comment]
@feniix You can click the "login as guest" button, or there is also a button to make an account.

That "Code Quality" check is running `tox`. The particular test that failed is part of `tox -e py34-syntax` (Running our syntax checks). In particular, include sorting:

```
[12:48:19]ERROR: /teamcity/work/19ad0dff41587ee6/release/__init__.py Imports are incorrectly sorted.
[12:48:19]--- /teamcity/work/19ad0dff41587ee6/release/__init__.py:before  2016-06-24 19:47:14.142935
[12:48:19]+++ /teamcity/work/19ad0dff41587ee6/release/__init__.py:after 2016-06-24 19:48:19.402630
[12:48:19]@@ -9,13 +9,13 @@
[12:48:19] 
[12:48:19] import argparse
[12:48:19] import copy
[12:48:19]-from distutils.version import LooseVersion
[12:48:19] import importlib
[12:48:19] import inspect
[12:48:19] import json
[12:48:19] import os.path
[12:48:19] import subprocess
[12:48:19] import sys
[12:48:19]+from distutils.version import LooseVersion
[12:48:19] 
[12:48:19] import pkg_resources
[12:48:19] import yaml
[12:48:19]@@ -25,6 +25,7 @@
[12:48:19] import pkgpanda.build
[12:48:19] import pkgpanda.util
[12:48:19] import release.storage
[12:48:19]+
[12:48:19] provider_names = ['aws', 'azure', 'bash']
```

https://teamcity.mesosphere.io/viewLog.html?buildId=314990&buildTypeId=DcosIo_Dcos_CodeQuality&tab=buildLog#_focus=762

**Comment by feniix** [comment]
@cmaloney can you help me interpret the last failing issue? It looks like it is not relevant to my change, but I might be wrong

**Comment by cmaloney** [comment]
Yep, that was a flaky test

**Comment by cmaloney** [comment]
Looks good, :ship: . I'll pull it into the next merge train

**Comment by feniix** [comment]
Awesome! thanks

**Pull request merged**
