### PR TITLE
Teach release to build all dockers in the `pkgpanda/docker` folder

### PR DESCRIPTION
**Pull request by cmaloney**
Ideally all this logic should live inside pkgpanda (and the dockers should be lazily built / pulled as needed). This is an MVP so we don't have to maintain more dockers out of band.

cc: @vespian

### CODE REVIEW

**Comment by lingmann** [comment]
Nice... 👍

**Comment by cmaloney** [comment]
🚢

**Comment by vespian** [comment]
@cmaloney Do you think we could use Dockerfiles from package repos referenced in buildinfo.json instead of keeping a copy in dcos repo ?

This way I would have a way to keep dependencies close to source and use the same Dockerfile for building using my laptop as well as pkgpanda - no need for copypasting/keeping in sync these files.

**Comment by cmaloney** [comment]
I think that would take a lot of work to implement currently. Makes the ordering of steps in doing things _much_ more complicated.

Currently all the dockers are built before we ever look at any packages / what might use them.

**Pull request merged**
