### PR TITLE
[1.12] Bump dcos-net

### PR DESCRIPTION
**Pull request by urbanserj**
## High-level description

Bump dcos-net

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4514](https://jira.mesosphere.com/browse/DCOS_OSS-4514) Expose Public IP
  - [DCOS_OSS-4666](https://jira.mesosphere.com/browse/DCOS_OSS-4666) Add thisnode.thisdcos.directory dns zone
  - [DCOS-46989](https://jira.mesosphere.com/browse/DCOS-46989) Backport DC/OS Net API to Easily obtain Public Service IP Address

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: none
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]
https://github.com/dcos/dcos-net/compare/e3d9a062788e9d5a89e7e4ef1937e35015498f8a...6866d1e5665496a912ff24c7d6dc8e2c131ff80b
https://github.com/dcos/dcos-net/pull/112
https://circleci.com/gh/dcos/dcos-net/803
https://codecov.io/github/dcos/dcos-net/commit/6866d1e5665496a912ff24c7d6dc8e2c131ff80b

___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by pcrews** [comment]
Hello, I believe you will need to fix the conflicts in CHANGES.md before this can proceed.

**Comment by orsenthil** [comment]
Hi @urbanserj  - please fix the conflict and feel free to merge it directly (if no trains are in progress).

**Comment by urbanserj** [comment]
Hey @orsenthil @pcrews,

I believe something is wrong with our process here. This PR has a conflict in `CHANGES.md`. If you force us to add release notes, we basically can't create PRs in the same day or every ~4 hours with the new train process. Each rebase involves at least three people (author + 2 reviewers + sometimes dcos-owner for overrides) and usually takes several hours. I also don't understand why now it's my problem to resolve such conflicts in the release notes, why my PR should be moved to "work in progress" because of it. If the new process doesn't work correctly in some edge cases it's your responsibility to fix the process and merge PRs manually while we have such issues.

To resolve the issue with conflicts in `CHANGES.md`, I would recommend to change merge strategy  from default to `union`. Please see how it was done in marathon repo using [.gitattributes](https://github.com/mesosphere/marathon/blob/master/.gitattributes).

To have more real and correct metrics about the new process, I'll set "Ready for review" label back.

Happy to discuss more.

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orsenthil** [comment]
Hi @urbanserj  - I understand your point. Happy to discuss more too. The process is evolving and if everyone followed the recommend format here - (https://github.com/dcos/dcos/blob/1.11/CHANGES.md) which needs to be placed in all the branches, then there would have been no conflicts. But we have a conflict now, that either needs to be resolved you or by me (so that we don't block others).
I think, it would have been helpful, you had merged and added the comment that you shared.

**Comment by orsenthil** [comment]
Also - to note - https://github.com/mesosphere/marathon/blob/master/.gitattributes is a good idea.  We can attempt that too.

**Pull request merged**
