### PR TITLE
Copy special files into position

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

The pkgpanda file format specifies that the contents of the `bin`, `etc`, `include`, and `lib` directories at the top of the unpacked package should be copied into the root-level equivalents.

This PR makes winpanda follow that convention. On Linux pkgpanda uses soft links for the "copy". Here, we use hard links on Windows. This restricts the code to working where the unpacked package and the installation directory are on the same disk. Although winpanda allows these to be placed on different disks, the DC/OS configuration settings ensure that they are in the same directory.

This PR also adds testing of winpanda code, with a simple test of the introduced `transfer_files` function.

## Corresponding DC/OS tickets (required)

  - [https://jira.mesosphere.com/browse/DCOS_OSS-5761](https://jira.mesosphere.com/browse/DCOS_OSS-5761) Copy special directories into location

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required change to unreleased code

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @DominikDary @anatolii-borysov @alekspv

**Comment by jongiddy** [comment]
@DominikDary please override failure with
```
@mesosphere-mergebot override-status teamcity/dcos/build/dcosWindows https://jira.mesosphere.com/browse/DCOS_OSS-5766
```
and I will re-run

**Comment by DominikDary** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcosWindows https://jira.mesosphere.com/browse/DCOS_OSS-5766

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jongiddy** [comment]
@mesosphere-mergebot sync

**Comment by jongiddy** [comment]
@mesosphere-mergebot sync

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ship It

**Comment by jongiddy** [comment]
Manually put this PR in Ship It since the Enterprise `aggregate` test does not change to OK despite the Enterprise PR being in Ship It.

**Pull request merged**
