### PR TITLE
Reset Docker unit before restarting it

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

On some OS versions, following a reboot, the Docker unit will fail before bootstrap creates the certificates used by the libnetwork plugin for Calico. Reset the Start Limit counters before attempting to restart it.

Manually tested that this fixes the problem. Extract from Docker journal after a reboot:
```
Sep 30 12:00:21 ip-172-16-0-49.ec2.internal systemd[1]: Failed to start Docker Application Container Engine.
Sep 30 12:00:21 ip-172-16-0-49.ec2.internal systemd[1]: Unit docker.service entered failed state.
Sep 30 12:00:21 ip-172-16-0-49.ec2.internal systemd[1]: docker.service failed.
Sep 30 12:00:24 ip-172-16-0-49.ec2.internal systemd[1]: docker.service holdoff time over, scheduling restart.
Sep 30 12:00:24 ip-172-16-0-49.ec2.internal systemd[1]: start request repeated too quickly for docker.service
Sep 30 12:00:24 ip-172-16-0-49.ec2.internal systemd[1]: Failed to start Docker Application Container Engine.
Sep 30 12:00:24 ip-172-16-0-49.ec2.internal systemd[1]: Unit docker.service entered failed state.
Sep 30 12:00:24 ip-172-16-0-49.ec2.internal systemd[1]: docker.service failed.
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal systemd[1]: Starting Docker Application Container Engine...
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal dockerd[4082]: time="2020-09-30T12:02:48.981571288Z" level=info msg="parsed scheme: \"unix\"" module=grpc
```
Note that at 12:00:24 Docker reaches restart limit and goes into failed state: "start request repeated too quickly for docker.service" from which it will not restart without intervention. It then does start at 12:02:48, due to failure being reset in Calico script:
```
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal create-calico-docker-network.py[4063]: etcd secure mode is enabled
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal create-calico-docker-network.py[4063]: Writing updated Docker daemon configuration to '/etc/docker/daemon.json'
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal create-calico-docker-network.py[4063]: Executing: systemctl stop docker
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal create-calico-docker-network.py[4063]: Unable to reload daemon, going to restart it instead
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal create-calico-docker-network.py[4063]: Executing: systemctl reset-failed docker.service
Sep 30 12:02:48 ip-172-16-0-49.ec2.internal create-calico-docker-network.py[4063]: Executing: systemctl start docker
```

## Corresponding DC/OS tickets (required)

  - [D2IQ-72103](https://jira.d2iq.com/browse/D2IQ-72103) Reset Docker if it fails due to Calcio certs
  - [COPS-6534](https://jira.d2iq.com/browse/COPS-6534) RootCA bundle is not written soon enough for Docker to find it before it exhausts startup limits on a reboot

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @jkoelker

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required will be back-ported

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @janisz

**Review by janisz — APPROVED** [review]

**Comment by jongiddy** [comment]
@mesosphere-mergebot backport 2.1

**Pull request merged**
