### PR TITLE
Update link to JIRA

### PR DESCRIPTION
**Pull request by joel-hamill**
## High Level Description

The current link to JIRA is incorrect. This fixes it.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
Ignoring CI failures for this trivial change.

**Comment by jgehrcke** [comment]
Thank you, Joel!

**Pull request merged**
