### PR TITLE
Bumped mesos to latest sha 63e0814.

### PR DESCRIPTION
**Pull request by vinodkone**
## High Level Description

This includes potential fix v1 HTTP adapter duplicate subscription
issue https://issues.apache.org/jira/browse/MESOS-7728.

## Related Issues

  - [CORE-1116](https://jira.mesosphere.com/browse/CORE-1116) An extra Elastic framework appeared during Mesos Master failover in Soak

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by vinodkone** [comment]
@asridharan and @bmahler can you guys review this PR?

**Comment by bmahler** [comment]
@vinodkone the squashed UI cherry pick looks good, shouldn't this update the SHAs in `packages/mesos/README.md`?

**Comment by vinodkone** [comment]
@bmahler updated the UI sha in README.md. PTAL. cc @asridharan

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@vinodkone  ^ Please note the msg above.  Updating this branch and running bump-ee will trigger the EE tests. Is there a corresponding EE PR for this change?

**Comment by vinodkone** [comment]
@mesosphere-mergebot bump-ee

**Comment by asridharan** [comment]
LGTM !!

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by falseperfection** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by falseperfection** [comment]
Enterprise tests are failing, but the failing tests don't seem to be flaking on master.

**Comment by orsenthil** [comment]
This PR will be dropped against this: https://github.com/dcos/dcos/pull/1711

**Comment by orsenthil** [comment]
https://github.com/dcos/dcos/pull/1711 carries the change that was originally submitted by this PR. So, we can close this one.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label Request For Comment

(Removing this ship-it).

**Comment by jgehrcke** [comment]
> #1711 carries the change that was originally submitted by this PR. So, we can close this one.

Closing as of this.

**Pull request closed without merging**
