### PR TITLE
bumping master to marathon 1.7

### PR DESCRIPTION
**Pull request by kensipe**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-39903](https://jira.mesosphere.com/browse/DCOS-39903) Bump Marathon 1.7 on DCOS 1.12

## Related tickets (optional)

Other tickets related to this change:

  - [MARATHON-8017](https://jira.mesosphere.com/browse/MARATHON-8017) Treat Non-absolute paths to /v2/groups as children.

  - [MARATHON-8305](https://jira.mesosphere.com/browse/MARATHON-8305)  Fix leadership transition race condition.
  - [MARATHON-8272](https://jira.mesosphere.com/browse/MARATHON-8272) Remove unreachable resident task terminal status.
  - [MARATHON-8311](https://jira.mesosphere.com/browse/MARATHON-8311) Added suppression operation metric .
  - [MARATHON-8310](https://jira.mesosphere.com/browse/MARATHON-8310) Ignore environment variables starting with `MARATHON_APP_`.
  - [MARATHON-8304](https://jira.mesosphere.com/browse/MARATHON-8304) Activate HeartbeatMonitor before Marathon is connected to Mesos.
  - [MARATHON-8282](https://jira.mesosphere.com/browse/MARATHON-8282) Log incoming offers at INFO level.
  - [MARATHON-8246](https://jira.mesosphere.com/browse/MARATHON-8246), [MARATHON-8247](https://jira.mesosphere.com/browse/MARATHON-8247), [MARATHON-8248](https://jira.mesosphere.com/browse/MARATHON-8248) Orchestrator logic updated to have instance goals .
  - [PR-6366](https://github.com/mesosphere/marathon/pull/6366) Fixed N^2 parallelism for persistence.
  - [PR-6226](https://github.com/mesosphere/marathon/pull/6226) Group versions cache size config validation.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [diff](https://github.com/mesosphere/marathon/compare/v1.6.535...master)
  - [x] Test Results: [ci](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/952/)
  - [x] Code Coverage (if available):  N/A

### CODE REVIEW

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
@mesosphere-mergebot Label Ready For Review

**Comment by orsenthil** [comment]
@kensipe  - metronome failure - https://teamcity.mesosphere.io/viewLog.html?buildId=1147901&buildTypeId=DcOs_Open_Test_IntegrationTest_AwsCloudFormationSimple

**Comment by kensipe** [comment]
@orsenthil there is still a bug in the master branch for metronome which was merged in... it has nothing to do with this PR.   This PR is marathon only and it is correct.

**Comment by kensipe** [comment]
@orsenthil the bump of timeouts on #3166 should have fixed this... I'll rebase... but there isn't anything wrong with this PR

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Pull request closed without merging**
