### PR TITLE
Update buildinfo.json

### PR DESCRIPTION
**Pull request by kvish**
https://jira.mesosphere.com/browse/DCOS-41149
https://jira.mesosphere.com/browse/DCOS-39579

### CODE REVIEW

**Comment by kvish** [comment]
master PR: https://github.com/dcos/dcos/pull/3397

**Comment by kvish** [comment]
@mesosphere-mergebot bump-ee

**Comment by kvish** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by kvish** [comment]
backport change to pass origin info onto custom manager for k8s soak

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
