### PR TITLE
[1.12] Mergebot Automated Train PR - 2018-Oct-02-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3505 - bump mesos-dns to bring in changes for mesos state endpoint
* #3519 - chore(dcos-ui): bump DC/OS UI v2.24.4

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcos/windows 
 https://jira.mesosphere.com/browse/DCOS-42046

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41677

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
