### PR TITLE
Set Cache-Control header for Windows artifacts.

### PR DESCRIPTION
**Pull request by orsenthil**
Attempts to solve - https://jira.d2iq.com/browse/D2IQ-65806 ( Windows Enteprise installer does not get updated after first commit)

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot request-review  @jongiddy

**Comment by DominikDary** [comment]
@mesosphere-mergebot changelog-not-required internal change

**Comment by orsenthil** [comment]
@mesosphere-mergebot backport  2.0

**Pull request merged**
