### PR TITLE
[DCOS 2.0] Use correct start arguments for cockroachdb 2.1 

### PR DESCRIPTION
**Pull request by jr0d**
## High-level description

Fixes an issuer where cockroachdb would advertise the node hostname

## Corresponding DC/OS tickets (required)

  - [DCOS-59735](https://jira.mesosphere.com/browse/DCOS-59735) CockroachDB uses DNS names for inter-node comms, instead of IP addresses (breaks cert verification, breaks cluster)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jongiddy** [comment]
Can you please change the PR title to say 2.0

**Comment by jr0d** [comment]
@mesosphere-mergebot request-review @jongiddy @timaa2k

**Comment by jr0d** [comment]
@mesosphere-mergebot changelog-not-required

**Comment by jongiddy** [comment]
change log not required - covered by existing changelog message indicating that CockroachDB has been updated to 2.1

**Comment by jgehrcke** [comment]
> @mesosphere-mergebot changelog-not-required

@jr0d you have found a bug here.  A reason must be provided, mergebot should reject this. CC @orsenthil  @AliakseiKhomchanka .

**Comment by jgehrcke** [comment]
> change log not required - covered by existing changelog message indicating that CockroachDB has been updated to 2.1

Right, and I want to add: the but that we have found here is not in a _released_ version

**Comment by AliakseiKhomchanka** [comment]
Note that mergebot commands must start with @mesosphere-mergebot

**Comment by jongiddy** [comment]
@AliakseiKhomchanka The comment from @jgehrcke refers to the override in https://github.com/dcos/dcos/pull/6372#issuecomment-540197009 where the comment `@mesosphere-mergebot changelog-not-required` with no reason was accepted by mergebot.

**Pull request merged**
