### PR TITLE
Update version to 1.12.0

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Update DC/OS version to 1.12.0

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
