### PR TITLE
Adding required ending forwardslash to download_url

### PR DESCRIPTION
**Pull request by cgawron1**
Due to parsing issue with build_teamcity_windows.ps1 on the Windows build TC job. This file needs to have a / at the end of the url for the script to validate the download_url successfully.

## High-level description
Fixing dcos-release-windows.config.yaml file to update the download_url to end with a /

___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by cgawron1** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-40611

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Pull request merged**
