### PR TITLE
Increase XHR timeouts in DCOS Installer UI

### PR DESCRIPTION
**Pull request by jfurrow**

### CODE REVIEW

**Comment by karlkfi** [comment]
@jfurrow: I verified that this timeout change fixes the pre-flight stage on dcos-vagrant, but this release build fails post-flight regularly on gui and manual mode. Can you rebase against master?

**Comment by jfurrow** [comment]
@karlkfi Rebased

**Comment by karlkfi** [comment]
well... that made things worse... now preflight doesn't pass...

**Comment by jfurrow** [comment]
@karlkfi Is it failing when using the UI installer exclusively, or failing for the command-line installer as well?

**Comment by karlkfi** [comment]
The first build failed for both gui and manual postflight. This new build I only tested gui and it failed preflight. I can try manual tomorrow.

**Comment by karlkfi** [comment]
gui install works on dcos-vagrant using this latest rebase build! ready to merge

**Comment by jfurrow** [comment]
Awesome! Thanks, Karl!

**Comment by karlkfi** [comment]
@cmaloney @malnick This is ready for merge.

**Comment by cmaloney** [comment]
:ship:

**Pull request merged**
