### PR TITLE
Make Mesos Agent waits for Telegraf

### PR DESCRIPTION
**Pull request by janisz**
Mesos Agent tasks requires telegraf so Mesos should wait for telegraf
socket to appear.

Refs:  https://github.com/dcos/dcos/pull/7473#discussion_r468721781
Fixes: https://jira.d2iq.com/browse/COPS-6355

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [D2IQ-ID](https://jira.d2iq.com/browse/D2IQ-ID) JIRA title / short description.

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot test

**Comment by janisz** [comment]
@mesosphere-mergebot test

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @jongiddy @pierrebeitz  @DominikDary

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required internal

**Review by jkoelker — APPROVED** [review]
Our systemd setup is :-1: ;)

**Comment by janisz** [comment]
@mesosphere-mergebot backport 2.1 2.0 1.13

**Pull request merged**
