### PR TITLE
Train 150

### PR DESCRIPTION
**Pull request by falseperfection**
## High Level Description

https://github.com/dcos/dcos/pull/1404 - Admin Router: Deduplication of auth-related code
~~https://github.com/dcos/dcos/pull/1420 - Add AWS bare cluster template~~ **test fail**

### CODE REVIEW

**Comment by falseperfection** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
The test failure is real.

```
test setup failed
boto_wrapper = <test_util.aws.BotoWrapper object at 0x7fc0c8231a20>

    @pytest.fixture(scope='session')
    def dcos_stack(boto_wrapper):
        """ Works with either Zen or Simple cloud formations
        """
        stack = test_util.aws.fetch_stack(os.environ['AWS_STACK_NAME'], boto_wrapper)
>       if isinstance(stack, test_util.aws.VpcCfStack):
E       AttributeError: module 'test_util.aws' has no attribute 'VpcCfStack'

resiliency/test_aws_cf.py:39: AttributeError
------- Stderr: -------
[2017-04-04 20:52:49,809] INFO: Calling paginated cloudformation:list_stack_resources with {'StackName': 'dcos-ci-test-cf-8GPNFI95W9'}
```

**Comment by falseperfection** [comment]
@mesosphere-mergebot bump-ee

**Comment by lingmann** [comment]
@falseperfection's first train... whooooo! :)

**Pull request merged**
