### PR TITLE
Update AWS templates to CoreOS Stable 1068.9.0

### PR DESCRIPTION
**Pull request by lingmann**
CoreOS 1068.9.0 includes:
* kernel: 4.6.3
* rkt: 1.7.0
* docker: 1.10.3
* etcd: 0.4.9, 2.3.2
* fleet: 0.11.7
* systemd: 229

See: https://coreos.com/releases/#1068.9.0 for full release notes.

### CODE REVIEW

**Comment by cmaloney** [comment]
We'll want to launch a number of clusters with this. 

Reported in DC/OS community slack:
```
kenan.fammiles: seems like the stable coreos isn’t an option, systemd is pretty broken
```
https://dcos-community.slack.com/archives/general/p1469196335002838

**Comment by KenanSulayman** [comment]
Hey, sorry. I didn't get to this more in depth, yet. I'll configure a new launch config later today and will update this comment.

**Comment by lingmann** [comment]
Attempted to launch an AWS cluster with 50 agents and had 33 of the agents fail to provision due to:
```
● dcos-download.service - Pkgpanda: Download DC/OS to this host.
   Loaded: loaded (/etc/systemd/system/dcos-download.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2016-07-26 19:23:03 UTC; 2h 1min ago
  Process: 1176 ExecStartPre=/usr/bin/curl -fLsSv --retry 20 -Y 100000 -y 60 -o /tmp/bootstrap.tar.xz https://downloads.dcos.io/dcos/testing/bootstrap/${BOOTSTRAP_ID}.bootstrap.tar.xz (code=exited, status=56)

Jul 26 19:18:47 ip-10-0-3-18.us-west-2.compute.internal curl[1176]: <
Jul 26 19:18:47 ip-10-0-3-18.us-west-2.compute.internal curl[1176]: { [5 bytes data]
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal curl[1176]: * SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal curl[1176]: * Closing connection 0
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal curl[1176]: } [5 bytes data]
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal curl[1176]: curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal systemd[1]: dcos-download.service: Control process exited, code=exited status=56
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal systemd[1]: Failed to start Pkgpanda: Download DC/OS to this host..
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal systemd[1]: dcos-download.service: Unit entered failed state.
Jul 26 19:23:03 ip-10-0-3-18.us-west-2.compute.internal systemd[1]: dcos-download.service: Failed with result 'exit-code'.
```

Need to investigate further before this PR can land.

**Comment by lingmann** [comment]
Could not reproduce on dcos/dcos master build (CoreOS Beta 1068.3.0) with a 1 master + 12 agents cluster...

**Comment by cmaloney** [comment]
Maybe there's something in the SSL negotiation which changed?

There isn't anything really obvious that changed... The things whch are even tangnetially related are:
 - libpcre update
 - systemd escaping fix (https://github.com/coreos/bugs/issues/1459). But we don't use that
 - bash update (and unicode changes)
 - Newer coreos metadata that includes AWS instance id
 - systemd transient unit fix (https://bugzilla.redhat.com/show_bug.cgi?id=1350909#c3) although that shouldn't come into play here.

**Comment by spahl** [comment]
@lingmann let us know if you are good shipping this please

**Comment by spahl** [comment]
Ok this is not gonna make the first EA. Looks like it's still causing problems.

**Comment by lingmann** [comment]
On a hunch I tried launching this template again with the following cluster configs:
* 1m x 15a
* 1m x 50a

And I could not reproduce... so I am now thinking this is an issue with cloudfront artifacts not fully available after a fresh build. To test my theory, I'm going to refresh this branch against master and then launch a 50x agent cluster to see if I can repro.

**Comment by lingmann** [comment]
Launched a 1m x 50a cluster on a new build... on this test 48/50 agents started successfully, and 2 had systemd related failures. On login to the failed agents we see:
```
CoreOS stable (1068.8.0)
Last login: Sat Jul 30 00:30:48 2016 from 10.0.6.94
Failed to retrieve unit: Activation of org.freedesktop.systemd1 timed out
Update Strategy: No Reboots
Failed to list units: Connection timed out
```

The boot logs contained:
```
Jul 29 23:17:22 localhost systemd[1]: Started D-Bus System Message Bus.
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'org.freedesktop.locale1': Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'org.freedesktop.timedate1': Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'org.freedesktop.login1': Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'org.freedesktop.machine1': Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'org.freedesktop.import1': Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'org.freedesktop.hostname1': Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to NameOwnerChanged signal for 'com.coreos.update1': Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to subscribe to activation signal: Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to register name: Connection timed out
Jul 29 23:17:47 localhost systemd[1]: Failed to set up API bus: Connection timed out
```

and

```
Jul 29 23:17:50 localhost systemd[1]: Looping too fast. Throttling execution a little.
Jul 29 23:17:51 localhost systemd[1]: Looping too fast. Throttling execution a little.
Jul 29 23:17:52 localhost systemd[1]: Looping too fast. Throttling execution a little.
Jul 29 23:17:53 localhost systemd[1]: Looping too fast. Throttling execution a little.
Jul 29 23:17:54 localhost systemd[1]: systemd-logind.service: Main process exited, code=exited, status=1/FAILURE
Jul 29 23:18:33 localhost systemd[1]: Failed to start Login Service.
Jul 29 23:18:33 localhost systemd[1]: systemd-logind.service: Unit entered failed state.
Jul 29 23:18:33 localhost systemd[1]: systemd-logind.service: Failed with result 'exit-code'.
Jul 29 23:18:33 localhost systemd[1]: system-cloudinit@usr-share-oem-cloud\x2dconfig.yml.service: Main process exited, code=exited, status=1/FAILURE
Jul 29 23:18:33 localhost systemd[1]: Failed to start Load cloud-config from /usr/share/oem/cloud-config.yml.
Jul 29 23:18:33 localhost systemd[1]: Dependency failed for Load system-provided cloud configs.
Jul 29 23:18:33 localhost systemd[1]: Dependency failed for Load user-provided cloud configs.
Jul 29 23:18:33 localhost systemd[1]: user-config.target: Job user-config.target/start failed with result 'dependency'.
Jul 29 23:18:33 localhost systemd[1]: system-config.target: Job system-config.target/start failed with result 'dependency'.
Jul 29 23:18:33 localhost systemd[1]: system-cloudinit@usr-share-oem-cloud\x2dconfig.yml.service: Unit entered failed state.
Jul 29 23:18:33 localhost systemd[1]: system-cloudinit@usr-share-oem-cloud\x2dconfig.yml.service: Failed with result 'exit-code'.
```

I did not launch this build immediately after uploading the artifacts to s3, so this was not quite the test I wanted to run. But still these results are not encouraging for CoreOS stable build...

**Comment by KenanSulayman** [comment]
retest this please

**Comment by lingmann** [comment]
Updated PR to use CoreOS 1068.9.0, which looks like a minor update to address curl security issues. Suspect we will still see the same failures around D-Bus System Message Bus...

**Comment by lingmann** [comment]
Ok this is promising... launched a 1Mx61A cluster right after the build completed. All 61 of the agents launched successfully (although a bit slowly... which is good, because this means cloudfront is still distributing bits and we did not hit the curl issue that I saw on my first test).

Thoughts on next steps from a testing perspective @spahl and @cmaloney ?

**Comment by lingmann** [comment]
Launched a 1Mx101A cluster and a 3Mx2A cluster with 100% success rate... I'm a :shipit:  @cmaloney and @spahl

**Comment by cmaloney** [comment]
🚢

**Comment by KenanSulayman** [comment]
@lingmann what changed that it works now?

**Comment by cmaloney** [comment]
As far as we can tell, they updated curl and magically a couple other things got better.

**Comment by lingmann** [comment]
@KenanSulayman we haven't been able to reproduce the d-bus issue with this build of CoreOS and large deploys, so that failure mode I saw doesn't have much concern at this point (could have been a temporary AWS issue).

**Pull request merged**
