### PR TITLE
Train 229

### PR DESCRIPTION
**Pull request by colin-msphere**
Included PRs:

#1857 - prefer system libraries for exec'd
#1858 - add tests for dcos-l4lb CNI plugins

### CODE REVIEW

**Comment by colin-msphere** [comment]
@mesosphere-mergebot bump-ee

**Comment by colin-msphere** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by lingmann** [comment]
Cool! First train with mergebot end-to-end status checks + ship-it. :)

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
