### PR TITLE
chore(dcos-ui): update package

### PR DESCRIPTION
**Pull request by bstavroulakis**
## High-level description

Update the DC/OS UI package to include the latest fixes and improvements.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

- [DCOS-19720](https://jira.mesosphere.com/browse/DCOS-19720): adjust hasHealthChecks condition
- [DCOS-19869](https://jira.mesosphere.com/browse/DCOS-19869): fix duplicate local string in region/ zone column
- [DCOS-19828](https://jira.mesosphere.com/browse/DCOS-19828): correct FRAMEWORK_REMOVED message format
- [DCOS-19747](https://jira.mesosphere.com/browse/DCOS-19747): add tooltip to serviceStatusIcon
- [DCOS-12802](https://jira.mesosphere.com/browse/DCOS-12802): introduce Jenkinsfile
- [DCOS-19771](https://jira.mesosphere.com/browse/DCOS-19771): avoid framework regex errors

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [v1.11.0-rc.5](https://github.com/dcos/dcos-ui/releases/tag/v1.11.0-rc.5)
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1568/testReport/
  - [x] Code Coverage (if available): https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1568/cobertura/
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by bstavroulakis** [comment]
@mesosphere-mergebot bump-ee

**Comment by MatApple** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker https://jira.mesosphere.com/browse/DCOS-19542

**Comment by jgehrcke** [comment]
@mesosphere-mergebot pr-status-checks

**Pull request merged**
