### PR TITLE
Update version to 1.10.4

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Update DCOS version to version 1.10.4

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
One CI run failed with `Execution timeout` as if infra flakiness, rerunning.

**Comment by mesosphere-teamcity** [comment]
Corresponding DC/OS PR: https://github.com/dcos/dcos/pull/2439

**Pull request merged**
