### PR TITLE
[1.10] Mergebot Automated Train PR - 2018-May-03-04-37

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2822 - Add checks for ftype=1 for docker and mesos directories if using XFS
* #2825 - Metronome 0.4.2 Bump for DCOS 1.10.next
* #2838 - Update 1.10.7
* https://github.com/dcos/dcos/pull/2791 - [1.10] Bump Mesos to nightly 1.4.x 315d047

### CODE REVIEW

**Comment by mesosphere-mergebot2** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot merge-it  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Ship It |Work In Progress |Ready For Review |Request For Comment |Holding] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
