### PR TITLE
merges minuteman code to navstar as navstar_l4lb

### PR DESCRIPTION
**Pull request by GoelDeepak**
## High Level Description

Fixes two issues
1. merges the minuteman code to navstar as navstar_l4lb
2. fixes iptables which were mangled by docker 1.12+

## Related Issues

  - [DCOS_OSS-902](https://jira.mesosphere.com/browse/DCOS_OSS-902) move minuteman code to navstar
 - [DCOS_OSS-980](https://jira.mesosphere.com/browse/DCOS_OSS-980) docker 1.12+ breaks virtual network

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]

https://github.com/dcos/navstar/pull/64
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot label ready for review

**Comment by lingmann** [comment]
Hi @GoelDeepak can you please ping two people who would be good candidates to review this change?

**Comment by GoelDeepak** [comment]
@lingmann could you please add @drewkerrigan and @nlsun

**Comment by lingmann** [comment]
@GoelDeepak pinging them in the comments (like you did) is the best way to request a review right now. :) Thanks!

**Comment by lingmann** [comment]
Just to be explicit, @drewkerrigan and @nlsun could you please review? Thanks!

**Comment by mellenburg** [comment]
Is there a reason this hasnt shipped yet? If not, I will tag it to go once the tests are green

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
Flip-flopped on merging this in because there was a single failed case of test_vip in strict mode test for the EE bump. However, upon looking at the test history, it seems that this test is known to consistently fail a case, so I'm reasonably certain this PR is still a net benefit and that flake-out is unrelated

**Comment by mellenburg** [comment]
All tests did pass for EE-strict. So that last failure was a flake-out. :ship:

**Pull request merged**
