### PR TITLE
[master] Mergebot Automated Train PR - 2018-Jan-22-16-43

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2335 - Bump dcos-signal sha
* #2341 - Revert "Copy systemd unit files instead of symlinking"
* #2342 - Replace deprecated m3 instance types with m4 in cloud templates

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
`teamcity/dcos/test/azure/arm` - needs to be overridden with https://jira.mesosphere.com/browse/DCOS-19542

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-19542

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
