### PR TITLE
Train 197

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 197, and it is comprised of these two pull requests:
- #1759 Latest DCOS-UI for 1.10
- #1775 dcos version = 1.10-beta2

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
`smoke-test/dcos-docker` failure reported in https://jira.mesosphere.com/browse/DCOS_OSS-1481.

**Comment by colin-msphere** [comment]
`integration-test/upgrade-onprem` failure reported in https://jira.mesosphere.com/browse/DCOS_OSS-1485

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
