### PR TITLE
Train 154

### PR DESCRIPTION
**Pull request by BenWhitehead**
## Included changes
* https://github.com/dcos/dcos/pull/1139
* https://github.com/dcos/dcos/pull/1310
* https://github.com/dcos/dcos/pull/1411
* https://github.com/dcos/dcos/pull/1422
* https://github.com/dcos/dcos/pull/1447

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label let's ship-it today.

**Comment by lingmann** [comment]
@BenWhitehead @mellenburg worthwhile for me to wait for these Azure tests to pass? Seems like they have not gone green yet with past attempts on this branch.

**Comment by mellenburg** [comment]
I think this is just about to go green on azure but that previous failure was a consecutive case of a flake I've been seeing pop up a lot more. Ticket filed for it here: https://jira.mesosphere.com/browse/DCOS-15228

**Comment by lingmann** [comment]
Thanks @mellenburg !

**Pull request merged**
