### PR TITLE
DO NOT MERGE - Remove iframe deny on 1.12

### PR DESCRIPTION
**Pull request by niartenyaw**
# DO NOT MERGE

I am using this for testing, please do not delete it.

### CODE REVIEW

**Comment by niartenyaw** [comment]
@mesosphere-mergebot bump-ee

**Comment by nLight** [comment]
Please don't just remove it: https://github.com/dcos/dcos/pull/3783
UI Team has the COPS in progress. As the policy suggests we're fixing from the bottom up.

**Comment by nLight** [comment]
@niartenyaw We've merged the fix for the iframe issue can we close this now?

**Comment by niartenyaw** [comment]
@nLight awesome! i'd like to make sure it works for our use case, and I can do that some time tomorrow. Will let you know!

**Comment by niartenyaw** [comment]
Hey @nLight, the change from `DENY` to `SAME-ORIGIN` unfortunately doesn't fix our use case. The origin of the iframe is not the same as the DC/OS UI. We have created a [ticket](https://jira.mesosphere.com/browse/DCOS-43064) to be able to configure `ALLOW-FROM`. We'll continue to need access to https://downloads.mesosphere.com/dcos-enterprise/testing/pull/3843/dcos_generate_config.ee.sh. If this artifact will persist after closing the PR, we can definitely close it. Just want to make sure we will have access to it. Thanks!

**Comment by nLight** [comment]
@niartenyaw oh, but that is a separate issue! We've fixed the banner plugin we have in the UI that wraps the UI with iframe.

**Comment by tnguyen0** [comment]
@nLight, nice that you guys have that fixed!

Since this is a separate issue, we are going to still need this PR (or at least the artifact @niartenyaw 
 mentioned) so we can have the UI wrapped in an iframe for the learning platform until this [ticket](https://jira.mesosphere.com/browse/DCOS-43064) is addressed.

**Pull request closed without merging**
