### PR TITLE
[master] Mergebot Automated Train PR - 2019-Mar-13-10-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #4660 - [master] Automated Bump DC/OS UI v2.59.0

### CODE REVIEW

**Comment by gpaul** [comment]
The frontend team's bot had a minor bug that had it operate on train PRs that included their PRs. They've since fixed their bot.

The bot closed the Enterprise train PR (the current PRs sibling) but left this one open. @orsenthil should we also close this one and have both htrain PRs be recreated?

**Comment by jbarrick-mesosphere** [comment]
I believe that is the right course of action. Unfortunately, I don't have rights to delete the PR.

**Comment by orsenthil** [comment]
@gpaul  / @jbarrick-mesosphere  - The frontends both PRs are still open, which means that just closing this train would have included them again. I have closed these PRs, and let close this train.

**Comment by gpaul** [comment]
Thanks @orsenthil! That sounds good to me. The PR I cared about (bumping rexray) was subsequently merged while I slept. Automated, automerging trains _really_ kick ass.

**Pull request closed without merging**
