### PR TITLE
bump marathon 1.6.496

### PR DESCRIPTION
**Pull request by meln1k**
## High-level description

Marathon 1.6.496 bump

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [MARATHON-8149](https://jira.mesosphere.com/browse/MARATHON-8149) Fix links to DC/OS documentation.
  - [MARATHON-8151](https://jira.mesosphere.com/browse/MARATHON-8151) Track mesos offer requests.
  - [MARATHON-8148](https://jira.mesosphere.com/browse/MARATHON-8148) Pod failure reasons are not visible in the UI/API.
  - [MARATHON-8172](https://jira.mesosphere.com/browse/MARATHON-8172) Limit max number of concurrently running deployments.
  - [MARATHON-8174](https://jira.mesosphere.com/browse/MARATHON-8174) Upgrade to Jersey 2.27.
  - [MARATHON-8200](https://jira.mesosphere.com/browse/MARATHON-8200) Default to application/json when Accept */* provided.
  - [MARATHON-7680](https://jira.mesosphere.com/browse/MARATHON-7680) Add Marathon/Mesos compatibility matrix to the docs.
  - [MARATHON-8219](https://jira.mesosphere.com/browse/MARATHON-8219) Introduce a GCActor cleaning interval.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/mesosphere/marathon/compare/f9d087d2f...5e9295c8f
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-team-releases/job/marathon-community-release-1.6/40/console
  - [x] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by meln1k** [comment]
@mesosphere-mergebot bump-ee

**Comment by meln1k** [comment]
@mesosphere-mergebot label Work In Progress

**Comment by meln1k** [comment]
Bug is fixed in 1.6.490

**Comment by orsenthil** [comment]
Hi @meln1k  - You did a merge at https://github.com/dcos/dcos/pull/2932/commits/b1a3abc66ccabc8b47d8dfbc8f5c3706af89d6e6 and later didn't do a bump-ee. The EE side reference does not point to the HEAD of this change.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by meln1k** [comment]
Another bug fixed in 1.6.493

**Comment by meln1k** [comment]
@mesosphere-mergebot bump-ee

**Comment by meln1k** [comment]
Another fix

**Comment by meln1k** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
