### PR TITLE
Revert "D2IQ-65520: added missing AppRotate* params of NSSM while Winpanda setup"

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

I looked at the all builds in #7035 and in all other PRs test were able to run (some of them failed – this is fine) and only in #7031 test timed out. Let's see if revert PR pass tests. If not we should search for another change – maybe it's in ansible?

### Reverts:
* dcos/dcos#7031
* https://github.com/dcos/dcos/pull/7040

## Corresponding DC/OS tickets (required)

  - [D2IQ-65520](https://jira.d2iq.com/browse/D2IQ-65520) 

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @jongiddy @jeschkies @DominikDary @sergiimatusEPAM @KostiantynOleksiienko

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required Reverting change not included in changelog

**Comment by janisz** [comment]
@mesosphere-mergebot sync

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ship It

**Comment by janisz** [comment]
@mesosphere-mergebot sync

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by DominikDary** [comment]
@mesosphere-mergebot label Ship It

**Comment by janisz** [comment]
@mesosphere-mergebot sync

**Comment by DominikDary** [comment]
@mesosphere-mergebot merge-it

**Comment by DominikDary** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
