### PR TITLE
Update to latest cosmos snapshot

### PR DESCRIPTION
**Pull request by cruhland**
## High Level Description

Various code and test refactorings that don't change the functionality of Cosmos. This release is mainly being made to bring cosmos up to date in Enterprise DC/OS. See the corresponding Enterprise PR for more details.

## Related Issues

- [DCOS-15635](https://jira.mesosphere.com/browse/DCOS-15635) Get rid of `PackageRunner`
- [DCOS-11808](https://jira.mesosphere.com/browse/DCOS-11808) Allow extensible Error accross projects
- [DCOS-15844](https://jira.mesosphere.com/browse/DCOS-15844) Refactor error handling in service/update

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: tests are in the cosmos repo
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [change log](https://github.com/dcos/cosmos/compare/df6306ebf1...8695730)
  - [X] [Test Results](https://teamcity.mesosphere.io/viewLog.html?buildId=683769&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_PublishSnapshot)
  - [X] [Code Coverage](https://teamcity.mesosphere.io/viewLog.html?buildId=683767&tab=buildResultsDiv&buildTypeId=DcosIo_Cosmos_Scoverag)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by cruhland** [comment]
@mesosphere-mergebot bump-ee

**Comment by cruhland** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by cruhland** [comment]
@jsancio @orsenthil please review!

**Comment by jgehrcke** [comment]
Is there a JIRA ticket to be  closed now that this landed?

**Comment by cruhland** [comment]
@jgehrcke https://jira.mesosphere.com/browse/DCOS-16106

**Pull request merged**
