### PR TITLE
Train 195

### PR DESCRIPTION
**Pull request by margaret**
## High Level Description

[#1751](https://github.com/dcos/dcos/pull/1751) "1.9.2 should report its version as 1.9.2 😸"
[#1758](https://github.com/dcos/dcos/pull/1758) "Update the DC/OS UI package to include the latest fixes and improvements."

### CODE REVIEW

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
Any reason not to include other 1.9.x PRs with Ship-Its?
https://github.com/dcos/dcos/pull/1742
https://github.com/dcos/dcos/pull/1757
Why have them wait for 1.9.3 when they're ready now?

**Comment by margaret** [comment]
@adam-mesos Both of those had comments saying to wait til 1.9.3. I'm under the impression that 1.9.2 was supposed to be 'done' after the version bump, but in that case it'd make more sense to also defer the UI update to 1.9.3 😕❓ @lingmann

**Comment by lingmann** [comment]
@adam-mesos @margaret that is correct, we started a soak a few days ago for releasing 1.9.2 and there is a specific desire to not destabilize anything that has been soaked. The PR's on this train are the only ones that were deemed safe to add (would not reset soak time) per discussions with Cathy. Once this lands we will release 1.9.2, create the 1.9 "next" branch, and everyone's 1.9 PR's can start targeting that.

**Comment by margaret** [comment]
Tests failing on the Enterprise PR are Custom-CA which is not meant to work until 1.10, and `test_networking.test_vip` which is unfortunately flaky.

**Comment by jgehrcke** [comment]
Thank you!

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
