### PR TITLE
skip intermediate tarball to avoid `tar: Unrecognized archive format`

### PR DESCRIPTION
**Pull request by jkt628**
## High Level Description

What features does this change enable? What bugs does this change fix? High-Level description of how things changed.

allows MacOS to run dcos_generate_config.sh without requiring GNU tar by dropping the intermediate tarball.

## Related Issues

  - [DCOS_OSS-168](https://jira.dcos.io/browse/DCOS_OSS-168) dcos_generate_config.sh should support OS X.

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:

build requires Linux, install requires MacOS.

  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by karlkfi** [comment]
`integration-test/dcos-docker` is a new CI test. It's not required to pass, yet. But now that it's green on master, I've kicked off a new build for this PR.

**Comment by jkt628** [comment]
looks like integration-test/vagrant-bash fails for unrelated reasons.

**Comment by jkt628** [comment]
`continuous-integration/jenkins/pr-head` lacks the guest access mentioned in [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)

**Comment by karlkfi** [comment]
integration-test/vagrant-bash failed on:
```
test_service_discovery.test_service_discovery_docker_bridged_network
test_networking.test_ip_per_container
```

I'm not sure if those are known to be flakey or not. So I just kicked off that build again.

**Comment by karlkfi** [comment]
`continuous-integration/jenkins/pr-head` was just waiting for approval to run non-employee code. I told it to proceed, but I'm not sure if there's a way to tell it to approve any for this PR.
@vespian, Is there a way to do that with a PR comment? I'm not familiar with how it works for jenkins pipelines.

**Comment by vespian** [comment]
@karlkfi It is possible but will require some groovy-foo and an external database of some sort that is accessible to Jenkins. I think I would need 2-3 days to implement it. Currently, it needs to be ACKed on every change.

**Comment by jkt628** [comment]
seems like this hit a [chicken and egg problem](https://en.wikipedia.org/wiki/Chicken_or_the_egg): `Ready For Review` requires all tests to pass but one of the tests is minimum two reviews.

**Comment by orsenthil** [comment]
The two minimum reviews required is on this PR. That's an enforcement we do for contributions to `dcos/dcos` project.

**Pull request closed without merging**
