### PR TITLE
[1.12] Increase "instant" checks timeout to 5s

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

Attempts to reduce the relatively common occurrence of timeouts in checks that have no real way to time out by increasing the timeout to 5 seconds in case load is preventing a cluster from being able to run the check in the normal 1 second.

Bacports: https://github.com/dcos/dcos/pull/5529
---

## Corresponding DC/OS tickets (required)

  - [DCOS-53742](https://jira.mesosphere.com/browse/DCOS-53742)

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @drewvanstone @br-lewis @makkes

**Comment by jgehrcke** [comment]
Hmm, `continuous-integration/jenkins/pr-head` does not report back. That counts as CI instability. Preparing an override command.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status continuous-integration/jenkins/pr-head https://jira.mesosphere.com/browse/DCOS-55834

**Comment by jgehrcke** [comment]
We are OK w/o looking at the result of `continuous-integration/jenkins/pr-head` because this PR does not touch Admin Router.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ship It

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
