### PR TITLE
Bumped Mesos to 579ed551953149b4c56d7a3daa077a23ba87ae31.

### PR DESCRIPTION
**Pull request by bbannier**
## High-level description

This bump includes a DC/OS-specific backport of MESOS agent API changes done as part of [MESOS-8388](https://issues.apache.org/jira/browse/MESOS-8388).

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

- [DCOS_OSS-2377](https://jira.mesosphere.com/browse/DCOS_OSS-2377) MESOS: cherry-pick MESOS-8388 into dcos patch list

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins//job/mesos/job/Mesos_CI-build/3286
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by bbannier** [comment]
@mesosphere-mergebot bump-ee

**Comment by bbannier** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by greggomann** [comment]
@bbannier @asridharan were RP resources in the GET_AGENTS response not also needed as part of this backport?

**Comment by bbannier** [comment]
@greggomann The changes to the Mesos master API's `GET_AGENTS` depend on a larger refactoring series of the master which we IMO should not backport since it e.g., introduces too large a delta between actual 1.5 and our fork. @jdef mentioned that he would be able to get what he needs from the Mesos agent API changes backported here which are way less risky.

**Comment by bbannier** [comment]
@asridharan Could you please formally review this patch so it can move forward?

**Comment by asridharan** [comment]
@greggomann @orsenthil just noticed there is another Mesos nightly bump PR that is pending:
https://github.com/dcos/dcos/pull/2790

Would that PR conflict with this one?

**Comment by greggomann** [comment]
Good point @rukletsov , I should have caught that. @karya0 it looks like DC/OS 1.11 did not include `patches.json` in the Mesos package directory. Should we introduce that file into the `1.11` branch?

**Comment by greggomann** [comment]
According to @karya0 if `patches.json` isn't found, the automated bumps will use `README.md`, so @bbannier could you either change this PR to update that file, or open a new one for that purpose? Then we can use the automated 1.11 bumps to get your changes in.

**Comment by bbannier** [comment]
@greggomann On it, will open a new one.

**Pull request closed without merging**
