### PR TITLE
Add metronome test

### PR DESCRIPTION
**Pull request by gabrielhartmann**
## High-level description

What features does this change enable? What bugs does this change fix?

This creates a test which currently fails due to a regression in metronome.  This job should work.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-2036](https://jira.mesosphere.com/browse/DCOS_OSS-2036) Metronome 0.3.3 bump on DCOS 1.11 (testing/master)

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orsenthil** [comment]
+1 good idea!

**Comment by gabrielhartmann** [comment]
I'd like to see this test fail and then have someone force merge it.  Is the right person to do that you @spahl?

**Comment by spahl** [comment]
Sounds good to me.

**Comment by spahl** [comment]
Is the above JIRA the right one to poing the mergebot override to?

**Comment by gabrielhartmann** [comment]
@spahl I think that JIRA should be the one that is resolved when the bug in Metronome is fixed, so yes...

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
I just noticed, the failure if see anything, should be in dcos-commons and that will be exercised in enterprise bump PR

**Comment by gabrielhartmann** [comment]
@orsenthil Why do you mention `dcos-commons`?  I don't follow.

**Comment by orsenthil** [comment]
@gabrielhartmann  - I striked and updated my comment.

**Comment by gabrielhartmann** [comment]
@orsenthil:  Still not sure I follow.  This Metronome bug made it in because `dcos-commons` didn't have any smoke tests exercising Metronome.  That hasn't changed.

**Comment by orsenthil** [comment]
> This Metronome bug made it in because dcos-commons didn't have any smoke tests exercising Metronome. That hasn't changed.

My mistake. I thought, it got caught by a downstream test that you had.

**Comment by gabrielhartmann** [comment]
Yes we caught it in our CI.  Not all of our CI is run in every DC/OS PR because it takes a few hours.

**Comment by gabrielhartmann** [comment]
@mellenburg: Out of Azure quota?
```
[22:51:35]	Traceback (most recent call last):
[22:51:35]	File "dcos_launch/cli.py", line 133, in <module>
[22:51:35]	File "dcos_launch/cli.py", line 125, in main
[22:51:35]	File "dcos_launch/cli.py", line 80, in do_main
[22:51:35]	File "dcos_launch/arm.py", line 38, in create
[22:51:35]	File "dcos_launch/platforms/arm.py", line 109, in deploy_template_to_new_resource_group
[22:51:35]	Exception: Template verification failed!
[22:51:35]	InvalidTemplateDeployment: The template deployment 'teamcity-dcos-test-azure-arm-cqlrybu1rm-Deployment' is not valid according to the validation procedure. The tracking id is '05617880-bc26-4664-812f-879bbe4ee7c6'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
[22:51:35]	
[22:51:35]	QuotaExceeded: Operation results in exceeding quota limits of Core. Maximum allowed: 200, Current in use: 198, Additional requested: 14. Please read more about quota increase at http://aka.ms/corequotaincrease.
[22:51:35]	
[22:51:35]	QuotaExceeded: Operation results in exceeding quota limits of Core. Maximum allowed: 200, Current in use: 198, Additional requested: 14. Please read more about quota increase at http://aka.ms/corequotaincrease.
```

**Comment by gabrielhartmann** [comment]
The test failed, but with a different failure message than I'm used to.

**Comment by gabrielhartmann** [comment]
This testing should be owned by the Metronome team, and be included when a fix is introduced to DC/OS.  In the mean time it should be preferred to revert the original breakage which is pretty old now.

**Pull request closed without merging**
