### PR TITLE
Bump dcos-diagnostics

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

Bump dcos-diagnostics

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5384](https://jira.mesosphere.com/browse/DCOS_OSS-5384) 
  - [DCOS_OSS-5303](https://jira.mesosphere.com/browse/DCOS_OSS-5303) 

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @drewvanstone @br-lewis @makkes

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required version bum

**Comment by janisz** [comment]
:wave: @drewvanstone @br-lewis @makkes  Can you review, please?

**Comment by makkes** [comment]
> > @mesosphere-mergebot changelog-not-required version bum
> 
> @janisz let's please try to explain in a meaningful way to other people (especially reviewers) why this change does not need to have a changelog entry. "Version bump" doesn't tell me much 🎈
> 
> Looks like https://jira.mesosphere.com/browse/DCOS_OSS-5303 might be worth having a CHANGES.md entry. Is there a plan for putting the same patch into 1.13.x (the JIRA ticket unfortunately doesn't tell, it does not have fixVersion values set for expressing intent)?

I'll try to explain why I believe this does not require an entry in the CHANGES.md:

* https://jira.mesosphere.com/browse/DCOS_OSS-5303 is no user-facing change in that this is a new API that's currently not used by any component (we're planning to migrate to the new API from the CLI which definitely is a user-facing change then, of course). The ticket only replicates the behaviour that's already in the old Diagnostics API.
* https://jira.mesosphere.com/browse/DCOS_OSS-5384 is also not user-facing since no user/operator will be able to configure this via `dcos-config.yaml`. This is only meant to be used by the Windows team for quickly making Diagnostics run on Windows agents.

**Comment by janisz** [comment]
@jgehrcke Is it OK to have changelog entry like this:

> * Updated DC/OS Diagnostics to [0130853fcfe0905e34ffd132d57d77a281660c76](https://github.com/dcos/dcos-diagnostics/commit/0130853fcfe0905e34ffd132d57d77a281660c76).

I'd like to have automatic bump PR after every commit merged to diagnostics

**Pull request merged**
