### PR TITLE
Admin Router: Train #1

### PR DESCRIPTION
**Pull request by vespian**
#1438
#1477
#1521 

EE DC/OS PR: https://github.com/mesosphere/dcos-enterprise/pull/889

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot label Ready for review

**Comment by vespian** [comment]
@orsenthil This is already the minimal required set.

**Comment by amitaekbote** [comment]
This is three pr's into one branch for the sake of sanity, admin router had merge conflicts that I asked @vespian to handle. The individual pr's commits make sense

**Comment by spahl** [comment]
No need to squash here IMHO. Quite to the contrary we would loose valuable information.

**Comment by orsenthil** [comment]
Sorry @spahl ,  I picked few randomly to review commits.



```
@vespian	Admin Router: Add missing scheme-related tests for "/service" location			770fa10
 @vespian	Admin Router: Simplify statefull /service location tests  …			972b216
 @vespian	Admin Router: Add some extra documentation about tooling			287dea7


```
How these are giving **valuable** information when these once landed in master is going to live _for-ever_.

I am not opposed to not-squashing and favor things moving fast. But, I think, we all should care about clean design of things.

**Comment by vespian** [comment]
@orsenthil Some context for you.

Apart from how time consuming fixing history would be (rebasing again + repushing tests), as one of AR maintainers I *do* see point in these commits. After comparing mine vs. yours number of AR contributions, I think you can take my word for granted ;)
```
# vespian at budrys.vespian.net in ~/work/git_repos/ar-o on git:prozlach/ar-train-1 o [20:46:50]
$ git ls-tree -r -z --name-only HEAD -- */* | xargs -0 -n1 git blame --line-porcelain HEAD |grep  "^author "|sort|uniq -c|sort -nr
  12703 author Pawel Rozlach
   2875 author Karl Isenberg
    298 author Martin Hrabovcin
     64 author Gustav Paul
      4 author Jan-Philip Gehrcke
```
This is inaccurate of course - after merging AR into DC/OS repo JPs, Martins and Gustavs contributions are counted as mine.

I would very much appreciate if we could invest our time and effort into figuring out how we can merge remaining AR PRs before the code freeze instead:
https://github.com/dcos/dcos/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20Admin%20Router
https://github.com/mesosphere/dcos-enterprise/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20Admin%20Router
I am *very* worried that it will block other teams and cause delays, i.e. https://jira.mesosphere.com/browse/DCOS-14891 which *needs* above changes in order to work.

Another thing is all the "Work in Progress" PRs from the list are simply PRs that are stashed on top of one another and are waiting for the ones in front of them. Even though I pointed out in #foundations channel on Slack, on many occasions, that "In Review" state is confusing/ambigous, we have PRs like: https://github.com/dcos/dcos/pull/1477 - *one line* change that was given "Ready for Review" label three weeks ago and up until yesterday nobody noticed :(

This train improves this situation because it merges 2 PRs and makes this queue shorter/unblocks it and on top of that it also merges important&urgent fix for JPMC. Individual PRs were complex, the train is even more complex and thus the number of commits. Even if 3 out of 28 commits that you pointed out were questionable, I *really* do not believe that we should be putting so much attention to it considering other issues we are currently struggling with.

And finally we arrive at this mini-train/PR - @amitaekbote was kind enough to try to fix this/improve this mess, on her own initiative. I am very grateful for what she did/is doing.

I hope you that this will manage to convince you!
Thanks.

**Comment by orsenthil** [comment]
@vespian 

I see you as owner of the admin-router code. No questions there.

The reasoning you gave did not answer "why" these commits should be separate. 

All I ask for is - if you can squash them all into single commit for a single PR and land it that's fine. Carefully crafting it into individual commits is more work, but if you are open do to do that, that will be awesome.

Instead, if we just let everything go (I pointed out that some commits are maintaining "distracting history") because we are in a  'hurry', then I am -1 on it.   

I am in for quick trains and merges, but with clean history (that's my fervent ask). :)

I did not review other commits. I will those shortly and you can take your call.

**Comment by adam-mesos** [comment]
Chiming on the squash convo, I don't think there's a real need to squash here, as there can be valuable information in breaking up the AR commits. Some guidelines I like to follow:
- If # commits > # files, you should consider squashing (not true here)
- If # commits / PR > 10, you should consider squashing (only true for #1438 )
- No trivial commit messages like "Fixed tpyo" or "speling" (these are pretty good)
Thankfully, each commit is prefixed with "Admin Router:" for easy scanning/filtering.

**Comment by spahl** [comment]
I'd also like to add that these were going in individually at first (well 3 chunks). Result on history was gonna be the same.

Let's close this discussion please. We need to find a way to work on multiple components in a single repo a bit better. We can use this afternoons meeting.

**Comment by orsenthil** [comment]
SGTM.

I hope the original reviewers had requested the squash (#1438 ) earlier so that I did not have to bring this one up late.

**Comment by amitaekbote** [comment]
@adam-mesos lets merge this, ill bump ee once we get this in

**Comment by mellenburg** [comment]
I am very confused with what happened here. This seems to have completely broken with our protocol for how we ship code. This was NOT a merge train, this was a feature train that could have been pushed into a train. Why did this cut infront of the official merge train that I have been ushering?

**Pull request merged**
