### PR TITLE
WIP: Testing multi/hierarchical roles

### PR DESCRIPTION
**Pull request by adam-mesos**
## High Level Description

Testing multi-role frameworks and hierarchical roles.

For this Mesos franken-branch,
1. Start with a recent Mesos master (487c667)
2. Add Neil's hrole patches (14 files in 4 commits): https://github.com/neilconway/mesos/commits/hrole-squashed
3. Add Benjamin's test infra (4 files in 82 commits): https://github.com/bbannier/mesos/commits/t/multirole_example_w_hrole (includes Neil's)
4. Add Alexander's hrole authz (5 files in 3 commits): https://github.com/mesosphere/mesos-private/commits/alexander/hierarchical-role/authz
5. Add dcos-mesos cherry-picks (7 files in 5 commits)

Then update the dcos/dcos PR and cherry-pick a couple of mesos-modules and test commits from https://github.com/dcos/dcos/pull/1343/commits

## Checklist for component/package updates:

  - [x] Change log from the last version integrated: https://github.com/mesosphere/mesos/compare/dfd332085e9dec451239aa17102d912e909f8a98...9e51ea8365007431bdad0439558dffef7b289c9e
  - [ ] Test Results: [link to CI job test results for component]

### CODE REVIEW

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by bbannier** [comment]
@adam-mesos: I updated the PR to build and install the full test suite. With that change the example framework is put into `/opt/mesosphere/packages/mesos--*/libexec/mesos/tests/multirole-framework[_test.sh]`. I confirmed that the executable can be used to register with multiple roles and to start tasks.

The framework cannot be run via the test suite (a la the originally intended and previously demo'ed way: `./build/src/mesos-tests --gtest_filter='ExamplesTest.MultiRoleFramework' --verbose`) since DC/OS does not keep the Mesos sources around which this causes `mesos-tests` to fail a `CHECK` at startup. A way forward might be to adjust `multirole-framework_test.sh` for a DC/OS environment. This likely would at least involve:

* remove code starting Mesos masters and agents (`start_[master|agent]`) everywhere.
* update `setup_env`: set `MULTIROLE_FRAMEWORK` to the install location, adjust `LD_LIBRARY_PATH`, remove unsupported constructs and dead code.
* globally setting `MASTER_PORT` to the port of the master. If we cannot run the demo from a master update all locations assuming `localhost` to `leader.mesos`.
* fix all tests relying on the number of agents, agent availability, and agent resources, at least
  - `test_quota`
  - `test_reserved_resources`
  - `test_fair_share`
* replace use of `httpie` in some places with equivalent `curl` constructs or make `httpie` available.

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by adam-mesos** [comment]
Stale. No longer needed.

**Pull request closed without merging**
