### PR TITLE
Train 125

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

This train includes the following PRs

#914 - Refactor azure 
#1121 - Set LIBPROCESS_PORT for marathon and metronome
#1198 - cosmos: restrict admin and http ports to localhost
#1187 -  standardize on zookeeper connection string
#1188 - mesos-dns bugfixes and truncate bit disable
#1202 - Make delete volumes resilient to rate limiting

### CODE REVIEW

**Comment by orsenthil** [comment]
This is the downstream enterprise train: https://github.com/mesosphere/dcos-enterprise/pull/557

**Comment by orsenthil** [comment]
The downstream bump has a failure: https://github.com/mesosphere/dcos-enterprise/pull/557 - /cc @gpaul

**Comment by adam-mesos** [comment]
Please drop #1134 from the train in favor of #1198

**Comment by orsenthil** [comment]
The EE bump is successful too: https://github.com/mesosphere/dcos-enterprise/pull/557

This can be merged (after two approvals).

**Pull request merged**
