### PR TITLE
[master] Mergebot Automated Train PR - 2018-Apr-25-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2733 - Admin Router: Conditional request buffering for /service endpoint
* #2752 - dcos-checks: bump for register of subcommands

### CODE REVIEW

**Comment by orsenthil** [comment]
Hey @vespian  - It seems like https://jira.mesosphere.com/browse/DCOS-20269 for #2733 should be listed in https://github.com/dcos/dcos/blob/master/CHANGES.md file. Would you like add it to CHANGES.md in this train branch? ( Ideally, we will bring it as part of the PR itself, that is in #2733. Since we early with this CHANGELOG process, it seems okay to add it to train branch for now).

@gpaul  - My guess is #2752 isn't a customer facing change, so need not be included in [CHANGES.md ](https://github.com/dcos/dcos/blob/master/CHANGES.md)file. WDYT?

**Comment by gpaul** [comment]
@orsenthil agreed!

**Comment by vespian** [comment]
@orsenthil  Thanks for your comment. I thought that setting releaseVersion field and release-notes label in Jira is enough. Do we have now two processes for documenting these changes? If so, should I just push a commit into this Train PR?

**Comment by vespian** [comment]
@orsenthil Done.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
The `teamcity/dcos/test/aws/cloudformation/simple` tests all passed but tearing down the cluster timed out.

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/QUALITY-2092

**Comment by orsenthil** [comment]
@branden  / @mnaboka  - PTAL.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
