### PR TITLE
Bump Marathon to 1.9.118 on 2.0

### PR DESCRIPTION
**Pull request by jeschkies**
## High-level description

This bump includes a simple bug fix that enable pod status reports for task with `TASK_UNKOWN`
status.

## Corresponding DC/OS tickets (required)

  - [MARATHON-8710](https://jira.mesosphere.com/browse/MARATHON-8710) Marathon hides resident pod instances with task status TASK_UNKNOWN from /v2/pods/::status

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Marathon changelog](https://github.com/mesosphere/marathon/commit/d1bdb0e78f08c23651aeb0ae455d33a6e5c1feeb#diff-42ba1d994f4fa8c6ad17a7efae7936cc)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [x] Test Results: [Marathon build](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/)
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jeschkies** [comment]
@mesosphere-mergebot Ready For Review

**Comment by jeschkies** [comment]
@mesosphere-mergebot bump-ee

**Comment by jeschkies** [comment]
@mesosphere-mergebot bump-ee

**Comment by jeschkies** [comment]
@mesosphere-mergebot Ready For Review

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ship It

**Comment by jeschkies** [comment]
@mesosphere-mergebot sync

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ship It

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ship It

**Comment by jeschkies** [comment]
@mesosphere-mergebot sync

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ship It

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/build/dcosWindows DCOS-62753

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
> with JIRA while attempting to override: <class 'concurrent.futures._base.CancelledError'>:

* This was due to JIRA issue. Mergebot was able to authenticate and add watchers, but failed to add a comment.
* The override itself was successful. 

@AliakseiKhomchanka  might capture this in JIRA if this problem resurfaces. 

Thank you

**Pull request merged**
