### PR TITLE
Train 276 (master)

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 276 targeted for the 1.11 release. It contains the following pull requests:

- #2170 (chore(dcos-ui): update package to 1.11.0-rc.4)

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Launched the train-specific CI runs just now.

**Comment by adamtheturtle** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by mellenburg** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by mellenburg** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
