### PR TITLE
Remove windows pull request status from readme file.

### PR DESCRIPTION
**Pull request by DominikDary**
## High-level description

Remove windows pull request status.

### CODE REVIEW

**Comment by DominikDary** [comment]
@mesosphere-mergebot request-review  @orsenthil @jeschkies

**Comment by DominikDary** [comment]
@mesosphere-mergebot changelog-not-required not required

**Comment by jeschkies** [comment]
@mesosphere-mergebot changelog-not-required internal

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
