### PR TITLE
Bump UI for latest 1.11 bits

### PR DESCRIPTION
**Pull request by MatApple**
## High-level description

Contains a large portion of 1.11 work.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

 - [DCOS-19104](https://jira.mesosphere.com/browse/DCOS-19104): Consistent Service Status on Dashboard
- [DCOS-19528](https://jira.mesosphere.com/browse/DCOS-19528): Replace Suspend state with Stop
- [DCOS-19345](https://jira.mesosphere.com/browse/DCOS-19345): Add linked clusters page and menu link
- [DCOS-19483](https://jira.mesosphere.com/browse/DCOS-19483): Add new IS constraint operator constant
- [DCOS-19372](https://jira.mesosphere.com/browse/DCOS-19372): Use new Icon for deploying state
- [DCOS-17968](https://jira.mesosphere.com/browse/DCOS-17968): Redesign service Status
- [DCOS-18268](https://jira.mesosphere.com/browse/DCOS-18268): Create and use StatusBar component
- [DCOS-18264](https://jira.mesosphere.com/browse/DCOS-18264): Create and use StatusIcon component
- [DCOS-19335](https://jira.mesosphere.com/browse/DCOS-19335): Add cluster link in sidebar
- [DCOS-19339](https://jira.mesosphere.com/browse/DCOS-19339): Refactor ConfigurationMap edit action
- [DCOS-19398](https://jira.mesosphere.com/browse/DCOS-19398): Prevent Mount wrapping
- [DCOS-18317](https://jira.mesosphere.com/browse/DCOS-18317): Remove hover regression
- [DCOS-19132](https://jira.mesosphere.com/browse/DCOS-19132): Create and use ConfigurationMapToggleValue
- [DCOS-19026](https://jira.mesosphere.com/browse/DCOS-19026): Remove empty continuation lines
- [DCOS-19043](https://jira.mesosphere.com/browse/DCOS-19043): Add zone column to nodes table
- [DCOS-19266](https://jira.mesosphere.com/browse/DCOS-19266): Disable delete group functionality
- [DCOS-19370](https://jira.mesosphere.com/browse/DCOS-19370): Add tooltip to instances column
- [DCOS-18201](https://jira.mesosphere.com/browse/DCOS-18201): Introduce Framework configuration components
- [DCOS-19133](https://jira.mesosphere.com/browse/DCOS-19133): Add Mounts in Overview Details
- [DCOS-18317](https://jira.mesosphere.com/browse/DCOS-18317): Remove hover state in forms that shouldn't have it
- [DCOS-19026](https://jira.mesosphere.com/browse/DCOS-19026): Fix empty continuation line warning in Dockerfile
- [DCOS-18171](https://jira.mesosphere.com/browse/DCOS-18171): Show Region and Zone in service’s tasks page
- [DCOS-19135](https://jira.mesosphere.com/browse/DCOS-19135): Introduce Banner component
- [DCOS-18265](https://jira.mesosphere.com/browse/DCOS-18265): Introduce general purpose Progress-bar
- [DCOS-17966](https://jira.mesosphere.com/browse/DCOS-17966): Adjust instances column
- [DCOS-18197](https://jira.mesosphere.com/browse/DCOS-18197): Ddd delete status while service is deleting and disable actions
- [DCOS-18156](https://jira.mesosphere.com/browse/DCOS-18156): Introduce Connections Tab view components
- [DCOS-17965](https://jira.mesosphere.com/browse/DCOS-17965): Rename instances to tasks
- [DCOS-18172](https://jira.mesosphere.com/browse/DCOS-18172): Show “region” and “zone” columns in nodes page
- [DCOS-18858](https://jira.mesosphere.com/browse/DCOS-18858): Add Region and Zone information to node Overview page
- [DCOS-18949](https://jira.mesosphere.com/browse/DCOS-18949): Add Region and Zone name to the node detail tab
- [DCOS-18198](https://jira.mesosphere.com/browse/DCOS-18198): Trigger destroy with enter key while in input
- [DCOS-18157](https://jira.mesosphere.com/browse/DCOS-18157): Add Copy command in Table View for connections
- [DCOS-18358](https://jira.mesosphere.com/browse/DCOS-18358): Introduce mesos operator event stream package
- [DCOS-18006](https://jira.mesosphere.com/browse/DCOS-18006): Add uninstall Modal for Frameworks and SDK services
- [DCOS-18705](https://jira.mesosphere.com/browse/DCOS-18705): Change cluster provisioning
- [DCOS-18687](https://jira.mesosphere.com/browse/DCOS-18687): Introduce Resource Service
- [DCOS-18153](https://jira.mesosphere.com/browse/DCOS-18153): Introduce store for SDK Services and their connections

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by MatApple** [comment]
@mesosphere-mergebot bump-ee

**Comment by MatApple** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot pr-status-checks

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot pr-status-checks

**Pull request merged**
