### PR TITLE
bootstrap: More robust handling of a zk.pid file while waiting for exhibitor[master]

### PR DESCRIPTION
**Pull request by vespian**
It is a backport of https://github.com/dcos/dcos/pull/2212

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@mesosphere-mergebot label ready for review

**Comment by vespian** [comment]
@mesosphere-mergebot override-status  teamcity/dcos/test/aws/onprem/static-redhat https://jira.mesosphere.com/browse/DCOS-18018

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat https://jira.mesosphere.com/browse/DCOS-18018

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat DCOS-18018

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
Glad that you found the logging bug. Did we now cover all the code, at least with manual tests?

**Comment by jgehrcke** [comment]
Does that mean the the 1.10 branch now has this 'logging bug'? 

(https://github.com/dcos/dcos/pull/2212)

**Comment by vespian** [comment]
@jgehrcke:
> ...Did we now cover all the code...

Bootstrap has no automated tests whatsoever, it is a problem I am communicating for some time already.

> at least with manual tests?

I did test the original change manually, but like with all manual tests - it is easy to miss something hence the bug that AdamB spotted :( I will double check the change once more today.

**Comment by vespian** [comment]
> I will double check the change once more today.
I have just manually verified that the fix indeed works.

**Pull request merged**
