### PR TITLE
[1.12] Bump Mesos to nightly 1.7.x 4f21147

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
## High-level description

This is a routine bump to the latest Mesos and mesos-modules.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Changelog:
    https://github.com/apache/mesos/compare/b97f0ba29d40a279dec00ffe51512e3b5a146049...4f21147a9334ef9ed84dcf11742ce448062f3ec1
    https://github.com/dcos/dcos-mesos-modules/compare/545c3ff25e8bf5dcff166b83ee419584db22a5c4...85a3ee2e4ac2b180b13690ea98fd87a8ef473697
    
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot bump-ee

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS-40539

**Comment by rukletsov** [comment]
@mesosphere-mergebot sync

**Comment by rukletsov** [comment]
@mesosphere-mergebot sync

**Comment by rukletsov** [comment]
@mesosphere-mergebot sync

**Pull request merged**
