### PR TITLE
Update DC/OS UI package to 1.10.0-rc.8 (1.10)

### PR DESCRIPTION
**Pull request by orlandohohmeier**
## High Level Description

Update the DC/OS UI package to include the latest fixes and improvements.

What features does this change enable? What bugs does this change fix? High-Level description of how things changed.

## Related Issues

- [DCOS_OSS-1582](https://jira.mesosphere.com/browse/DCOS_OSS-1582): Fix `unreachableStrategy` validation

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-ui/compare/v1.10.0-rc.7...v1.10.0-rc.8)
  - [x] Test Results: [Unit, Integration, System](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/386/)
  - [x] Code Coverage (if available): [Cobertura Report](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/386/cobertura/)

___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orlandohohmeier** [comment]
@orsenthil `1.10` or `1.10.0`?

**Comment by orsenthil** [comment]
`dcos:1.10` is correct. However, there is something wrong with pkgpanda here: 

`fatal: ambiguous argument 'v1.10.0-rc.8^{commit}': unknown revision or path not in the working tree.` 

* `teamcity/create-release-pr ` had a failure.

```
[Building package dcos-ui variant <default>] pkgpanda.build.BuildError: Validation error when fetching sources for package: Unable to find sha1 of ref_origin v1.10.0-rc.8: Unable to find ref 'v1.10.0-rc.8' in '/teamcity/work/19ad0dff41587ee6/packages/cache/packages/dcos-ui/dcos-ui/cache.git': Command '['git', '--git-dir', '/teamcity/work/19ad0dff41587ee6/packages/cache/packages/dcos-ui/dcos-ui/cache.git', 'rev-parse', 'v1.10.0-rc.8^{commit}']' returned non-zero exit status 128
[15:33:21]	
```

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ship It]

**Pull request merged**
