### PR TITLE
kill minuteman ewma

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

**Comment by sargun** [comment]
@spacejam 
1. Can you spin up a cluster with 1 agent -- then setup three backends, and see how load gets distributed (stable state) amongst the three backends?
2. Can you expand the cluster to 2 agents, and create a NEW vip, and send traffic from one machine to the VIP, and see how load gets distributed amongst the backends?

**Comment by spacejam** [comment]
seems pretty tight
```core@ip-10-0-5-112 ~ $ sort single_slave_log | uniq -c
  15110 Hello world (3250) app running at: :17450, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15024 Hello world (3251) app running at: :12162, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15004 Hello world (3315) app running at: :4539, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15203 Hello world (3364) app running at: :23654, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15275 Hello world (3399) app running at: :29048, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15324 Hello world (3451) app running at: :13968, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15073 Hello world (3494) app running at: :24905, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15210 Hello world (3552) app running at: :18886, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15328 Hello world (3614) app running at: :2835, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
  15169 Hello world (3649) app running at: :6501, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
core@ip-10-0-5-112 ~ $ sort double_slave_log | uniq -c
   1448 Hello world (1816) app running at: :20941, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
   1313 Hello world (1884) app running at: :24189, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
   1384 Hello world (1889) app running at: :1640, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
   1440 Hello world (1949) app running at: :23344, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
   1346 Hello world (2031) app running at: :10631, on hostname: ip-10-0-3-137.us-west-2.compute.internal, and say string `version1`
   1430 Hello world (3004) app running at: :26232, on hostname: ip-10-0-3-228.us-west-2.compute.internal, and say string `version1`
   1402 Hello world (3010) app running at: :21229, on hostname: ip-10-0-3-228.us-west-2.compute.internal, and say string `version1`
   1442 Hello world (3065) app running at: :27278, on hostname: ip-10-0-3-228.us-west-2.compute.internal, and say string `version1`
   1417 Hello world (3118) app running at: :1091, on hostname: ip-10-0-3-228.us-west-2.compute.internal, and say string `version1`
   1413 Hello world (3181) app running at: :23318, on hostname: ip-10-0-3-228.us-west-2.compute.internal, and say string `version1````

**Comment by sargun** [comment]
I pulled the use new vip specification into #352 

The hash should get updated in the security PRs.

**Comment by alberts** [comment]
Closed at @sargun 's request

**Pull request closed without merging**
