### PR TITLE
Bump Marathon to 1.4.7.

### PR DESCRIPTION
**Pull request by jeschkies**
## High Level Description

What features does this change enable? What bugs does this change fix? High-Level description of how things changed.

## Related Issues

* [MARATHON-7715](https://jira.mesosphere.com/browse/MARATHON-7715) - Marathon would not notice an unreachable / lost resident task was gone, or that a reservation should be released, unless if it was idle. This is has been resolved.
* [MARATHON-1703](https://jira.mesosphere.com/browse/MARATHON-1703) - Resident task instance placement now properly respects constraints which rely on the placement state of instance peers (such as hostname:UNIQUE).
* [MARATHON-7707](https://jira.mesosphere.com/browse/MARATHON-7707) - Resident task instance agentId and host name values are now properly updated on re-launch.
* [MARATHON-7654](https://jira.mesosphere.com/browse/MARATHON-7654) - Marathon resident task re-launch requests are no longer denied by Mesos for having the same id as another unreachable task (because Marathon no longer re-uses task ids).

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [1.4.6 to 1.4.7](https://github.com/mesosphere/marathon/commit/2dd635d168ac68c03e36917f4d837ca9670e2a30)
  - [x] Test Results: [Jenkins](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/releases%252F1.4/73/)
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jeschkies** [comment]
@mesosphere-mergebot bump-ee

**Comment by kensipe** [comment]
it seems a few tests are flaky... recorded the failures and retesting

**Comment by timcharper** [comment]
```

    @retrying.retry(wait_fixed=1000,
                    retry_on_result=lambda ret: ret is False,
                    retry_on_exception=lambda x: False)
    def _wait_for_dcos_history_data(self):
        ro = self.get('/dcos-history-service/history/last')
        # resp_code >= 500 -> backend is still down probably
        if ro.status_code <= 500:
            log.info("DC/OS History is probably getting data")
            json = ro.json()
            # if an agent was removed, it may linger in the history data
>           assert len(json["slaves"]) >= len(self.all_slaves)
E           AssertionError

.tox/py35-upgrade-test/lib/python3.5/site-packages/dcos_test_utils/dcos_api.py:265: AssertionError
```

looks flaky. rebuilding.

**Comment by kensipe** [comment]
This is the 2nd consecutive failure in that test suite (with different test failures) :(

**Comment by adam-mesos** [comment]
Downstream has a ShipIt despite a single strict-mode test failure (known flaky in 1.9), so I'm applying the ShipIt here too.

**Comment by mellenburg** [comment]
Confirmed that downstream failure is a flake that should not block this. Its ready for merge.

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
