### PR TITLE
Fixed location of DC/OS Signal integration test

### PR DESCRIPTION
**Pull request by makkes**
## High-level description

What features does this change enable? What bugs does this change fix?

This test was at the wrong location.

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5479](https://jira.mesosphere.com/browse/DCOS_OSS-5479)     DC/OS Signal integration test not run

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS-57770

**Comment by makkes** [comment]
@mesosphere-mergebot request-review @janisz @br-lewis @drewvanstone

**Comment by makkes** [comment]
@mesosphere-mergebot changelog-not-required only re-activating an integration test

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Holding

**Comment by jongiddy** [comment]
@makkes This PR introduces an error - `test_signal` was not added to the `test_groups.yaml`. This was masked by the override issued for the other `test_groups.yaml` error (https://jira.mesosphere.com/browse/DCOS-57770).

It is revealed in the train #6119 which had DCOS-57770 fixed.

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by makkes** [comment]
@mesosphere-mergebot label Work In Progress

**Comment by makkes** [comment]
@mesosphere-mergebot label Ready For Review

**Pull request merged**
