### PR TITLE
Train 283 (master)

### PR DESCRIPTION
**Pull request by jgehrcke**
This is train 283. It contains the following pull requests:

- #2159 (Mesos: Increase min libprocess worker threads to 16. [1.11])
- #2196 (chore(dcos-ui): update package)

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
.0

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status  teamcity/dcos/test/azure/arm DCOS_OSS-1877

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS_OSS-1877

**Comment by vespian** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS_OSS-1877

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
