### PR TITLE
Update dcos-diagnostics

### PR DESCRIPTION
**Pull request by janisz**
Fixes: DCOS_OSS-4322

## High-level description

* Update dcos-diagnostics to the latest version with small fixes and upgraded dependencies

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4322](https://jira.mesosphere.com/browse/DCOS_OSS-4322) 

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-diagnostics/compare/f612504f524c74f10b48c0e1a2cdb06820529e50...a6a4009d8610f947badf3d93bc4d0874cf50230d
  - [x] Test Results: https://travis-ci.org/dcos/dcos-diagnostics/builds/440056367
  - [x] Code Coverage (if available): https://codecov.io/gh/dcos/dcos-diagnostics/compare/cc04232576c777824ef7bb6bd8d3bc01aba0d602...a6a4009d8610f947badf3d93bc4d0874cf50230d

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by janisz** [comment]
@klueska @philipnrmn @bamarni @branden Can you review this and following PRs:

* [1.12] #3626
* [1.11]  #3627
* [1.10]  #3628

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status
teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-41675

**Pull request merged**
