### PR TITLE
chore(dcos-ui): bump DC/OS UI package to 1.11+v1.12.0

### PR DESCRIPTION
**Pull request by juliangieseke**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

### Bug Fixes

* [DCOS-22215](http://jira.mesosphere.com/browse/DCOS-22215) **DSLInputField:** adjust change event handling ([c227b22](https://github.com/dcos/dcos-ui/commit/c227b22)) 
* [DCOS-21798](http://jira.mesosphere.com/browse/DCOS-21798) **editservicemodal:** render empty modal if the service is not loaded ([bd2d9e9](https://github.com/dcos/dcos-ui/commit/bd2d9e9)) 
* [DCOS-22128](http://jira.mesosphere.com/browse/DCOS-22128) **marathonUtil:** fix parsePod function ([d4373f5](https://github.com/dcos/dcos-ui/commit/d4373f5)) 
* [DCOS-22301](http://jira.mesosphere.com/browse/DCOS-22301) **MesosStateStore:** add linearBackoff retry to the stream ([132279e](https://github.com/dcos/dcos-ui/commit/132279e)) 
* [DCOS-22189](http://jira.mesosphere.com/browse/DCOS-22189) **MesosStateStore:** adjust stream data handling ([f20cf55](https://github.com/dcos/dcos-ui/commit/f20cf55)) 
* [DCOS_OSS-2397](http://jira.mesosphere.com/browse/DCOS_OSS-2397) shows filter default on task page loading ([52041fa](https://github.com/dcos/dcos-ui/commit/52041fa)) 
* [DCOS_OSS-2386](http://jira.mesosphere.com/browse/DCOS_OSS-2386) **MesosStateStore:** adjust stream event sampling ([2b2b0a2](https://github.com/dcos/dcos-ui/commit/2b2b0a2)) 
* [DCOS-22304](http://jira.mesosphere.com/browse/DCOS-22304) **MesosStream:** delay reconnections ([fec41d8](https://github.com/dcos/dcos-ui/commit/fec41d8)) 
* [DCOS-22170](http://jira.mesosphere.com/browse/DCOS-22170) **OverviewDetailTab:** display mesos start and elected time ([ce29e25](https://github.com/dcos/dcos-ui/commit/ce29e25)) 
* [DCOS-20260](http://jira.mesosphere.com/browse/DCOS-20260) **tasknametextfilter:** include id search in task text filter ([#2875](https://github.com/dcos/dcos-ui/issues/2875)) ([d4ac40d](https://github.com/dcos/dcos-ui/commit/d4ac40d)) 
* [DCOS-21989](http://jira.mesosphere.com/browse/DCOS-21989) **UserAccountDropdown:** fix menuItems data type ([683fb84](https://github.com/dcos/dcos-ui/commit/683fb84)) 

### Features

* [DCOS-21614](http://jira.mesosphere.com/browse/DCOS-21614) **EditServiceModal:** show cosmos services in json-schema form ([13ab6be](https://github.com/dcos/dcos-ui/commit/13ab6be))

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by juliangieseke** [comment]
@mesosphere-mergebot bump-ee

**Comment by Poltergeist** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by juliangieseke** [comment]
@mesosphere-mergebot label [Ready for Review]

**Comment by juliangieseke** [comment]
@mesosphere-mergebot label [Ship It]

**Comment by Poltergeist** [comment]
@mesosphere-mergebot label [Ship It]

**Comment by juliangieseke** [comment]
🤔

**Comment by juliangieseke** [comment]
@orlandohohmeier 🙏

**Pull request merged**
