### PR TITLE
Bump mesos-modules to master edc45dc57664ba87d15eef44f35288a4837d3799.

### PR DESCRIPTION
**Pull request by qianzhangxa**
## High-level description

Bump mesos-modules to master edc45dc57664ba87d15eef44f35288a4837d3799.

## Corresponding DC/OS tickets (required)

  - [D2IQ-71789](https://jira.d2iq.com/browse/D2IQ-71789) Mesos module in DC/OS failed to build

### CODE REVIEW

**Comment by qianzhangxa** [comment]
@mesosphere-mergebot test all

**Review by asekretenko — APPROVED** [review]

**Comment by qianzhangxa** [comment]
@mesosphere-mergebot changelog-not-required internal

**Comment by qianzhangxa** [comment]
@mesosphere-mergebot test teamcity/dcos/test/terraform/aws/onprem/static/group3

**Comment by qianzhangxa** [comment]
@mesosphere-mergebot label Ready For Review

**Review by asekretenko — APPROVED** [review]

**Pull request merged**
