### PR TITLE
Train 295

### PR DESCRIPTION
**Pull request by margaret**
# 🚂:two::nine::five::train::sparkles::snowflake: (master)

https://github.com/dcos/dcos/pull/2210 – **bump dcos-test-utils**

### CODE REVIEW

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
onprem/static failure I think is https://jira.mesosphere.com/browse/DCOS-19542 `test_vip failed with RetryError on MarathonApp.wait`. The signature in the jira description is different (does not mention pods) but the failure happens when waiting for the app to come up.

**Comment by margaret** [comment]
azure/arm failure is multiple failures of test_networking.test_vip I thought that it should be assigned to this one https://jira.mesosphere.com/browse/DCOS_OSS-1463 , however the ticket is closed. I think we might have to reopen it.

**Comment by margaret** [comment]
test_mesos_task_state_remains_consistent failed in the upgrade test. There was a ticket for it here https://jira.mesosphere.com/browse/DCOS-17633 which looks like it's about to be closed

**Comment by margaret** [comment]
@mesosphere-mergebot label ready for review

**Comment by adam-mesos** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static DCOS-19542

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/upgrade  https://jira.mesosphere.com/browse/DCOS-17633

**Comment by adam-mesos** [comment]
Looks like the teamcity/dcos/test/azure/arm failures could also be attributed to DCOS-19542

**Comment by adam-mesos** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-19542

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by mesosphere-teamcity** [comment]
Corresponding DC/OS PR: https://github.com/dcos/dcos/pull/2437

**Pull request merged**
