### PR TITLE
Winpanda App: Fix Package Shared Config Dir Auto-Cleanup On Package S…

### PR DESCRIPTION
**Pull request by anatolii-borysov**
…etup

1) fix logic of processing package configuration sources during package setup
2) improve error reporting

JIRA: DCOS_OSS-5758 - Missing Config Files for dcos-diagnostics and telegraf Packages

### CODE REVIEW

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot changelog-not-required Part of overall Windows changes

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @jongiddy

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by DominikDary** [comment]
@mesosphere-mergebot bump-ee

**Comment by anatolii-borysov** [comment]
@jongiddy I supose we should plan a separate discussuion to make decisions on the **"winpanda upgrade"** command, implementing DC/OS upgrade procedure. DC/OS 4 Windows Beta scope assumes implementing only the **"winpanda setup"** (clean DC/OS setup) and the **"winpanda start"** (start Windows services that are already set up) commands. When we figure out all the requirements to the DC/OS upgrade procedure we can proceed to developing feature design and agree on every impementation detail.

**Pull request merged**
