### PR TITLE
[master] Mergebot Automated Train PR - 2018-Jul-12-12-04

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3050 - Add ExecStartPre step on Mesos agents for resource provider config dir
* #3063 - Change Adminrouter access_log logging facility to daemon

### CODE REVIEW

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by orsenthil** [comment]
@jieyu  - We can merge this as soon as the status checks turn green.

**Comment by urbanserj** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
