### PR TITLE
[master] Bump Mesos to nightly master d4b000f

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
FILL IN

### CODE REVIEW

**Comment by mesosphere-teamcity** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by mesosphere-teamcity** [comment]
Corresponding EE PR: https://github.com/mesosphere/dcos-enterprise/pull/2258

**Comment by mesosphere-teamcity** [comment]
Closing PR in lieu of #2451

**Comment by mesosphere-teamcity** [comment]
Closing PR in lieu of #2439

**Comment by mesosphere-teamcity** [comment]
Closing PR in lieu of #2439

**Comment by greggomann** [comment]
Description can be found in the corresponding EE PR.

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS_OSS-2115

**Comment by mesosphere-teamcity** [comment]
Closing PR in lieu of #2472

**Comment by mesosphere-teamcity** [comment]
Closing PR in lieu of #2476

**Comment by mesosphere-teamcity** [comment]
Closing PR in lieu of #2475

**Pull request closed without merging**
