### PR TITLE
Bump 1.10 to 1.10.7

### PR DESCRIPTION
**Pull request by bstavroulakis**
## Corresponding DC/OS tickets (obligatory)

DCOS-34561: flatten the service tree to avoid extra lookups
DCOS-37420: adjust Framework struct to improve performance
DCOS-37422: adjust flagSDKTask to improve performance
DCOS-37423: improve performance of composite store nodes list getter
DCOS-35759: throttle mesos state fetching
DCOS-37421: Adjust GetSetBaseStore to stop dispatching events on every change
DCOS-35757: remove 2 seconds timeout
DCOS-22400,DCOS-22404: update login and user for privacy policy

## Checklist for all PRs

  - [X] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [X] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/job/frontend/job/deprecated/job/dcos-ui-pull-requests/3190/testReport/)
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot override-status  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot label [Ready For Review |Holding |Request For Comment |Ship It |Work In Progress] 
@mesosphere-mergebot bump-ee  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by bstavroulakis** [comment]
@mesosphere-mergebot bump-ee

**Comment by nLight** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by nLight** [comment]
@mesosphere-mergebot please?

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orlandohohmeier** [comment]
This PR addresses the following issues (see PR description) and should be include 1.10.7:

[DCOS-34561](https://jira.mesosphere.com/browse/DCOS-34561): flatten the service tree to avoid extra lookups
[DCOS-37420](https://jira.mesosphere.com/browse/DCOS-37420): adjust Framework struct to improve performance
[DCOS-37422](https://jira.mesosphere.com/browse/DCOS-37422): adjust flagSDKTask to improve performance
[DCOS-37423](https://jira.mesosphere.com/browse/DCOS-37423): improve performance of composite store nodes list getter
[DCOS-35759](https://jira.mesosphere.com/browse/DCOS-35759): throttle mesos state fetching
[DCOS-37421](https://jira.mesosphere.com/browse/DCOS-37421): Adjust GetSetBaseStore to stop dispatching events on every change
[DCOS-35757](https://jira.mesosphere.com/browse/DCOS-35757): remove 2 seconds timeout
[DCOS-22400](https://jira.mesosphere.com/browse/DCOS-22400), [DCOS-22404](https://jira.mesosphere.com/browse/DCOS-22404): update login and user for privacy policy

**Comment by orsenthil** [comment]
@orlandohohmeier  - please open a separate PR against 1.10.7. - We to explicitly state that this is UI only change and does not require soak testing, and get the approval from chandler.

**Pull request merged**
