### PR TITLE
Bump version to 1.9.3

### PR DESCRIPTION
**Pull request by adam-mesos**
## High Level Description

Bumps version from 1.9.2 to 1.9.3!

Tracked via https://jira.mesosphere.com/browse/DCOS_OSS-1530

### CODE REVIEW

**Comment by adam-mesos** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
`TestUpgrade.test_mesos_task_state_remains_consistent` failed. Re-running.
Tracked via https://jira.mesosphere.com/browse/DCOS-17633

**Comment by jgehrcke** [comment]
`mergebot/enterprise/build-status/aggregate` failed because a small subset of its tests failed as of a known service outage, tracked via DCOS-17704.

**Comment by jgehrcke** [comment]
`integration-test/upgrade-onprem` failed again. Rerunning.

**Comment by jgehrcke** [comment]
The upgrade test https://jira.mesosphere.com/browse/DCOS_OSS-1503

**Comment by jgehrcke** [comment]
If the `integration-test/upgrade-onprem` test needs special treatment as of the version number then it seems someone with the corresponding knowledge needs to apply that.

**Comment by amitaekbote** [comment]
upgrade test passed! looks like it was a parameter issue, thanks @mellenburg for pointing that out

**Comment by jgehrcke** [comment]
> upgrade test passed! looks like it was a parameter issue, thanks @mellenburg for pointing that out

Thank you! :-) Would you mind documenting the solution for this in https://jira.mesosphere.com/browse/DCOS_OSS-1503 (or in a better place, if you know one)?

**Pull request merged**
