### PR TITLE
DCOS 1.9 - Train 287

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

* Mesos: Increase min libprocess worker threads to 16. [1.9]  #2161 
* [1.9] Bump navstar  #2174
* Add JIRA ids to owners.json  #2188 
* bump to metronome 0.3.1 on DCOS 1.9  #2201

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@lingmann / @mellenburg / @jgehrcke / @vespian  - Please help with overriding `teamcity/dcos/test/upgrade` https://jira.mesosphere.com/browse/DCOS-19208

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by adam-mesos** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/upgrade DCOS-19208

**Comment by adam-mesos** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
