### PR TITLE
Train 198

### PR DESCRIPTION
**Pull request by jgehrcke**
This merge train contains:
- https://github.com/dcos/dcos/pull/1778 (Bump navstar)

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
`integration-test/azure` has one test failure: `test_networking.test_l4lb`

That is either a regression or a flake (the latter is tracked via https://jira.mesosphere.com/browse/DCOS-14948)

**Comment by orsenthil** [comment]
For a single PR train, we could simply merge it.

**Comment by jgehrcke** [comment]
> For a single PR train, we could simply merge it.

Yeah, first I thought more is ready and when I realized it isn't I thought: well, then why not test interaction with downstream changes in proper 'train pair'. I'll take the simpler route next time :).

**Pull request merged**
