### PR TITLE
[master] Mergebot Automated Train PR - 2018-Apr-06-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2366 - Add CHANGES.md with empty 1.12.0 changelog 
* #2703 - Metronome bump 0.5.0 on Master

### CODE REVIEW

**Comment by orsenthil** [comment]
Here is a problem with mergebot (https://jira.mesosphere.com/browse/QUALITY-2017). 
I am going to close the other PRs and create the EE train by hand.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Extended Tests Triggered (in Queue) - https://teamcity.mesosphere.io/viewQueued.html?itemId=1029237

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2310

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status 
teamcity/dcos/test/docker https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2310

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
