### PR TITLE
[master] Mergebot Automated Train PR - 2019-Jul-05-18-16

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #5726 - Server certificate verification for Mesos components.

### CODE REVIEW

**Comment by tillt** [comment]
@mesosphere-mergebot sync

**Comment by tillt** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/strict/group/3 https://jira.mesosphere.com/browse/DCOS-56126

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group3  DCOS-56126

**Comment by tillt** [comment]
@mesosphere-mergebot sync

**Pull request merged**
