### PR TITLE
Update owners.json

### PR DESCRIPTION
**Pull request by cprovencher**
## High-level description

Adding a dcos-owner for helping with the train process
Removing members no longer at Mesosphere

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@cprovencher If you don't mind, could you please add me to this list. I am added in master and 1.11. .

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@GoelDeepak OK

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot Ready For Review

**Comment by cprovencher** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
Applying ship-it label since it is an owners file change, and has the required approvals.

**Pull request merged**
