### PR TITLE
pkgpanda-api: don't use systemd socket

### PR DESCRIPTION
**Pull request by gpaul**
## High Level Description

The `dcos-pkgpanda-api` service runs as a gunicorn web server. This service listens on a unix socket `/run/dcos/pkgpanda-api.sock`. This socket used to be managed by systemd as the `dcos-pkgpanda-api.socket` unit. However, gunicorn removes the socket file when it exits and creates it on start if it doesn't already exist. In short, it is not intended for use with systemd managed sockets.

This PR removes the systemd socket unit and relies on gunicorn's command-line flags to correctly set the permissions and ownership of its socket file.

This fixes an issue where upgrading a master from 1.8.8 to 1.9.0 would sometimes require a manual `systemctl restart dcos-pkgpanda-api.socket` as a final step so the `dcos-pkgpanda-api` service could start.

## Related Issues

  - [DCOS-14644](https://jira.mesosphere.com/browse/DCOS-14644) DC/OS 1.8.8 -> 1.9.0-rc3 DC/OS Component Package Manager (Pkgpanda) (Unhealthy)

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: This is seen during upgrade. Three nodes were upgraded to this PR and it worked every time.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___

### CODE REVIEW

**Comment by gpaul** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
@branden @orsenthil PTAL

**Comment by gpaul** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by gpaul** [comment]
@branden I think so, yes

**Pull request merged**
