### PR TITLE
Include task metadata with task logs sent to Fluent Bit

### PR DESCRIPTION
**Pull request by branden**
## High-level description

This bumps mesos-modules to include https://github.com/dcos/dcos-mesos-modules/pull/109.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-53834](https://jira.mesosphere.com/browse/DCOS-53834) Integrate Mesos task log module fix with DC/OS

## Related tickets (optional)

Other tickets related to this change:

N/A

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: This fix will be backported to 1.13, so no changelog entry necessary.
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Fluent Bit doesn't output logs by default, so we can't cover this with an integration test. Instead I tested manually that task logs are emitted to an Elasticsearch cluster with the correct metadata.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-mesos-modules/compare/2633cb7135c978f640d08819f2408c541d6dedb2...2b74cd36d99d6540959b715dad0a942509570a4b
  - [x] Test Results: [link to CI job test results for component](https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/modules/job/DCOS_Mesos_Modules-nightly/906/)
  - [x] Code Coverage (if available): N/A

### CODE REVIEW

**Comment by greggomann** [comment]
Looks like this PR still points to Joseph's personal branch - @branden could you update to point to modules master?

**Comment by branden** [comment]
@greggoman dcos/dcos master currently points to dcos-mesos-modules's 1.13 branch. I'll push a commit pointing it to master, but LMK if that isn't OK to do with this PR. I'm not sure if there's something on master we might not want to pull in.

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by branden** [comment]
@kaysoky @greggomann This PR is ready for your review.

**Pull request merged**
