### PR TITLE
Bumped the Mesos modules package to include bug fixes.

### PR DESCRIPTION
**Pull request by greggomann**
## High-level description

This package bump incorporates changes which avoid excessive error logging from the metrics Mesos isolator module.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-4152](https://jira.mesosphere.com/browse/DCOS_OSS-4152) Metrics isolator module incorrectly attempts to DELETE check containers

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: This affects error logging from the metrics isolator and includes a couple other bug fixes for Mesos modules. It does not affect external interfaces.
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: This includes a test for the modified metrics isolator behavior.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [mesos-modules diff](https://github.com/dcos/dcos-mesos-modules/compare/29561f11a12372752b77839be73418d1d75abe63...545c3ff25e8bf5dcff166b83ee419584db22a5c4)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Hi @greggomann  - The bump-ee not working is due to this - https://jira.mesosphere.com/browse/DCOS-42235 (I am on it).

**Comment by greggomann** [comment]
@mesosphere-mergebot bump-ee

**Comment by rukletsov** [comment]
This has landed as part of https://github.com/dcos/dcos/pull/3477. Closing.

**Pull request closed without merging**
