### PR TITLE
[master] Automated Bump DC/OS UI v5.2.1

### PR DESCRIPTION
**Pull request by pierrebeitz**
* closes [COPS-4665](https://jira.d2iq.com/browse/COPS-4665)
* closes [D2IQ-57756](https://jira.d2iq.com/browse/D2IQ-57756)

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot backport 2.1 2.0 1.13

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by AliakseiKhomchanka** [comment]
I've removed the word "Automated" from the PR name, Mergebot's parser glitched because of that word for some reason and can't create a train.

**Comment by AliakseiKhomchanka** [comment]
Never mind, didn't help, returning the original name.

**Review by jongiddy — APPROVED** [review]

**Pull request merged**
