### PR TITLE
Fix some things I noticed in a cluster startup

### PR DESCRIPTION
**Pull request by cmaloney**
- Make Mesos-DNS wait for spartan
 - Teach metronome to wait for leader.mesos (marathon does already)
 - Teach cosmos to wait for leader.mesos

cc: @sargun @aquamatthias @BenWhitehead

### CODE REVIEW

**Comment by sargun** [comment]
Should Mesos-DNS wait for Spartan? Pretty sure the two are unrelated.

**Comment by cmaloney** [comment]
@sargun without it you get a whole lot of:
```
Sep 06 04:29:21 ip-10-0-4-168.us-west-2.compute.internal systemd[1]: Started Mesos DNS: DNS based Service Discovery.
Sep 06 04:29:21 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:21 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:21 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:21 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:21 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:21 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:21 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:21 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:22 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:22 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:22 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:22 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:22 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:22 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:22 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:22 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:22 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:22 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:23 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:23 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:23 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:23 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:23 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:23 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:23 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:23 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:23 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:23 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:24 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:24 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:24 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:24 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:24 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:24 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:24 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:24 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:24 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:24 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:25 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:25 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:25 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:25 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:25 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:25 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:25 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:25 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:25 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:25 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:26 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:26 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:26 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:26 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:26 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:26 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:26 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:26 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:26 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:26 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:27 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:27 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:27 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:27 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:27 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:27 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:27 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:27 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:27 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:27 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:29 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:29 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:29 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:29 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:29 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:29 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:29 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:29 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:29 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:29 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:30 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:30 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
Sep 06 04:29:30 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:30 Failed to connect to zk-5.zk:2181: dial tcp: lookup zk-5.zk: no such host
Sep 06 04:29:30 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:30 Failed to connect to zk-3.zk:2181: dial tcp: lookup zk-3.zk: no such host
Sep 06 04:29:30 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:30 Failed to connect to zk-4.zk:2181: dial tcp: lookup zk-4.zk: no such host
Sep 06 04:29:30 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:30 Failed to connect to zk-2.zk:2181: dial tcp: lookup zk-2.zk: no such host
Sep 06 04:29:31 ip-10-0-4-168.us-west-2.compute.internal mesos-dns[1575]: 2016/09/06 04:29:31 Failed to connect to zk-1.zk:2181: dial tcp: lookup zk-1.zk: no such host
```

**Comment by BenWhitehead** [comment]
The cosmos change looks okay to me.

**Comment by cmaloney** [comment]
:ship: in the next train

**Pull request merged**
