### PR TITLE
Train 304

### PR DESCRIPTION
**Pull request by margaret**
# 🚂:three::zero::four::train: (master)

* #2267 fix cloud_images CI yum error

### CODE REVIEW

**Comment by margaret** [comment]
@mesosphere-mergebot bump-ee

**Comment by margaret** [comment]
`docker/smoke` failure was a flake with the oinker integration test https://jira.mesosphere.com/browse/DCOS_OSS-1681

**Comment by lingmann** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/docker/smoke https://jira.mesosphere.com/browse/DCOS_OSS-1681

**Comment by margaret** [comment]
Needs override: azure/arm failure is https://jira.mesosphere.com/browse/DCOS-19542

**Comment by mellenburg** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-19542

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
