### PR TITLE
[1.12] Bump dcos-net

### PR DESCRIPTION
**Pull request by urbanserj**
## High-level description

Bump dcos-net.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-3855](https://jira.mesosphere.com/browse/DCOS_OSS-3855) Restart dcos-net causing traffic break
  - [DCOS_OSS-4110](https://jira.mesosphere.com/browse/DCOS_OSS-4110) Incorrect DNS name in vips endpoint
  - [DCOS_OSS-4146](https://jira.mesosphere.com/browse/DCOS_OSS-4146) Improve logging in dcos-overlay [step 2]
  - [DCOS_OSS-4308](https://jira.mesosphere.com/browse/DCOS_OSS-4308) dcos-dns uses container name instead of service ID for the record on PODs

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: minor improvements
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]
https://github.com/dcos/dcos-net/compare/e78ab07e5d3f03239b23c24402b38e6ae917ff97...d8dd43289b5626b8df30639e20bcefc4c0c437fa
https://github.com/dcos/dcos-net/pull/81
https://github.com/dcos/dcos-net/pull/82
https://github.com/dcos/dcos-net/pull/83
https://github.com/dcos/dcos-net/pull/85
https://github.com/dcos/dcos-net/pull/86
https://github.com/dcos/dcos-net/pull/88
https://github.com/dcos/dcos-net/pull/89
https://github.com/dcos/dcos-net/pull/90
https://github.com/dcos/dcos-net/pull/91
https://github.com/mesosphere/gen_netlink/pull/19
https://circleci.com/gh/dcos/dcos-net/696
https://codecov.io/github/dcos/dcos-net/commit/d8dd43289b5626b8df30639e20bcefc4c0c437fa

___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-41677

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS-41677

**Comment by urbanserj** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
