### PR TITLE
Add cluster ID to diagnostics bundle for 1.10

### PR DESCRIPTION
**Pull request by surdy**
## High Level Description

https://github.com/dcos/dcos/pull/1806 did not get merged into master before 1.10 was cut. Hence this PR

## Related Issues

Edit(JP): https://jira.mesosphere.com/browse/DCOS_OSS-1627

## Checklist for all PR's

  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___

@darkonie @jgehrcke  Please review

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
The following PR applies the same change against the master branch:
https://github.com/dcos/dcos/pull/1970

**Comment by gpaul** [comment]
I approved this PR but that has no effect, likely because my review wasn't requested.

**Comment by gpaul** [comment]
The EE bump failed it's tests.

**Comment by gpaul** [comment]
The EE bump failed as of the changes this PR makes to `dcos-config.yaml` being necessary in the EE bump, too.

**Comment by gpaul** [comment]
Let's not merge this until upstream CI is green. We'd end up in an awkward spot where all PRs fail.

**Pull request merged**
