### PR TITLE
Add JIRA ids to owners.json

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

This will be used with mergebot override feature.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

https://jira.mesosphere.com/browse/DCOS-19647

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@jgehrcke  / @vespian  - could you please help with overriding the `teamcity/dcos/test/azure/arm ` failure with https://jira.mesosphere.com/browse/DCOS_OSS-1830

**Comment by lingmann** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS_OSS-1830

**Pull request merged**
