### PR TITLE
Remove Storing artifacts in Azure Cloud.

### PR DESCRIPTION
**Pull request by orsenthil**
## Corresponding DC/OS tickets (required)

  -https://jira.d2iq.com/browse/D2IQ-71632 indicates the credentials of Azure have changed.

I also realized that we don't use Azure URLs for releases.   So, we either fix with updated credentials or if this PR succeeds we can remove storing of artifacts in the azure cloud.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot test  all

**Comment by orsenthil** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by DominikDary** [comment]
> I also realized that we don't use Azure URLs for releases. So, we either fix with updated credentials or if this PR succeeds we can remove storing of artifacts in the azure cloud.

I'm also not aware of azure being used anymore after windows support has been dropped.

**Comment by cprovencher** [comment]
@mesosphere-mergebot backport

**Review by cgawron1 — APPROVED** [review]

**Comment by orsenthil** [comment]
@mesosphere-mergebot test-all

**Comment by orsenthil** [comment]
@mesosphere-mergebot test

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
The Jenkins Failure needs to be investigated - https://jenkins.mesosphere.com/service/jenkins/job/public-security/job/dcos-open-adminrouter/job/PR-7613/7/display/redirect and overriden with a JIRA.

**Comment by janisz** [comment]
@mesosphere-mergebot backport 1.13

**Pull request merged**
