### PR TITLE
1.12 train 11/06/2018

### PR DESCRIPTION
**Pull request by cprovencher**
#3727 Update dcos-test-utils
#3709 (1.12) Improve reliability of metrics tests
#3702 (1.12) Fix Telegraf dcos_statsd plugin race condition
#3698 [1.12] Bump Mesos to nightly 1.7.x cb07b69
#3695 Add fetch_cluster_logs.bash
#3682 [1.12] packages/java: Update to 8u192
#3631 [1.12] Mesos: logged request processing time.
#3626 [1.12] Update dcos-diagnostics
#3577 [1.12] Do not pull overlay data when overlay is disable

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot bump-ee

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status https://jira.mesosphere.com/browse/DCOS_OSS-4342 teamcity/dcos/test/aws/onprem/static

**Comment by gauripowale** [comment]
@mesosphere-mergebot override-status https://jira.mesosphere.com/browse/DCOS_OSS-4342 teamcity/dcos/test/aws/onprem/static

**Comment by gauripowale** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-4342

**Comment by cprovencher** [comment]
@mesosphere-mergebot label ship it

**Comment by cprovencher** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
