### PR TITLE
chore(dcos-installer-ui): fix error when installing npm modules

### PR DESCRIPTION
**Pull request by ahoskins**
## High-level description

Update the dcos-installer-ui to fix an issue with installing it's deps.

## Corresponding DC/OS tickets (obligatory)

None

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by ahoskins** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahoskins** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orlandohohmeier** [comment]
There seems to be an issue with our test suite. I've ran the test locally to verify and all test fail with the following runtime error:
 
```FAIL  src/js/plugin-bridge/__tests__/PluginSDK-test.js 
● Runtime Error
Error: Failed to get mock metadata: /Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/core-js/library/modules/$.global.js
    at Loader._generateMock (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:251:15)
    at Loader.requireMock (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:677:45)
    at Loader.requireModuleOrMock (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:788:19)
    at Object.eval (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/core-js/library/modules/$.export.js:1:137)
    at Loader._execModule (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:206:17)
    at Loader.requireModule (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:760:14)
    at Loader._generateMock (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:243:34)
    at Loader.requireMock (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:677:45)
    at Loader.requireModuleOrMock (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:788:19)
    at Object.eval (/Users/orlandohohmeier/Workspace/dcos-installer-ui/node_modules/core-js/library/modules/es6.object.assign.js:2:15)```

**Comment by orsenthil** [comment]
@ahoskins  -  The `teamcity/dcos/build/dcos ` failure needs to be addressed before this can be considered ready for review.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label work in progress

**Comment by ahoskins** [comment]
@orsenthil yes, we're going to hold on this until we can confirm how important the installer is, and if worth spending time maintaining.

**Comment by nLight** [comment]
@orlandohohmeier any news on this installer situation?

**Comment by orlandohohmeier** [comment]
@nLight I'd argue that we can close this one.

**Comment by orsenthil** [comment]
Closing this PR. Please bring in against the latest changes if the issue with ui installer is not yet addressed.

**Pull request closed without merging**
