### PR TITLE
Update cosmos to version 0.2.0-SNAPSHOT-70-refs_heads_master-4e0578df82

### PR DESCRIPTION
**Pull request by BenWhitehead**

### CODE REVIEW

**Comment by BenWhitehead** [comment]
@spahl can this be merged tomorrow? There is a fix to an api regression in this new snapshot.

**Comment by spahl** [comment]
:ship: why wait:-)

**Comment by BenWhitehead** [comment]
because it might break the CLI release. is it possible to unmerge and then remerge tomorrow?

**Comment by BenWhitehead** [comment]
actually it looks like the CLI release already took place.

**Comment by spahl** [comment]
The 0.4.8 CLI has been released before I merged

**Pull request merged**
