### PR TITLE
Add timestamp for dmesg, distro version, timedatectl and systemd unit status to diag bundle

### PR DESCRIPTION
**Pull request by surdy**
This is only for 1.12 OSS I will backport and do a PR for EE after this gets approved

## High-level description
Get following additional things in a diag bundle 
1) Have dmesg with human readable timestamp
2) `timedatectl` for ruling out time sync issues 
3) Get distro version to rule out untested distro bugs
4) Get DC/OS systemd unit status
5) /v2/pods marathon endpoint
 
What features does this change enable? What bugs does this change fix?
Reduced back and forth while debugging cluster issues since more data is collected in the bundle

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-3861](https://jira.mesosphere.com/browse/DCOS_OSS-3861) Add more diagnostics data(e.g. timestamp for dmesg, distro version, systemd unit status etc) into the bundle

## Checklist for all PRs

  - [X] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by surdy** [comment]
CC @ashahan

**Comment by surdy** [comment]
@mesosphere-mergebot label Work In Progress

**Comment by surdy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by surdy** [comment]
@branden @philipnrmn Please review

I added you guys at random. Please let me know if I should add someone else for reviewing this

**Comment by philipnrmn** [comment]
@surdy the code looks good, but I think you'll need to do a bump-ee to get all the tests green.

**Comment by surdy** [comment]
@mesosphere-mergebot bump-ee

**Comment by surdy** [comment]
Thanks @janisz I was just waiting for changes to be finalized on OSS before sending PR for EE. Now I have it here https://github.com/mesosphere/dcos-enterprise/pull/3179

**Comment by surdy** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@surdy Tests are failing

**Comment by surdy** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by janisz** [comment]
@orsenthil Can we get this merged?

**Comment by gpaul** [comment]
> Have dmesg with human readable timestamp
:sob: so beautiful!
> timedatectl for ruling out time sync issues
> Get distro version to rule out untested distro bugs
> Get DC/OS systemd unit status
> /v2/pods marathon endpoint
w000t!

**Comment by surdy** [comment]
@philipnrmn @gpaul if you have a moment to put a review approval on this. I can try to bug @orsenthil to find a way to get this merged

**Comment by janisz** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Pull request merged**
