### PR TITLE
Bumping marathon to 1.7.111

### PR DESCRIPTION
**Pull request by wavesoft**
## High-level description

Improved marathon defaults, and optimised the user experience.

## Corresponding DC/OS tickets (obligatory)

* [DCOS-39290](https://jira.mesosphere.com/browse/DCOS-39290) - Bump Marathon's max_instances_per_offer, task_launch_confirm_timeout, task_launch_timeout, and task_reservation_timeout
* [DCOS-37999](https://jira.mesosphere.com/browse/DCOS-37999) - Loosen constraint validation during migration
* [DCOS_OSS-4007](https://jira.mesosphere.com/browse/DCOS_OSS-4007) - dcos-launch missing docker dependency

## Related tickets (optional)

* [MARATHON-8394](https://jira.mesosphere.com/browse/MARATHON-8394) - Benchmark Feature Branch
* [MARATHON-8326](https://jira.mesosphere.com/browse/MARATHON-8326) - Add "wipe=true" support for pod's instances endpoint, as it is implemented for app's tasks
* [MARATHON-8381](https://jira.mesosphere.com/browse/MARATHON-8381) - Use Different Exit Code for Marathon Suicide
* [MARATHON-7969](https://jira.mesosphere.com/browse/MARATHON-7969) - Applications created via PUT do not receive a default portDefinitions value
* [MARATHON-8314](https://jira.mesosphere.com/browse/MARATHON-8314) - Better document the dangers of canceling deployments
* [MARATHON-8381](https://jira.mesosphere.com/browse/MARATHON-8381) - Use Different Exit Code for Marathon Suicide
* [MARATHON-8386](https://jira.mesosphere.com/browse/MARATHON-8386) - Move Clients from dcos to shakedown.clients
* [MARATHON-8380](https://jira.mesosphere.com/browse/MARATHON-8380) - SI `test_app_update_rollback` is flaky
* [MARATHON-8384](https://jira.mesosphere.com/browse/MARATHON-8384) - Import the CLI Python Code
* [MARATHON-8049](https://jira.mesosphere.com/browse/MARATHON-8049) - UnreachableStrategy Has Inconsistent JSON validation

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated : [Git Diff Changelog](https://github.com/mesosphere/marathon/compare/ec85cdca7...faead2763)
  - [X] Test Results: [Link to Jenkins](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/1024)
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by wavesoft** [comment]
@mesosphere-mergebot bump-ee

**Comment by wavesoft** [comment]
@mesosphere-mergebot Label Ready for Review

**Comment by kensipe** [comment]
Azure failure due to https://jira.mesosphere.com/browse/DCOS-41324

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status 
teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-41324

**Pull request merged**
