### PR TITLE
[1.11] Prevent dcos-history leaking auth tokens 

### PR DESCRIPTION
**Pull request by philipnrmn**
## High-level description

dcos-history used a common method for creating the headers used to make
requests to mesos (which could have an Authorization header set with a token)
and making responses to the client.

This led to the auth token being leaked in the header.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-40373](https://jira.mesosphere.com/browse/DCOS-40373) History service returns its auth token in the header

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by philipnrmn** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by philipnrmn** [comment]
See https://github.com/dcos/dcos/pull/3257/comment#issuecomment-412121620 re CI

**Comment by philipnrmn** [comment]
@mesosphere-mergebot bump-ee

**Comment by philipnrmn** [comment]
@mesosphere-mergebot bump-ee

**Comment by philipnrmn** [comment]
@branden mind reviewing this PR?

**Comment by philipnrmn** [comment]
@mesosphere-mergebot label ship it

**Comment by jgehrcke** [comment]
> @mesosphere-mergebot label ship it

Let's submit a JIRA ticket and send it to the cluster ops team if Mergebot is not doing the expected thing :)

CC @gpaul

**Comment by orsenthil** [comment]
> Let's submit a JIRA ticket and send it to the cluster ops team if Mergebot is not doing the expected thing :)

@philipnrmn  - Would you like to be in owners file? That will allow you to apply "ship-it" for others PR. :)

**Pull request merged**
