### PR TITLE
[1.11] Mergebot Automated Train PR - 2018-Aug-22-11-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3302 - [1.11] Bump Martahon's task_launch_confirm and task_reservation timeouts
* #3315 - Bump metronome to 0.4.4

### CODE REVIEW

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS-40767

**Comment by orsenthil** [comment]
I am going go merge this, and bump-ee so that we can fix the owners.json problem post-merge (https://jira.mesosphere.com/browse/DCOS-40767)

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
