### PR TITLE
Train 298 (master)

### PR DESCRIPTION
**Pull request by mellenburg**
#2259 Temporary disable hostname verification for Erlang Distribution Protocol
#2252 metronome 0.3.2 bump for dcos 1.11

### CODE REVIEW

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Comment by mellenburg** [comment]
Failures on train due to failure to *delete*. The tests passed perfectly and as such these will be overridden

**Comment by mellenburg** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2018

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2018

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-2018

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static-redhat https://jira.mesosphere.com/browse/DCOS_OSS-2018

**Comment by jgehrcke** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by jgehrcke** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
