### PR TITLE
Bumped Mesos and mesos-modules to master.

### PR DESCRIPTION
**Pull request by gkleiman**
## High Level Description

Bumps Mesos and mesos-modules to the HEAD of their `master` branches.

## Related Issues

  - [MESOS-8014](https://issues.apache.org/jira/browse/MESOS-8014) Provide HTTP authenticatee interface re/usable for the scheduler library.
  - ...

## Checklist for all PR's

  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: the changes are covered by the Mesos and DC/OS test suite.
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] [mesos-modules changelog](https://github.com/dcos/dcos-mesos-modules/compare/11b2e62489dd3efe98046d06ef9fa43fb51e8d47...9adfabc5d07048f55c3da5a1bad17d2109750f0e)
  - [X] [mesos changelog](https://github.com/apache/mesos/compare/1.4.0...28f8827)
  - [X] [Test Results](https://jenkins.mesosphere.com/service/jenkins/job/mesos/job/Mesos_CI-build/1892/)

### CODE REVIEW

**Comment by gkleiman** [comment]
@mesosphere-mergebot label [Work In Progress]
@mesosphere-mergebot bump-ee

**Comment by bamarni** [comment]
I was looking with @klueska yesterday on how to do this :+1:

**Comment by tillt** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
@adam-mesos I was hoping to get a better "High Level Description" and list of related issues before marking this as ready for review... but I couldn't find any volunteers yet ;-)

**Comment by gkleiman** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
@mesosphere-mergebot bump-ee

**Comment by gkleiman** [comment]
@mesosphere-mergebot bump-ee

**Comment by asridharan** [comment]
@lingmann @orsenthil this one has been pending for a while. It has the approvals but seems like the CI is not picking up the approvals.

**Comment by orsenthil** [comment]
@asridharan - there is only one approval since the last push in EE.

img 

And EE does not have any reviews.

**Pull request merged**
