### PR TITLE
Train 236

### PR DESCRIPTION
**Pull request by falseperfection**
#1992 - Add Mesos work dir config params

### CODE REVIEW

**Comment by falseperfection** [comment]
@mesosphere-mergebot bump-ee

**Comment by falseperfection** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by lingmann** [comment]
`mergebot/enterprise/build-status/aggregate` will not go green, due to known test issue on enterprise side. Adding a manual ship-it.

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
