### PR TITLE
Bump dcos-ui package to 1.11-rc.1

### PR DESCRIPTION
**Pull request by nLight**
## High Level Description

Update the DC/OS UI package to include the latest fixes and improvements.

## Related Issues

 - [DCOS-15709](https://jira.mesosphere.com/browse/DCOS-15709): Introduce Connection Manager
 - [DCOS-17721](https://jira.mesosphere.com/browse/DCOS-17721): Edit configuration settings
 - [DCOS-18055](https://jira.mesosphere.com/browse/DCOS-18055): Improvements for deployment behavior in Catalog
 - [DCOS-18144](https://jira.mesosphere.com/browse/DCOS-18144): SDK Connection Endpoints (Enterprise + OSS): Create actions for SDK Endpoints
 - [DCOS-18199](https://jira.mesosphere.com/browse/DCOS-18199): implement new actions for package edit
 - [DCOS-18200](https://jira.mesosphere.com/browse/DCOS-18200): add support to stores for package edit
 - [DCOS-18357](https://jira.mesosphere.com/browse/DCOS-18357): Implement a separate RecordIO package
 - [DCOS-18694](https://jira.mesosphere.com/browse/DCOS-18694): Pod Endpoints protocol json parser adds 0 to json
 - [DCOS-18788](https://jira.mesosphere.com/browse/DCOS-18788): The JSON editor duplicates and fails to properly parse app definition
 - [DCOS_OSS-1528](https://jira.mesosphere.com/browse/DCOS_OSS-1528): Select version of package to deploy when deploying from the UI
 - [DCOS_OSS-1558](https://jira.mesosphere.com/browse/DCOS_OSS-1558): Select version of package: API call
 - [DCOS_OSS-1559](https://jira.mesosphere.com/browse/DCOS_OSS-1559): Select version of package: Populate store with data from API
 - [DCOS_OSS-1560](https://jira.mesosphere.com/browse/DCOS_OSS-1560): Select version of package: Display versions dropdown

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log: [Change log](https://github.com/dcos/dcos-ui/compare/v1.10.1...v1.11.0-rc.1)
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/688/
  - [x] Code Coverage (if available): https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/688/
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by nLight** [comment]
@mesosphere-mergebot bump-ee

**Comment by nLight** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by nLight** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@orlandohohmeier @MatApple let's add some reviews :)

@mellenburg would you  mind looking into the two currently reported CI failures?

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

Let's get this going again. @orlandohohmeier we _try_ to help pushing PRs like this across the finish line. But you must also push on that front from your side. It's sad to see this sit here for weeks.

**Comment by orlandohohmeier** [comment]
@jgehrcke based on your comment https://github.com/dcos/dcos/pull/1971#issuecomment-333665022 I made sure the UI bump is reviewed and waited for further input form @mellenburg  regarding the unrelated test failures. I'll push harder next time and help ping people if that helps.

**Comment by jgehrcke** [comment]
The current docker/smoke test failure is a known instability, tracked via https://jira.mesosphere.com/browse/DCOS_OSS-1457. Restarted the run.

**Comment by jgehrcke** [comment]
This now has a ship-it label but not all CI checks completed. Anyway, this is good. Leaving the label as-is.

**Comment by jgehrcke** [comment]
This is good to go on the next train. Thanks!

**Pull request merged**
