### PR TITLE
Train 168

### PR DESCRIPTION
**Pull request by vespian**
#1595 Admin Router: Fix /metadata endpoint plus add regression tests
#1593 Admin Router: Logging tunning, fix test-harness resource leaks

EE Train: https://github.com/mesosphere/dcos-enterprise/pull/968

### CODE REVIEW

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by vespian** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by spahl** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
