### PR TITLE
Downgrade DC/OS Net due to discovered bug in recent changes in L4LB

### PR DESCRIPTION
**Pull request by ichernetsky**
## High-level description

Downgrading to stabilize the nightly CI. A proper fix requires further discussion with a teammate who is on PTO right now. The effort is tracked in [DCOS_OSS-5671](https://jira.mesosphere.com/browse/DCOS_OSS-5671)

## Corresponding DC/OS tickets (required)

  - [DCOS-60966](https://jira.mesosphere.com/browse/DCOS-60966) test_ldap_sync tests failing with AssertionError

## Checklist for component/package updates:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): None, downgrading
  - [ ] Included a test which will fail if code is reverted but test is not: None, downgrading
  - [ ] Test Results: None, downgrading
  - [ ] Code Coverage: None, downgrading

### CODE REVIEW

**Comment by ichernetsky** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
Since this is a revert and tests are success, let us merge this directly.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
