### PR TITLE
Pin flake8 version to 3.3.0.

### PR DESCRIPTION
**Pull request by orsenthil**
## High Level Description

* https://jira.mesosphere.com/browse/DCOS_OSS-1477

Pin Flake8 Version to 3.3.0

Corresponding backport PR to 1.9: #1776

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review.

**Comment by lingmann** [comment]
@orsenthil do we need to backport to 1.9 as well?

**Comment by orsenthil** [comment]
@lingmann  - yes. Needs to be backported to 1.8 and 1.9. I will create individual PRs.

**Comment by margaret** [comment]
👍 Looks good. Is there a plugin or something we can use to remind us to bump the version when there's a new release?

**Comment by lingmann** [comment]
thanks @orsenthil, can you link all the backport PR's in the description? that will help us get all the reviews quickly I think.

**Comment by orsenthil** [comment]
Backport PR: https://github.com/dcos/dcos/pull/1776  (Applicable only to 1.9 In 1.8, we did not introduce this test).

**Comment by orsenthil** [comment]
@margaret  - You might need to approve  using Github Approvals Dialog. You will get that when you click on Files Changed Link and follow the Review button.

**Comment by margaret** [comment]
Cool, I didn't know you could access that dialogue on this repo even if you weren't an assigned reviewer 👍

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by lingmann** [comment]
@margaret if you put in your git commit message `DCOS_OSS-1477` it should be linked to the Jira ticket. At least it used to do that... :) And if it's not working that way then #jira-wizards may know more.

**Pull request merged**
