### PR TITLE
[1.12] Mergebot Automated Train PR - 2018-Nov-14-02-38

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3701 - [1.12] Bump dcos-net
* #3740 - Bump cosmos to latest version

### CODE REVIEW

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm https://jira.mesosphere.com/browse/DCOS-40611

**Comment by pcrews** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by pcrews** [comment]
@mesosphere-mergebot merge-it

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
