### PR TITLE
Improve upon initial automated Exhibitor lock-down E2E tests

### PR DESCRIPTION
**Pull request by timaa2k**
## High-level description

This PR adds new-line stripping to the Exhibitor lock-down PSK reading script.
This PR improves upon existing E2E tests for the automated Exhibitor lock-down feature to make it more easily maintainable.

## Corresponding DC/OS tickets (required)

  - [DCOS-57648](https://jira.mesosphere.com/browse/DCOS-57648) Automated Exhibitor lock-down: Clean up E2E tests.

### CODE REVIEW

**Comment by timaa2k** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by timaa2k** [comment]
@mesosphere-mergebot changelog-not-required this only affects tests

**Comment by timaa2k** [comment]
Please run `@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS-57770`
and
`@mesosphere-mergebot override-status teamcity/dcos/test/test-e2e/group1 https://jira.mesosphere.com/browse/DCOS-57231`

**Comment by jongiddy** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group2 https://jira.mesosphere.com/browse/DCOS-57770

**Comment by jongiddy** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/test-e2e/group1 https://jira.mesosphere.com/browse/DCOS-57231

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required Fix to unreleased change

**Comment by timaa2k** [comment]
Thanks @jongiddy Enterprise also needs some love though!

**Pull request merged**
