### PR TITLE
[master] chore(dcos-ui): bump DC/OS UI v2.34.1

### PR DESCRIPTION
**Pull request by juliangieseke**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

* [DCOS_OSS-4270](https://jira.mesosphere.com/browse/DCOS_OSS-4270) Remove "Restart" from the Pods menu
* [DCOS-44138](https://jira.mesosphere.com/browse/DCOS-44138) i18n Mark is imported twice in VirtualNetworkDetail
* [DCOS-43041](https://jira.mesosphere.com/browse/DCOS-43041) Integrate lingui I18nProvider on multiple render mounts
* [DCOS-42394](https://jira.mesosphere.com/browse/DCOS-42394) Fix error message for environment variables
* [DCOS-41578](https://jira.mesosphere.com/browse/DCOS-41578) Black screen transition flash when opening Catalog config 
* [DCOS-41415](https://jira.mesosphere.com/browse/DCOS-41415) DC/OS UI Package: Setup CI to bundle and update the package
* [DCOS-41121](https://jira.mesosphere.com/browse/DCOS-41121) Tooltips in Version cells are misaligned
* [DCOS-41015](https://jira.mesosphere.com/browse/DCOS-41015) Nodes Health missing link
* [DCOS-40781](https://jira.mesosphere.com/browse/DCOS-40781) Catalog Search offers no feedback when nothing is found
* [DCOS-40650](https://jira.mesosphere.com/browse/DCOS-40650) Upload sourcemaps on Release to Sentry
* [DCOS-40644](https://jira.mesosphere.com/browse/DCOS-40644) Fix tooltip for service configuration
* [DCOS-40640](https://jira.mesosphere.com/browse/DCOS-40640) Cache cypress installation to speed up the build
* [DCOS-40635](https://jira.mesosphere.com/browse/DCOS-40635) In Nodes view, whenever there are no nodes, Grid View loads forever
* [DCOS-39800](https://jira.mesosphere.com/browse/DCOS-39800) Show allocated resources on the Nodes Grid view
* [DCOS-35756](https://jira.mesosphere.com/browse/DCOS-35756) Properly fix Headings levels in Config Screens
* [DCOS-21986](https://jira.mesosphere.com/browse/DCOS-21986) Missing method on TaskContainer
* [DCOS-21307](https://jira.mesosphere.com/browse/DCOS-21307) Changing custom VIP port from the form doesn't work
* [DCOS-20222](https://jira.mesosphere.com/browse/DCOS-20222) Invalid Environment variables have no error and are simply ignored

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by juliangieseke** [comment]
@mesosphere-mergebot bump-ee

**Comment by juliangieseke** [comment]
@mesosphere-mergebot label [Ready for Review]

**Comment by juliangieseke** [comment]
@mesosphere-mergebot bump-ee

**Comment by juliangieseke** [comment]
@mesosphere-mergebot bump-ee

**Comment by nLight** [comment]
@orsenthil would you please close this one and it's EE https://github.com/mesosphere/dcos-enterprise/pull/3738? It has been superseded. Thanks!

**Pull request closed without merging**
