### PR TITLE
[master] Mergebot Automated Train PR - 2018-Mar-23-20-26

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #2270 - Fix upgrade script to print errors if checks fail after upgrade
* #2593 - Upgrade REX-Ray to v0.11.2
* #2616 - dcos-integration-test: Fix SAML integration tests
* #2637 - Use pytest-dcos plugin

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
Extended Tests Triggered - https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_ManualTriggers_TriggerTrainBuilds&branch_DcOs_Open_ManualTriggers=pull%2F2667&tab=buildTypeStatusDiv

**Comment by mellenburg** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
