### PR TITLE
Winpanda App: Fix Misprocessing Escape Sequences in JSON

### PR DESCRIPTION
**Pull request by anatolii-borysov**
1) add screening stage to processing JSON-formatted data
   to eliminate improper recognition/handling of escape
   sequences  by the standard JSON-parser
2) add loading package info descriptor to package manifest

JIRA: DCOS_OSS-5622 - Winpanda App: Fix Misprocessing
                      Escape Sequences in JSON

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jongiddy** [comment]
As I understand this problem, `pkgpanda.build` is adding the string `C:\dcos\thing` into the `pkginfo.json` file as the characters `"C:\dcos\thing"` rather than the correct JSON encoding of `"C:\\dcos\\thing"`? This appears to be a bug in `pkgpanda` and should be fixed there, so that this additional code is not required.

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot changelog-not-required

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @jongiddy

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by anatolii-borysov** [comment]
@jongiddy wrote on Fri 11/1/2019 11:05 AM
Ref: https://github.com/dcos/dcos/pull/6468#issuecomment-548716546
> As I understand this problem, `pkgpanda.build` is adding the string `C:\dcos\thing` into the `pkginfo.json` file as the characters `"C:\dcos\thing"` rather than the correct JSON encoding of `"C:\\dcos\\thing"`? This appears to be a bug in `pkgpanda` and should be fixed there, so that this additional code is not required.

I believe that a good application should implement two startegies on processing external input:
**1) "resilience"** - to be able to survive and still accomplish a task being provided with incomplete or malformed data by augmenting it to some reasonable degree in some predefined way (in accordance with applications logic). For eaxample FS path normalization operations (os.path.normcase()/normpath(), encoding URL-incompatible characters (urllib.parse.quote()) or use hardcoded defaults for missed params.
**2) "fail fast"** - to fail immediately when reasonable preprocessing is not going to provide acceptable content anyway. For example when data formatting rules are unrecoverably broken (JSON-formatting) or there is no way to provide any reasonable default vaule for a missed part of critical data.

This fix follows the approach described above and allows not to decline the whole DC/OS build (a whole deployment is obviously to fail, if a single DC/OS package is malformed) and makes the whole system more tolerate to minor discrepancies in config data.

If the considerations above still look unreasonable for you we can decline these changes.

**Comment by jongiddy** [comment]
@anatolii-borysov  This code:
- adds complexity to a simple piece of code, without an actual problem being observed.
- is not obvious as to what it does. I know how JSON is parsed, but I don't know with a quick look at this what non-JSON is permitted.
- appears to break valid JSON. How do I provide a tab character (`\t`) or a newline (`\n`) in a JSON string with this code?
- does not appear to be complete - what if the path component starts with a capital letter (`A-Z`)? Or a `_`?

In this case it is much better to fail the installation rather than guess the correct value. We are parsing code-generated JSON here, not typed user input. DC/OS packages are created using an automated process that should not create malformed contents. If they do, we should fix them, and we want to see the failures so we know to fix them.

So I will decline the changes to JSON parsing, although I expect the simple change to `packages/winpanda/extra/src/winpanda/core/package.py` is still required?

**Comment by anatolii-borysov** [comment]
OK.
Just decline the whole PR then.
I'll add that small change to the packages/winpanda/extra/src/winpanda/core/package.py to load the pkginfo.json along with the next PR, addressing the https://jira.mesosphere.com/browse/DCOS_OSS-5570.

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Holding

**Pull request closed without merging**
