### PR TITLE
Bump Mesos SHA to recent master

### PR DESCRIPTION
**Pull request by adam-mesos**
This Mesos bump includes all the commits in the official Mesos 1.1.0 tag, the fixes for [MESOS-6465](https://issues.apache.org/jira/browse/MESOS-6465) (task_id -> container_id mapping in state.json), as well as "code-complete" for Debugging (I/O switchboard, AttachContainerInput/Output and LNCSession, authz, etc.).

# Component checklist:
 - [X] Change Log from dcos `master`: https://github.com/mesosphere/mesos/compare/dcos-mesos-master-35ce5042...mesosphere:dcos-mesos-master-30d6edb
 - [x] Test Results: https://mesosphere.slack.com/messages/core-ci/ 
    - OSS Mesos: https://teamcity.mesosphere.io/viewLog.html?buildId=502519&tab=report_project134_Results
 - [ ] Code Coverage: N/A, but coverity runs on Apache Mesos regularly

# Highlights from changelog:
```
30d6edb Fixed container-logger subprocess environment setup.
8dcef9c Added Mesos logo to the list of files installed for the web UI.
a567345 Made the IO Switchboard wait for the reader to signal before exiting.
57d986c Used agent environment variables for I/O switchboard.
77b16d8 Added authorization support when attaching to container input/output.
be45c94 Added support for 'ATTACH_CONTAINER_INPUT' call to the io switchboard.
fd142a0 Supported TTY in I/O switchboard.
0e0fc46 Added API handler for LAUNCH_NESTED_CONTAINER_SESSION.
dcf0f1c Added support to handle ATTACH_CONTAINER_OUPUT in the io switchbaord.
19296e0 Added authorization actions for Nested Container and Debug API.
7e472c3 Added the v1 \`ATTACH_CONTAINER_INPUT\` call handler on the agent.
d536a13 Added API handler for ATTACH_CONTAINER_OUTPUT.
9d73fe7 Added a level of indirection for logger through an IO Switchboard.
d4ba90f Added new parameter for user to ContainerLogger's prepare function.
a030970 Added ContainerStatus.container_id to JSON endpoints.
```

# Issues blocked by this:
[DCOS-9722](https://mesosphere.atlassian.net/browse/DCOS-9722) Update UI to use Logging API instead of Files API
[DCOS-11245](https://mesosphere.atlassian.net/browse/DCOS-11245) `dcos task log` should work with logging API & nested containers (pods)
[DCOS-9569](https://mesosphere.atlassian.net/browse/DCOS-9569) Implement the `dcos task exec` command
[DCOS-11251](https://mesosphere.atlassian.net/browse/DCOS-DCOS-11251) OSS Mesos changes for Container Attach/Exec and the entire rest of the Debugging Epic

# Checklist

 - [ ] Included a test which will fail if code is reverted but test is not.
_Tests for enabling new Mesos features are coming in the PRs that enable them. #1042 for rlimit and #1031 for the debugging API_
 - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by adam-mesos** [comment]
@jieyu Should we add `posix/rlimits` to the default DCOS isolators like you did in https://github.com/dcos/dcos/pull/889 , or is this something customers would configure themselves? Should we add a config.yaml flag for it?

**Comment by spahl** [comment]
This should not be a configurable option. We need to be able to add it to the default isolator list.

**Comment by adam-mesos** [comment]
Ok, we'll I've added a comment along those lines to https://mesosphere.atlassian.net/browse/CORE-386 and we'll handle enabling the rlimit isolator in a separate PR so we don't hold up debugging, etc.

**Comment by spahl** [comment]
Thanks, yes it should definitely be a separate PR.

**Comment by adam-mesos** [comment]
Looks like there are two sets of recent changes causing different modules to fail to build:
1. @kaysoky - JournalD fails to compile because ContainerLogger::prepare has a new parameter.
```
d4ba90f Added new parameter for user to ContainerLogger's prepare function.
```
2. @joerg84 `dockercfg/remover.cpp` fails to compile due to Till's recent changes to that hook:
```
3037755 Removed superseded `slavePreLaunchDockerHook` hook.
1fe9876 Removed superseded `slavePreLaunchDockerEnvironmentDecorator` hook.
dadb22b Fixed some nits in hooks interfaces.
8509a6d Added new hook for covering executor and task environment.
```

**Comment by tillt** [comment]
In theory, the DockerCfg module should be unaffected by those changes as it relies on `slavePostFetchHook` - so none of the deprecated callbacks.

**Comment by tillt** [comment]
The problem should be fixed now - I have bumped Mesos again to contain cherry-picked
```
commit a6b40e8223525e0b75b6a442b1bd9c19e20b5aa2
Author: Till Toenshoff <toenshoff@me.com>
Date:   Wed Nov 30 16:35:55 2016 +0100

    Added generated hook proto header to nodist section.
```

This should fix the DockerCfg compilation problem.

**Comment by adam-mesos** [comment]
Bumped to latest Mesos master and updated the PR description.

**Comment by adam-mesos** [comment]
The changes to enable/test debugging have been pulled out into #1031 so that we can land the Mesos bump earlier for logging's sake

**Comment by adam-mesos** [comment]
We are now "feature-complete" for debugging, and this PR is all green. :green_heart:
Ready for Review?
We could merge this as is in the next train to unblock logging/debugging CLI PRs, and we'll certainly be bumping Mesos (and modules) again later for various bug-fixes, but that's no reason to hold up reviewing/merging this PR.
Note that there are module interface changes included in this Mesos bump, so any downstreams may need to update isolator and/or authorization modules when they bump the upstream to include this Mesos bump.

**Comment by adam-mesos** [comment]
Squashed and updated the description. Yes, there really were that many Mesos changes in the past month, and yes this Mesos bump blocks all of the linked issues (CLIs because of `Added ContainerStatus.container_id to JSON endpoints.`).
The tests for enabling these new Mesos features are coming in the PRs that enable them. #1042 for rlimit and #1031 for the debugging API

**Comment by cmaloney** [comment]
This updates a component, needs the component update part of the PR Checklist

**Comment by spahl** [comment]
:ship: 

please get the link for history but this looks good to go

**Comment by adam-mesos** [comment]
Provided a link for #core-ci and the appropriate CI run for Apache Mesos master at SHA `30d6edb` that we're based off of. I submitted a dcos-mesos CI job with the dcos-mesos branch, but it hasn't completed yet. Will update once the CI link is ready, but that shouldn't stop us from shipping this.

**Comment by lingmann** [comment]
@adam-mesos could you explain a bit the [Mesos OSS Test Results](https://teamcity.mesosphere.io/viewLog.html?buildId=502519&tab=report_project134_Results)? There is a quite a bit of red and orange showing.

**Comment by lingmann** [comment]
Thanks for the clarification @adam-mesos Let's continue to work on making the open Mesos CI jobs more useful / representative. That will definitely help as we try and streamline our review process.

**Pull request merged**
