### PR TITLE
marathon: bump to version 1.7.189-48bfd6000

### PR DESCRIPTION
**Pull request by jdef**
## High-level description

* Bump Marathon to 1.7.189
* Cherry-pick of 78257b9fe67124a3d25c5cad4a8604a52cf8d580, which already landed on the 1.12 branch.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [MARATHON-8539](https://jira.mesosphere.com/browse/MARATHON-8539) Marathon drops on recognized fields for volume sources on offer reply

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by jdef** [comment]
@mesosphere-mergebot label ready for review

**Comment by jdef** [comment]
@mesosphere-mergebot bump-ee

**Comment by jdef** [comment]
rebased because the EE PR was complaining about an out-of-date "upstream" reference

**Comment by jdef** [comment]
@mesosphere-mergebot bump-ee

**Comment by jdef** [comment]
group2, group4 failures are related to a bad bump of the universe MoM package. I've already pinged marathon on-call about this.

xref https://github.com/mesosphere/universe/commit/563e61df6138f243daa5db31b5192a7dac93b94f#r31843872

**Comment by orsenthil** [comment]
@jdef - I was wondering why did the previous runs succeed - https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_IntegrationTest_AwsOnpremWStaticBackendGroup4&branch_DcOs_Open_Test_IntegrationTest=pull%2F4053&tab=buildTypeStatusDiv ?

**Comment by orsenthil** [comment]
The marathon universe package bug is claimed to be fixed. I have re-triggered the test suites to verify, and we can merge this as soon as they go green. Thank you!

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
