### PR TITLE
[COPS-4651] Bump client_max_body_size to 4GB in adminrouter config

### PR DESCRIPTION
**Pull request by takirala**
## High-level description

What features does this change enable? What bugs does this change fix?

Increases the limit of max payload of a http request from 1 GB to 4 GB. So far, we have been manually changing this value during MWT and customers were recommended to change this value and restart AR. From 1.13 and above, we can use 4 GB as a more sensible default by looking at https://downloads.mesosphere.com/universe/packages/packages.html Also refer to [DCOS-20269](https://jira.mesosphere.com/browse/DCOS-20269) for some more context

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [COPS-4651](https://jira.mesosphere.com/browse/COPS-4651) 413 Entity Too Large error when trying to add any packages where the .dcos bundled file is over 1 GB

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [x] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: Not a user facing change.
  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: No such tests
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by takirala** [comment]
@DominikDary @jongiddy please suggest if you any thoughts. cc @kaiwalyajoshi @meichstedt

**Comment by kaiwalyajoshi** [comment]
Given that the sizes of [certain packages in package-registry](https://downloads.mesosphere.com/universe/packages/packages.html) exceed 1Gb (particularly datastax-dse) we'll need to bump AR to accomodate or customers will have to perform this surgery manually and this will appear as a gross oversight.

**Comment by jongiddy** [comment]
This change allows all client requests to be 4GB. Although the Package Manager service is designed to handle such large requests, other services have not been, and we don't know the effect of changing the value for them.

At the point where files > 1GB are being passed around, it would be preferable to access the source/target repositories directly, rather than proxying. This is reasonable inside the cluster, where the package registry can exist on a different port to Admin Router, and be exposed to agents. However, for uploading from an external client to the package registry, this creates additional security concerns.

Where do clients get these large packages? If they are downloading them from our universe repo and then uploading into their own cluster, can we look at solutions that download into the cluster directly from the universe repo, setting up proxies as required?

In the meantime, according to http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size the `client_max_body_size` directive can be placed into a `location` stanza. Can we experiment with keeping the `http` level directive at 1G, and increasing just the client upload location to 4G?

**Comment by jgehrcke** [comment]
> Can we experiment with keeping the http level directive at 1G, and increasing just the client upload location to 4G?

I support this.

Would also love for us to add an integration test. There's probably a neat/simple way to set this up.

**Pull request closed without merging**
