### PR TITLE
Bump dcos-test-utils

### PR DESCRIPTION
**Pull request by jeschkies**
## High-level description

This bumps `dcos-test-utils` which should lower the timeout and yield cluster launch issues much faster.

### CODE REVIEW

**Comment by jeschkies** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by jeschkies** [comment]
@mesosphere-mergebot changelog-not-required internal change

**Comment by jeschkies** [comment]
@mesosphere-mergebot changelog-not-required internal

**Comment by janisz** [comment]
@mesosphere-mergebot sync

**Pull request merged**
