### PR TITLE
Revert " Double Free in psutil"

### PR DESCRIPTION
**Pull request by janisz**
Reverts dcos/dcos#6993

https://jira.d2iq.com/browse/D2IQ-65642

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @jongiddy @jeschkies @DominikDary

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required revert on not changeloged change

**Comment by jongiddy** [comment]
Holding, as this change was not the cause of https://jira.d2iq.com/browse/D2IQ-65642

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Holding

**Comment by janisz** [comment]
See @cprovencher comment https://jira.d2iq.com/browse/D2IQ-65642?focusedCommentId=325044&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-325044

Issue was found and fixed.

**Pull request closed without merging**
