### PR TITLE
Train 226

### PR DESCRIPTION
**Pull request by gauripowale**
Train 226 for master. The following PR's are added:
Testing m4 xlarge - https://github.com/dcos/dcos/pull/1931

### CODE REVIEW

**Comment by gauripowale** [comment]
@mesosphere-mergebot bump-ee

**Comment by gauripowale** [comment]
Restarted integration-test/vagrant-bash due to the following error message. Based on slack history, this seems like a very common error for this test:

```[21:00:50][Step 2/3] Vagrant can't use the requested machine because it is locked! This
[21:00:50][Step 2/3] means that another Vagrant process is currently reading or modifying
[21:00:50][Step 2/3] the machine. Please wait for that Vagrant process to end and try
[21:00:50][Step 2/3] again. Details about the machine are shown below:
[21:00:50][Step 2/3] 
[21:00:50][Step 2/3] Name: m3
[21:00:50][Step 2/3] Provider: virtualbox
[21:00:50][Step 2/3] Process exited with code 1 ```

**Comment by gauripowale** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by lingmann** [comment]
Giving this a ship-it. See comments on Enterprise half regarding the issue with `mergebot/enterprise/build-status/aggregate`.

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
