### PR TITLE
Update dcos-test-utils

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

Update dcos-test-utils to the version with modified fixtures to prevent CLI timeouts. This is required to fix problems in Enterprise integration tests.

This enables a backport of DCOS-38213 in order to resolve DCOS-43687. DCOS-13496 is also applied, as it is required by the updated dcos-test-utils.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-43687](https://jira.mesosphere.com/browse/DCOS-43687) DC/OS Enterprise - Test flake retry failing to download CLI.
 - [DCOS-38213](https://jira.mesosphere.com/browse/DCOS-38213) dcoscli fixture times-out while downloading CLI
  - [DCOS-13496](https://jira.mesosphere.com/browse/DCOS-13496) Enforce that paths in test handle leading slash consistently

## Related tickets (optional)

Other tickets related to this change:

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: test framework only
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
test framework only
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [dcos-test-utils](https://github.com/dcos/dcos-test-utils/compare/caf020d4c247bd0286fdfee8f361b7569dd92947...c1608590e010ca08c418f8bd9d9ebd764d511d57)
  - [x] Test Results: [https://teamcity.mesosphere.io/viewLog.html?buildId=1281183&buildTypeId=DcosIo_DcosTestUtils_ToxIntegrationTest]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
Can an owner please run
```
@mesosphere-mergebot override-status teamcity/dcos/test/dcos-docker/static https://jira.mesosphere.com/browse/DCOS-42485
```

**Comment by timaa2k** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/dcos-docker/static https://jira.mesosphere.com/browse/DCOS-42485

**Comment by jongiddy** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by adamtheturtle** [comment]
Thanks @jongiddy ! I've done a few spot checks but please can you confirm that there's nothing new (idea-wise) in this branch, that isn't in e.g. `master`.

**Comment by jongiddy** [comment]
Confirming that changes are purely derived from the master PR's from the quoted issues.

**Pull request merged**
