### PR TITLE
Added linting for DC/OS commits.

### PR DESCRIPTION
**Pull request by lava**
This commits adds a configuration file for the `pre-commit`
git hook lifecycle management framework. It is used to
run various linting checks on all git commits.

In particular, initially we check that all commit messages
start with an uppercase letter, no line exceeds 72 characters,
that all executables have valid shebangs, and that no non-ascii
characters are introduced accidentallu.

To enable pre-commit for this repository, first pre-commit must
be installed

    pip3 install pre-commit

and afterwards the following commands must be run once in the
the root folder of the git repository:

    pre-commit install --install-hooks --hook-type pre-commit
    pre-commit install --install-hooks --hook-type commit-msg

Subsequent changes to the linter configuration will be picked
up automatically.

For more information, visit pre-commit.com

## Corresponding DC/OS tickets (required)

  - [DCOS-5803](https://jira.mesosphere.com/browse/DCOS_OSS-5803) Add linting for DC/OS commits

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by lava** [comment]
@mesosphere-mergebot label "Ready for Review"

**Comment by lava** [comment]
@mesosphere-mergebot changelog-not-required "Not a user-facing change."

**Comment by lava** [comment]
@orsenthil I've added a JIRA link. The README section is already expanded to include `pre-commit` in the current PR, if you want more detailed instructions I'd propose opening a follow-up PR so we don't have to dismiss the existing approvals for this one.

**Comment by vinodkone** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
