### PR TITLE
DCOS-16113: Update DC/OS UI 1.10 package

### PR DESCRIPTION
**Pull request by orlandohohmeier**
## High Level Description

Update the DC/OS UI package to include the latest fixes and improvements.

## Related Issues

- [DCOS-15287](https://jira.mesosphere.com/browse/DCOS-15287) Add checks to verify marathon response (tests)
- [DCOS-12290](https://jira.mesosphere.com/browse/DCOS-12290) Support a default "bridge" network for UCR in the DC/OS UI
- [DCOS-13419](https://jira.mesosphere.com/browse/DCOS-13419) Support host volumes for Mesos containers.
- [DCOS-12861](https://jira.mesosphere.com/browse/DCOS-12861) The UI should enable "force pull" option for UCR
- [DCOS-15568](https://jira.mesosphere.com/browse/DCOS-15568) Change form to show "warning" in case there is more than one network
- [DCOS-14844, DCOS-14756](https://jira.mesosphere.com/browse/DCOS-14844) Remove applyPatch function
- [DCOS-12810](https://jira.mesosphere.com/browse/DCOS-12810) Create a pod with labels
- [DCOS-15172](https://jira.mesosphere.com/browse/DCOS-15172) Include framework tasks in bar
- [DCOS-15865](https://jira.mesosphere.com/browse/DCOS-15865) Prevent service/task ID collision
- [DCOS-15172](https://jira.mesosphere.com/browse/DCOS-15172) Health check and bar do not match
- [DCOS-12243](https://jira.mesosphere.com/browse/DCOS-12243) Redirect user back to original relative path after logged-in
- [DCOS-15718](https://jira.mesosphere.com/browse/DCOS-15718) System integration test for Universe in the UI
- [DCOS-12810](https://jira.mesosphere.com/browse/DCOS-12810) Create a pod with labels
- [DCOS_OSS-956](https://jira.mesosphere.com/browse/DCOS_OSS-956) Vip port auto assign / Vip port field
- [DCOS-14465](https://jira.mesosphere.com/browse/DCOS-14465) Add multi container tests
- [DCOS-12849](https://jira.mesosphere.com/browse/DCOS-12849) Defaults services logs to stderr
- [DCOS_OSS-981](https://jira.mesosphere.com/browse/DCOS_OSS-981) Host port auto-assign issue
- [DCOS-14334](https://jira.mesosphere.com/browse/DCOS-14334) Update CLI setup script
- [DCOS_OSS-1050](https://jira.mesosphere.com/browse/DCOS_OSS-1050) Remove image if no id is provided
- [DCOS-14334](https://jira.mesosphere.com/browse/DCOS-14334) Remove all references to dcosInstallCommandExtraSteps and update windows install command instruction
- [DCOS-12849](https://jira.mesosphere.com/browse/DCOS-12849) Defaults services logs to stderr
- [DCOS-15332](https://jira.mesosphere.com/browse/DCOS-15332) Validate redirect is the same domain as the original hostname
- [DCOS-14334](https://jira.mesosphere.com/browse/DCOS-14334) Update CLI setup script
- [DCOS_OSS-1108](https://jira.mesosphere.com/browse/DCOS_OSS-1108) Fix jobs status display
- [DCOS_OSS-1050](https://jira.mesosphere.com/browse/DCOS_OSS-1050) Fix pod docker image validation
- [DCOS-15615](https://jira.mesosphere.com/browse/DCOS-15615) Fix job schedule editing
- [DCOS-14465](https://jira.mesosphere.com/browse/DCOS-14465) Fix Review and Run test for multi container
- [DCOS-15817](https://jira.mesosphere.com/browse/DCOS-15817) Fix "beta-optin" message
- [DCOS-14465](https://jira.mesosphere.com/browse/DCOS-14465) Add multi container tests
- [DCOS_OSS-1132](https://jira.mesosphere.com/browse/DCOS_OSS-1132) Adjust the constraints validation to fix validation errors
- [DCOS-15332](https://jira.mesosphere.com/browse/DCOS-15332) Rename domain to url, improve security adding url parsing to redirect query
- [DCOS-14851](https://jira.mesosphere.com/browse/DCOS-14851) Remove UCR option from service create form
- [DCOS_OSS-1132](https://jira.mesosphere.com/browse/DCOS_OSS-1132) Fix service form `GROUP_BY` placement constraint validation
- [DCOS-15234](https://jira.mesosphere.com/browse/DCOS-15234) Display service ports only when available
- [DCOS-15332](https://jira.mesosphere.com/browse/DCOS-15332) Add unit test to new methods added
- [DCOS-15234](https://jira.mesosphere.com/browse/DCOS-15234) minor change to how checks the service port
- [DCOS-12054](https://jira.mesosphere.com/browse/DCOS-12054) Fix CPU allocation view
- [DCOS-15332](https://jira.mesosphere.com/browse/DCOS-15332) Validate redirect is the same domain as the original hostname.
- [DCOS-16274](https://jira.mesosphere.com/browse/DCOS-16274) Add Intl (ECMA-402) polyfill

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [changelog](https://github.com/dcos/dcos-ui/compare/8169cebaa99bb84858978fab6f956cc00e6189aa...1bbe9b5a67780112c74b7c4522f3dd43a40a0fc0)
  - [x] Test Results: [unit](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/public-dcos-ui-pulls/8177/),  [integration](https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/public-dcos-ui-pulls-integration/5099/)
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label Work In Progress

**Comment by orlandohohmeier** [comment]
@rcorral @weblancaster please review this one once @MatApple updated the PR to include the `DCOS-15999`. 👀  🙇

**Comment by orlandohohmeier** [comment]
No need for further updates... @rcorral @weblancaster could you please review?

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ship It]

**Comment by adam-mesos** [comment]
Before we give this a ShipIt, let's get the CI green and/or explain away the failed/flaky tests.
- test_vip is known flaky: https://jira.mesosphere.com/browse/DCOS-14108
- But test_3dt.test_3dt_nodes_node_units_unit is newly flaky. Any idea if the test_3dt.test_3dt_nodes_node_units_unit flakiness could be caused by this PR? Do we even have any integration tests that would be affected by the UI?

**Comment by orlandohohmeier** [comment]
@adam-mesos I'm not aware of any system integration tests other then the DC/OS UI ones which could be affected by this UI change. 
I checked the `test_3dt.test_3dt_nodes_node_units_unit` test and the test is checking "a specific unit for a specific node, endpoint `/system/health/v1/nodes/<node>/units/<unit>`" using the API directly, thus I'm pretty sure the flakiness is unrelated to the latest DC/OS UI bump.

**Comment by orlandohohmeier** [comment]
@adam-mesos I dug a little deeper and it seems that the test fails every now and then (first failure: 24 Jul 16, https://github.com/dcos/dcos/pull/396). Maybe @mellenburg can shed some light.

**Comment by adam-mesos** [comment]
I've added the ShipIt label, but we still need to get a JIRA to track the flakiness of `test_3dt.test_3dt_nodes_node_units_unit`. cc: @klueska

**Comment by falseperfection** [comment]
@adam-mesos I re-ran the failing tests this morning hoping for all-green so I could add them to the train. Seems to have worked.

**Comment by adam-mesos** [comment]
Holding until the matching EE PR passes all its tests.
https://github.com/mesosphere/dcos-enterprise/pull/1048

**Comment by orlandohohmeier** [comment]
I've updated the PR to include dcos/dcos-ui#2262 which should fix the issues with the tests.

**Comment by orsenthil** [comment]
The Enterprise-PR tests are are now required. I updated the EE-PR to reference this branch/sha in upstream.json and the EE-PR aggregate status will now be reported here.

**Pull request merged**
