### PR TITLE
1.9.1 train 171

### PR DESCRIPTION
**Pull request by mellenburg**
* #1530 
* #1574 
* #1592 
* #1597 
* #1598

### CODE REVIEW

**Comment by jgehrcke** [comment]
`test_octarine` failed in https://teamcity.mesosphere.io/viewLog.html?buildId=669843. I restarted it and  updated DCOS-16020.

**Comment by jgehrcke** [comment]
`test_upgrade_vpc.marathon_app_tasks_survive_upgrade` failed in https://teamcity.mesosphere.io/viewLog.html?buildId=669837. That's probably already tracked, via https://jira.mesosphere.com/browse/DCOS_OSS-1065.

**Comment by jgehrcke** [comment]
Test failures:
```
test_networking.test_if_overlay_ok 	
 test_networking.test_ip_per_container 	
 test_service_discovery.test_if_service_discovery_works_docker_bridged_network 	
 test_service_discovery.test_if_service_discovery_works_docker_host_network 
```
(https://teamcity.mesosphere.io/viewLog.html?buildId=669847)

Not funny. Created https://jira.mesosphere.com/browse/DCOS_OSS-1195 with blocker status, needs to be triaged.

**Comment by jgehrcke** [comment]
The failure of `test_if_ucr_app_runs_in_new_pid_namespace` is tracked via https://jira.mesosphere.com/browse/DCOS_OSS-862. Restarting.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
bump-ee has been fixed to work across all branches. So, the corresponding enterprise PRs (if any) can be added to this mesosphere/dcos-enterprise#985

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
Just FYI: the previous event was not triggered by Github API. I am not triggering again as the upstream bump was already done.

**Pull request merged**
