### PR TITLE
[2.2][BACKPORT] 7780 from  master: Bump Metronome to 0.6.68

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
This is a backport of the following PR:

https://github.com/dcos/dcos/pull/7780

* MARATHON-8776

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot changelog-not-required bump

**Review by pierrebeitz — APPROVED** [review]

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot bump-ee

**Review by timcharper — APPROVED** [review]

**Comment by timcharper** [comment]
We should probably add a changelog entry?

**Comment by pierrebeitz** [comment]
> We should probably add a changelog entry?

We currently have "Metronome jobs now support dependencies".

**Comment by timcharper** [comment]
Is suppose so, I've never been clear if we want to show changelog entries that report what's changed since the last RC... I think for the final release notes it would be noise to include that, personally, but there are varying opinions on this

**Pull request merged**
