### PR TITLE
Bumping spartan and minuteman

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by sargun** [comment]
@spahl

**Comment by spahl** [comment]
:ship:

**Comment by sargun** [comment]
You have to hit the button, methinks

**Comment by spahl** [comment]
It needs rebase. Feel free to do it and we can merge. Until there is a bot I batch them in groups

**Comment by sargun** [comment]
Wonderful!

**Comment by cmaloney** [comment]
We should have added a integration test for the new functionality

**Pull request merged**
