### PR TITLE
Backport changes from #2426

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Brings in changes from #2426

(Discussion is here: https://github.com/dcos/dcos/pull/2426#issuecomment-368958266)

### CODE REVIEW

**Comment by orsenthil** [comment]
@mellenburg / @jeschkies  / @urbanserj  - Please review and approve. Both this and EE part.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mellenburg  - Thanks for catching that.. I thought we removed it https://github.com/dcos/dcos/pull/2426/files - No, we did not.

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mellenburg  - Please take a look again.

**Pull request merged**
