### PR TITLE
[1.11] Disable the 3DES and TLS 1.1 for Master Admin Router by default.

### PR DESCRIPTION
**Pull request by ahairape**
## High-level description

This PR disables the 3DES bulk encryption algorithm and TLS 1.1 for Master Admin Router by default in DC/OS 1.11.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

https://jira.mesosphere.com/browse/DCOS-21958

## Checklist for all PRs

  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by ahairape** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
@mesosphere-mergebot bump-ee

**Comment by ahairape** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by ahairape** [comment]
@mhrabovcin @jgehrcke could you please review this PR?

**Comment by jgehrcke** [comment]
Maybe @gpaul's reviews can successfully hack mergebot.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Pull request merged**
