### PR TITLE
Fix test_dcos_cni_l4lb integration test

### PR DESCRIPTION
**Pull request by urbanserj**
## High-level description

Fix test_dcos_cni_l4lb integration test

Bugs:
* Client task has a VIP label, the same as server task's VIP label
* The test checks only connectivity, but not correctness of the output
* It must kill all the tasks, but it keeps them running

Improvements:
* Let's use `MarathonApp` class everywhere
* Run tasks on random ports
* Use human-readable task names
* Make logging sane
* Enable test_service_discovery_docker_bridged_network test

## Corresponding DC/OS tickets (required)

  - [DCOS-49805](https://jira.mesosphere.com/browse/DCOS-49805) test_networking.test_dcos_cni_l4lb fails on universal installer provisioned cluster

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by GoelDeepak** [comment]
@urbanserj  we should commit this PR irrespective of DCOS-49805 as it has some good improvements. I would just like to make a small addition to this PR in `spartan.cni` config to incorporate subnets created by `terraform`. So instead of `172.16.0.0/12` could be please change it to `172.0.0.0/8`

**Comment by urbanserj** [comment]
@GoelDeepak as of dcos-terraform 0.2, default `cidr_block` has been changed from `172.16.0.0/16` to `172.12.0.0/16`. Please set `version` to `"~> 0.2"` in your configuration accordingly, so we no longer have to support that public subnet in that cni integration test.

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by urbanserj** [comment]
@mesosphere-mergebot request-review GoelDeepak ichernetsky

**Pull request merged**
