### PR TITLE
Bump Marathon to 1.11.16

### PR DESCRIPTION
**Pull request by pierrebeitz**
* [COPS-6533](https://jira.mesosphere.com/browse/COPS-6533)
* [MARATHON-8770](https://jira.mesosphere.com/browse/MARATHON-8770)
* [D2IQ-72504](https://jira.mesosphere.com/browse/D2IQ-72504)

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot label Ready For Review

**Review by DominikDary — APPROVED** [review]

**Comment by DominikDary** [comment]
DC/OS Build is green but not reported to github /cc @orsenthil

**Comment by DominikDary** [comment]
@mesosphere-mergebot label Ship It

**Comment by pierrebeitz** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
