### PR TITLE
Train 158

### PR DESCRIPTION
**Pull request by BenWhitehead**
* #1509 
* #1510

### CODE REVIEW

**Comment by BenWhitehead** [comment]
mesosphere-mergebot label Ready for Review

**Comment by BenWhitehead** [comment]
@mesosphere-mergebot label Ready for Review

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by orsenthil** [comment]
The upstream bump was this https://github.com/mesosphere/dcos-enterprise/pull/862 and that's all green.

**Pull request merged**
