### PR TITLE
bump from latest dcos-net master

### PR DESCRIPTION
**Pull request by bernadinm**
This includes latest windows support.

## High-level description

This is related to the work for dcos-net to run on windows. 

Author: @aserdean 

cc: @urbanserj @GoelDeepak 

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-2073](https://jira.mesosphere.com/browse/DCOS_OSS-2073) DC/OS Hybrid Cluster: DC/OS Spartan Service Support on Mesos Windows Agent	

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change:
  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

### CODE REVIEW

**Comment by urbanserj** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by urbanserj** [comment]
@mesosphere-mergebot bump-ee

**Comment by urbanserj** [comment]
Hi @bernadinm,

Thank you for the PR!

Yesterday we merged 2 huge PRs (https://github.com/dcos/dcos-net/pull/37, https://github.com/dcos/dcos-net/pull/43) into master branch. I've bumped dcos-net and erlang packages in my own branch. It includes all changes from this bump PR.

Could you please close your PR on favor of https://github.com/dcos/dcos/pull/2635?

**Comment by bernadinm** [comment]
according to @GoelDeepak,  this is obsolete by https://github.com/dcos/dcos/pull/2635. Marking this closed.

**Pull request closed without merging**
