### PR TITLE
Metronome 0.4.2 bump on 1.11 [cherry-pick to 1.11.2]

### PR DESCRIPTION
**Pull request by gpaul**
Cherry-pick of https://github.com/dcos/dcos/pull/2826 to 1.11.2.

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot override-status  
@mesosphere-mergebot merge-it  
@mesosphere-mergebot label [Ready For Review |Holding |Request For Comment |Ship It |Work In Progress] 
@mesosphere-mergebot bump-ee  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by gpaul** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by gpaul** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
@kensipe @alenkacz @orsenthil @jgehrcke PTAL

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
