### PR TITLE
[WIP] Modified overlay agent module behavior for handling Docker failures.

### PR DESCRIPTION
**Pull request by asridharan**
This PR changes the failure handling of the overlay agent module. The overlay agent modules no longer fails hard on an unsuccessful overlay configuration.

# Issues

[DCOS-10952](https://mesosphere.atlassian.net/browse/DCOS-10952)
...

# Checklist

 - [* ] Included a test which will fail if code is reverted but test is not
 - [*] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

If this is a component/package update, include

 - [ ] Change Log from last: <link>
 - [ ] Test Results: <link>
 - [ ] Code Coverage: <link>

### CODE REVIEW

**Comment by asridharan** [comment]
This is waiting PR #1100  since it needs the latest mesos to work.

**Comment by adam-mesos** [comment]
@asridharan Please rebase on latest #1100 which includes the latest Mesos master

**Comment by adam-mesos** [comment]
@asridharan It looks like these overlay modules changes were already merged into dcos-mesos-modules and will be included in train 118 ( #1131 ), from #1108 (dcos-mesos-modules bump) along with #1100 for the Mesos bump. Is there anything else we'd need (config changes, etc.)?

**Comment by asridharan** [comment]
@adam-mesos you are right. #1108 already has these changes. Will go ahead and close this PR for the time being.

**Pull request closed without merging**
