### PR TITLE
chore(dcos-ui): update package to 1.11.0-rc.3

### PR DESCRIPTION
**Pull request by orlandohohmeier**
## High-level description

Update the DC/OS UI package to include the latest fixes and improvements.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

* [DCOS-19481](https://jira.mesosphere.com/browse/DCOS-19481) swap placement form fields
* [DCOS-19559](https://jira.mesosphere.com/browse/DCOS-19559) use placement constraints widget
* [DCOS-19657](https://jira.mesosphere.com/browse/DCOS-19657) add advanced type to constraints input
* [DCOS-19103](https://jira.mesosphere.com/browse/DCOS-19103) re-order breadcrumb and update style based on new design.
* [DCOS-18275](https://jira.mesosphere.com/browse/DCOS-18275) switch to Mesos Event Stream
* [DCOS-19557](https://jira.mesosphere.com/browse/DCOS-19557) extract placement constraints partial
* [DCOS-19283](https://jira.mesosphere.com/browse/DCOS-19283) render YAML ace editor
* [DCOS-19541](https://jira.mesosphere.com/browse/DCOS-19541) add mountpoints for config screen
* [DCOS-18992](https://jira.mesosphere.com/browse/DCOS-18992) extract placement tab

## Related tickets (optional)

_No related tickets_

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): https://github.com/dcos/dcos-ui/releases/tag/v1.11.0-rc.3
  - [x] Test Results: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1407/testReport/
  - [x] Code Coverage (if available): https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-pull-requests/1407/cobertura/
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot bump-ee

**Comment by orlandohohmeier** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by jgehrcke** [comment]
Thank you for another beautiful PR, @orlandohohmeier. Trying to push this across the finish line.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot pr-status-checks

**Pull request merged**
