### PR TITLE
Bump dcos-ui package. Includes binary cli instructions.

### PR DESCRIPTION
**Pull request by rcorral**

### CODE REVIEW

**Comment by spahl** [comment]
@rcorral not building

**Comment by cmaloney** [comment]
@rcorral This is very consistently not building: https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcosIo_Dcos_BuildPr&branch_DcosIo_Dcos=pull%2F337&tab=buildTypeStatusDiv

**Comment by rcorral** [comment]
I'm still looking into this, haven't found a solution.

**Comment by rcorral** [comment]
Build should pass now

**Comment by cmaloney** [comment]
Checking with @tamarrow if there's any other changes we need to pair with this / moving to the binary CLI. (I know that https://github.com/dcos/dcos/pull/61 is laying around, no idea if it is still relevant).

**Pull request merged**
