### PR TITLE
update owners list

### PR DESCRIPTION
**Pull request by GoelDeepak**
## High-level description

This is to update the dcos owners list. It adds dgoel and removes avinash

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot merge-it  
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot override-status  
@mesosphere-mergebot label [Holding |Ship It |Request For Comment |Work In Progress |Ready For Review] 
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by orsenthil** [comment]
@GoelDeepak  - Please update the description. :)

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@urbanserj  - could you please review this one too.

**Comment by mesosphere-mergebot-dev** [comment]
:wave: This PR has been inactive for 3 days. Please review the status checks to see what needs to be done to move it forward or change the label to Work in Progress. Thank you!

**Comment by mesosphere-mergebot-dev** [comment]
:wave: This PR has been inactive for 3 days. Please review the status checks to see what needs to be done to move it forward or change the label to Work in Progress. Thank you!

**Comment by mesosphere-mergebot-dev** [comment]
:wave: This PR has been inactive for 3 days. Please review the status checks to see what needs to be done to move it forward or change the label to Work in Progress. Thank you!

**Comment by mesosphere-mergebot-dev** [comment]
:wave: This PR has been inactive for 3 days. Please review the status checks to see what needs to be done to move it forward or change the label to Work in Progress. Thank you!

**Comment by urbanserj** [comment]
@GoelDeepak there is an issue in ee build, it have been fixed recently in master branch. could you please rebase your PR?

Also see: https://github.com/dcos/dcos/pull/2980/files

**Comment by GoelDeepak** [comment]
@mesosphere-mergebot bump-ee

**Comment by urbanserj** [comment]
@orsenthil could you please review it again?

**Pull request merged**
