### PR TITLE
Bump dcos-net

### PR DESCRIPTION
**Pull request by urbanserj**
## High-level description

Bump dcos-net

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5495](https://jira.mesosphere.com/browse/DCOS_OSS-5495) dcos-net: task update leads to two DNS zone updates
  - [DCOS_OSS-5620](https://jira.mesosphere.com/browse/DCOS_OSS-5620) DC/OS overlay networks should be compared by-value
  - [DCOS_OSS-5634](https://jira.mesosphere.com/browse/DCOS_OSS-5634) Drop labels from Lashup's kv_message_queue_overflows_total metric
  - [DCOS_OSS-5641](https://jira.mesosphere.com/browse/DCOS_OSS-5641) Remove support for `set` mode from dcos dns
  - [DCOS_OSS-5464](https://jira.mesosphere.com/browse/DCOS_OSS-5464) Switch to Mesos Operator Streaming API in DC/OS L4LB

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]
 
 https://github.com/dcos/dcos-net/compare/8e3302aa7e3815c5739c7b0460974103217ea161...eb7242123907009892634a87f8d14c97d3f6c331
https://github.com/dcos/dcos-net/pull/182
https://github.com/dcos/dcos-net/pull/183
https://github.com/dcos/dcos-net/pull/187
https://github.com/dcos/dcos-net/pull/188
https://github.com/dcos/dcos-net/pull/189
https://github.com/dcos/lashup/pull/56
https://circleci.com/gh/dcos/dcos-net/1423
https://codecov.io/github/dcos/dcos-net/commit/c0f07b291af84513cbb82460b9757e77402d0c2b

### CODE REVIEW

**Comment by urbanserj** [comment]
@mesosphere-mergebot changelog-not-required non-user facing issues or back-ported to earlier releases

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Work In Progress]

**Comment by urbanserj** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by urbanserj** [comment]
@mesosphere-mergebot request-review @ichernetsky @mainred

**Comment by urbanserj** [comment]
@mesosphere-mergebot sync

**Comment by orsenthil** [comment]
Hi @urbanserj  -

Looks like this change broke the permissive mode clusters running nightly

https://teamcity.mesosphere.io/viewLog.html?buildId=2430877&buildTypeId=DcOs_Enterprise_Test_Inte_AwsOnpremWStaticBackendAndSecurityPermissive&tab=buildResultsDiv

- Is this due to any dcos-net change itself?

**Comment by urbanserj** [comment]
We changed the l4lb architecture in this PR. I'm not sure if it's related, but it looks like there is something wrong with l4lb. According to the diagnostic bundle either l4lb fails to add backends for freeipa VIPs or someone continuously remove them from ip_vs configuration.

**Comment by urbanserj** [comment]
@ichernetsky may I kindly ask you to take a look? It's a bit weird why it started failing only(?) on the permissive mode clusters.

**Comment by ichernetsky** [comment]
@urbanserj will do it today.

**Pull request merged**
