### PR TITLE
[DO NOT MERGE] Testing status updates from TeamCity

### PR DESCRIPTION
**Pull request by AliakseiKhomchanka**

### CODE REVIEW

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by AliakseiKhomchanka** [comment]
@mesosphere-mergebot test teamcity/dcos/build/dcos

**Comment by orsenthil** [comment]
We will open a new PR to test.

**Pull request closed without merging**
