### PR TITLE
Winpanda App: Fix Recognition Of Configuration File Templates

### PR DESCRIPTION
**Pull request by anatolii-borysov**
1) change supported names of DC/OS package's installation related configuration
   files to  <package_name>.<base_extension>.j2 form (e.g. package.extra.j2) to
   reflect that fact that they are Jinja2-style templates, and require
   rendering procedure to become real pieces of package configuration
2) remove excessive pre-processing of command line string definitions specified
   in extra DC/OS package installation options configuration file
3) minor code style fixes

JIRA: DCOS_OSS-5676 - Winpanda App: Fix Recognition Of Configuration File
                      Templates

## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Related tickets (optional)

  - [DCOS-ID](https://jira.mesosphere.com/browse/DCOS-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @jongiddy

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required Internal Windows change

**Comment by wend1zel** [comment]
@mesosphere-mergebot label Ship It

**Comment by anatolii-borysov** [comment]
@mesosphere-mergebot label Ship It

**Pull request merged**
