### PR TITLE
Merge Train for DC/OS 1.9.9

### PR DESCRIPTION
**Pull request by orsenthil**
* [1.9] Increase executor reregistration timeout to 10 seconds. #2696 
* Fixed bug in `calculate_ip_detect_public_contents()`.  #2731 
* [1.9] Bump curl from 7.48 to 7.59  #2757 
* [Ready for Review] Backport Adminrouter DNS entry TTL override of 5 seconds to 1.9 OSS #2772
* [DCOS-14199][1.9] Write strings to files atomically in pkgpanda.util  #2786 
* Bump dcos-ui 1.9.6 in 1.9 release  #2787
* [1.9] Bump Mesos to nightly mesosphere/1.2.x 563f24c #2807

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/QUALITY-1975

**Comment by mesosphere-mergebot2** [comment]
@orsenthil, an [owner](https://raw.githubusercontent.com/dcos/dcos/master/owners.json) other than the PR creator needs to issue that command.

**Comment by orsenthil** [comment]
@branden  - I made a note here for the inclusion (https://github.com/dcos/dcos/pull/2832#issuecomment-385575588) as I felt it was only appropriate to do so when we are dealing with a moving dependency/emergency situation.  In the similar vein, I would actually apply a ship-it label to that PR, please disagree if you think that is not a good process to follow.

I will go ahead with applying a ship-it label to #2832 - Please help in a) doing the appropriate overrides in this PR, b) Adding a ship-it label to this one EE and c) `merge-it` to get across the line. Thanks!

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/cloudformation/simple https://jira.mesosphere.com/browse/QUALITY-1975

**Pull request merged**
