### PR TITLE
Set DC/OS version to 1.14.0-alpha-dev

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (required)

* DCOS-56899  - Set DC/OS Version to 1.14.0-Alpha

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by orsenthil** [comment]
Hi @jgehrcke - We don't need a release branch. I had noted it here and share some more details on things to look out for here: https://jira.mesosphere.com/browse/DCOS-56899

* The -alpha does not result in a release. No release branches are created. 

* The development continues on the top of alpha (master branch), and if a developer wants to know the version of DC/OS in the branch under development, the developer should see 1.14.0-alpha in the version for the master when we are in alpha phase.

This is also the process of how the 1.13.0-alpha, and previous releases were accomplished (https://github.com/dcos/dcos/pull/4786/files)

----

Just to share, the rest of the versioning will play out of this way.

1. master version becomes 1.14.0-alpha - in this PR.
2. beta code-freeze happens in few weeks.
a) New branch 1.14 is created, and the version is set to 1.14.0-beta in 1.14 branch. The master branch at this point is now, 1.15.0-dev. So, if a developer deploys DC/OS from any branch, knows the current version the developer is using.
b) A short term-release branch 1.14.0-beta is created, based on the soak version, and upon release, this artifact is shared externally with customers and branch converted to tag. This has no impact on the developer workflow unless a critical bugfix needs to be cherry-picked on top of soak version.

3. Development continues in master and 1.14 branches, and 1.14.0 release will be cut from the 1.14 branch.

I hope this explanation helps. If we change anything, it will be something new. I am not saying that we should not,  we have to identify the benefits and do that. 

Given 1.14.0-alpha is not going to be release-out-of-door, and no 1.14 branch will be created, setting the master version to 1.14.0-alpha seems like the right thing to do, and is aligned with our practice.

**Comment by jgehrcke** [comment]
Then let's call it `1.14.0-alpha-dev`, and let's keep `1.14.0 (in development)` in `CHANGES.md`. What do you think?

**Comment by orsenthil** [comment]
> Then let's call it 1.14.0-alpha-dev, and let's keep 1.14.0 (in development) in CHANGES.md. What do you think?

SGTM. Thank you!

**Comment by orsenthil** [comment]
Here are some changes required if we are going to start calling it as `1.14.0-alpha-dev`

- This will necessitate creating a branch called `1.14.0-alpha` when giving to soak. The branch will be should have the version changed to `1.14.0-alpha`. This branch should be deleted and converted to tag immediately because no development should happen in this branch.

The other options are:

- We call this version as `1.14.0-alpha` but internally in communications, the version string is set to `1.14.0-alpha-dev`  I am -1 on this, this will result in confusion.

- Keep the status-quo and call it as 1.14.0-alpha.  The suffixing the `-dev` seems to be a better indicator of the state, even if it results in minor change listed above. So, adopting the `-dev` suggestion.

**Comment by orsenthil** [comment]
@jgehrcke  - PTAL again. Thank you.

**Comment by orsenthil** [comment]
> So, I think if a name refers to a moving target then -dev is helpful, it expresses that. 

Definitely, I agree.

**Comment by orsenthil** [comment]
> I am not 100 % sure if I understood your last comments.

I stated a desire that `version-string` in the artifact should be same as the version name we call it colloquially.  So, I will have to change the `version-string` again for the SOAK artifact so that `version-string` and the `version-name` we use in communication is same. Previously, we didn't have do that, but we had moving version identified by the string `1.13.0-alpha`, now the moving version can be called as `1.13.0-alpha-dev`, and as you mention, it is a better representation. :)

**Comment by jgehrcke** [comment]
This had various failed CI checks. Some failed with Cosmos returning 500 HTTP responses. I tried to debug the cause of all these problems up in the master node logs but these were not collected as of https://jira.mesosphere.com/browse/DCOS-57007.

Maybe the problem I described in https://jira.mesosphere.com/browse/DCOS-57007 has been fixed in the current head of master right now. Which is why I opted for "Update branch", re-running all the CI checks.

**Comment by jgehrcke** [comment]
Now with the better debuggability I see that the 500 HTTP responses emitted by Cosmos are because of:
```
2019-07-25 10:24:36.637733 +0000 UTC INFO  2019-07-25 10:24:36,636 [finagle/netty4-5] access: 0.0.0.0 - "GET /dcos-metadata/dcos-version.json HTTP/1.1" 200 19
1B 5ms "cosmos/unknown-version"
2019-07-25 10:24:36.64041 +0000 UTC WARN  2019-07-25 10:24:36,639 [finagle/netty4-6] c.m.c.handler.PackageInstallHandler: Processing [InstallRequest(hello-wor
ld,Some(2.2.0-0.42.2),None,None,None)] resulted in : assertion failed: Value '1.14.0-alpha-dev' does not conform to expected format ^(?:0|[1-9][0-9]*)(?:\.(?:
0|[1-9][0-9]*))*(?:-[A-Za-z0-9]+)?$
2019-07-25 10:24:36.64241 +0000 UTC WARN  2019-07-25 10:24:36,640 [finagle/netty4-6] com.mesosphere.cosmos.Cosmos$: Unhandled throwable:
2019-07-25 10:24:36.642713 +0000 UTC java.lang.AssertionError: assertion failed: Value '1.14.0-alpha-dev' does not conform to expected format ^(?:0|[1-9][0-9]
*)(?:\.(?:0|[1-9][0-9]*))*(?:-[A-Za-z0-9]+)?$
2019-07-25 10:24:36.643024 +0000 UTC at scala.Predef$.assert(Predef.scala:219)
2019-07-25 10:24:36.643325 +0000 UTC at com.mesosphere.universe.v3.model.DcosReleaseVersionParser$.$anonfun$parse$1(DcosReleaseVersionParser.scala:27)
2019-07-25 10:24:36.643538 +0000 UTC at com.twitter.util.Try$.apply(Try.scala:15)
```

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/test-e2e/group1 https://jira.mesosphere.com/browse/DCOS-57019

**Comment by jgehrcke** [comment]
@mesosphere-mergebot changelog-not-required version change does not need changelog entry

**Comment by orsenthil** [comment]
Thanks, @jgehrcke . Calling it `-alphadev` is fine.

**Comment by orsenthil** [comment]
Going with an immediate merge as the required tests are successful.

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Comment by jgehrcke** [comment]
> The -alpha does not result in a release. No release branches are created.

After all, we decided that there will be a release, and a corresponding manual testing branch was created: https://github.com/dcos/dcos/tree/1.14.0-alpha

**Comment by orsenthil** [comment]
> After all, we decided that there will be a release.

Yeah. Something new  as had not done this for 1.13 or 1.12 `alpha` phase.

**Pull request merged**
