### PR TITLE
gen/calc: normalize check timeouts

### PR DESCRIPTION
**Pull request by gpaul**
## High-level description

What features does this change enable? What bugs does this change fix?

This PR normalizes dcos-checks timeouts to either `1s` or `30s` depending on whether the check is supposed to succeed virtually instantly, or whether it may take a few seconds to complete. The `30s` option is taken from the fact that it is the current highest timeout and @timaa2k and I see no reason to go higher.

The associated Enterprise PR fixes a bug where the `mesos_master_replog_synchronized` never got updated from 1s to 30s due to the weird interaction between the Open and EE repositories.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-39571](https://jira.mesosphere.com/browse/DCOS-39571) dcos-checks-poststart: fix timeouts to fix flakiness

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: This is not a user-facing change.
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Just a refactoring.
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___

### CODE REVIEW

**Comment by gpaul** [comment]
@mesosphere-mergebot bump-ee

**Comment by gpaul** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by gpaul** [comment]
@timaa2k @branden PTAL (and the EE bump, too)

**Comment by gpaul** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/dcos-docker/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by gpaul** [comment]
@orsenthil please override this one

**Comment by rukletsov** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/dcos-docker/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Pull request merged**
