### PR TITLE
Make dcos-spartan-watchdog start later rather than have a random 60 second sleep

### PR DESCRIPTION
**Pull request by cmaloney**
cc: @sargun

### CODE REVIEW

**Comment by sargun** [comment]
No, the purpose of this is to prevent the two systemd units from starting at the same time, and on slow systems this means that you get into this awkward restart loop where both systemd units keep starting at the same time. And the watchdog resets spartan, etc..

**Comment by cmaloney** [comment]
@sargun Please tell me how `sleep 60` is any different from telling the timer to start / fire 60 seconds later? I fail to see how there is any difference there....

**Comment by sargun** [comment]
Will Systemd always keep them on different intervals? Systemd has a habit of starting things together, and this is the behaviour I'm trying to avoid.

**Comment by cmaloney** [comment]
Having the sleep inside the unit vs. the delay on the outside doesn't seem like it makes any difference in there, esp. since the `After=` line is being removed as well so there's no direct link between the two

**Comment by cmaloney** [comment]
we could change the fire / restart loop interval to make sure they aren't on the same timing cycle potentially, but I'm pretty sure `dcos-spartan` is already on a 5 second restart loop (https://github.com/dcos/dcos/blob/master/packages/spartan/extra/dcos-spartan.service#L8) while this is a 5 minute loop (https://github.com/dcos/dcos/blob/master/packages/spartan/extra/dcos-spartan-watchdog.timer#L5)

**Comment by cmaloney** [comment]
Lowered fire period to 2 minutes, if spartan which is just a DNS proxy takes > 2 minutes to initialize, much of our other software probably has issues

**Pull request merged**
