### PR TITLE
Mesos: Increase min libprocess worker threads to 16. [1.11]

### PR DESCRIPTION
**Pull request by karya0**
## High-level description

This is to avoid any potential deadlocks due to unavailable libprocess workers. The previous (default) value was 8.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-1943](https://jira.mesosphere.com/browse/DCOS_OSS-1943) Increase LIBPROCESS_NUM_WORKER_THREADS for Mesos master from 8 to 16.

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review):
  - [ ] Test Results:
  - [ ] Code Coverage (if available):
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by karya0** [comment]
@mesosphere-mergebot bump-ee

**Comment by karya0** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by karya0** [comment]
@mesosphere-mergebot label [Ready For Review]

**Comment by jgehrcke** [comment]
I left a comment on the JIRA ticket. The CI run failures need inspection (so that we keep proper track of test instabilities).

**Comment by karya0** [comment]
Failures in `test_networking.test_vip[*]` seem flaky (they passed one out of three attempts) and are potentially related to https://jira.mesosphere.com/browse/DCOS-19542 or https://jira.mesosphere.com/browse/DCOS-19801 as noted by @adam-mesos in https://github.com/dcos/dcos/pull/2165#issuecomment-349813384.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status `teamcity/dcos/test/azure/arm` DCOS-19542

**Comment by jgehrcke** [comment]
@mesosphere-mergebot bump-ee

**Comment by sambatyon** [comment]
The `teamcity/dcos/test/azure/arm` failed with:

```
[21:29:14]	[Step 5/7] File "site-packages/azure/mgmt/resource/resources/v2016_02_01/operations/deployments_operations.py", line 318, in get
[21:29:14]	[Step 5/7] msrestazure.azure_exceptions.CloudError: Azure Error: ResourceGroupNotFound
[21:29:14]	[Step 5/7] Message: Resource group 'teamcity-dcos-test-azure-arm-45tk1q2xmq' could not be found.
```

which seems more of a problem of the infrastructure than of the PR itself. Other than that, this looks good to me.

I still would like you to update the description mentioning that this is a workaround and that a more permanent solution is in the works, perhaps with a URL in the related tickets section to the Mesos issue.

**Comment by jgehrcke** [comment]
@mesosphere-mergebot ship_it_label_status_check

**Comment by jgehrcke** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static DCOS-19542

**Pull request merged**
