### PR TITLE
Replace Jinja2 with pkgpanda templating for dcos-config-windows.yaml

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

Use pkgpanda template language for `dcos-config-windows.yaml`. This matches the language used for `dcos-config.yaml` on Linux, making the files more consistent between platforms.

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5892](https://jira.d2iq.com/browse/DCOS_OSS-5892) Parse dcos-config-win using pkgpanda templating.

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jongiddy** [comment]
@mesosphere-mergebot changelog-not-required change to unreleased code

**Comment by jongiddy** [comment]
@mesosphere-mergebot request-review @DominikDary

**Comment by DominikDary** [comment]
did an end to end test and the change was working fine 👍

**Pull request merged**
