### PR TITLE
Remove dcos-signal

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

Remove dcos-signal

## Corresponding DC/OS tickets (required)

  - [D2IQ-69818](https://jira.d2iq.com/browse/D2IQ-69818) 

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot test  teamcity/dcos/test/terraform/aws/onprem/static/group3

**Comment by orsenthil** [comment]
@mesosphere-mergebot test

**Comment by janisz** [comment]
@mesosphere-mergebot test

**Comment by janisz** [comment]
@mesosphere-mergebot test all

**Pull request merged**
