### PR TITLE
marathon 1.5.7 bump

### PR DESCRIPTION
**Pull request by meln1k**
## Marathon 1.5.7 bump

What features does this change enable? What bugs does this change fix?

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Related tickets (optional)

Other tickets related to this change:

  - [DCOS_OSS-<number>](https://jira.mesosphere.com/browse/DCOS_OSS-<number>) Foo the Bar so it stops Bazzing.

## Checklist for all PRs

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [x] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by meln1k** [comment]
@mesosphere-mergebot label ready-for-review

**Comment by kensipe** [comment]
@mesosphere-mergebot bump-ee

**Comment by meln1k** [comment]
@mesosphere-mergebot label ready-for-review

**Comment by orsenthil** [comment]
@meln1k  - In future PRs, this description could be updated appropriately

```What features does this change enable? What bugs does this change fix?

Corresponding DC/OS tickets (obligatory)
These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

DCOS_OSS- Foo the Bar so it stops Bazzing.
Related tickets (optional)
Other tickets related to this change:

DCOS_OSS- Foo the Bar so it stops Bazzing.
```

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/upgrade-from-previous-major https://jira.mesosphere.com/browse/QUALITY-1923

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status  teamcity/dcos/test/upgrade-from-previous-major QUALITY-1923

**Comment by orsenthil** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
