### PR TITLE
 Bump Metronome to version 0.6.62

### PR DESCRIPTION
**Pull request by janisz**
## High-level description

Bump Metronome 

## Corresponding DC/OS tickets (required)

  - [DCOS_OSS-5988](https://jira.d2iq.com/browse/DCOS_OSS-5988) 

## Related tickets (optional)

  - [D2IQ-ID](https://jira.mesosphere.com/browse/D2IQ-<number>) JIRA title / short description.

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-mergebot request-review @timcharper  @pierrebeitz  @DominikDary

**Comment by janisz** [comment]
@mesosphere-mergebot changelog-not-required not released fix

**Review by DominikDary — DISMISSED** [review]

**Review by DominikDary — APPROVED** [review]

**Comment by janisz** [comment]
@mesosphere-mergebot test

**Comment by janisz** [comment]
@mesosphere-mergebot test all

**Comment by janisz** [comment]
@mesosphere-mergebot test all

**Comment by janisz** [comment]
@mesosphere-mergebot merge-it

**Comment by janisz** [comment]
I manually checked CI statuses and they were green, we have issue on reporting CI status back to github. Merging should be fine

**Pull request merged**
