### PR TITLE
DCOS-46438 - Synchronize integration test requirements with panda package versions.

### PR DESCRIPTION
**Pull request by jbarrick-mesosphere**

### CODE REVIEW

**Comment by jbarrick-mesosphere** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jbarrick-mesosphere** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static/group3 DCOS-48351

**Comment by jbarrick-mesosphere** [comment]
@orsenthil would you be able to apply the override here?

**Comment by orsenthil** [comment]
Hi @jbarrick-mesosphere  - The PR description is helpful. We have to update our PR template too.

* I triggered the flaky test. I want to make sure if that is a flaky, not something that is related to change in dependencies being introduced here.

**Pull request merged**
