### PR TITLE
3dt refactor

### PR DESCRIPTION
**Pull request by darkonie**
## High Level Description

3dt refactor and vendor folder update.

## Related Issues

[DCOS-14886](https://jira.mesosphere.com/browse/DCOS-14886)

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  existing integration tests should be enough to cover this refactor.
  - [X] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [X] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [X] Change log from the last version integrated (this should be a link to commits for easy verification and review): [3dt](https://github.com/dcos/3dt/compare/25cc4189d66ba20422cabf4565448312267e0f38...18ba85fc27867113e292c5a5ba6598cf8b750bf9)
  - [X] Test Results: [jenkins#321](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-3dt-pulls/321/console)
  - [X] Code Coverage (if available): [jenkins#321](https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-3dt-pulls/321/console)
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by darkonie** [comment]
@mesosphere-mergebot bump-ee

**Comment by darkonie** [comment]
@mesosphere-mergebot bump-ee

**Comment by darkonie** [comment]
@mesosphere-mergebot bump-ee

**Comment by darkonie** [comment]
@lingmann @spahl this is ready for review

**Comment by lingmann** [comment]
Hi @darkonie I'm probably not the right person to review this (and likely neither is @spahl). Can you ping some other folks with more Go experience and/or 3dt knowledge to review these changes? I would suggest some of the Hamburg folks or the new members of the management team.

**Comment by darkonie** [comment]
@lingmann this has been reviewed here https://github.com/dcos/3dt/pull/89

**Comment by darkonie** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
@collinvandyck can you approve this request since you reviewed the go changes?

**Comment by collinvandyck** [comment]
Yes. My only point on the 3dt changeset was that I am not really all that familiar with the 3dt codebase but I reviewed the changes and they seemed to be a fairly typical refactor.  I didn't see anything which jumped out as being "wrong" necessarily.  That being said, if all the tests pass.... 🎆 

image

**Comment by lingmann** [comment]
Thanks @collinvandyck @amitaekbote @spahl for reviewing. Let's work towards continuing to get more people comfortable reviewing all of the 3dt code! :)

**Pull request merged**
