### PR TITLE
Bump Marathon to v1.3.13

### PR DESCRIPTION
**Pull request by ichernetsky**
## High Level Description

A few improvements to the constraint migration logic and better handling of exceptions when forwarding requests to a Marathon leader.

## Related Issues

  - [MARATHON-4802](https://jira.mesosphere.com/browse/MARATHON-4802) Constraint migration was not really implemented. This commit makes sure that it is fully implemented. During migration some constraints get sanitized. For instance, `["field", "UNIQUE", "value"]` gets transformed to `["field", "UNIQUE"]` because the `UNIQUE` constraint should not have any value. In addition to that the validation of `CLUSTER` is relaxed, because it doesn't require a value, and such a constraint did not pass the validation before.
  - [#5487](https://github.com/mesosphere/marathon/pull/5487) Handle socket timeout exception when forwarding requests to a leader.

## Checklist for all PR's

  - [x] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [Marathon changes](https://github.com/mesosphere/marathon/compare/acc261835097aa7dbfe2b33565fb0eb35439a3d2...9ac3bad2db506c8ace2152c4858034ccd5fda918)
  - [x] Test Results: [CI job for the release](https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/marathon-pipelines/detail/releases%2F1.3/7/pipeline)
  - [ ] Code Coverage (if available):

### CODE REVIEW

**Comment by ichernetsky** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by ichernetsky** [comment]
@mesosphere-mergebot bump-ee

**Comment by ichernetsky** [comment]
@lingmann, it's done. Could you please check it out again?

**Comment by lingmann** [comment]
Since mergebot/enterprise/build-status/aggregate tests are failing we need to get a good understanding before we can merge. @mellenburg is going to try and re-trigger the Enterprise tests with the older "1.8" parameters, since some of our automatic integration tests no longer work with 1.8 builds. fyi @ichernetsky

**Comment by ichernetsky** [comment]
There is only one failing test, and it is not related to Marathon. There is a ticket for it: https://jira.mesosphere.com/browse/DCOS_OSS-1503

**Comment by cdaw** [comment]
@ichernetsky @lingmann @orsenthil  I agree with Ivan's assessment.  Let's work on getting this merged by end of day Monday.

**Comment by mellenburg** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
