### PR TITLE
(1.11) Retry logging API test assertions

### PR DESCRIPTION
**Pull request by branden**
## High-level description

This places a retry around some logging API test assertions, which should make them less flaky.

## Corresponding DC/OS tickets (required)

  - [DCOS-56866](https://jira.mesosphere.com/browse/DCOS-56866) teamcity/dcos/test/terraform/aws/onprem/static/group2 has flaky test: test_log_v2_pod_logs

## Related tickets (optional)

N/A

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain.
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]

### CODE REVIEW

**Comment by branden** [comment]
@mesosphere-mergebot changelog-not-required This is a test improvement. There should be no user-facing impact.

**Comment by branden** [comment]
@mesosphere-mergebot label ready for review

**Comment by branden** [comment]
`teamcity/dcos/test/terraform/aws/onprem/static/group2` needs an override with DCOS-57770

**Comment by philipnrmn** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/terraform/aws/onprem/static/group2 DCOS-57770

**Pull request merged**
