### PR TITLE
Backport - Include LICENSE, NOTICE file in dcos-image.

### PR DESCRIPTION
**Pull request by orsenthil**
## High-level description

Backport changes from https://github.com/dcos/dcos/pull/2128 to 1.10 branch

JIRA Ticket: https://jira.mesosphere.com/browse/COPS-2050

### CODE REVIEW

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
`teamcity/dcos/test/azure/arm` should be overridden with https://jira.mesosphere.com/browse/DCOS_OSS-1830

**Comment by mellenburg** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/arm DCOS_OSS-1830

**Pull request merged**
