### PR TITLE
Import sort ordering fixes

### PR DESCRIPTION
**Pull request by lingmann**
Misc fixes for our `tox -e py34-syntax` tests.

### CODE REVIEW

**Comment by lingmann** [comment]
@cmaloney any idea why these ordering issues didn't trigger a code-quality failure before getting merged into master?

**Comment by cmaloney** [comment]
So a couple things that are happening here:

1. need to update isort because some fo these are known third party 
https://github.com/dcos/dcos/blob/master/.isort.cfg
known_third_party: azure, retrying, passlib

2. Need to update tox.ini to have isort search these folders
https://github.com/dcos/dcos/blob/master/tox.ini#L21

**Comment by lingmann** [comment]
@cmaloney thanks, will investigate further.

**Comment by cmaloney** [comment]
@lingmann https://github.com/dcos/dcos/pull/643 should help a lot here / radically change what needs to happen in this PR.

Everything in master currently passes (And is always included by default now). If you see more issues we can open a new PR.

**Pull request closed without merging**
