### PR TITLE
Scripts to create DC/OS compatible cloud images

### PR DESCRIPTION
**Pull request by lingmann**

### CODE REVIEW

**Comment by cmaloney** [comment]
Is there any way we can add some sort of test that this all works? (Even if it's just one we run nightly / hourly / etc)

**Comment by spahl** [comment]
Yes we will be building the ami through a CI job so we might as well let it run nightly or so

**Comment by cmaloney** [comment]
Return to review once we have some sort of CI job button that can be pressed (this stuff bitrots quickly)

**Comment by spahl** [comment]
This was closed by mistake.

**Comment by spahl** [comment]
https://github.com/dcos/dcos/pull/205

**Pull request closed without merging**
