### PR TITLE
Update Marathon to 1.5.0-SNAPSHOT-706-g27c2744

### PR DESCRIPTION
**Pull request by jeschkies**
## High Level Description

Upgrade to latest Marathon 1.5 master with latest bug fixes.

## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [x] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by jeschkies** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by jeschkies** [comment]
@mesosphere-mergebot bump-ee

**Comment by jgehrcke** [comment]
> Test Results: [link to CI job test results for component]

You checked that mark, but there is no link. Can you still add one?

**Comment by adam-mesos** [comment]
Changelog link please!

**Comment by kensipe** [comment]
@adam-mesos  the changelog link was provided with the initial PR:  https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae

**Comment by kensipe** [comment]
@adam-mesos forgive me... my response was incorrect.   The changelog was provided but what karsten provided wasn't the marathon changelog.. I will resolve.

**Comment by kensipe** [comment]
@adam-mesos changelog:  https://github.com/mesosphere/marathon/compare/596e861...27c2744
ci test green:  https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/213/

**Comment by jgehrcke** [comment]
Thanks for adding the details, Ken.

I have manually checked the CI state of the downstream PR. It's green. Not sure why `mergebot/enterprise/build-status/aggregate` is shown as red here.

**Comment by orsenthil** [comment]
>Not sure why mergebot/enterprise/build-status/aggregate is shown as red here. 

I am not sure too. The status event got lost.

I sent the status event again (just by re-running check-style in EE PR), the aggregate status got delivered (again), updating this PR to correct status.

I will keep this in mind to figure out where a re-try (if any possible) could be introduced.

**Pull request merged**
