### PR TITLE
[master] Mergebot Automated Train PR - 2018-Sep-12-12-00

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
# Mergebot Train Pull Request.
This Integration PR consists of the following PRs.

* #3371 - Add wait command to dcos-docker instructions

### CODE REVIEW

**Comment by pcrews** [comment]
@mesosphere-mergebot label ready for review

**Comment by pcrews** [comment]
@mesosphere-mergebot override-status  teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-1258

**Comment by cprovencher** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/aws/onprem/static https://jira.mesosphere.com/browse/DCOS_OSS-2115

**Comment by pcrews** [comment]
@mesosphere-mergebot override-status 
teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-41679

**Comment by orsenthil** [comment]
@mesosphere-mergebot override-status teamcity/dcos/test/azure/hybrid-cloud https://jira.mesosphere.com/browse/DCOS-41679

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ready for review

**Comment by pcrews** [comment]
@mesosphere-mergebot label ship it

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
