### PR TITLE
[DCOS_OSS-3620] Bump dcos-test-utils

### PR DESCRIPTION
**Pull request by jongiddy**
## High-level description

Bump dcos-test-utils to latest version. This provides better debugging info and allows tests fixtures to be made more robust to network timeouts.

## Corresponding DC/OS tickets (obligatory)

These DC/OS JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS_OSS-3620](https://jira.mesosphere.com/browse/DCOS_OSS-3620) Log stderr on failing command execution

## Related tickets (optional)

- [DCOS-38213](https://jira.mesosphere.com/browse/DCOS-38213) dcoscli fixture times-out while downloading CLI

## Checklist for all PRs

  - [ ] Added a comprehensible changelog entry to `CHANGES.md` or explain why this is not a user-facing change: Change to test library
  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Changes behavior of tests
  - [x] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [x] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [x] Change log from the last version integrated (this should be a link to commits for easy verification and review): [changelog](https://github.com/dcos/dcos-test-utils/compare/c7eaecd8c0502e854d4fb1818947fb9d17cbac79...dcos:c1608590e010ca08c418f8bd9d9ebd764d511d57)
  - [x] Test Results: [https://teamcity.mesosphere.io/viewLog.html?buildId=1099248&buildTypeId=DcosIo_DcosTestUtils_ToxIntegrationTest]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by mesosphere-mergebot-dev** [comment]
This repo has @mesosphere-mergebot integration. You can interact with the following commands.
```
@mesosphere-mergebot merge-it  
@mesosphere-mergebot label [Ready For Review |Request For Comment |Work In Progress |Holding |Ship It] 
@mesosphere-mergebot bump-ee  
@mesosphere-mergebot override-status  
```

* PR creators can apply one of  `[Ready For Review |Work In Progress]`. [Owners](https://github.com/dcos/dcos/blob/master/owners.json) can apply any label.

**Comment by jongiddy** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
@mesosphere-mergebot bump-ee

**Comment by jongiddy** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by gpaul** [comment]
@orsenthil this PR has had two approvals, in Review, with all checks green, for 4 hours and still no ship it label. What are we missing here?

**Comment by mhrabovcin** [comment]
This bug has already occurred - https://jira.mesosphere.com/browse/DCOS-38059 and https://github.com/mesosphere/dcos-enterprise/pull/2867

**Comment by jongiddy** [comment]
@orsenthil This PR is still approved without Ship It:
- Can we add Ship It to this PR, or is something preventing it?
- Is it a problem that the EE bump has been merged, but this bump has not?

**Comment by orsenthil** [comment]
@jongiddy  / @mhrabovcin  - This can happen when a github doesn't register the approval event.  A work around is to send the event again ( like I approved this again).  I have to better solution as part of DCOS-38059

**Pull request merged**
