### PR TITLE
[Backport-2.1] Bumping the etcd version to v3.4.9

### PR DESCRIPTION
**Pull request by wavesoft**
## High-level description

This commit bumps the etcd version to 3.4.9  (back-ported to 2.1)

## Corresponding DC/OS tickets (required)

  - [COPS-6341](https://jira.d2iq.com/browse/COPS-6341) Etcd need to be upgraded to 3.4.9

## Related tickets (optional)

(None)

### CODE REVIEW

**Comment by wavesoft** [comment]
@mesosphere-mergebot request-review

**Comment by wavesoft** [comment]
@mesosphere-mergebot request-review  @jkoelker @DominikDary

**Comment by DominikDary** [comment]
@mesosphere-mergebot label Ship It

**Comment by DominikDary** [comment]
@mesosphere-mergebot merge-it

**Pull request merged**
