### PR TITLE
Train 215

### PR DESCRIPTION
**Pull request by sschneid**
#1891 Update DC/OS UI package to 1.10.0-rc.8

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-mergebot bump-ee

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ready For Review

**Comment by orsenthil** [comment]
Hi @sschneid ,

We need trains when we have more than 1 PR, and we want to "test" their integration against the master of DC/OS. Once we prove those integrations are fine, we merge them.

When it is a single PR, we do not need train because they are already tested against master.

In this situation, https://github.com/dcos/dcos/pull/1891, can be merged and it's corresponding EE change can be merged too: https://github.com/mesosphere/dcos-enterprise/pull/1376 

Also, the DCOS-UI PR #1891, had EE change which brought in additional changes (https://github.com/mesosphere/dcos-enterprise/pull/1376 ) - This train-pr is missing those changes.

We could either:

1. Include the https://github.com/mesosphere/dcos-enterprise/pull/1376 changes in bump (https://github.com/mesosphere/dcos-enterprise/pull/1395) and wait for the EE tests to finish again.
2. Or we could merge those DCOS-UI PRs immediately.

**Comment by orsenthil** [comment]
@sschneid  - There are more EE PRs that are ready to merge. We could include them in the EE side and merge these train.

**Comment by sschneid** [comment]
@mesosphere-ci label Ship It

**Comment by sschneid** [comment]
@mesosphere-mergebot label Ship It

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Comment by lingmann** [comment]
@mesosphere-mergebot bump-ee

**Pull request merged**
