### PR TITLE
Update version to 1.11

### PR DESCRIPTION
**Pull request by amitaekbote**
## High Level Description

Update version to 1.11.0 
https://jira.mesosphere.com/browse/DCOS_OSS-1765
## Checklist for all PR's

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here:
  - [ ] Read the [DC/OS contributing guidelines](https://github.com/dcos/dcos/blob/master/contributing.md)
  - [ ] Followed relevant code rules [Rules for Packages and Systemd](https://github.com/dcos/dcos/tree/master/docs)

## Checklist for component/package updates:

If you are changing components or packages in DC/OS (e.g. you are bumping the sha or ref of anything underneath `packages`), then in addition to the above please also include:

  - [ ] Change log from the last version integrated (this should be a link to commits for easy verification and review): [example](https://github.com/dcos/dcos-mesos-modules/compare/f6fa27d7c40f4207ba3bb2274e2cfe79b62a395a...6660b90fbbf69a15ef46d0184e36755881d6a5ae)
  - [ ] Test Results: [link to CI job test results for component]
  - [ ] Code Coverage (if available): [link to code coverage report]
___
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and Review Process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using github's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner. Once a PR has **2 ship-it's**, **no red reviews**, and **all tests are green** it will be included in the [next train](https://github.com/dcos/dcos/blob/master/contributing.md).

### CODE REVIEW

**Comment by amitaekbote** [comment]
changed to 1.11-dev

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by amitaekbote** [comment]
the docker smoke test was broken because we didnt have a 1.11 build of the cli, that should have been fixed. rerunning it.

**Comment by branden** [comment]
Looks like this is superseded by #2013.

**Comment by jgehrcke** [comment]
> Looks like this is superseded by #2013.

Closing because of this.

**Comment by amitaekbote** [comment]
@jgehrcke can you please close the one that was opened later? I have been tracking this for a while now.

**Comment by jgehrcke** [comment]
> @jgehrcke can you please close the one that was opened later? I have been tracking this for a while now.

Mhm. We should always start with a JIRA ticket, and every PR should link to its corresponding JIRA ticket. That can help preventing such collision from happening :)

Can you please talk to @lingmann and figure out which PR should survive?

**Comment by orsenthil** [comment]
@mesosphere-mergebot bump-ee

**Comment by orsenthil** [comment]
@mesosphere-mergebot label  ready for review

**Comment by orsenthil** [comment]
> mergebot/enterprise/build-status/aggregate is expected as EE has test failures (https://jira.mesosphere.com/browse/DCOS-18664)

**Comment by orsenthil** [comment]
@mellenburg  and @sschneid  - Please approve the EE PR as well.

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it 

The EE failures are due to: (https://jira.mesosphere.com/browse/DCOS-18664)

**Comment by orsenthil** [comment]
@mesosphere-mergebot label ship-it

**Pull request merged**
